### PR TITLE
Adds support for transpiling TypeScript code with Babel.

### PR DESCRIPTION
**Pull request by jallamsetty1**

### CODE REVIEW

**Comment by saghul** [comment]
We might need something similar for Metro.

Also, is this the way to go, vs ts-loader?

**Comment by saghul** [comment]
One more thing @jallamsetty1: why did you need to add this since your code is in TS? I'd expect the generated bundle to not have any TS.

**Comment by jallamsetty1** [comment]
> One more thing @jallamsetty1: why did you need to add this since your code is in TS? I'd expect the generated bundle to not have any TS.

Oops forgot to mark it as draft, was testing to see if this fixes the torture test failures on my LJM branch. Torture tests are failing with the following build error though it builds fine for me.
SyntaxError: /home/jenkins/workspace/pr-test/jitsi-meet/node_modules/lib-jitsi-meet/modules/sdp/SdpSimulcast.ts: Unexpected reserved word ‘interface’. (7:0)
Its still treating it as JS and not TS code. Do you know what is possibly happening there ?

**Comment by saghul** [comment]
That's weird, we shouldn't be using that file at all, and use the bundled lib-jitsi-meet.min.js instead.

**Pull request closed without merging**
