### PR TITLE
Updated Czech Translation

### PR DESCRIPTION
**Pull request by fersman**
I updated Czech translation.

### CODE REVIEW

**Comment by damencho** [comment]
Don't add empty translations, as that will avoid to fallback to the English one, and there will be labels with no text.

**Comment by fersman** [comment]
> Hi, thanks for your contribution! If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

I already signed it some time ago.

**Comment by fersman** [comment]
> Don't add empty translations, as that will avoid to fallback to the English one, and there will be labels with no text.

I will fix it.

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
