### PR TITLE
Implementing whiteboard on jitsi

### PR DESCRIPTION
**Pull request by DavideCoppola**
NOTE: DO NOT ACCEPT THIS PULL REQUEST.

This PR is part of the Hackathon "Winning over the classroom with Jitsi". In one of the messages in Slack, participants were encouraged to submit PRs so that their project has more visibility. That is the reason behind this PR. However, the code in this PR needs refactoring and the functionality is nor finished, that's why I don't want this PR to be accepted (yet). I'm going to keep working on the functionality after the Hackathon, and only then the merge will have sense.

Overview

Our proposal was to implement the Excalidraw whiteboard to encourage all the call participants (like students and teachers) on modify and edit the same drawing thanks to the created shared room. It is available from a new button that redirects to the Excalidraw room

UI

It was added a new button on the Toolbox called "Go to Whiteboard"

Current limitations and future work

Now all the participants in the same room can edit the drawing. In future release we can propose to use Excalidraw whiteboard without its main site's link

### CODE REVIEW

**Comment by DavideCoppola** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Hi, me and my team have already signed CLA for individuals. What do we need to be in compliance? Maybe CLA for corporations? Best regards

**Comment by saghul** [comment]
If you signed it already you're good. The bot is not very smart :-P

**Comment by DavideCoppola** [comment]
Oook, thank you very much for you answer 👍 :)

**Comment by manouchk38** [comment]
Hi,
as the breakoutroom feature was just merged in jitsi::master (https://github.com/jitsi/jitsi-meet/pull/10170), I was wondering if there were was already some powerfull whiteboarding possibilities associated with breakout rooms. One basic idea would be that each break out room could have its own whiteboard and that all whiteboard could be seen and saved by the teacher and that it could be used for presentation and discussion after a breakout room session during a lesson. This would be the transposition of the use of small whiteboard that was "invented" by David Hestenes students if not mistaken. It is a must have in particular in teaching physics, because talking in physics is very often for sufficient and many activities involve work with equations, graphics and diagrams that are not easily communicable or even stored in working memory. Some ideas of these ideas have been implemented by https://whiteboard.fi/ which was bought by kahoot, if I understood well. I already talked about this in breakout room discussion. I hope I wrote this message in the correct place, if not please point me out a correct place for that.

**Comment by saghul** [comment]
There is no whiteboard implementation at the moment, breakout rooms related or otherwise.

WNO can be integrated via Etherpad, I think that's the easiest way to go about it.

**Comment by saghul** [comment]
Closing. Something like this should be attainable once "generic iframe" lands.

**Pull request closed without merging**
