### PR TITLE
FIX SASS outdated FIX #1961

### LINKED ISSUE #1961: Icon not showing (bis)
I'm trying to use the jitsi SDK in an android project which is not a react-native one.
(https://github.com/vector-im/riot-android/tree/jitsi/vector)

I saw that someone got similar issue https://github.com/jitsi/jitsi-meet/issues/1688.

But, your answer was fine for a react-native project but not in my case.

So, i've made the same steps than gcobcqwe (i did not read it before).
And, i have the same issues.

I assume the icons are created by the css and 
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
is not the right command to create them properly.

I would to understand why this command line is not enough to have the icons.

Could you help me to have a valid bundle ? 
I'm sure many other developer will have the same issue.

I will give some feedbacks if i succeed to fix it.

### PR DESCRIPTION
**Pull request by ruojianll**
FIX Android app‘s icons are missing and can't creat index bundle.

### CODE REVIEW

**Comment by ruojianll** [comment]
I signed the ICLA agreement.

**Comment by saghul** [comment]
I don't understand this PR: are the two fixes related? If not (I suspect not) please make separate PRs.

Regarding the SASS update: we pin dependencies and commit package-lock.json, so please adjust that accordingly.

Regarding the Android fix: I don't fully understand why you need it, can you please elaborate?

**Comment by virtuacoplenny** [comment]
Updating of SASS may have been addressed by https://github.com/jitsi/jitsi-meet/pull/2777. Could you please confirm?

**Comment by saghul** [comment]
@virtuacoplenny It has. I'm going to go ahead and close this.

**Pull request closed without merging**
