### PR TITLE
feat(breakout-rooms): moderation of visibility

### PR DESCRIPTION
**Pull request by wfleischer**
Allowing moderators to control the visibility of breakout rooms to the participants. See the related PR https://github.com/jitsi/lib-jitsi-meet/pull/1833.

### CODE REVIEW

**Comment by saghul** [comment]
What is the intent of this? To hide the room to non-moderators for a bit?

Shouldn't LJM filter the rooms when emitting the events in case you have a new front end talking to an older backend?

I worry about backwards compatibility on this one, specially on mobile, where the front end is not updated at the same time as the backend.

**Comment by wfleischer** [comment]
Thank you, @saghul for your valuable feedback.

> What is the intent of this? To hide the room to non-moderators for a bit?

Yes. This is to allow moderators to prepare the breakout rooms and control when they can be used.

> Shouldn't LJM filter the rooms when emitting the events in case you have a new front end talking to an older backend?
> 
> I worry about backwards compatibility on this one, specially on mobile, where the front end is not updated at the same time as the backend.

This is a valid concern. I have updated this and the related lib-jitsi-meet PR to hide the moderation option if the feature is not supported on the backend. Please have a look.

**Comment by wfleischer** [comment]
Marked this as WIP for now. This PR is pending on some UI redesign. No ETA. Sorry.

**Comment by wfleischer** [comment]
@saghul, @hristoterezov: Please take a look at this feature request, similar to the breakout rooms renaming PR. Let me know if you want me to rebase.

**Comment by saghul** [comment]
I think it would make sense to have it, but I defer to @hristoterezov since I won't have the cycles to review it in the short term.

**Comment by saghul** [comment]
Sigh. @wfleischer if you are still interested in this please rebase it and I will review it.

**Comment by wfleischer** [comment]
> Sigh. @wfleischer if you are still interested in this please rebase it and I will review it.

Sorry for the late reply, @saghul! I was a bit busy with other stuff. I will be happy to provide a rebase. Thank you for considering!

**Comment by wfleischer** [comment]
Closing as superseeded by #14676

**Pull request closed without merging**
