### PR TITLE
feat(external_api) add function to toggle virtual background

### PR DESCRIPTION
**Pull request by HannesOberreiter**
(closes old issue: https://github.com/jitsi/jitsi-meet/issues/9399)

New API command to change the virtual background with a custom base64 image.

```javascript
// Command
api.executeCommand('setVirtualBackground', false, 'data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==');
// Function
api.setVirtualBackground(true, 'data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==');
```

### CODE REVIEW

**Comment by damencho** [comment]
@saghul and @hristoterezov do we prefer functions or commands?

**Comment by HannesOberreiter** [comment]
My main reason for including the function was that it provides a convenient spot for JSDoc comments to explain its purpose. If we remove the function, we lose that explanation. Not sure if avoiding redundancy outweighs keeping the clarity.

**Comment by saghul** [comment]
That is a very good point. Let's keep it.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
has the CLA been signed?

**Comment by HannesOberreiter** [comment]
Yes was earlier this year, company "certible".

**Pull request merged**
