### PR TITLE
Remove async keyword from _renderMask

### PR DESCRIPTION
**Pull request by jbis9051**
This will significantly speed up blur.

### CODE REVIEW

**Comment by jbis9051** [comment]
This should have been done in https://github.com/jitsi/jitsi-meet/pull/7473

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by jallamsetty1** [comment]
@jbis9051, I don't see any significant different in the performance of the blur with your changes. How are you making these measurements ?

**Comment by jbis9051** [comment]
@jallamsetty1 I visually saw a frame rate improvement, checked in the performance tab of Firefox developer tools, and added a frame rate checker and saw an improvement. I can post screenshots later.

**Comment by saghul** [comment]
The entire blur effect got redone. Closing since this would need reevaluating.

**Pull request closed without merging**
