### PR TITLE
Update main-eo.json

### PR DESCRIPTION
**Pull request by Mutusen**
Completed missing Esperanto translations

### CODE REVIEW

**Comment by Mutusen** [comment]
It's done. Do I need to send the signed document to someone?

**Comment by saghul** [comment]
Looks like somehow this has a conflict now. Can you please take care of it?

**Comment by Mutusen** [comment]
> Looks like somehow this has a conflict now. Can you please take care of it?

Done, I've solved the conflict.

**Comment by luixxiul** [comment]
Unless CLA is not confirmed, let's just merge this PR.

**Comment by saghul** [comment]
Jenkins please test this please.

**Pull request merged**
