### PR TITLE
feat(reservations) start lobby and set password from reservation

### PR DESCRIPTION
**Pull request by shawnchin**
@damencho As briefly discussed in DM, I'm attempting to add support for enabling lobby from reservations.

Enabling lobby programmatically brings about 2 complications:
1.  Moderator needs a way to get into the room to admit others, hence the additional support for setting passwords
    * password support is optional. Users could also use something like [token_lobby_bypass](https://github.com/jitsi-contrib/prosody-plugins/tree/main/token_lobby_bypass)
2. It is now possible to have lobby enabled with nobody in the main room, and empty rooms get deleted automatically thus terminating the lobby too. I've added the logic to handle this as a separate module (mod_persistent_lobby) because:
     a. It is non trivial and makes the reservations module harder to follow
     b. It is reasonably standalone and reusable by other plugin writers e.g. I can simplify [lobby_autostart](https://github.com/jitsi-contrib/prosody-plugins/tree/main/lobby_autostart) significantly by reusing this module.

### CODE REVIEW

**Review by damencho — APPROVED** [review]
I like it :) we can use the lobby thing and fr other use-cases. 
Will merge it later.

**Comment by shawnchin** [comment]
sorry. force pushed a small fix to handle missing import.

**Comment by shawnchin** [comment]
I've been testing this further, in particular mod_persistent_lobby, and found an edge case where it doesn't work -- when there are existing moderators in the room and we programmatically trigger lobby, existing moderators will not get notification that someone is in the lobby. The UI also does not reflect that lobby is enabled (i.e. the toggle in the security modal is false, no lobby section in participants pane, etc). It works as expected for new joining moderators.

I haven't yet confirmed if we're missing the notification, or if the UI is ignoring it because there is not actor for this event.

Any ideas @damencho ?

**Comment by damencho** [comment]
> I've been testing this further, in particular mod_persistent_lobby, and found an edge case where it doesn't work -- when there are existing moderators in the room and we programmatically trigger lobby, existing moderators will not get notification that someone is in the lobby. The UI also does not reflect that lobby is enabled (i.e. the toggle in the security modal is false, no lobby section in participants pane, etc). It works as expected for new joining moderators.
> 
> I haven't yet confirmed if we're missing the notification, or if the UI is ignoring it because there is not actor for this event.
> 
> Any ideas @damencho ?
> 
> **Edit**: this doesn't affect the case where it is triggered by reservations module since that happens on room pre-create, so not a blocker for this ticket. It only really affects plugin writers that want to enable lobby programmatically for existing room.

Hum, that is strange.

**Comment by damencho** [comment]
It works when doing it from the UI, at least on meet.jit.si versions ... Can you try that, does it work for you that way.

**Comment by shawnchin** [comment]
yes. It works when done in the UI. 

I think the problem here is that we are only triggering the broadcast to existing moderators on 'muc-config-submitted' event ([ref](https://github.com/jitsi/jitsi-meet/blob/fb2cfaa204734a68e376d9a53c567eec4a0d2c74/resources/prosody-plugins/mod_muc_lobby_rooms.lua#L325)). When done in the UI, the roomconfig form is submitted ([ref](https://github.com/jitsi/lib-jitsi-meet/blob/e1ca2f5a7b74ca2443f6cb4948f5e53b78aee1c6/modules/xmpp/ChatRoom.js#L1423)) but that is not done when we enable lobby from the prosody plugin.

Assuming that is correct, still not sure what's the best way to deal with this. Do we provide an easy way to manually trigger that notification? or force 'muc-config-submitted' event?

**Comment by damencho** [comment]
So you found it :) 
Maybe we can wire the notify_lobby_enabled to an event ... like create lobby room

**Comment by shawnchin** [comment]
I will explore some options :) 

Notifications for automated lobby will be a bit different because it doesn't have a real actor, and I don't want to break current functionality or risk triggering duplicate notifications.

**Comment by shawnchin** [comment]
If I'm understanding correctly, it looks like we also need to worry about affiliations of all the existing members in the room before `room:set_members_only()` -- the call will [kick out all non-members in room](https://github.com/bjc/prosody/blob/afa583dfcdcf1e3a53ccb88691985a1c691046d0/plugins/muc/members_only.lib.lua#L25-L29) and in the Jitsi Meet we deal with it by [promoting everyone not already a member/owner](https://github.com/jitsi/lib-jitsi-meet/blob/3fc032652d4a14c32a97ca2427e4acf1f13c2e50/modules/xmpp/ChatRoom.js#L1378-L1395).

Not an issue in the case of the reservations module use case, but for other plugins that might want to trigger lobby for rooms with existing members it has to do the same?

If so, maybe we just need another helper function that handles user affiliations and notifications to be called only when required. It should not be called from the usual flow of things, and is also kinda out of scope of the current PR 🤔

**Comment by damencho** [comment]
> Not an issue in the case of the reservations module use case, but for other plugins that might want to trigger lobby for rooms with existing members it has to do the same?

Yep.



> If so, maybe we just need another helper function that handles user affiliations and notifications to be called only when required. It should not be called from the usual flow of things, and is also kinda out of scope of the current PR 🤔

Sounds, like it. Till now we had only backend turn on of lobby on room creation and during the call possible only through UI. You may at least add a warning/comment in the lobby module for this case.
I think setting everyone to members ... we had this code somewhere in lua ... Need to check

**Comment by shawnchin** [comment]
Thanks. I've handle the case for setting everyone to member. 

Now just need work out how to properly handle muc#roomconfig form submission, and notification to existing moderators. Work in progress...

**Comment by shawnchin** [comment]
I see. I will try that. 

But perhaps as a separate PR at some point? That use case does not affect reservations module or standard case where moderators trigger lobby. I don't want to over complicate this PR.

I've added a comment in muc_lobby_rooms about this use case.

**Comment by shawnchin** [comment]
@damencho Sorry to bother you again. Quick question -- what triggers the 'conference.membersOnlyChanged' xmpp event and is it possible to do this from prosody plugin?

It looks like that's what sets the 'features/lobby' state and correctly updates the UI:

https://github.com/jitsi/jitsi-meet/blob/6e32a146e3d86a2a4fad54c417b532fcf6ad484f/react/features/lobby/middleware.js#L91-L92

**Comment by damencho** [comment]
When someone changes the xmpp muc dataform (by enabling lobby) a presence with status 104 is received, everyone retrieves the new form and on comparing the values sees that member_only field changed and that event is fired ... I guess we need to check in prosody code how this can be triggered server side. 
Hum ... are you setting this?

**Comment by damencho** [comment]
O yeah the creation of lobby is doing that 
https://github.com/jitsi/jitsi-meet/blob/7522de033a8b698579426cbd9b7e1cefd2206b3b/resources/prosody-plugins/mod_muc_lobby_rooms.lua#L439

**Comment by shawnchin** [comment]
Hmm... that was what I was hoping, that it would be magically sent when `room:set_members_only()`. But for some reason existing moderators in the room do not get that so the Lobby toggle state is wrong. It works fine if new moderator joins.

**Comment by damencho** [comment]
This is what you need to do create this message with status code 104 (https://github.com/bjc/prosody/blob/449311b2d112182be22ab9bef06ae00d200726e9/plugins/muc/members_only.lib.lua#L100) and send it
https://github.com/bjc/prosody/blob/cbcb57fa24650c6ac001c4c1c9ab39a61b6266eb/plugins/muc/muc.lib.lua#L986

**Comment by shawnchin** [comment]
Nice. I will try that. Thanks

**Comment by damencho** [comment]
> It works fine if new moderator joins.

Yeah new once do the form retrieval dance on join :) so they get the updated value.

**Comment by shawnchin** [comment]
It works! 🕺 

I will clean it up and test some more.

Last questions (hopefully):
- do you want the change to mod_lobby_rooms in another PR or just this one?
- do we need another Notification type for when lobby is enabled by backend? The current one expects an actor and want to show participant name, so it won't work.

**Comment by damencho** [comment]
> * do you want the change to mod_lobby_rooms in another PR or just this one?

Your choice.



> * do we need another Notification type for when lobby is enabled by backend? The current one expects an actor and want to show participant name, so it won't work.

Hum, maybe we can make the actor optional in the logic and make it work ... does it work that way if you skip the from part? We need to check for errors in the UI, we maybe are trying to display who enabled it.

**Comment by shawnchin** [comment]
> Hum, maybe we can make the actor optional in the logic and make it work ... does it work that way if you skip the from part?

I'm not sure. Even if I rephrase it so it works without the author in the English text, it will be hard to not break all the other [translated versions](https://github.com/jitsi/jitsi-meet/search?q=notificationLobbyEnabled). Also, I was planning to only handle server-enabled, but not server-disabled yet since that case is not fully tested.

Another option is not to send a notification at all for backend enabled lobby? We will still see the "X wants to join the meeting" message, just not the "Lobby has been enabled by X"

**Comment by damencho** [comment]
> Another option is not to send a notification at all for backend enabled lobby? We will still see the "X wants to join the meeting" message, just not the "Lobby has been enabled by X"

O yeah. That sounds good and simplifies things. You had tackled the form and correct state in UI so this is good enough.

**Comment by shawnchin** [comment]
👍 works for me.

Will be a small change then, so I will include in this PR shortly. 

If I have time tonight I might also share a plugin in jitsi-contrib that will use this feature. Will make it easier to test that it works, and serve as example of how it can be used.

**Review by damencho — APPROVED** [review]

**Comment by cyrenity** [comment]
I am trying to use lobby_bypass with "lobby: true" and  password set in reservation response. Moderator can now skip the lobby but it still asks for the password. I don't want password enforcement for moderators and just want the member to have option of either using password or ask for join option

**Comment by shawnchin** [comment]
Related post on community forum : https://community.jitsi.org/t/jwt-param-to-bypass-room-password/126718

**Pull request merged**
