### PR TITLE
[RN] Don't auto-capitalize email field in settings

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
@zbettenbuk Can you PTAL?

**Comment by virtuacoplenny** [comment]
Drive by comment: are autoCorrect/spellCheck also disabled?

**Comment by saghul** [comment]
@virtuacoplenny Nope, but makes sense to do so for the URL too! Thanks for pointing that out, I'll add it.

**Comment by lyubomir** [comment]
@saghul, could we please have autoCorrect and autoCapitalize (if that's not disabled by autoCorrect) disabled for the "Display name" (it autocorrects my name on iOS, for example) as well? I don't see any of the three text fields needing autocorrection-related functionality.

**Comment by saghul** [comment]
Updated, PTAL. @lyubomir now all fields have auto-corrrect off, and the display name is the only one which has auto-capitalize on, since I think it's common for people to write their name with a capital letter first.

**Pull request merged**
