### PR TITLE
Rn jitsi sdk component unmount close

### PR DESCRIPTION
**Pull request by Larens94**
Hello

the problem is that the call remains active if the parent component is destroyed... in my case I need jitsi to manage autonomously the resources no longer needed when the component is closed and then close everything.

Sincerely

### CODE REVIEW

**Comment by saghul** [comment]
I don't think this is correct since it will run with every re-render. We already have a useEffect to prepare the props and I reckon a cleanup function there would accomplish what you need.

**Comment by Larens94** [comment]
> I don't think this is correct since it will run with every re-render. We already have a useEffect to prepare the props and I reckon a cleanup function there would accomplish what you need.

I actually think I committed the wrong code because it should only be executed when the component is destroyed.

useLayoutEffect(() => {
   // do side effects
   return () => /* clean up */
}, [dependencies, arrays]);

**Comment by saghul** [comment]
Yes, but then why do you explicitly need useLayoutEffect instead of useEffect?

**Comment by saghul** [comment]
But that should be set by the time we cleanup, no?

**Comment by Larens94** [comment]
> But that should be set by the time we cleanup, no?

I debugged and it works fine.

When I destroy the component (without going through the jitsimeet.close()) because in some cases in the application I don't have it.
Then I destroy the parent component where I inserted JitsiMeet, doing so activates the unmount component and then I clean up jitsi.

If you're not convinced, it could also be I don't know your system well but for the moment it seems to work correctly.


Sincerely

**Comment by saghul** [comment]
> I debugged and it works fine.

Sorry, but the current PR state is broken how do we know it works fine?

**Comment by Larens94** [comment]
> > I debugged and it works fine.
> 
> Sorry, but the current PR state is broken how do we know it works fine?

Done.

**Review by saghul — DISMISSED** [review]
LGTM. @Calinteodor can you PTAL too?

**Comment by Calinteodor** [comment]
@Larens94 Can you please rebase and fix the conflict? Thank you!

**Comment by Larens94** [comment]
> @Larens94 Can you please rebase and fix the conflict? Thank you!
Done

**Review by Calinteodor — APPROVED** [review]

**Review by Calinteodor — DISMISSED** [review]

**Review by Calinteodor — APPROVED** [review]

**Pull request merged**
