### PR TITLE
added flashlight feature for iOS

### PR DESCRIPTION
**Pull request by patidars**
Implemented flashlight for iOS. Provided a way to enable/disable flashlight for iOS by passing flag from native. Added option to turn-on/off flashlight in overlay menu. Flashlight will also get off, if user change camera facing mode or hangup the call.

### CODE REVIEW

**Comment by saghul** [comment]
HI @patidars thanks for the PR! This certainly required some work! Now, I see *what* it does, but I'm afraid I don't understand the *why*. Why does this functionality need to be part of the app? Both iOS and Android have support for it system-wide so there is no need for Jitsi Meet to provideo it. Or am I missing something? Thanks!

**Comment by patidars** [comment]
Thanks @saghul Yes flashlight features is available on system-wise. But it does not work with Jitsi-meet.
Steps(iOS):

- Open Jitsi with Video on
- Turn-on flashlight
- Comeback to Jitsi-Meet and observed flashlight turned-off automatically
So user will not able to use flashlight feature in Jitsi-Meet. I have verified this scenario on iPhone X and iPhone 8+
Because of this issue, this PR/functionality should be the part of the Jitsi-Meet app. It will allow user to turn-on/off flashlight within app.

**Comment by saghul** [comment]
@patidars I see. While I do see some (very narrow) use cases, FaceTime or the builtin camera don't allow video recording with the flashlight on.

I'm sorry, but this is not something we are willing to integrate into the app.

**Comment by deliciouslytyped** [comment]
I'm an android user but I'm sad this was not merged or at least conceptually accepted.
Who cares what FaceTIme does. Jitsi can be better.

Unless there is an upstream API limitation, this can be a useful feature, especially when an operating system only grants exclusive device access to one app at a time and doesn't allow you to then toggle the flashlight at the system level. I.e. there is literally no way to do this other than support in the app,

**Pull request closed without merging**
