### PR TITLE
Revert "feat(ScreenshotCaptureEffect) Implement."

### PR DESCRIPTION
**Pull request by saghul**
This reverts commit a18ed3a779f41a2fcec3a581e11fa864f99b5330.

### CODE REVIEW

**Comment by saghul** [comment]
I had to revert this because it has some critical problems:

- It broke mobile.
- It's not a separate bundle, that's a big no-no and the reason why mobile is broken. We specifically did this for the blur effect, and this effect should follow.
- It caches the entire Redux store. If access to the store is needed, it should get a reference to the store, not the full state in order to use it later on.
- It should not be loaded at all (imported really, since this fails at import time)

The fact that the effect needs access to the store at different points in time means that we might need some communication mechanism so the main app does the sending, since teh code running on a separate bundle won't have access to it.

Ping @muscat1 @jallamsetty1

**Comment by saghul** [comment]
Alternative bandaid: https://github.com/jitsi/jitsi-meet/pull/5022

**Comment by jallamsetty1** [comment]
@saghul, do we need to make it a separate bundle ? I thought the reason for making blur a separate bundle is because of the size of the TF modules that are loaded when the effect is created. 
I think your PR   #5022 fixes the error on mobile that we are seeing. I was able to set up my mobile build yesterday and saw the same error. 
The effect actually doesn't need access to the redux store, it is needed during the processing of the screenshots that are generated by the effect. The processing part was in the branding PR initially but then was moved here as per @hristoterezov's suggestion. Could we move it there so that we don't have to pass the state when creating the effect ?

**Comment by saghul** [comment]
> do we need to make it a separate bundle ? I thought the reason for making blur a separate bundle is because of the size of the TF modules that are loaded when the effect is created.

I don't know if we need it, but we could've considered it. The TF size was indeed the initial reason for the split.

> The effect actually doesn't need access to the redux store, it is needed during the processing of the screenshots that are generated by the effect. The processing part was in the branding PR initially but then was moved here as per @hristoterezov's suggestion. Could we move it there so that we don't have to pass the state when creating the effect ?

The way it's currently implemented looks quite bug prone to me. I think we should get everything we need in the constructor and make the effect as dumb as possible.

I currently don't have time to re-trhink this so I went ahead and merged the other simpler approach. I guess we cacn revisit when / if issues arise.

**Comment by bigdong89** [comment]
loadScript.native.js with logging...
Selection_134

stacktrace in node_modules/react-native/Libraries/Blob/URL.js
Selection_138

all 'createObjectURL' lines in video-blur-effect.min.js
Selection_139
Selection_140

all 'createObjectURL' lines in original react codes:
Selection_141

**Comment by saghul** [comment]
This feature doesn’t work on mobile.

**Comment by bigdong89** [comment]
why doesn't it work?
@saghul  saw your Jan comments but your main problem is that the blur js was not loaded. i can load it from remote server.

**Comment by saghul** [comment]
Even if you load it, the WebRTC plugin does not have the ability to draw on a canvas and extract a stream from there, etc.

**Comment by bigdong89** [comment]
@saghul considered 2 other solutions for applying effects to mobile :
1. get video track and fetch real video frame -> apply effects -> render to react-native canvas
-- find no methods to extract video frame from video track
2.  fetch camera stream -> apply effects -> create fake video input device -> replace original one
-- i have to try to  create another worker. 
any suggestions?

**Pull request closed without merging**
