### PR TITLE
Occitan version

### PR DESCRIPTION
**Pull request by Quent-in**
Occitan local file

### CODE REVIEW

**Comment by gpolitis** [comment]
Hi @Quent-in, thank you very much for providing the translation file! We actually manage translations through http://translate.jitsi.org. You can create an account and use the interface to do the translation there. Just give us some time to add the Occitan language to translate.jitsi.org. I'll ping the appropriate person who can do that.

**Comment by gpolitis** [comment]
Hi @Quent-in, we've just added the Occitan language to translate.jitsi.org for the Jitsi Meet project, so you can start working on it there!

**Comment by Quent-in** [comment]
Hello, could you just merge the file? I can't get the hang of translate.jitsi.org...
The file is ready with the translation. I can''t send it in .json and I don't want to redo the whole job again.

**Comment by gpolitis** [comment]
Hi @Quent-in, I understand that this is going to be a big hassle to do the job again, and I wish we had an import function on translate.jitsi.org that would just take the json file and update the language strings (maybe there is an import function? @ibauersachs @emcho @bgrozev), but we generally don't directly commit to the lang/ directory as it's managed by translate.jitsi.org (Pootle).

**Comment by ibauersachs** [comment]
There is an update from VCS button in Pootle, but I don't think it works (due to the hacks I had to write so that this po<->json conversion is working in the first place). If you don't like Pootle's UI, you can download offline tools to cretae Po-files. These can be uploaded to Pootle.
@gpolitis You can try to merge and import it, but if it doesn't work it needs to be rolled back. Also, maybe it'd help for future translators to rename Translation.md to readme.md so that Github automatically shows the file when entering the lang/ folder.

**Comment by Quent-in** [comment]
Merging is worth trying I think, I did respect the structure of the English language file.

**Pull request closed without merging**
