### PR TITLE
Update Croatian translation

### PR DESCRIPTION
**Pull request by milotype**
- update according to the current "main.json" file

### CODE REVIEW

**Comment by milotype** [comment]
@jitsi-jenkins ??? I did that already at Update Croatian translation #11870? Why do you need it again?

**Comment by saghul** [comment]
It's not good at remembering 😅  Please check the linter output, some file is not conforming to the rules.

**Comment by milotype** [comment]
@jitsi-jenkins @saghul 
I'm not a programmer. So what do I have to do to get the PR merged?

**Comment by damencho** [comment]
@milotype There is a missing comma around line 487, you can see the error message by clicking "Details" on the failure above, or here: https://github.com/jitsi/jitsi-meet/actions/runs/3307264916/jobs/5458765449

**Review by damencho — APPROVED** [review]

**Pull request merged**
