### PR TITLE
Revert change to dial in numbers link

### PR DESCRIPTION
**Pull request by skolmer**
Revert a change that might cause an issue in the display of dial in numbers until we have time to investigate the root cause.

### CODE REVIEW

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Jenkins test this please.

Now it will run and that test.

**Comment by skolmer** [comment]
> 
> 
> Jenkins test this please.
> 
> Now it will run and that test.

I shouldn't be awake at 5:45AM at our time but TGIF. Just let me know if it was the cause of the failing test before I fall asleep, thanks 🥴

**Comment by damencho** [comment]
Go to sleep!

**Comment by damencho** [comment]
The test that covers this is now running and green.

**Comment by skolmer** [comment]
> 
> 
> The test that covers this is now running and green.

I found the issue, I was testing with the new config format while the test was using the deprecated format to configure dial-in number. I created a new PR that respects both formats: https://github.com/jitsi/jitsi-meet/pull/8702

**Pull request merged**
