### PR TITLE
feat(config) Added option to remove Show More link from GSM popover

### PR DESCRIPTION
**Pull request by robertpin**
Added config option to change visibility of Show More link.
Whitelisted existing save logs config

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins, add to whitelist.

**Comment by damencho** [comment]
Is the requirement for this to be disabled by default?
Asking as this changes the current behavior?

**Comment by robertpin** [comment]
> Is the requirement for this to be disabled by default?
> Asking as this changes the current behavior?

No. I also created a PR in jitsi-video-infrastructure to have this true by default

**Comment by muscat1** [comment]
I think he created a corresponding infra PR to add the flag for our deployments, but that would mean that people having their own deployments would have this disabled by default, unless they also add the config flag. (I might be mistaken)

Wouldn't it be better to have a falsy flag such as `disableShowMoreStats` so in that way, the default behaviour wouldn't change, but it could be explicitly disabled if one so desires?

WDYT @robertpin @damencho

**Review by vp8x8 — APPROVED** [review]

**Comment by damencho** [comment]
> I think he created a corresponding infra PR to add the flag for our deployments, but that would mean that people having their own deployments would have this disabled by default, unless they also add the config flag. (I might be mistaken)
> 
> Wouldn't it be better to have a falsy flag such as `disableShowMoreStats` so in that way, the default behaviour wouldn't change, but it could be explicitly disabled if one so desires?
> 
> WDYT @robertpin @damencho

Yes, that's why I asked. People that will update to latest version will stop seeing that and they need to go and explicitly enable it in their config.
We better add a flag to diable it and it is enabled by default as it is currently.

**Review by damencho — APPROVED** [review]

**Review by muscat1 — APPROVED** [review]

**Pull request merged**
