### PR TITLE
Config option to hide filmstrip

### PR DESCRIPTION
**Pull request by vanishree1**

### CODE REVIEW

**Comment by saghul** [comment]
Hi @vanishree1 thanks for your contribution! Can you please move this one to interface_config.js ? That's where we put UI related settings.

**Comment by vanishree1** [comment]
Hey @saghul , I have done the required changes.

**Comment by saghul** [comment]
@virtuacoplenny Do you see issues with this? It's an "easy win" of sorts.

**Comment by virtuacoplenny** [comment]
In its current state, it does not play gracefully with the tile view button. Possible solutions I can think of are toggling visibility, which may not work because videos may not autoplay, or straight up disabling the tile view feature when the config option is enabled. Why not instead allow start with filmstrip hidden? Just thinking of an alternative that maybe gets the same look with less complication.

**Comment by virtuacoplenny** [comment]
I realize now my recommendation about "start with filmstrip hidden" is confusing. I mean why not instead set filmstrip to default as toggled. The term "hidden" is generally associated with the filmstrip toggle button. I think if this flag were to go in, the naming needs to be changed and be more in line with setFilmstripEnabled/SET_FILMSTRIP_ENABLED.

**Comment by vanishree1** [comment]
@virtuacoplenny I have made the requested changes.

**Comment by virtuacoplenny** [comment]
@saghul we're okay with the interaction here with tile view?

**Comment by PedroD** [comment]
Hello?

**Pull request closed without merging**
