### PR TITLE
feat(dialog) start recording/live stream screens, new AlertDialog

### PR DESCRIPTION
**Pull request by Calinteodor**
1. Start Recording becomes a navigation screen.
2. Start Live Stream becomes a navigation screen.
3. Removed CustomSubmitDialog, BaseSubmitDialog and BaseDialog.
4. AlertDialog becomes new native dialog.

### CODE REVIEW

**Comment by Calinteodor** [comment]
Webp net-resizeimage

**Comment by Calinteodor** [comment]
Webp net-resizeimage (1)
Webp net-resizeimage (2)

**Comment by saghul** [comment]
Can we also remove BaseDialog (on mobile) now?

**Review by saghul — APPROVED** [review]
Excellent work m8!

**Pull request merged**
