### PR TITLE
Update main-es.json

### PR DESCRIPTION
**Pull request by yajo**
"Compartir pantalla" is much simpler and it indicates the button purpose.

### CODE REVIEW

**Comment by saghul** [comment]
In english that label says "Start / stop screen sharing", which is what the spanish translation tries to say.

**Comment by Yajo** [comment]
The problem is that "alternar" is not a word commonly used in this context. Although it's a direct translation from the English "toggle", "alternar" is not commonly used to indicate that you start doing something or stop doing it. Instead, it's more used to indicate that you are doing one thing or doing other thing.

For instance, you can properly translate "toggle light and dark themes" by "alternar temas claro y oscuro" because you either turn on one thing and turn off the other, or vice-versa.

However, for screen sharing, when you turn it on, there's nothing else you're turning off. Instead you "do it or stop doing it". It's an action. Not sure how to express this in English, but really it didn't sound natural.

We could translate "start/stop" by "comenzar/detener"... but how to complete those sentences? It would be: "comenzar / detener la compartición de pantalla", but yet again we're far from what a human would say. You never say "comienza la compartición de pantalla". You just say "comparte la pantalla".

I updated the translation to reflect how a human would say that. It ended up a bit long, but it sounds natural now. Maybe it would be easier for translators if buttons didn't express 2 actions, but just one, and their labels changed accordingly. I guess English version would get simplified too BTW.

**Comment by Yajo** [comment]
CLA signed, BTW.

**Comment by saghul** [comment]
Sorry this fell through the cracks! So, some context: I'm Spanish :-)

We have many occurrences of "alternar XXX" in the translations file, we should settle on some wording and update it all to match.

My preference would be "Comenzar / detener compartit pantalla" this follows the "start / stop ACTION" structure, which works with other options such as "Abrir / cerrar configuracion" "Comenzar / detener grabacion" etc.

**Review by saghul — APPROVED** [review]

**Pull request merged**
