### PR TITLE
Add translations in language and main files.

### PR DESCRIPTION
**Pull request by SelyanKab**
Please merge this fork.
note: The CLA has already been signed.

### CODE REVIEW

**Comment by SelyanKab** [comment]
ClA Already signed

**Comment by Quenty-tolosan** [comment]
> CLA Already signed

C'est un peu lourd de devoir redire à chaque fois qu'on a déjà signé :(

**Comment by SelyanKab** [comment]
@Quenty-tolosan oui, tout à fait, à chaque fois, on redit ça, :(

**Comment by SelyanKab** [comment]
s there someone to merge? We are still waiting to get the kab version deployed online.
Thanks

**Comment by saghul** [comment]
Hey @SelyanKab sorry for the delay. Can you please add an entry for "kab" in languages.json ? Otherwise it won't be selectable.

**Comment by SelyanKab** [comment]
Hello @saghul , yes i am going to add an entry for kab ( kabyle)

**Comment by SelyanKab** [comment]
@saghul it's done ( adding entry for kab in languages-kab.json)

**Comment by mozillakab** [comment]
@SelyanKab I checked the 2 files. It's ok and also signed the CLA
@jitsi-jenkins I'm the L10N manager of the Kabyle at Mozilla. Everything is ok. Thank you.

**Comment by SelyanKab** [comment]
@saghul 
Hello, please any one to merge, My PR has been waiting 14 days.

**Pull request merged**
