### PR TITLE
lang: update Ukrainian translation

### PR DESCRIPTION
**Pull request by nomadbyte**
- updates for the languages file
- updates, harmonization, and proofreading for the main file

### CODE REVIEW

**Comment by nomadbyte** [comment]
I wonder if you need any action from my side to get this PR going?

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Nope, thanks for the reminder.

Jenkins, test this please.

**Review by damencho — CHANGES_REQUESTED** [review]
Please sort the entries. Check the Github actions that failed.

**Comment by nomadbyte** [comment]
@damencho Just sort the file? I originally used the lang/ .py script to generate the respective -uk file.

**Comment by damencho** [comment]
You can use: https://github.com/jitsi/jitsi-meet/blob/master/resources/lang-sort.sh

**Comment by nomadbyte** [comment]
Looking closer at the CI run log, it seems that the CI checks have some issue with escape char in the strings, specifically an escaped forward slash `\/`.

I'm not familiar enough with the CI part of the project, but I can try simply un-escape the forward slashes.

Apparently, the translation program applied these escapes, probably for some markup safety reasons.

**Comment by damencho** [comment]
Jenkins test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
