### PR TITLE
ref(Android): use Bundle for color scheme instead of WritableMap

### PR DESCRIPTION
**Pull request by paweldomas**

### CODE REVIEW

**Comment by paweldomas** [comment]
Done in https://github.com/jitsi/jitsi-meet/pull/3899

**Comment by moskaland** [comment]
@paweldomas Hi, can you help me by giving an example of correctly created Bundle to change colours? Trying different approach to set custom colors, yet seems I don't know how Android Bundle corresponds  with [defaultScheme.js](https://github.com/jitsi/jitsi-meet/blob/9f9e192c3ca795826b08e0bfca79a2ea081844e5/react/features/base/color-scheme/defaultScheme.js)

**Comment by paweldomas** [comment]
@moskaland sorry I don't know exactly how this part works. Can you try looking for usages of 'colorScheme' maybe https://github.com/jitsi/jitsi-meet/commit/5b3e8a9b5ec5e613fe0182be2f1300a9bfefa9a5#diff-96211556e55b9cb67253fa62720de38065bce53459eace38e5c8d2b7059a8215R124 ?

**Comment by moskaland** [comment]
@paweldomas yes, I grep all android sdk part, yet did not find anything useful which indicates how Bundle should be structured. I went all the way down to core React layer but I don't know much about js. Searching for an example usage  on github/google was not helpful either. Regardless, thank you for your answer!

**Pull request closed without merging**
