### PR TITLE
update language-ptBR.json and main-ptBR.json strings from original files, and update all new translations

### PR DESCRIPTION
**Pull request by filhocf**
… updated all new strings

### CODE REVIEW

**Comment by filhocf** [comment]
Hi. I already signed CLA.

**Comment by damencho** [comment]
@filhocf Sorry for the delay, can you fix the conflicts, please?

**Comment by damencho** [comment]
Hum, there is another one which will again conflict with yours. Maybe I will merge the other one first https://github.com/jitsi/jitsi-meet/pull/8206

**Comment by damencho** [comment]
@filhocf WDYT?

**Comment by damencho** [comment]
I've merged the other one https://github.com/jitsi/jitsi-meet/pull/8206, so if you can fix this one. Sorry for the delay and trouble. I'm clearing those PRs so they can enter the next stable.

**Comment by saghul** [comment]
Bump, can you please fix the conflicts?

**Pull request closed without merging**
