### PR TITLE
fix(popper): resolve @atlaskit/popper to an unbuggy version

### PR DESCRIPTION
**Pull request by c0m1t**
If you open participants pane and then click on the overflow button, the inline dialog is displayed at the wrong position.

misplaced overflow menu

If we resolve `@popperjs/core` to `2.6.0` `2.11.2`, this bug will be fixed.

### CODE REVIEW

**Comment by saghul** [comment]
Shouldn't this require a bump in package.json ?

**Comment by c0m1t** [comment]
No, `@popperjs/core` is a dependency of `@atlaskit/popper`, which is a dependency of  `@atlaskit/inline-dialog`, which it is installed. Probably `package-lock.json` was deleted and created in #11003, so `@atlaskit/popper` was  resolved to a newer version, therefore the version of `@popperjs/core` got bumped.

**Comment by saghul** [comment]
Thanks for the analysis!

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by saghul — APPROVED** [review]

**Pull request merged**
