### PR TITLE
feat(chat): adaptive chat layout (left/bottom) based on client dimensions

### PR DESCRIPTION
**Pull request by vladertel**
Video Demostration inside archive (github does not accept videos 👎)
[resize.mkv.zip](https://github.com/jitsi/jitsi-meet/files/5417691/resize.mkv.zip)

### CODE REVIEW

**Comment by jallamsetty1** [comment]
@muscat1, can you please take a look at this PR as this addresses https://github.com/jitsi/jitsi-meet/issues/7787 ?

**Comment by vladertel** [comment]
Ping?

**Comment by vladertel** [comment]
@muscat1, can you please take a look at this PR?

**Comment by jallamsetty1** [comment]
> @muscat1, can you please take a look at this PR?

Hey there, the redesign idea is great but we are trying to run it by the product team to make sure they are ok with it, will get an update soon. Thanks for your patience.

**Comment by saghul** [comment]
Sorry for not getting back at you earlier, too many things going on :-/

We have since made the chat responsive so it will adapt to small client sizes. In addition it will be moving to the right side of the screen.

**Pull request closed without merging**
