### PR TITLE
feat(stats) : Additional connection stats for mobile

### PR DESCRIPTION
**Pull request by sparmar-atheer**

### CODE REVIEW

**Comment by sparmar-atheer** [comment]
@damencho @saghul Sorry to bother you. Can you please guide me on this? Any idea when you or someone else will be reviewing this? Do I need to do anything else? Thanks for you help.

**Comment by saghul** [comment]
Damn, so sorry I missed this. @sparmar-atheer are you still willing to see this one through?

**Comment by sparmar-atheer** [comment]
@saghul Thanks for getting back. Appreciate it. It will be great if we can get this in.

**Comment by saghul** [comment]
Excellent! Can you please rebase the PR with master? There are some conflicts now.

**Comment by sparmar-atheer** [comment]
Thanks @saghul I will take care of this today.

**Comment by saghul** [comment]
Ping @sparmar-atheer ?

**Pull request closed without merging**
