### PR TITLE
add systemd to letsencrypt installer

### PR DESCRIPTION
**Pull request by 53845714nF**
Hello,
I added a systemd component in the letsencrypt installer script.

With best regards
Sebastian

### CODE REVIEW

**Comment by saghul** [comment]
Doesn't `service` work? Not all distros uses systemd.

**Comment by 53845714nF** [comment]
Exactly, that's why I built it that way first tried `service`.
If that does not work it takes `systemctl`.
(On my Machine Debian 10 `service` doesn't work.)

**Comment by saghul** [comment]
Ah gotcha!

**Review by saghul — APPROVED** [review]

**Comment by eppesuig** [comment]
Hello @53845714nF,
it seems debian ships the `service` command in package `init-system-helpers`.
Anyway, just to improve the readability of these && and ||, I would change it to something like this:
```
if type service >/dev/null 2>&1
then
   ... use service command
else
  ... use systemctl command
fi
```

**Comment by 53845714nF** [comment]
Good point, I rewrote it again.

**Review by damencho — APPROVED** [review]

**Pull request merged**
