### PR TITLE
Update KnockingParticipantList.js

### PR DESCRIPTION
**Pull request by alternadom**
In order to translate the title.. Pull request #7246

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by alternadom** [comment]
@damencho , any idea why the translation is not taken for FR ?

https://github.com/jitsi/jitsi-meet/blob/3538761543c7207c1a251e1d989c935b2b2ba24f/lang/main-fr.json#L838

Thanks for you help (and you work by the way!)

**Comment by damencho** [comment]
Where which deployment or your self hosted where you had updated to the latest and it is not showing?

**Comment by alternadom** [comment]
I'm using the latest and I'm self hosted on debian.. everything is updated, I have the other translation working but this one in particular don't work.. I'm still having an hardcoded string, not the EN nor the FR translation :/

**Comment by damencho** [comment]
Are you running jitsi-meet-web 1.0.4257 or newer?

**Comment by alternadom** [comment]
Sorry @damencho , rooky mistake! All is working great ;)

**Pull request merged**
