### PR TITLE
Added doctype and fixed HTML errors.

### PR DESCRIPTION
**Pull request by bofrede**
Most HTML errors and warnings are fixed, with this pull request.
The validation was done using https://validator.w3.org/

This PR is sponsored by @semaphor-dk

### CODE REVIEW

**Comment by bofrede** [comment]
When this PR is merged #11517 can be closed too.

**Comment by saghul** [comment]
Thank you! Do you not get some broken UI in dialgos?

**Comment by bofrede** [comment]
I got a positioning problem with the button bar and the buttons were no longer square, but that was fixed in CSS, in the first commit of this PR.
If you see any other problems, please let me know how to reproduce the problem, and which browser and version you are using.

**Comment by saghul** [comment]
Thanks, I'll take a look shortly.

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
Looks good! Are you making more changes or should the be it?

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by saghul — APPROVED** [review]

**Comment by bofrede** [comment]
> Looks good! Are you making more changes or should the be it?

This is it. I haven't found any other layout issues.

**Comment by saghul** [comment]
Thank you!

**Comment by robertpin** [comment]
This breaks some UI elements (breakout rooms context menus, prejoin input and possibly others)
image
image

**Pull request merged**
