### PR TITLE
Feat/ordered raised hands list

### PR DESCRIPTION
**Pull request by bkrith**
**Overview**

- Provide an ordered list of the people that raised their hands

Currently, the functionality for raising hands is limited as it only displays a notification that someone raised their hand but moderators are not able to see who was the one who raised the hand first.

Our solution provides a list of the people that raised their hands, sorted by the time they have been waiting with their hand raised. This way, moderators can easily decide who should be the next person speaking.

Note: This PR is part of "Winning over the classroom with Jitsi" Hackathon

**How to enable**

This feature is planned to be enabled by default as you can see in our instance [https://open.youmeet.cloud/](https://open.youmeet.cloud/).

You must access the "Speaker Stats" window from the settings menu and you will see a new tab "Hands Raised" with the list of people that raised their hands and their waiting time, as you can see in the following screenshot:

**Demo instance**

An instance of Jitsi Meet with ordered raised hands list enabled is available at [https://open.youmeet.cloud/](https://open.youmeet.cloud/).

To try out this feature, use several browsers to join the same room on [https://open.youmeet.cloud/](https://open.youmeet.cloud/) and press the "Raise your hand" button at different times so you can get the list of people that have their hand raised and how long they have been waiting.

**What is included**

New tab in "Speaker stats" modal window with the list of people that have their hands raised.

**UI**
 
Speaker Stats replaced with 2 tabs dialog.

One tab with the Speaker Stats

and one tab with the raised hands list.

Red indicator in thumbnails/tiles for visual help.

Red indicator and hover waiting time in participants panel.

**Current Limitation**

The solution doesn't show how many people have their hands raised or the percentage of people with their hands raised or not.

**Future work (in follow up PRs)**

- UI/UX improvements.
- Have different hand colors available when raising the hand so people can vote for specific topics just selecting the hand color corresponding to the topic. For example people voting "Red" or "Yellow" in the picture below.

### CODE REVIEW

**Comment by bkrith** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

I have already signed CLA and just added the signed CLA email in my github account. Is this ok?

**Comment by gjaekel** [comment]
> The solution doesn't show how many people have their hands raised or the percentage of people with their hands raised or not.

@bkrith You may get inspriations from https://github.com/igniterealtime/openfire-pade-plugin/blob/master/src/webapp/custom_ofmeet.js#L1133-L1149

**Comment by marcoblancas** [comment]
@bkrith Great Job. I'm very happy with the result. It's a great feature I would love to be included in core.

I have recorded this video in order to present how it works.
https://youtu.be/HIXZm56EedM

Cheers.

**Comment by bkrith** [comment]
@marcoblancas Thank you very much for your feedback and the video.
I loved your idea with sums and percentage on the bottom. Will be included in our branch next commit for sure.

Cheers

**Comment by gjaekel** [comment]
@bkrith You may also add our CSS animation for the raised hand indicator. After a short time, it slowly changing between blue and red. And it's also a bit pulsating.

If you're in tile view mode in a conference with about 20++ participants, this will really help you to get notice of the raised hands.

```
@keyframes raisehand {
  from {
    background-color: #165ecc;
  }

  to {
    background-color: red;
    transform: scale(1.1);
  }
}

.raisehandindicator {
  animation-name: raisehand;
  animation-duration: 2s;
  animation-direction: alternate;
  animation-delay: 5s;
  animation-iteration-count: infinite;
}
```

**Comment by bkrith** [comment]
@gjaekel Thank you for your advices and code. Beautiful idea.

**Comment by gjaekel** [comment]
You may take a look at it on my evaluation installation; please ask floris for the URL and credentials.

**Comment by waja** [comment]
I would very welcome this feature.

**Comment by keunes** [comment]
Same here - just hoping this doesn't get lost in time, then rejected because it needs rebasing and the author lost interest 0:)

**Comment by saghul** [comment]
Sorry this fell through the cracks folks. It does need a rebase.

**Comment by AjayShivanagol** [comment]
Wow, When this feature will be in?

**Comment by alfredonodo** [comment]
Any update?

**Comment by keunes** [comment]
@bkrith Would you be able & willing to rebase, so @saghul can have a look? 😇 Thanks either way for your work!

**Comment by bkrith** [comment]
> @bkrith Would you be able & willing to rebase, so @saghul can have a look? 😇 Thanks either way for your work!

Hi! Sorry for the delay, I had some hard time in day job. I will rebase it this weekend for sure!

**Comment by bkrith** [comment]
@keunes @saghul I have rebased it.
Participant raisedHand(boolean) changed to object `raisedHand: { enabled: boolean, raisedAt: number }`
Improved search in SpeakerStats and RaisedHandStats.
I didn't implement anything for native. If we are happy with this, I will do it also.

**Comment by saghul** [comment]
Thanks! We'll run this by our product team and let you know!

**Comment by saghul** [comment]
Sorry everyone, my bad, completely missed updating this issue. Here is where things stand:

- As of right now, https://github.com/jitsi/jitsi-meet/commit/4b7a6741fa404ce980fab4e697eeb495c8dc64f0 changed the raise hand indicator to be a timestamp, so they are now in order!
- That order is how raised hand users are rendered in the participants pane
- I checked with Product and that's as far as we'd like to go at this stage. Adding extra duration indicators would clutter the UI quite a bit, and it's already UI heavy. Speaker Stats is also not something where we'd like to render raised hands for now 

This came at an unfortunate time, when we were working on the pane and many things were a bit in the air, now we have a clearer vision about it.

Apologies for the miscommunication here.

**Pull request closed without merging**
