### PR TITLE
Add option to open Etherpad on join

### PR DESCRIPTION
**Pull request by jeblair**
For sites that focus on collaborative editing during meetings, add
an option which, when set, will automatically open etherpad when a
participant joins.

### CODE REVIEW

**Comment by jeblair** [comment]
Hi, would you consider waiving the CLA requirement due to the very small size of this change?

If not, can you please let me know if Red Hat has signed the CCLA, so I can find out whether to ask for an amendment or an initial review?

Thanks.

**Comment by damencho** [comment]
> If not, can you please let me know if Red Hat has signed the CCLA, so I can find out whether to ask for an amendment or an initial review?

Nothing signed from Red Hat.

**Comment by Echolon** [comment]
@jeblair have you review the situation on this?

**Comment by jeblair** [comment]
The Red Hat legal folks have suggested that I consider this a personal contribution to avoid the overhead, so if you're happy with that, I'll rework the commit to indicate that and sign the CLA personally.

**Comment by jeblair** [comment]
Hi, I signed the CLA some time ago, how do we get the label on this PR changed?

**Comment by saghul** [comment]
This implementation does not consider mobile. It needs to, in order to be acceptable.

Also, please add the option to the whitelist.

**Comment by jeblair** [comment]
Thanks for looking at it.  I'll update it to address the whitelist.  I assume you're talking about the mobile app (as opposed to visiting in a mobile browser which works fine).  The app behaves a little differently: when a user opens the shared document, it takes over the whole screen, and there are no Jitsi controls or anything; a user would have to hit the back button in order to even verify that there is anyone else on the call on joining.  That may be a little surprising for users, so perhaps the status quo (where a user has to select "open shared document") is still the best behavior?  Or do you have any other suggestions for what we should do there?

Also, FYI, you can see this in action at https://meetpad.opendev.org/

**Comment by Echolon** [comment]
@saghul may you reply on the last comment?

**Pull request closed without merging**
