### PR TITLE
fix(notifications): support html descriptions

### PR DESCRIPTION
**Pull request by mihhu**
Fixes https://community.jitsi.org/t/browserwarning-popup-shows-object/110397/1

### CODE REVIEW

**Comment by mihhu** [comment]
Please Jenkins test this please.

**Comment by mihhu** [comment]
Please Jenkins test this please!

**Comment by gpatel-fr** [comment]
Thanks, the added comment in the renderDescription function is very welcome :-)

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
The test failures are unrelated, I have a PR which fixes them.

**Comment by damencho** [comment]
And they passed :)

**Pull request merged**
