### PR TITLE
minimized size without quality loss via optipng

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by PanderMusubi** [comment]
Just signed the icla.

**Comment by saghul** [comment]
Didn't we already apply this in https://github.com/jitsi/jitsi-meet/commit/fedaa0ae6e411e57fd46bcee5f8e0ccae173fe0c#diff-f63590810839501d1ccec9abde59d7b4 ?

**Comment by PanderMusubi** [comment]
I'm sorry, yes. Thought this was another one still outstanding.

**Comment by saghul** [comment]
No worries, thanks for being on the lookout!

**Pull request closed without merging**
