### PR TITLE
Duplicate favicon.ico's

### PR DESCRIPTION
**Pull request by tuncK**
I tried to eliminate one of the two copies.

### CODE REVIEW

**Comment by tuncK** [comment]
Already done before.

**Comment by tuncK** [comment]
Yes, I am aware of this and actually that is where I copied that line from. For some reason that I do not understand, the included line from title.html does not help for my case. To my understanding, this is what makes the server look for ./favicon.ico rather than images/favicon.ico

**Comment by damencho** [comment]
There are apps that need that html link tag.
So, I don't understand your PR then:
- you are duplicating an html tag which you say does not work for you
- and you say you see that just the icon in the main folder is needed, but you remove it from the source package

**Comment by tuncK** [comment]
Sorry, I should have been more clear.

BEFORE: On an Ubuntu server, the server looks for /usr/share/jitsi-meet/favicon.ico. The title.html does not seem to be included for an unclear reason, you can verify this by changing the title field to something else and observe no change. For that reason, `<link rel="icon" type="image/png" href="images/favicon.ico?v=1"/> ` line does not work, either.

AFTER: I duplicated that tag line to index.html, now the server looks for /usr/share/jitsi-meet/images/favicon.ico

I have a guess that this might have something to do with some incorrect path, because I just realized: L ` <!--#include virtual="title.html" -->` vs `<!--#include virtual="/interface_config.js" -->`. Will get back to you about this when I have a chance to check.

**Comment by tuncK** [comment]
The original fix that I proposed still works around the original problem. But, I checked the issue I mentioned above, and bingo! The Server Side Include commands do not work. This is from the index.html as delivered to the client:
```
   <script src="libs/lib-jitsi-meet.min.js?v=139"></script>
   <script src="libs/app.bundle.min.js?v=139"></script>
    <!--#include virtual="title.html" -->
    <!--#include virtual="plugin.head.html" -->
    <!--#include virtual="static/welcomePageAdditionalContent.html" -->
  </head>
```
For my own server, I circumvented this by providing a full directory for each SSIs (`<!--#include virtual=/usr/share/jitsti-meet/filename.html-->`). What is the proper way to fix the SSI configuration problem (of jetty)? I am using the latest jitsi-meet.deb out of the box on an Ubuntu 18.10 without Nginx or Apache.

**Comment by damencho** [comment]
Maybe default jetty config needs more resource declarations like this:
https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-web-config.postinst#L132

**Comment by tuncK** [comment]
Thanks for pointing to that. So, I fixed by adding an alias for title.html.

Jetty's SSIResourceHandler's search path does not seem to be set correctly, and based on the presence of other aliases for other included files, it has probably been a known problem for a while and I am leaving it as it is.

**Pull request closed without merging**
