### PR TITLE
Update for sq translation

### PR DESCRIPTION
**Pull request by ujdhesa**

### CODE REVIEW

**Comment by damencho** [comment]
Check out the tests, they are failing, I think, due to syntax errors.

**Comment by ujdhesa** [comment]
> Check out the tests, they are failing, I think, due to syntax errors.

I did. It complains about an unexpected string, but I see the string in main.json in line 74.
Any idea?

**Comment by damencho** [comment]
> > Check out the tests, they are failing, I think, due to syntax errors.
> 
> I did. It complains about an unexpected string, but I see the string in main.json in line 74.
> Any idea?

yes, you are missing a comma on the previous line

**Comment by ujdhesa** [comment]
> yes, you are missing a comma on the previous line
That was not the only one missing. My diff tool doesn’t flag missing comas.
I’ve fixed those and a few string changes now.
Thank you for the hint!!!

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Comment by ujdhesa** [comment]
@damencho Thank you for stepping up to help again!!!

**Pull request merged**
