### PR TITLE
fix(lang, shared-video): Reference to Youtube

### PR DESCRIPTION
**Pull request by wfleischer**
As you notice I only adjusted languages which I speak fluently.

### CODE REVIEW

**Comment by gpatel-fr** [comment]
I am only fluent in french, but as far as I understand english english, the translation for enGB:

        "shareVideoLinkError": "Please provide a correct youtube link.",
        "shareVideoLinkError": "Please provide a correct video link.",

is not coherent with the french translation:

      "shareVideoLinkError": "Veuillez fournir un lien YouTube correct.",
       "shareVideoLinkError": "Veuillez fournir un lien correct.",

because the english english translation preserves the link meaning (video), while it's lost in french translation.
My preference would go toward something more explicit, along the lines of:

       "shareVideoLinkError": "Veuillez fournir un lien de diffusion vidéo correct.",

but as you may know I'm not a contributor so feel free to ignore me.

**Comment by wfleischer** [comment]
> is not coherent with the french translation:
> 
> ```
>   "shareVideoLinkError": "Veuillez fournir un lien YouTube correct.",
>    "shareVideoLinkError": "Veuillez fournir un lien correct.",
> ```

Hey, thanks for reviewing. This is much appreciated.

You are citing from Canadian French. So are you specifically asking for Canadian French to be adjusted?

Btw: I would never dare to ignore you. I really appreciate your contribution. Continue to do so by translation or by any other means.

**Comment by gpatel-fr** [comment]
>>So are you specifically asking for Canadian French to be adjusted?

No, no ! I would never presume to speak Canadian French ! Non sum dignus. I misquoted. But the french translation has it  anyway. Possibly others. I don't know for sure.

**Comment by saghul** [comment]
Hey @wfleischer sorry for the delay here. We reorganized the lang files, sorry. Any chance you can rebase? If it's too much then just adjust English.

**Comment by wfleischer** [comment]
> Hey @wfleischer sorry for the delay here. We reorganized the lang files, sorry. Any chance you can rebase? If it's too much then just adjust English.

Thank you @saghul for considering this patch. We have users all over the world. So I could not withstand to rebase all touched languages. I really appreciate the new standardisation of the lang files using lang-sort. Thanks for all the good progress on this project!

**Review by saghul — APPROVED** [review]

**Pull request merged**
