### PR TITLE
fix(keyboard-a11y) Remove space from click trigger

### PR DESCRIPTION
**Pull request by robertpin**

### CODE REVIEW

**Comment by saghul** [comment]
👍 cal you pl add some explanation as to why we decided to do this, in the commit message?

**Comment by saghul** [comment]
Discussed it with Emil, we are going to skip this for now, and see if the other fix for blurring the selected element when the toolbox is hidden is enough in practice.

**Review by saghul — APPROVED** [review]

**Comment by damencho** [comment]
That is breaking push to talk. One of the problems if I recall correctly - we were seeing that the button was pressed multiple times one after another, which leads to a lot of other problems, like sending many packets to the server which are broadcasted, which triggers rate limiting of packets, which then leads to desync in the state of muted/unmuted state for the participants...

**Comment by saghul** [comment]
Is working with space part of WCAG?

**Comment by Leimi** [comment]
> That is breaking push to talk. One of the problems if I recall correctly - we were seeing that the button was pressed multiple times one after another, which leads to a lot of other problems, like sending many packets to the server which are broadcasted, which triggers rate limiting of packets, which then leads to desync in the state of muted/unmuted state for the participants...

Are you sure this fix is related to push to talk? Maybe I'm missing something.

From my understanding the push to talk code checks if anything is focused before triggering, so it shouldn't matter which key I use when I'm focused on a toolbox item: https://github.com/jitsi/jitsi-meet/blob/master/react/features/keyboard-shortcuts/actions.web.ts#L111-L114

But indeed, when I keep the space key pressed without having anything focused, the push to talk code is triggered 2 or 3 times a second until I stop pressing the key.

I feel what you are talking about is a push to talk code related issue, not associated with the fact we can activate any button via space.

> Is working with space part of WCAG?

No. To be WCAG friendly, only the Enter key is mandatory :)

But users on the web are used to having buttons work with both enter and space. And the Button ARIA design pattern (that I linked to earlier) lists the space key as requirement.

Here we offer something that looks like a button, that is announced by screen readers as a button, but that doesn't _totally_ act like a button.

I'm aware this is not the end of the world for sure but I'd love to understand better and see if we can fix everything while still keeping the space key to activate buttons.

**Comment by saghul** [comment]
> Are you sure this fix is related to push to talk? Maybe I'm missing something.

Yes, I'm aure. Here is the problem, which has 2 parts:

First, even when interacting with the toolbar using the mouse, the clicked element would be on focus, so if you mute / unmute and then press space you trigger the button action, not the PTT shortcut. This was further aggravated by the fact that we didn't clear the selected element even when the toolbar is hidden. That got fixed here: https://github.com/jitsi/jitsi-meet/commit/eda25ca3c9bdce4ef891c4b624c461f716d36d74

Even with that fix, if the toolbox is visible and the audio mute button was the last tone to be used, PTT can't work because it has the focus.

This is why we chose to drop the space from the action, since the shortcut for PTT has been around for close to a decade now.

> From my understanding the push to talk code checks if anything is focused before triggering, so it shouldn't matter which key I use when I'm focused on a toolbox item: https://github.com/jitsi/jitsi-meet/blob/master/react/features/keyboard-shortcuts/actions.web.ts#L111-L114
> 
> But indeed, when I keep the space key pressed without having anything focused, the push to talk code is triggered 2 or 3 times a second until I stop pressing the key.

That is because there is a focused element, after all.




> I feel what you are talking about is a push to talk code related issue, not associated with the fact we can activate any button via space.

Well, we want PTT to always work, because it's a global shortcut, if you have any ideas on how to accomplish that without breaking anything, we'd be happy.



> No. To be WCAG friendly, only the Enter key is mandatory :)

We had checked, but wanted to be extra sure ;-)



> I'm aware this is not the end of the world for sure but I'd love to understand better and see if we can fix everything while still keeping the space key to activate buttons.

Hopefully the above helps. The current solution is not cast in stone, happy to apply a different one, if it works. We had to take this approach because PTT is a widely used feature and our users and teammates started to complain about it being broken.

**Comment by Leimi** [comment]
Thanks for the feedback! I understand better now :) In my previous message, I forgot about mouse usage that focused things.

So if I get this right it means that any other button that listens for the space is also an issue, right? If the idea is that pressing space *always* works, even if an interactive element is focused.

Maybe a fix with a behavior like the [focus-visible polyfill](https://github.com/WICG/focus-visible#how-it-works) could help. What this does is check if the keyboard has been actually used, instead of relying only on focus events. I don't know. 

> > But indeed, when I keep the space key pressed without having anything focused, the push to talk code is triggered 2 or 3 times a second until I stop pressing the key.
> 
> That is because there is a focused element, after all.

Are you sure? When testing, the `document.activeElement` is body. From my pov it seems the problem is the PTT shortcut is registered like any other normal shortcut (behavior = "tap the key"), while it should handle the fact here the behavior = "press and hold the key".

Oh well anyways. Thanks, will maybe try to look for other solutions but know at least I get it :innocent:

**Comment by saghul** [comment]
> So if I get this right it means that any other button that listens for the space key is also an issue, right? If the idea is that pressing space _always_ works, even if an interactive element is focused.

Yep, any other button is an issue, it just manifests a bit more annoyingly so people noticed.



> Are you sure?

I'd have to re-test, but a quick glance at the code suggests that. 

> From my pov it seems the problem is the PTT shortcut is registered like any other normal shortcut (behavior = "tap the key"), while it should handle the fact here the behavior = "press and hold the key".

Might be because we handle keyDown vs keyUp...



> Thanks, will maybe try to look for other solutions but now at least I get it

Thank you!

**Pull request merged**
