### PR TITLE
Translation - complete and replace Greek translated strings

### PR DESCRIPTION
**Pull request by infl00p**
Hello Jitsi Meet team and Greek translators,
this PR is made to complete the missing strings for the Greek translation, replace mistakes and machine generated translations. 
It's an opinionated work, based on the needs of my community where we use Jitsi Meet, so I would like the other Greek translators to comment on this, before merging.

### CODE REVIEW

**Comment by infl00p** [comment]
> You need to sort the translations.

Is 'jq --sort-keys' enough?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/resources/lang-sort.sh

**Comment by damencho** [comment]
It is still failing.

**Comment by damencho** [comment]
Jenkins test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
