### PR TITLE
feat(end-meet-for-all) Trigger notifyReadyToClose event on end meetin…

### PR DESCRIPTION
**Pull request by horymury**
…g for all

### CODE REVIEW

**Review by saghul — DISMISSED** [review]

**Comment by saghul** [comment]
Watch out, the linter doesn't like you :-P

**Comment by horymury** [comment]
> Watch out, the linter doesn't like you :-P

linter smart :D May I get a reapprove?

**Review by saghul — APPROVED** [review]

**Comment by wfleischer** [comment]
@horymury: sorry for misusing this PR for a question. Is this part of a complete end-meeting-for-all feature? The reason I am asking is that I just finished a prosody module and the low level API part of such a feature. So I am wondering whether to continue and contribute or rather wait. Thanks for your fine work!

**Comment by damencho** [comment]
Yep this is part of a similar feature, but the rest of it is integrated into jaas and is a custom one that doesn't make sense to be here.

**Comment by wfleischer** [comment]
> Yep this is part of a similar feature, but the rest of it is integrated into jaas and is a custom one that doesn't make sense to be here.

Thanks, @damencho . That makes it clear.

**Pull request merged**
