### PR TITLE
feat(avatar) add ability to customize Gravatar base URL

### PR DESCRIPTION
**Pull request by saghul**
Also, default to libravatar.

Closes: https://github.com/jitsi/jitsi-meet/issues/4927

### CODE REVIEW

**Comment by saghul** [comment]
Depends on https://github.com/jitsi/js-utils/pull/44

**Comment by damencho** [comment]
I do not oppose this change, I'm just wondering about people's reactions where they had registered in gravatar and had put their avatars there and one day update jitsi-meet and find out that it is no longer working... What will be the avatar shown?

**Comment by saghul** [comment]
Lobtavatar anonymously proxies requests to gravatar, so this is a transparent change for users.

**Review by damencho — APPROVED** [review]

**Comment by njscop** [comment]
We are using Rocket Chat -> Jitsi integration with secure domain and jwt.
Rocket chat side we have users synced with LDAP and use default thumbnailPhoto as Avatar.

In jitsi stable it works as expected when you start meeting the avatar is the "thumbnailPhoto" from LDAP.

In jitsi-meet testing branch we get only the circle with "initials".

Looking at this thread where Damencho explains gravatar stuff: https://community.jitsi.org/t/where-is-image-coming-from/14760/6

I see that by default there is a lookup if E-mail is present.

Is it possible in Jitsi side to do something so that it continues to use thumbnailPhoto as it did previously?

**Pull request merged**
