### PR TITLE
fix(visitors): Fixes duplicated messages sent from guest domain.

### PR DESCRIPTION
**Pull request by eemehmet**

### CODE REVIEW

**Comment by eemehmet** [comment]
When visitor mode is enabled, messages sent from the guest domain are forwarded back to the participants.To avoid this, the check in `mod_fmuc.lua`, must be done with `local_domain` **(v1.meeet.jitsi)** instead `main_domain`**(meet.jitsi)**.
message from xmpp domain:
Screenshot 2023-10-06 at 14 33 39
message from xmpp guest domain:
Screenshot 2023-10-06 at 14 34 42

**Comment by damencho** [comment]
@eemehmet how do you reproduce the issue as I cannot reproduce it. We have seen this issue, but I'm trying to see in what case we hit it. 
Can you reproduce it on beta.meet.jit.si

**Comment by eemehmet** [comment]
> @eemehmet how do you reproduce the issue as I cannot reproduce it. We have seen this issue, but I'm trying to see in what case we hit it. Can you reproduce it on beta.meet.jit.si

Yep.
1. Start a conference on beta.meet.jit.si.
2. Join the conference on guest domain(another browser that not authenticated to beta.meet.jit.si) with 5 participants.
3. Now visitor mode is on.
4. Send a message from any guest-domain participant.

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Thank you for your contribution. Nice catch!

**Pull request merged**
