### PR TITLE
Added new mobile SDK delegate methods

### PR DESCRIPTION
**Pull request by imdatsolak**
# Added new mobile SDK delegate methods re onParticipantJoined, onParticipantLeft, onParticipantKicked

Added new Delegate methods to mobile SDK for iOS and Android:

## Android (Listener)
- onParticipantJoined
- onParticipantLeft
- onParticipantKicked

Also added these in JitsiMeetActivity.

## iOS
- participantJoined
- participantLeft
- participantKicked

Please check the source-code for documentation of the new delegate / listener methods.

### CODE REVIEW

**Comment by fritzfr** [comment]
@imdatsolak Great work, this is super helpful. I'm trying the same for onParticipantMuted/Unmuted, but having trouble finding the properties in the `PARTICIPANT_UPDATED` payload. Any ideas?

**Comment by imdatsolak** [comment]
> @imdatsolak Great work, this is super helpful.

Thank you, I really hope it gets merged some time soon...

**Comment by imdatsolak** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

This has been already signed and sent long time ago...

**Comment by imdatsolak** [comment]
@saghul Any news on this one? I have rebased my fork, no issues there. So, it would be highly appreciated if you could merge this PR

**Comment by imdatsolak** [comment]
Closing, as nothing happens and I have created a new PR

**Pull request closed without merging**
