### PR TITLE
fix(recording-label) Make REC label visible at all times

### PR DESCRIPTION
**Pull request by robertpin**
https://user-images.githubusercontent.com/11474153/126170310-6ddd9584-fecb-4d1f-b88f-f0a989f1db21.mov

### CODE REVIEW

**Comment by robertpin** [comment]
Jenkins please test this please.

**Review by horymury — CHANGES_REQUESTED** [review]

**Comment by horymury** [comment]
@robertpin   I notice you changed the behavior for hiding the header in meeting, now you use opacity for hiding stuff instead of sliding the header out of view. I can see why this was needed in order to keep rec label vizibile, but when the meeting is not in 'REC' state it looks a bit weird, as the toolbox slides out of view to the bottom, while the header slides out of view to the right so it does not look 'natural'. 

Think we need to confirm whether this is ok or not.

**Comment by robertpin** [comment]
> @robertpin I notice you changed the behavior for hiding the header in meeting, now you use opacity for hiding stuff instead of sliding the header out of view. I can see why this was needed in order to keep rec label vizibile, but when the meeting is not in 'REC' state it looks a bit weird, as the toolbox slides out of view to the bottom, while the header slides out of view to the right so it does not look 'natural'.
> 
> Think we need to confirm whether this is ok or not.

Reverted behaviour for non recording. Now the changes only applies when the recording label is used

**Review by horymury — APPROVED** [review]

**Comment by Freddie-m** [comment]
I think this could use some modification. The current behavior is **not** desirable. 

1. When the REC label is unhidden (now the default), Jibri captures the label in its recording and this shows in the recorded file. Definitely not desirable.
2. When the label is hidden using the config parameter, it's **_completely hidden from the interface_**. The preferred behavior would be for it to still show up for the set period of time and then autohide as in the previous implementation. The option should be between persistent or non-persistent, **not** persistent or non-visible.

Also, I now notice that the participant name is shown as a label on screen (and in recordings) in 2-party calls. I don't see any config parameter to toggle this option. Not sure if it's related to this REC label change.

Lastly, the conference title now shows up truncated in some clients (see screenshots):

Screen Shot 2021-07-30 at 12 05 19 AM
Screen Shot 2021-07-30 at 12 40 34 AM
_****_

**Comment by saghul** [comment]
>     1. When the REC label is unhidden (now the default), Jibri captures the label in its recording and this shows in the recorded file. Definitely not desirable.

Agreed. Jibri should "see" it.

>     2\. When the label is hidden using the config parameter, it's **_completely hidden from the interface_**. The preferred behavior would be for it to still show up for the set period of time and then autohide as in the previous implementation. The option should be between persistent or non-persistent, **not** persistent or non-visible.

Also agreed. I don't think we had the ability to completely hide the label previously.



> Also, I now notice that the participant name is shown as a label on screen (and in recordings) in 2-party calls.

Where is that displayed? Or do you mean the meeting name?



> Lastly, the conference title now shows up truncated in some clients (see screenshots):

That's correct, if there is not enough space for it.

**Comment by Freddie-m** [comment]
> Where is that displayed? Or do you mean the meeting name?

No, just above the toolbar - right around where closed captioning shows. I actually noticed it's not just in 2-party calls, but whenever the user is in stage view. See screenshot:

Screen Shot 2021-07-30 at 5 29 11 AM


> That's correct, if there is not enough space for it.

It's just 3 letters in this test though ("ABC"). In Chromium, when in stage view, the full title shows up, but in tile view, it gets truncated. Also, the participant count element disappears:

Screen Shot 2021-07-30 at 5 31 13 AM

**Comment by saghul** [comment]
> No, just above the toolbar - right around where closed captioning shows. I actually noticed it's not just in 2-party calls, but whenever the user is in stage view. See screenshot:

Right, @muscat1 just told me, this change happened while I was on leave :-)

> It's just 3 letters in this test though ("ABC"). In Chromium, when in stage view, the full title shows up, but in tile view, it gets truncated. Also, the participant count element disappears:

@muscat1 do you know anything about this one?

**Comment by muscat1** [comment]
> > It's just 3 letters in this test though ("ABC"). In Chromium, when in stage view, the full title shows up, but in tile view, it gets truncated. Also, the participant count element disappears:
> 
> @muscat1 do you know anything about this one?

I'm afraid I haven't been in that area, I can look into it next week if I have the time and if we choose to prioritize the task. It does seem weird, though 🤷🏻‍♂️

**Comment by Freddie-m** [comment]
> Right, @muscat1 just told me, this change happened while I was on leave :-)

Will there be an option to toggle it on/off?

FYI - These observations are in the latest unstable, so I presume they're probably not quite urgent right now. Just to keep them on the radar so they're looked at, at some point, before being pushed out to stable.

**Comment by saghul** [comment]
> Will there be an option to toggle it on/off?

Not sure TBH.

> FYI - These observations are in the latest unstable, so I presume they're probably not quite urgent right now. Just to keep them on the radar so they're looked at, at some point, before being pushed out to stable.

Sure thing! That's what unstable is for.

**Pull request merged**
