### PR TITLE
feat: Enable http2

### PR DESCRIPTION
**Pull request by otbutz**
Enable http2 for nginx as we do it for apache.

### CODE REVIEW

**Comment by damencho** [comment]
@saghul I see and docker is running like that. Do you see any problems with this?

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
LGTM!

**Comment by otbutz** [comment]
I'm not going to fill two pages of CLA to add two words in a config file.

**Comment by saghul** [comment]
I don't think we need it in this case, no worries.

**Comment by otbutz** [comment]
That's something that needs to be fixed and/or mitigated by nginx.

**Comment by saghul** [comment]
Indeed. You can also front the rocker setup with a proxy and make your own choices there. Ours tries to have some sane defaults.

**Pull request merged**
