### PR TITLE
fix(chat): added translation function

### PR DESCRIPTION
**Pull request by ilaydadastan**
added translation frunction to Private Message Button  https://github.com/jitsi/jitsi-meet/issues/14570

image

### CODE REVIEW

**Comment by damencho** [comment]
Hu, there are more places in the code like that, have you checked?

**Comment by damencho** [comment]
But most of them are native, so probably it is fine. But I see this one:
https://github.com/jitsi/jitsi-meet/blob/2d8014775a347d93ed7324fa4344714f5ac32796/react/features/chat/components/web/ChatButton.tsx#L30

**Comment by damencho** [comment]
But for some reason the Chat button is not a problem in the UI ...

**Comment by ilaydadastan** [comment]
Yes, I checked the entire project. In all class components, this is done with the withTranslation high order component. (https://react.i18next.com/latest/withtranslation-hoc ) So it works correctly where you mentioned. As for functional components, I could only find a deficiency here.

**Comment by damencho** [comment]
Thank you

**Pull request merged**
