### PR TITLE
feat(android): hermes and react native are synced

### PR DESCRIPTION
**Pull request by Calinteodor**

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by mesutaltuncu** [comment]
Is there a Beta version available on the Google Play Store with Hermes enabled?

**Comment by saghul** [comment]
Yes, the current beta in the Play Store uses Hermes indeed.

**Comment by mesutaltuncu** [comment]
The splash time duration seems to have increased during the beta period. In the non-beta version, I observed a shorter splash time duration.

**Comment by saghul** [comment]
That's what we observed back in the day wqhen we 1st tried Hermes too. Which is surprising, because it's supposed to provide better loading times 🤷

That said, the reason for migrating is also that JSC on Android is not getting any updates and won't support 16KB memory page sizes, as required by Android 15.

**Pull request merged**
