### PR TITLE
fix(local-recording) Add framerate

### PR DESCRIPTION
**Pull request by robertpin**

### CODE REVIEW

**Review by saghul — DISMISSED** [review]

**Comment by saghul** [comment]
Can you pl also add the high quality audio constraints?

**Comment by robertpin** [comment]
> Can you pl also add the high quality audio constraints?

Aa, which ones?

**Comment by saghul** [comment]
Check ScreenObtainer in LJM. The ones we have for share audio.

Sorry I'm walking in my phone or I'd paste a link :-)

**Comment by robertpin** [comment]
> Can you pl also add the high quality audio constraints?

Done

**Review by saghul — APPROVED** [review]
🚀

**Pull request merged**
