### PR TITLE
update ljm 1711487532

### PR DESCRIPTION
**Pull request by damencho**
- feat: Reduces into state region and shard changes from the lib.
- squash: Fixes few comments.
- chore(deps) lib-jitsi-meet@latest

### CODE REVIEW

**Review by saghul — COMMENTED** [review]
We need to cleanup the state when the connection ends, since on mobile state is preserved across calls.

**Comment by damencho** [comment]
But isn't mobile already doing that when moving from one config to another? I'm just updating the values, that we already have in the state. If those are not cleaned up on mobile, my changes are not a regression, it was a bug and before.

**Comment by damencho** [comment]
The PR is https://github.com/jitsi/jitsi-meet/pull/14546

**Comment by damencho** [comment]
We already clean the config in reducer in _setConfig.

**Pull request closed without merging**
