### PR TITLE
Allows to also import peertube videos

### PR DESCRIPTION
**Pull request by b4zz4**
I add regular expression to peertube

### CODE REVIEW

**Comment by saghul** [comment]
Have you tested this? Last I checked PeerTube does have the ability to embed them within an iframe, but the API is specific to PeerTube, and this way you'd try to use the YouTube API.

**Comment by b4zz4** [comment]
I thought jitsi used a browser for this, not youtube's api.

**Comment by saghul** [comment]
It uses the YouTube iframe API.

**Comment by b4zz4** [comment]
There is a way to call the iframe without using youtube API.
I could add peertube's autoplay control and ready

**Comment by atulraj85** [comment]
Yes! there should be peertube too in Jitsi.

**Pull request closed without merging**
