### PR TITLE
fix(screenshot-captue): get the right worker url

### PR DESCRIPTION
**Pull request by gabiborlea**

### CODE REVIEW

**Review by saghul — DISMISSED** [review]

**Comment by gabiborlea** [comment]
had some errors with typescript, can u pl recheck @saghul

**Comment by gabiborlea** [comment]
added a ts-ignore there

**Comment by gabiborlea** [comment]
or should I add this: https://stackoverflow.com/questions/2313620/is-it-possible-to-retrieve-the-last-modified-date-of-a-file-using-javascript?

**Comment by gabiborlea** [comment]
@saghul

**Pull request merged**
