### PR TITLE
Add isomorphic environment variables support #7290

### PR DESCRIPTION
**Pull request by shapkarin**
Hello. Thanks to bot's (stale) notify. I create this PR and hope this may help to make environment variables more handy. It's isomorphic so can be used at any part of this project - webpack and client side as well. For example to set `WEBPACK_DEV_SERVER_PROXY_TARGET`. I'm sure that it's pretty secure way. Please check and share your thoughts.

ref: #7290

### CODE REVIEW

**Comment by saghul** [comment]
We don't use this type of configuration on the client side and adding it just for a single env var feels unnecessary.

**Comment by shapkarin** [comment]
@saghul got that. But I suggest that for other variables.

**Comment by saghul** [comment]
Like which ones?

**Comment by shapkarin** [comment]
like some domains, for example JWT auth service domain or some other third party things.

**Comment by shapkarin** [comment]
@saghul the goal was to have such things at the client side in runtime.

**Comment by saghul** [comment]
We don't want to have that baked into the app but handled externally, see the Docker setup.

**Comment by shapkarin** [comment]
@saghul OK

**Pull request closed without merging**
