### PR TITLE
fix(theme) Fix tokens

### PR DESCRIPTION
**Pull request by robertpin**
Fix elements to use correct tokens

### CODE REVIEW

**Review by quitrk — DISMISSED** [review]

**Review by Calinteodor — CHANGES_REQUESTED** [review]
Please check if mobile buttons look visible and nothing changed about their appearance.

**Comment by robertpin** [comment]
Jenkins test this please

**Comment by saghul** [comment]
Needs a rebase now.

**Review by Calinteodor — APPROVED** [review]

**Comment by jluisfa** [comment]
Low contrast of the font colors not fixed in Lobby mode.
Tested on alpha jitsi net

See https://github.com/jitsi/jitsi-meet/issues/11838#issuecomment-1185402851

**Pull request merged**
