### PR TITLE
Adding isSharingScreen() to external API

### PR DESCRIPTION
**Pull request by sretika**
Adding isSharingScreen() to external API

### CODE REVIEW

**Comment by sretika** [comment]
CLA signed

**Comment by jallamsetty1** [comment]
> CLA signed

Hey there, thank you for your contribution. Can you please let me know the full name used in the signed CLA, I am trying to look it up.

**Comment by jallamsetty1** [comment]
Jenkins pls test this pls

**Comment by sretika** [comment]
> > CLA signed
> 
> Hey there, thank you for your contribution. Can you please let me know the full name used in the signed CLA, I am trying to look it up.

That would be Samuel Retika

**Pull request merged**
