### PR TITLE
change websocket url from http:// to ws://

### PR DESCRIPTION
**Pull request by TobiasKneidl**
I had to change the websocket URLs from http:// to ws:// to get websocket working with apache

### CODE REVIEW

**Comment by TobiasKneidl** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Done.

**Comment by nagmat84** [comment]
Just wanted to point to [this post}(https://community.jitsi.org/t/javascript-console-full-of-websocket-errors-with-http-code-404-not-found/92768/5). You also need the `mod_proxy_wstunnel` to be enabled in Apache and it is not necessary to have the regex.

**Comment by damencho** [comment]
@jotoeri Why http was working for you but not for @TobiasKneidl and @nagmat84? Did you have mod_proxy_wstunnel enabled?

**Comment by TobiasKneidl** [comment]
@damencho I had to enable proxy_wstunnel also. But with http:// it didn't work. Not until I've enabled proxy_wstunnel and change the url to ws://.

**Comment by damencho** [comment]
Is that module coming with default apache install? So then maybe that needs to be added here: https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-web-config.postinst#L221

**Comment by TobiasKneidl** [comment]
Yes, I will make a PR.

**Comment by jotoeri** [comment]
Hey Guys,

interesting. For me, it seems to work with the given configuration. I didn't check for active communication logs, but i didn't see any errors and our jitsi-instance works mostly. What would be the result if it did not work, @damencho ? I assume without videobridge, jitsi conferences do not work at all (except p2p)?
- Concerning my setup: Yes, mod `proxy_wstunnel` is active, however i **disabled** the websocket completely in `.../videobridge/jvb.conf` as we had certificate issues on browser-console using wss and as i saw the nginx config using http and port 9090.
- Very much of the change, i took from [this forum thread](https://community.jitsi.org/t/colibri-ws-websocket-not-working/88117/11). In difference to the thread, i used http - as i said, just as nginx-config does so: https://github.com/jitsi/jitsi-meet/blob/c856c2051331ee1234b26d3931a2a870c352eff9/doc/debian/jitsi-meet/jitsi-meet.example#L96

Greets,
Jonas

**Comment by damencho** [comment]
> What would be the result if it did not work, @damencho ?

The lowest resolution 180p, no dominant speaker, and no remote participant stats.

**Review by damencho — APPROVED** [review]

**Pull request merged**
