### PR TITLE
feat(external_api): Control participant volume

### PR DESCRIPTION
**Pull request by izakgl**
Participant volume is now stored in redux. Includes a command to set participant volume via iframe api.

### CODE REVIEW

**Comment by izakgl** [comment]
There are 2 things that I'm unsure about:
1. I stored participant volume in redux store features/base/participants. I think it fits ok here and don't know if there is a better place for this.
2. Is forcing the volume between 0 and 1 ok? I think that is the standard range for the volume.

**Comment by jmcclelland** [comment]
This change would really help us build a simultaneous interpretation feature using the iframe API method.

**Comment by jmcclelland** [comment]
Hi again - Here's working code that provides a slider for simultaneous interpretation in a Jitsi Meet conference: https://gitlab.com/mfmt/jsi using the Iframe API.

But, it depends on this pull request being merged. I hope it can be reviewed and merged.

Thanks for all the great work on Jitsi Meet!

**Comment by jmcclelland** [comment]
@izakgl - any chance you could rebase against jitsi-meet_6173? I tried to apply your patches and made it through all the conflicts until I got to `react/features/filmstrip/components/web/Thumbnail.js` - and there I got in over my head. We've been using your patches in production all summer - 2 - 3 meetings per week - with amazing results. But now we're hitting some stability issues with the older version of Jitsi Meet - yet we can't upgrade without these patches. 

Thank you!

And @saghul - if there is any way these commits could make it into stable it would be a huge advance for language tools in Jitsi Meet.

**Comment by saghul** [comment]
Oops, looks like this one fell through the cracks, sorry about that. Can you please rebase this @izakgl ?

**Comment by izakgl** [comment]
Rebased. This is now a lot smaller change since participant volume was moved to redux in another PR.

**Comment by damencho** [comment]
Ok jenkins test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
