### PR TITLE
update react-emoji-render to v1.2.3

### LINKED ISSUE #6501: JitsiMeet chat too eager to convert to emoji
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I stumbled on this while trying to share a URL on the JitsiMeet chat.

## Current behavior
Anything that could be assimilated to an emoji is converted.

## Expected Behavior
I wouldn't expect a subset of a word to be converted. For example, the following should not get any conversion:

https://wiki.example.com/doku.php?id=appliweb:pleroma

Yet on JitsiMeet current result is:

https://wiki.example.uk/doku.php?id=appliweb
😛leroma

## Possible Solution
I think a simple fix would be to ensure that only emoji either at the beginning of the line or after a white space should be evaluated. 

## Steps to reproduce

Sharing anything that contain a sequence that could be assimilated to an emoji. Example:
```
https://wiki.example.com/doku.php?id=appliweb:pleroma
```
# Environment details
Latest Debian repo stock install.

### PR DESCRIPTION
**Pull request by obfusk**
Fixes #6501.

### CODE REVIEW

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
The test failures look legit, have you tested this on Firefox?

**Comment by obfusk** [comment]
I hadn't tested with Firefox. Oops. I keep forgetting Firefox has terrible regular expression support :(
I'll get the library fixed and then make a new PR.

**Comment by saghul** [comment]
Excellent!

**Pull request closed without merging**
