### PR TITLE
The "t" key should not mute people.

### PR DESCRIPTION
**Pull request by bickelj**
For some reason the t key would always mute me in jitsi-meet whenever I made a new tab.

This PR removes that behavior. Not really sure about the second part of the code change if it was needed or not.

### CODE REVIEW

**Comment by bgrozev** [comment]
This removes the push-to-talk functionality...

**Comment by bickelj** [comment]
Oh, my mistake.

I did not know there was such a feature.

Perhaps it can be reworked to have "t" key do something when "Mute" has been enabled.

**Comment by bgrozev** [comment]
Do you mean to do something when mute has **not** been enabled? 
I don't know what other people think, but personally I like the current behavior. I tend to use "t" whenever I want to mute and only speak occasionally. When I press it, I don't always pay attention to whether I am muted, and I assume that after I un-press I will be muted.

Opening a new tab with ctl/cmd+t shouldn't trigger it, though (it doesn't for me). Maybe you should find out why that happens with your browser.

**Comment by bickelj** [comment]
My comment was to change the software behavior from "whenever T is touched, after it is released I go into mute mode" to "if muted, whenever T is touched, after it is released I go into mute mode."

Or, I guess alternatively, "If, whenever T is touched, after it is released I go into whatever mode was previously enabled."

Ctrl-T in Abrowser (Firefox) 44.0.2 causes mute to happen, and I don't see that it happened because the new tab is up.

In Iridium (Chromium) 46.0 Ctrl-T doesn't cause mute.

So I guess it could be a Firefox compatibility thing.

**Comment by bgrozev** [comment]
> My comment was to change the software behavior from "whenever T is touched, after it is released I go into mute mode" to "if muted, whenever T is touched, after it is released I go into mute mode."

Yes, understood. My point was that when I use push-to-talk I don't always pay attention to the mode I'm in when I press "t", but I expect to be muted when I release.

**Comment by bickelj** [comment]
> My point was that when I use push-to-talk I don't always pay attention to the mode I'm in when I press "t", but I expect to be muted when I release.

It makes sense.

**Pull request closed without merging**
