### PR TITLE
fix(carmode) Force portrait when in carmode

### PR DESCRIPTION
**Pull request by horymury**

### CODE REVIEW

**Review by saghul — CHANGES_REQUESTED** [review]
Left some comments, PTAL

**Comment by horymury** [comment]
> Left some comments, PTAL

@saghul  addressed.

**Comment by quyenvsp** [comment]
@horymury 
this merge added wonday/react-native-orientation-locker which not stable I think. when my app using sdk build with this feature running on Samsung device will got crash right after join room because https://github.com/wonday/react-native-orientation-locker/issues/206

**Comment by saghul** [comment]
What commit did you build? We have fixed that issue on our end.

**Comment by quyenvsp** [comment]
Yeah thank you so much for information, I uasually use Stable tag. so latest is stable/jitsi-meet_7882. I am going to use master now 👍

**Comment by saghul** [comment]
Stable tags are for the web, they are not mobile stable.

We just released a stable SDK with the tag android-sdk-6.2.1 it's got an annoying bug which we'll fix on Monday though 😅

**Pull request merged**
