### PR TITLE
fix: Fixes and adding some translations to spanish

### PR DESCRIPTION
**Pull request by ebadilla10**
I realized that the change for Mute Everyone Else doesn't have the spanish dialogues, I added it and also some another typos.

Signed-off-by: Esteban Badilla A <ebadilla10@gmail.com>

### CODE REVIEW

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
Gracias Eduardo!

**Comment by ebadilla10** [comment]
Esteban* ;)

**Comment by saghul** [comment]
> Esteban* ;)

🤦‍♂

**Comment by saghul** [comment]
Gracias Esteban!

**Pull request merged**
