### PR TITLE
feat(api): add toggleCamera action

### PR DESCRIPTION
**Pull request by keremoge**
add **toggleCamera** action to be able to toggle Camera Facing Mode programmatically

### CODE REVIEW

**Comment by saghul** [comment]
@tmoldovan8x8 can you PTAL?

**Comment by keremoge** [comment]
Can we consider this or no chance? @saghul

**Comment by saghul** [comment]
Sure thing, sorry it fell through the cracks. Can you please rebase it?

**Comment by keremoge** [comment]
it is ready now

**Comment by saghul** [comment]
Can you please tame the linter?

**Comment by keremoge** [comment]
> Can you please tame the linter?

sorry, forgot to lint, fixed

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Pull request merged**
