### PR TITLE
Breakout Rooms

### PR DESCRIPTION
**Pull request by saghul**
Continuation of https://github.com/jitsi/jitsi-meet/pull/9131

PLEASE stop asking when this will be ready. It will be ready when it's ready.

### CODE REVIEW

**Comment by luddilo** [comment]
Exciting to follow the progress on this. Question to you @saghul: once this is merged, how does a roll-out to the Jitsi-as-a-service offering look like?

**Comment by saghul** [comment]
Usually JaaS gets deployed a bit later, once we have gathered some production experience with it.

**Comment by hacktivista** [comment]
I'm sorry to post here as if it were a forum, but I've been following this issue (and the previous one) for a good while, let me say it: this is absolutely great. And I appreciate a lot the great efforts being made to bring it into a stable reality. I appreciate a lot what you're doing guys. Keep up the good work!

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by robertpin — APPROVED** [review]

**Review by robertpin — APPROVED** [review]

**Comment by saghul** [comment]
This has landed! Once again I'd like to thank @wfleischer for all the work here! ❤️ 🚀

**Comment by wfleischer** [comment]
Thanks to @saghul and the brilliant minds of the Jitsi team! Without their encouragement and help this would not have been possible.

**Comment by ImaCrea** [comment]
amazing! can't wait to test :) thank you so much for your contribution

**Comment by smith476** [comment]
Dear Werner, Dear Jitsi team!
many thanks for this great feature, want to test it asap...

**Comment by saghul** [comment]
Should already be available in the unstable Debian packages from our repo.

**Pull request merged**
