### PR TITLE
fix(toolbar): Re-add "mute everyone's video" button

### PR DESCRIPTION
**Pull request by vp8x8**

### CODE REVIEW

**Comment by saghul** [comment]
Can you add it to mobile as well please?

**Comment by vp8x8** [comment]
> Can you add it to mobile as well please?

Done.

**Review by Calinteodor — DISMISSED** [review]

**Comment by vp8x8** [comment]
@saghul I have added the dialog but the functionality does not work in the simulator. Do yo have any idea why?

**Comment by saghul** [comment]
Thanks Vlad! Let me check.

**Comment by saghul** [comment]
This feature is reasonably recent and hasn't been deployed on meet.jit.si. Alpha works, so LGTM.

**Review by saghul — APPROVED** [review]

**Pull request merged**
