### PR TITLE
feat(Filmstrip): Collapse filmstrip to avoid toolbar overlap on mobile

### PR DESCRIPTION
**Pull request by muscat1**
Screen Shot 2021-07-06 at 11 24 34

### CODE REVIEW

**Review by hristoterezov — CHANGES_REQUESTED** [review]
I tested the PR and I see weird effect: We try to center vertically the filmstrip if there is empty spaces. Now when you free more space for the filmstrip there we position it again in the middle of the screen and practically the toolbar still covers the thumbnails. Also this makes the animation a little weird.

On the other hand I don't see the same thing on your screenshots. Did I missed to deploy something or maybe something changed during the rebasing of the PR?

Also I'm wondering don't we want something similar for desktop if the screen is very small? I guess this would be happening if somebody is using the iframe API and limit the width a lot. Although the toolbar looks different on desktop....

**Comment by muscat1** [comment]
From my understanding, the intent was for the toolbar to not cover the bottom tiles, therefore you need to scroll down to the bottom, if the filmstrip is larger than the viewport, and then you should see it working. Even in my screenshot, you can see I am actually scrolled all the way to the bottom, and those tiles are not covered by the toolbar. I have deployed this commit to my lonely (mihai.jitsi.net) so you can test it out there if you like.

**Comment by muscat1** [comment]
As a bit of a follow-up, I can see what you mean, by testing it in Chrome it looks like that to me too - some available space and we reduce the filmstrip size. That's because there wouldn't be enough room for the toolbar to fit together with the filmstrip (filmstrip + toolbar size > available height) so we need to reduce the filmstrip size in order to enable the toolbar to be displayed, at least that's how I thought it should behave, but any other proposals are welcome.

**Comment by hristoterezov** [comment]
I don't have any issue with the approach. See the following screenshots:
Screenshot_20210715-181442_Chrome
Screenshot_20210715-181224_Chrome


Th first one is with toolbar hidden. The second one is with toolbar displayed. Do you see the gap on the top of the toolbar displayed screenshot? So I think the position of the filmstrip is not correct because we try to center it. Additionally because of this the animation when we show the toolbar looks weird because of the gap and the centering - the filmstrip jumps a little.

**Comment by muscat1** [comment]
Jenkins please test this please.

**Comment by hristoterezov** [comment]
Now it works great when you have enough participants to fill the whole screen. But I noticed strange behaviour when you have less participants:
Screenshot_20210719-143816_Chrome

There are big gaps on the top and bottom and in the same time there are scrollbars. I think in this use case we don't need to collapse anything. Maybe there is a problem with the `filmstripOverflows` check.

**Comment by muscat1** [comment]
Jenkins please test this please.

**Review by hristoterezov — APPROVED** [review]

**Pull request merged**
