### PR TITLE
Added BrowserStack Logo to Readme

### PR DESCRIPTION
**Pull request by naineet**
Hi,

Thanks for signing up for our open source program! We hope you’ve found it valuable. 

Open source projects like yours power the world of tech, and we’re honored to be helping you. We’ve benefitted from hundreds of open source projects, and now's our time to give back.

I have added BrowserStack Logo under “Testing powered by” heading to the Readme

This helps us reach more open source developers like you, ones who can use BrowserStack’s infrastructure for free and build great products.

Naineet Patel
BrowserStack DevRel

### CODE REVIEW

**Comment by saghul** [comment]
How is our testing powered by BrowserStack?

**Comment by naineet** [comment]
Hi Saghul,

Sure even that works. 

I have updated the PR. Let me know if this is what you had in mind?

**Comment by saghul** [comment]
I'm very confused. AFAIK none of our testing uses BrowserStack in any way. Maybe someone on the team gave it a go at some point?

**Comment by naineet** [comment]
Hi @saghul,

I re-checked and yes, you are correct one member gave it a try recently but if the project is not using it on Production; then this is not required.

Hence, I will close the PR. Sorry if it caused any inconvenience. 

Thank you for your time.

**Comment by saghul** [comment]
No worries!

**Pull request closed without merging**
