### PR TITLE
lang: sort json keys

### PR DESCRIPTION
**Pull request by csett86**
This is the result of

    find lang -name "*.json" | while read file; do
      echo "Standardizing ${file}"
      t=$(mktemp)
      jq --indent 4 -S "." ${file} > ${t}
      mv ${t} ${file}
    done

### CODE REVIEW

**Comment by saghul** [comment]
Ah sorry about the conflict, can you rebase pl?

**Comment by csett86** [comment]
Rebased to master

**Review by saghul — DISMISSED** [review]

**Comment by csett86** [comment]
Don't merge yet, I accidentally missed --indent 4, will resubmit

**Comment by csett86** [comment]
Now its good to go

**Comment by csett86** [comment]
(I mangled the commit message, thus repushed same diff with fixed commit message)

**Review by saghul — APPROVED** [review]

**Pull request merged**
