### PR TITLE
feat(overlay) drop permissions overlay

### PR DESCRIPTION
**Pull request by saghul**
It covers the entire meeting and it's not helpful. A different version of the same concept might be implemented using less intrusive UX, like a modal.

### CODE REVIEW

**Comment by damencho** [comment]
Hum, shouldn't we implement that modal first? So, with dropping it, what are we going to show? It will be just the browser prompt, and you can still enter a meeting by ignoring the browser prompt. If you later allow access to the browser, will it automatically turn on video for you, although you did not see any video on pre-join because of missing permissions?

**Comment by saghul** [comment]
The prompt is pretty "in your face" already. And now we have pre-join enabled by default. None of this was true a few years ago so it was easier to miss.

If you enter a meeting without granting permission and you grant it later, the obvious expectation is that yes, you'll enable the camera.

**Comment by saghul** [comment]
Let's discuss, @yanas was ok with landing this first.

**Comment by damencho** [comment]
@hristoterezov You are right you cannot land into the situation I was saying is possible.

**Comment by damencho** [comment]
@saghul we discussed it, and I tested it and we show the spinner for configuring devices and even if you try dismissing the dialog many times we end up with audio video muted and it will never turn on after giving permissions. After changing the permission the browser (chrome) ask you to reload the page because of the page. You can trigger in some situation the permissions prompt if you try to unmute video, which is what we want.

**Comment by damencho** [comment]
Testing now in FF, you cannot join till gum timeout or you allow/block mic permissions. And by default do not ask you about  video permissions.

**Comment by damencho** [comment]
In Safari the browser permissions do not allow you to join. It never timeouts ... so no choice there.

**Review by damencho — APPROVED** [review]

**Comment by saghul** [comment]
🙌🙌

**Pull request merged**
