### PR TITLE
fix(av-moderation) Don't stop local screensharing on mute all

### PR DESCRIPTION
**Pull request by robertpin**

### CODE REVIEW

**Comment by damencho** [comment]
Wasn't this functionality your are disabling added with https://github.com/jitsi/jitsi-meet/pull/9989 ?

**Comment by robertpin** [comment]
> Wasn't this functionality your are disabling added with #9989 ?

No. That one was for Stop all video. The problem this one fixes is that Mute all (audio) stops screensharing

**Comment by damencho** [comment]
But then why when Mute all audio is executed we pass stopScreenSharing as true to this function?

**Comment by robertpin** [comment]
You make a good point. I changed it

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
I'm fixing the grid and once that is fixed and tests pass, I will merge it.

**Comment by damencho** [comment]
Jenkins, test this please.

**Pull request merged**
