### PR TITLE
fix(blur on sharescreen): Disable blur on sharescreen.

### PR DESCRIPTION
**Pull request by tudor-phd**

### CODE REVIEW

**Comment by saghul** [comment]
This one can be a bit tricky. As a user, if I had blur on and toggled screen sharing and then stopped I'd expect to still have it on.

Then there is an interesting corner case: what if you enable your video during screen-sharing? We don't have plans to enable blur there, but cut you off the background instead. We're not there yet, which means your background will be visible, albeit in a small section. I think this is a reasonable compromise.

So, let's make sure we turn blur back on if it was enabled before screen-sharing started please.

**Comment by jallamsetty1** [comment]
We need a better solution for fixing all the other cases where switching of streams is involved. This PR fixes the case when the user switches to screenshare when the blur is still enabled. However, if the user mutes video when blur is enabled, then switches to a different camera and tries to unmute, client doesn't switch to the new camera. So blur needs to be toggled off when the camera track is removed from the peerconnection (video mute also removes the track from the peerconnection) and it needs to be toggled back on when the any camera track is added back to the peerconnection.

**Review by jallamsetty1 — CHANGES_REQUESTED** [review]
We need a better solution for fixing all the other cases where switching of streams is involved. This PR fixes the case when the user switches to screenshare when the blur is still enabled. However, if the user mutes video when blur is enabled, then switches to a different camera and tries to unmute, client doesn't switch to the new camera. So blur needs to be toggled off when the camera track is removed from the peerconnection (video mute also removes the track from the peerconnection) and it needs to be toggled back on when the any camera track is added back to the peerconnection.

**Comment by saghul** [comment]
I think I have solved this by accident here: https://github.com/jitsi/jitsi-meet/pull/8788/commits/989b15a0d86f51fd124ee494af7d8bb0001264fb#diff-0ed756c1dec5e6ffe4782a500c0be72d0c71c18cfd0d4f73f5e44cd78e5b5d3cR19

**Comment by jallamsetty1** [comment]
> I think I have solved this by accident here: [989b15a#diff-0ed756c1dec5e6ffe4782a500c0be72d0c71c18cfd0d4f73f5e44cd78e5b5d3cR19](https://github.com/jitsi/jitsi-meet/commit/989b15a0d86f51fd124ee494af7d8bb0001264fb#diff-0ed756c1dec5e6ffe4782a500c0be72d0c71c18cfd0d4f73f5e44cd78e5b5d3cR19)

I am not sure if this change fixes all the issues around virtual backgrounds and changing of tracks while the video is muted. The root cause of the issue is that when the video is muted, we set the `stream` on the JitsiLocalTrack to `null`. Any replaceTrack operation for the local video will result in an error if the effect is not toggled off before the video mute because the client tries to stop the effects before disposing the track after it is replaced on the peerconnection. It is here https://github.com/jitsi/lib-jitsi-meet/blob/676c7a910505833810314a665ad1e825a158850c/modules/RTC/JitsiLocalTrack.js#L355 that the client throws an exception because the `stream` has been already been set to `null` when the local video was muted.

**Pull request closed without merging**
