### PR TITLE
add a build script in js to support cross-platform build.

### PR DESCRIPTION
**Pull request by vipcxj**
The script test success on window. And the script may require node >= 10.

### CODE REVIEW

**Comment by vipcxj** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Signed.

**Comment by vipcxj** [comment]
`cross-env` should be add to the dev dependencies, If we want to provide a cross-platform env to the command. But this is not the part of this pull-request.

**Comment by saghul** [comment]
I'm not sure we want to replace the current Makefile. At the same time I get that this being a JS application having the build script also in JS is one less barrier for contribution, so I'm +0.5 at this time.

Now, in order to make sure this can move forward we'd need the Makefile to reroute the commands to this script, so people (and our automation) can continue to use it without risking going out of sync.

**Comment by vipcxj** [comment]
> I'm not sure we want to replace the current Makefile. At the same time I get that this being a JS application having the build script also in JS is one less barrier for contribution, so I'm +0.5 at this time.
> 
> Now, in order to make sure this can move forward we'd need the Makefile to reroute the commands to this script, so people (and our automation) can continue to use it without risking going out of sync.

My plan is not to replace the Makefile, just provide a cross-platform way to build. because makefile not work on windows. Even using nmake, the command in makefile not work on windows. 
I think most command to start a webpack dev server is platform independent，and can be exec by js or coding in js.

**Comment by saghul** [comment]
What I meant is that the Makefile should call this script, to avoid going out of sync.

**Pull request closed without merging**
