### PR TITLE
fix(participants-pane): leave breakout room button appearance

### PR DESCRIPTION
**Pull request by wfleischer**
Additionally refactoring to TypeScript and using the new button component. Also refactoring the add breakout room and auto assign buttons to TypeScript.

Before
After

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by wfleischer** [comment]
Hey @saghul. Let me know if anything is pending here. Cheers!

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Sorry for the delay!

**Comment by wfleischer** [comment]
Thank you, @saghul. No worries. I am certainly not the only one bugging you. I appreciate very much your hard work!

**Pull request merged**
