### PR TITLE
fix(reactions) Batch events before sending

### PR DESCRIPTION
**Pull request by robertpin**
Batch events before sending
Added keyboard shortcuts in tooltips
Added amplitude events

### CODE REVIEW

**Comment by robertpin** [comment]
Jenkins please test this please.

**Comment by robertpin** [comment]
Jenkins please test this please.

**Comment by robertpin** [comment]
Jenkins please test this please.

**Comment by robertpin** [comment]
Jenkins please test this please.

**Comment by robertpin** [comment]
Jenkins please test this please.

**Review by muscat1 — APPROVED** [review]

**Pull request merged**
