### PR TITLE
Update TileView.js

### PR DESCRIPTION
**Pull request by qwertiko**
set video tile aspect ratio in app to 16:9 like it's standard in browser

### CODE REVIEW

**Comment by saghul** [comment]
I'm not sure we want to do this outright. It probably makes the tiles quite small at the very least on portrait mode, doesn't it?

**Comment by qwertiko** [comment]
The change to allow 16/9 format arose when realising that data is simply missing for mobile clients.
The size is not such an issue on tablets or when only a few people are in the room.

Making this a configurable setting would let the user choose, however leaving the default at 1:1

**Comment by qwertiko** [comment]
as seen here when using a different font, the app might cut some strings (recorded on OnePlus 6t)

Screenshot_20200618-095014

**Comment by johntyree** [comment]
It seems like a very small jump to go from what's here to just measuring the aspect ratio of the window and using that directly. That way things like very narrow windows would correctly stack the videos, etc. See #6366.

**Comment by johntyree** [comment]
How sad.

**Pull request closed without merging**
