### PR TITLE
fixes async_handler_wrapper

### PR DESCRIPTION
**Pull request by aaronkvanmeerten**
adds missing runner variable from async to async_handler_wrapper
removes redundant have_async definition in wrap_async_run, defined at top of module

### CODE REVIEW

**Comment by aaronkvanmeerten** [comment]
This fixes an issue in prosody 0.11 where the async runner isn't globally defined, so the event wrapper handler fails.  The solution is to use the same logic as in the simpler wrapper, pulling a runner variable after checking if async is defined

**Comment by damencho** [comment]
Aren't async_handler_wrapper and wrap_async_run almost the same? Can we remove async_handler_wrapper and be just using wrap_async_run everywhere?

**Comment by damencho** [comment]
Or the other way around, I can try migrating current code to use async_handler_wrapper 
 and remove wrap_async_run. I can try doing and testing it tomorrow.

**Comment by aaronkvanmeerten** [comment]
> Or the other way around, I can try migrating current code to use async_handler_wrapper
> and remove wrap_async_run. I can try doing and testing it tomorrow.

The main difference is that headers can be returned.  I agree these could be the same handler, and am happy to discuss the best way to accomplish that.

**Pull request merged**
