### PR TITLE
android: fix initializing soloader from Activity context

### PR DESCRIPTION
**Pull request by saghul**
It has to be an application context.

### CODE REVIEW

**Comment by jgorozco** [comment]
Hi! as i comment here

https://github.com/jitsi/jitsi-meet/issues/9956

I make a similar test and now it working. I think this patch will solve the problem, but i think a review about what context is used in classes will help. Android SDK is a mess of activity context, application context, any-other-wtf-context and sometimes is a little crazy

**Comment by saghul** [comment]
> Android SDK is a mess of activity context, application context, any-other-wtf-context and sometimes is a little crazy.

A report like #9956 helps, a sentence like the above, not really.

**Comment by jgorozco** [comment]
Sorry for this kind of sentence. with Android Sdk i mean google android sdk, not jitsi one. 

Again. Thanks for the patch and good job. Is a great webrtc sdk (i think the best open source) for mobile platforms

**Comment by saghul** [comment]
Understood, thanks you!

**Review by tmoldovan8x8 — APPROVED** [review]

**Pull request merged**
