### PR TITLE
Improve tile layout: optimally pack tiles, remove forced top/bottom margin

### LINKED ISSUE #7509: Tiles are very small in the tile view
**Is your feature request related to a problem you are facing?**
Can't make tile sizes bigger, wasting too much of useful space
Zoom_Meeting

**Describe the solution you'd like**
Be able to customize tiles, e.g. via the interface config https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js

**Describe alternatives you've considered**
Google Meet

### LINKED ISSUE #7526: Tile view uses tiny video tiles when low Jitsi window height
### Description:

The tile view seems to have a hard-coded margin of 100px on top and 100px on bottom. This makes the tile view especially useless when the window has low height (say, around 200px), even if the window is wide so could accommodate video quite well.

### Steps to reproduce:

1. Open any Jitsi meeting
2. Enter tile view
3. Shrink the height of the window

### Expected behavior:

Videos use the available vertical space.

### Actual behavior:

Here's a screenshot with two participants and the tools hidden:

image

Here's a screenshot with two participants and the tools shown:

image

Perhaps the tools are the motivation for the 100px margins, but I think it would be much better to use the available vertical space. For comparison, the non-tile view uses the available vertical space, and it looks great even with tools overlaid:

image

### Server information:

meet.jit.si

### Client information:

- Browser / app version: Chrome 84.0.4147.125
- Operating System: Windows 10 

### Additional information:

This issue is related to #5758, but that is about modal dialogs. The cause here seems to be separate (but the spirit is the same).

I couldn't find an override in https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js but I apologize if I missed it.

### PR DESCRIPTION
**Pull request by edemaine**
## Summary
Fix #7509 and fix #7526 by optimizing the tile layout to use (almost) the entire window. Tile view now uses all window sizes (including long and skinny sizes) very effectively &mdash; optimally!

## Details
There are two main changes in this PR, each in their own commit:

1. The choice of how many columns to use in the tile layout now optimizes for two things:
    * At highest priority, try to fit as many participants as possible, subject to the limit on the numbers of rows and columns (so 25 participants forces 5x5 layout).
    * At next priority, try to maximize the size of tile thumbnails.  This is the major advance.  For example, if there are two videos and the window is wider or equal to 16:9 aspect ratio, then the videos get placed horizontally adjacent, while if the window is taller than 16:9, then the videos get placed vertically adjacent.

   This optimization is done by brute force: try all possible number of columns. Given that the number of columns is limited to 5, this should be very reasonable.

   By contrast, the old layout algorithm tried to make a k &times; k ("square") layout for some integer k. This is good if the window size (minus possible chat window and minus the symmetric margins) is exactly 16:9 (the aspect ratio of thumbnails), but inefficient in nearly all other cases.

2. Reduce the forced 100px margin at top and bottom, and forced 30px margin at left and right, to 10px.  This provides plenty of space for the glowing blue borders to indicate who is speaking, without wasting much space.

   This change was requested (by me) in #7526 to support smaller window sizes. In [my application](https://github.com/edemaine/comingle), users can freely resize their Jitsi iframe to varying aspect ratios and sizes. Currently, Jitsi Meet is terrible in a wide short window, even if there's plenty of area, because of the forced 100px top/bottom margin. See the screenshots in #7526 and #7509.

## Screenshots

image

image

image

image

image

## Possible Improvements
* We could make the tile-view top/bottom and left/right margins into configurable interface constants. Now that it's no longer hard-coded in the CSS, this would be easy to add &mdash; just say the word (and maybe suggest preferred names).
  * Related, we could restore large defaults when the interface isn't set to auto-hide (which is what makes the small margin values quite useful &mdash; most of the time, you're looking at faces, not interacting with Jitsi's buttons).
* Especially with the new algorithm, I feel like we might want to increase the maximum possible number of rows or columns beyond 5. I imagine there's a worry when going beyond 25 thumbnails, but I could imagine settings where you want up to 10 columns and up to 2 rows, say, or something along these lines. I could also see wanting to go beyond 25 thumbnails (e.g. Zoom allows up to 49). I'm fine with the *defaults* being 5, but the code currently hard-codes a maximum of 5 independent of interface configuration. But I thought I should check first.

Please let me know your feedback; happy to implement any further changes.

### CODE REVIEW

**Comment by edemaine** [comment]
Let me know if there's anything I can do to help get this merged!

**Comment by Dash1a** [comment]
This change would be very welcome! Any chance on seeing this integrated (also in the docker version)?

**Comment by tautologe** [comment]
Is there a way to help this getting integrated soon?

**Comment by edemaine** [comment]
For what it's worth, I still prefer this layout over the new layout that deployed recently.  The deployed layout prevents you from seeing everyone in the meeting, without scrolling, even when you have just 7 or so people.  This PR's layout would show you everyone, up to a much more reasonable limit.  I care much more about seeing the presence of the people in the meeting than I do about seeing individual pixels...

Unless there's a way to configure the new layout that fully subsumes this PR?

**Comment by saghul** [comment]
With the current layout you should be able to see 20+ people without scrolling. What size is your window?

Happy to continue the discussion, but I'm closing this since it no longer applies in its original form.

**Comment by edemaine** [comment]
@saghul I often use a window that is half of my (40", 4K) monitor.  With some zoom levels (150% in a 1890x2100 window), Jitsi only displays 2 video panels per row, which means once I hit 7+ users, it just becomes a huge scrollable list. Here's a simple example:

screenshot

By contrast, other video call tools I use (Zoom, Meet, Discord) attempt to tile so that I can see everyone at once in a single window.  Perhaps we could add:
* A "see everyone" toggle (not sure the best name)
* An `interface_config.js` setting that changes the minimum width of a video stream.

In [my application Comingle](https://github.com/edemaine/comingle) (by now used by a few universities to teach several classes), smaller Jitsi windows are quite common, because Comingle allows the window to be partitioned into different components to mix together meeting tools such as a whiteboard, in addition to the Jitsi call, which is useful for collaboration. Here's an example on my 40" 4K monitor (again 150% zoom):

screenshot

In the iframe context, Jitsi seems even more insistent on keeping just two video streams per row.  I can switch to 125% zoom or make the tab fill about 50% more width and it still just shows two videos per row.

Conversely, in short but wide windows, Jitsi's current layout uses nice small windows, but is extremely wasteful, discarding half of the space:

image

This layout problem is what this PR aimed to solve, but trying different layouts (number of columns/rows) to find the best one.

I haven't yet figured out where the width and height is currently decided, but perhaps the algorithm could just be tweaked as in this PR?

**Comment by saghul** [comment]
I see. Let's do this then: please rebase YOur improvements on top of master and let's see how those look like then. Generally I'm not a fan of adding an extra setting for rows since it can create "impossible" scenarios.

**Comment by edemaine** [comment]
OK, thanks; I'll work on this. Given the extensive changes to master, it might take a while, but hopefully I can figure it all out again. 🙂

**Comment by edemaine** [comment]
I'm sorry I haven't had a chance to return to this yet (a busy semester), but I do plan to do so.

**Comment by damencho** [comment]
Mind that more changes are coming https://github.com/jitsi/jitsi-meet/pull/9236

**Comment by saghul** [comment]
Sorry looks like this fell through the cracks and we have addressed this in several changes that have happened recently.

**Pull request closed without merging**
