### PR TITLE
feat: feature flag for invite functionalities

### PR DESCRIPTION
**Pull request by zbettenbuk**

### CODE REVIEW

**Comment by zbettenbuk** [comment]
@saghul i did it this way because we have 2 flags for it in config.js too

**Comment by saghul** [comment]
> @saghul i did it this way because we have 2 flags for it in config.js too

I suspected as much, but feature flags deal with, well, "features" (at least that's what I had in mind when they got added). The feature in question here is inviting participants, isn't it? Also, none of the current feature flags translate to config values, FWIW.

I guess my real question here is: is there a valid use-case for an SDK implementor to disable one of the 2 if the deployment where the meetings are held supports both? If we think the answer is "yes", then let's go for it. If we think it's a "no", I'd go for a "invite.enabled" flag.

WDYT?

**Comment by saghul** [comment]
Come to think of it, I wonder if something like this would make more sense: https://github.com/jitsi/jitsi-meet/pull/4577

We could add a way to configure the  overflow menu buttons as a whole. Take that as a rough idea. WDYT?

**Comment by zbettenbuk** [comment]
I think that's different, because that operates on a UI level, but middleware and other codes may still run. I'm ok with your "feature" concept, I can change it, but I think a feature toggle is more than just a UI toggle

**Comment by saghul** [comment]
I'm happy with the current solution, thanks for considering my feedback! Approved.

**Pull request merged**
