### PR TITLE
Additional setting to disable password options

### PR DESCRIPTION
**Pull request by dimitardelchev93**
This is implementation of issue https://github.com/jitsi/jitsi-meet/issues/11829

### CODE REVIEW

**Comment by AjackusAnubha** [comment]
Hi, I am using jitsi-meet and is in need of the feature. when can this PR be merged?

**Comment by saghul** [comment]
We haven't gotten around reviewing this yet alas. Sorry about that.

**Comment by Delitefully** [comment]
Also need this feature, can this be merged?

**Comment by FaizanZahid** [comment]
need this , can someone merge this? we want to stop lobby mode and stop password feature altogether.

**Comment by amsnek** [comment]
this would be interesting though, since it would also solve an issue when using JWT auth and the following plugins: lobby_autostart + token_moderation + token_lobby_bypass
A guest/non moderator with a JWT token would still be able to bypass the lobby, when he is the first to join, by by clicking "enter password" and provide a blank one. While this is not a huge issue, it makes it prevents the moderator to be guaranteed to be the "first" in the room/lobby and allow knocking people in.

**Comment by x140l1n** [comment]
+1  
This configuration is still very useful and needed for several setups...

Could someone pick up this PR or reopen it? Many implementations rely on being able to fully disable password options to avoid unexpected behavior in the room entry flow.

**Pull request closed without merging**
