### PR TITLE
Create .eslintrc

### PR DESCRIPTION
**Pull request by daviKoth**
I want a .eslintrc to use modules

### CODE REVIEW

**Comment by saghul** [comment]
Why is this needed? We already have an eslint config elsewhere.

**Comment by daviKoth** [comment]
I need to set it to module.

**Comment by daviKoth** [comment]
Please review this

**Comment by saghul** [comment]
> I need to set it to module.

That's not what I asked. *Why* do you need to set it to that value? What problem are you encountering?

**Pull request closed without merging**
