### PR TITLE
Update main-ptBR.json

### PR DESCRIPTION
**Pull request by brlarini**
Added missing translation strings in main-ptBR.json for Brazilian Portuguese localization of Jitsi Meet.

### CODE REVIEW

**Comment by brlarini** [comment]
I've signed the agreement, do I have to do anything else? How does it associate with me?
This isn't detailed in the [Contributing Guidelines](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-contributing/).
Thanks.

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by brlarini** [comment]
The failed test on Chrome has anything to do with the translation file? Does this error prevent the merge from being approved?
Do I need to change anything?
Thanks.

**Comment by saghul** [comment]
> The failed test on Chrome has anything to do with the translation file? Does this error prevent the merge from being approved? Do I need to change anything? Thanks.

It's all good, no worries!

**Pull request merged**
