### PR TITLE
feat(sound-settings) Added ability to control sounds

### PR DESCRIPTION
**Pull request by robertpin**
Added Sounds tab in settings
image

### CODE REVIEW

**Comment by robertpin** [comment]
Jenkins please test this please

**Comment by muscat1** [comment]
Jenkins please test this please.

**Comment by robertpin** [comment]
Jenkins please test this please.

**Comment by robertpin** [comment]
Jenkins please test this please.

**Comment by robertpin** [comment]
Jenkins please test this please.

**Comment by robertpin** [comment]
Jenkins please test this please.

**Review by muscat1 — APPROVED** [review]

**Pull request merged**
