### PR TITLE
fix(reactions-firefox) Fix drawer menu not scrollable on FF

### PR DESCRIPTION
**Pull request by horymury**
- fix reactions menu not visibile on FF when in drawer mode
- fix subscriber for tileview

### CODE REVIEW

**Comment by horymury** [comment]
Please see a before and after picture
image


-issues on FF where no scroll on the drawer menu and reactions and raise hand not visible ( rendered out of viewport)

**Review by Calinteodor — APPROVED** [review]

**Comment by horymury** [comment]
Jenkins please test this please.

**Comment by Mithun1508** [comment]
@horymury I  Viewed the reviewed changes as well as working on the feature locally

**Comment by Mithun1508** [comment]
@horymury 
I've made some changes to address the linting errors in OverflowMenuButton.tsx. Could you please review the PR and approve it for merge? 

The commit message for the fix is: "Fix linting errors in OverflowMenuButton.tsx (PR #123)".

Thanks! It works locally on my machine. I Viewed the reviewed changes as well as working on the feature locally .Looking forward for approval of review to merge this PR

**Comment by Mithun1508** [comment]
@horymury 

I've addressed the linting errors in OverflowMenuButton.tsx with the commit message: "Fix linting errors in OverflowMenuButton.tsx".

Could you please provide an update on the status of my pull request "Fixed Overflow Menu button of popover #14101"? It seems that it hasn't been merged yet. I'd appreciate any feedback on why there's a delay and how I can resolve any concerns or issues.

**Comment by Calinteodor** [comment]
> @horymury
> 
> I've addressed the linting errors in OverflowMenuButton.tsx with the commit message: "Fix linting errors in OverflowMenuButton.tsx".
> 
> Could you please provide an update on the status of my pull request "Fixed Overflow Menu button of popover #14101"? It seems that it hasn't been merged yet. I'd appreciate any feedback on why there's a delay and how I can resolve any concerns or issues.

If you check the PR you will see that you have to:

1. Fix conflicts.
2. Provide comparison based on screenshots and a better explanation regarding your proposal, just like you mentioned in your last comment.

**Pull request merged**
