### PR TITLE
complete EU translation

### PR DESCRIPTION
**Pull request by erral**
Update basque (eu) translation.

Anyway I see that the Spanish JSON file has a different structure than the basque, perhaps the eu one is not updated. Can someone regenerate all translation files so that we can update them completely? Thanks.

### CODE REVIEW

**Comment by erral** [comment]
Signed.

**Review by aitzol — APPROVED** [review]

**Review by aitzol — APPROVED** [review]

**Comment by damencho** [comment]
You just need to update from the main.json manually. This is currently what we have, we are looking to add a translation system in the future ...

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by erral** [comment]
Ok. Then wait before merging, I will update the file with the missing bits from the main.json

**Comment by erral** [comment]
@damencho I have updated the file with the missing bits from main.json

If it's useful I have created a python script to update a translation file with the new messages present in the main.json file. This is the script:

https://gist.github.com/erral/e1c12a550435703b267cd0db85219a44

**Comment by damencho** [comment]
Jenkins test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
