### PR TITLE
Add DISABLE_SUBJECT_TEXT to interface config

### PR DESCRIPTION
**Pull request by kormang**
Added DISABLE_SUBJECT_TEXT option to interface config.
I had to remove subject text but leave participants count and timer. I guess other users too, will benefit from it.

### CODE REVIEW

**Comment by kormang** [comment]
Already signed individual agreement.

**Comment by kormang** [comment]
If you wonder why is this needed - Room names are often generated randomly. In such cases, subject text might be really weird. Subject text might be nice to have sometimes, but it is far from necessary feature.

**Comment by edemaine** [comment]
I for one would be interested in this feature landing. My application uses randomly generated room names and really doesn't need the subject displayed within Jitsi.

**Comment by saghul** [comment]
There is a hideConferenceSubject option now in config.js

**Comment by pratik9722** [comment]
better create https://example.com/myname#config.subject=“Test Meeting” new flag so we can change the subject title dynamically

**Pull request closed without merging**
