### PR TITLE
lang: update/fix Japanese translation, add missing fields in main-ja.js…

### PR DESCRIPTION
**Pull request by ivywe**
* lang: update/fix Japanese translation, add missing fields in main-ja.json

Based on actual main-enGB.json, my translation.

    fixed incorrect context meaning of some fields,
    added missing fields and translated them.

### CODE REVIEW

**Comment by saghul** [comment]
There seem to be some conflicts, can you please rebase?

**Comment by tisayama** [comment]
@ivywe 

As saghul has pointed out, please rebase to latest `jitsi/jitsi-meet:master` and resolve this PR conflict.

I am interested in contributing to the japanese translation work on this project too, but since my translation changeset is in conflict with this PR, I can't proceed with my work unless this PR is merged first. So I need you to deal with it first.

**Comment by ivywe** [comment]
@tisayama

Thanks.
I'm now adding Japanese translation from the last main.jason.

But, I can't understand what is the "PR" meaning.
and I don't know how to rebase, sorry.

**Comment by ivywe** [comment]
@tisayama
@saghul

Sorry about my poor performance at work.

I committed to my repository.

   Update Japanese main-ja.json based on master main.json 4bd5769
   https://github.com/ivywe/jitsi-meet/blob/master/lang/main-ja.json

Please tell me what should I do for the "rebase" ?

Please help me in Japanese.
日本語で教えていただけると助かります。

**Comment by tisayama** [comment]
(ここは英語を使うリポジトリーなので、日本語版は下の方に書いています。
The Japanese version is below.)

As for your question, "PR" means Pull request.

[CONTRIBUTING.md](https://github.com/jitsi/jitsi-meet/blob/master/CONTRIBUTING.md#creating-pull-requests) of this repository requires you to rebase the working branch to the top of the `master` before creating a Pull request. Rebasing is an operation that changes the point from which the changes you've already committed were made.
By doing rebase, you can take the `master` changes on `jitsi/jitsi-meet` into your branch after you've made them.

This time, it looks like there was a change in the `lang/main-ja.json` of the `master` by [another Pull request](https://github.com/jitsi/jitsi-meet/commit/02885ea71693d28d37175ae8f6801cadd6702286) after you created this Pull Request. I think that change conflicts with this Pull request, so you were pointed to do a rebase first.

## Rebasing guide
Here's a step-by-step guide of the rebase process.

### Prerequisites.
- You're using Git on the command line.
- Your local Git repository has `origin` set as remote, which is set in your fork repository on GitHub

* If your situation does not meet these prerequisites, for example, if you are using the GUI Git client, you may need to adjust accordingly.

### 1. Make sure your working tree is clean
Run `git status` to make sure there are no uncommitted changes.

If you see "nothing to commit, working tree clean", you have no problem.


### 2. Add an upstream to the remote
To take the latest changes, set the `jitsi/jitsi-meet` repository to remote with the name `upstream`

Run `git remote add upstream https://github.com/jitsi/jitsi-meet.git`

### 3. Take the latest jitsi/jitsi-meet changes into your local repository
Run `git fetch upstream` to download the latest changes in `jitsi/jitsi-meet`


### 4. Rebase to the latest master
Run `git rebase upstream/master` .

### 5. Conflict resolution
If there are conflicts, you will see an error message, so you need to fix the conflicts in the file.

> Auto-merging lang/main-ja.json
> CONFLICT (content): Merge conflict in lang/main-ja.json

The way to fix the conflicts is as follows:

- https://docs.github.com/en/github/using-git/resolving-merge-conflicts-after-a-git-rebase (English)
- https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line (English)

- https://fuqda.hatenablog.com/entry/2018/08/29/210526 (Japanese)
- https://docs.github.com/ja/github/using-git/resolving-merge-conflicts-after-a-git-rebase (Japanese)
- https://docs.github.com/ja/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line (Japanese)

Also, please note the following points.
- Please be careful not to break the JSON structure.
- Please take care not to accidentally delete another changes

### 6. Confirm the resolution of conflicts and proceed with the work
Run `git status` and see the message that you've resolved the conflict

 `git rebase --continue` to proceed with the rebasing process. Repeat steps 5 and 6 several times, as you'll encounter several conflicts.

### 7. If all conflicts have been resolved and the JSON is OK, push it to origin
`git push origin master`

-------
ご質問いただいていた件ですが、「PR」とはPull-Requestを意味します。

このリポジトリーの [CONTRIBUTING.md](https://github.com/jitsi/jitsi-meet/blob/master/CONTRIBUTING.md#creating-pull-requests)では、Pull requestの作成前に作業ブランチを`master` の一番先頭にrebaseすることを求めています。rebaseとはすでにコミットした変更の元になっている地点(分岐点)を変更する操作です。
これを行うことで ivyweさん が変更を行った後に反映された`master`の変更を、あなたのブランチに取り込むことができます。

今回、ivyweさんがPull requestを作成した後に、[別のPull request](https://github.com/jitsi/jitsi-meet/commit/02885ea71693d28d37175ae8f6801cadd6702286)によって`master`の`lang/main-ja.json`に変更があったようです。その変更がこちらのPull requestとコンフリクトしているため、saghulさんに先にrebaseを行うように指摘を受けたのだと思います。


## rebaseの手順について
rebaseの手順についてご説明します。

### 前提条件
- Gitをコマンドラインで使用している
- ローカルGitリポジトリーにはremoteとしてoriginが設定されており、ivyweさんのGitHub上のforkリポジトリーがセットされている

※この前提条件に合わない状況、たとえばGUIのGitクライアントを使用している等の場合は臨機応変に読み替えていただければと思います。

### 1.  作業ツリーがクリーンなことを確認
`git status` を実行して、コミットしていない変更がないことを確認してください。

"nothing to commit, working tree clean" と表示されれば問題ないと思います。

### 2.  remoteにupstreamを追加
最新の変更を取り込むために、`jitsi/jitsi-meet` リポジトリーを `upstream` という名前でremoteに設定します。
以下のコマンドです。

```
git remote add upstream https://github.com/jitsi/jitsi-meet.git
```

### 3. `jitsi/jitsi-meet` の最新の変更をローカルリポジトリーに取り入れる
`git fetch upstream` を実行してください。`jitsi/jitsi-meet` での最新の変更がローカルにダウンロードされます


### 4. 最新のmasterにrebaseする
`git rebase upstream/master` を実行します。

### 5. コンフリクトの解決
コンフリクトしているとエラーが表示されますので、ファイルの中でコンフリクトしている箇所を都度修正してください。

以下に紹介がある方法で修正していきます。

- https://fuqda.hatenablog.com/entry/2018/08/29/210526
- https://docs.github.com/ja/github/using-git/resolving-merge-conflicts-after-a-git-rebase
- https://docs.github.com/ja/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

また、以下の点に注意してください。
- JSONの構造が壊れないように配慮してください
- コンフリクトしている別の人の変更を間違って消さないように配慮してください

### ６. コンフリクトの解消を確認し、作業を進める
`git status` を実行し、コンフリクトが解消できたことをコマンドラインメッセージで確認します。

`git rebase --continue` を実行して、rebase作業を進めます。何度かコンフリクトが発生するので、5, 6の手順を何度か繰り返してください。

### 7. すべてのコンフリクトが解消し、JSONに問題がなければoriginにプッシュしてください
`git push origin master`

**Comment by ivywe** [comment]
@tisayama

Thank you so much for your kindness!

At the last

219:jitsi-meet ivywe$ git status
rebase in progress; onto b087b22d4
You are currently rebasing branch 'master' on 'b087b22d4'.
  (all conflicts fixed: run "git rebase --continue")
nothing to commit, working tree clean

**Comment by tisayama** [comment]
@ivywe 

Take a look at this Pull request on the web. It looks like it's still in conflict.

Your local repositories seem to be still in the process of rebasing, as the message you pasted in says.
> You are currently rebasing branch 'master' on 'b087b22d4'.

Try running the following command as shown in the message to finish the remaining rebasing work. (You may need to do this several times.)
```console
git rebase --continue
```

After that, if there are no problems with JSON, please push
```console
git push origin master
```

If there are no problems with the rebase operation, I think the conflicts on this pull request page will disappear.

---

このPull requestをWebで見てみてください。以下のメッセージが表示されており、まだコンフリクトしているようです。
> This branch has conflicts that must be resolved
> Only those with write access to this repository can merge pull requests.

ivywe さんが貼り付けたメッセージに表示があるように、ivyweさんのローカルリポジトリーは、まだrebaseの途中のようです。
> You are currently rebasing branch 'master' on 'b087b22d4'.

メッセージにあるように以下のコマンドを実行し、残されたrebase作業を終わらせてみてください。(何度かこの操作が必要かもしれません)
```console
git rebase --continue
```

その後、JSONに問題が無ければpushしてください
```console
git push origin master
```
rebaseの操作に問題が無ければ、このPull requestページ上のコンフリクトの表示が消えると思います。

**Pull request closed without merging**
