### PR TITLE
deps: react-native@0.60

### PR DESCRIPTION
**Pull request by saghul**
Android compiles but doesn't yet run :-(

### CODE REVIEW

**Comment by saghul** [comment]
Needs: https://github.com/jitsi/lib-jitsi-meet/pull/963

**Comment by paweldomas** [comment]
When I try to build this version locally I get a diff in pod lock file and then xcode fails with:

`jitsi-meet/ios/Pods/Folly/folly/Conv.h:38:10: 'double-conversion/double-conversion.h' file not found`

**Comment by paweldomas** [comment]
This is how the file looks like after `pod install`:
```
PODS:
  - Amplitude-iOS (4.0.4)
  - boost-for-react-native (1.63.0)
  - BVLinearGradient (2.5.6):
    - React
  - Crashlytics (3.12.0):
    - Fabric (~> 1.9.0)
  - DoubleConversion (1.1.6)
  - Fabric (1.9.0)
  - Firebase/Core (5.18.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.7.0)
  - Firebase/CoreOnly (5.18.0):
    - FirebaseCore (= 5.3.1)
  - Firebase/DynamicLinks (5.18.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (= 3.4.1)
  - FirebaseAnalytics (5.7.0):
    - FirebaseCore (~> 5.3)
    - FirebaseInstanceID (~> 3.6)
    - GoogleAppMeasurement (= 5.7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.2.0)
  - FirebaseCore (5.3.1):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseDynamicLinks (3.4.1):
    - FirebaseAnalytics (~> 5.1)
    - FirebaseAnalyticsInterop (~> 1.0)
    - FirebaseCore (~> 5.2)
  - FirebaseInstanceID (3.7.0):
    - FirebaseCore (~> 5.2)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/UserDefaults (~> 5.2)
  - Folly (2018.10.22.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - glog (0.3.5)
  - GoogleAppMeasurement (5.7.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - GoogleSignIn (4.4.0):
    - "GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
    - "GoogleToolboxForMac/NSString+URLArguments (~> 2.1)"
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.2.0):
    - GoogleToolboxForMac/Defines (= 2.2.0)
  - GoogleToolboxForMac/Defines (2.2.0)
  - "GoogleToolboxForMac/NSDictionary+URLArguments (2.2.0)":
    - GoogleToolboxForMac/DebugUtils (= 2.2.0)
    - GoogleToolboxForMac/Defines (= 2.2.0)
    - "GoogleToolboxForMac/NSString+URLArguments (= 2.2.0)"
  - "GoogleToolboxForMac/NSString+URLArguments (2.2.0)"
  - GoogleUtilities/AppDelegateSwizzler (5.4.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (5.4.1)
  - GoogleUtilities/Logger (5.4.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (5.4.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (5.4.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (5.4.1)"
  - GoogleUtilities/Reachability (5.4.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (5.4.1):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.2.1)
  - nanopb (0.3.901):
    - nanopb/decode (= 0.3.901)
    - nanopb/encode (= 0.3.901)
  - nanopb/decode (0.3.901)
  - nanopb/encode (0.3.901)
  - ObjectiveDropboxOfficial (3.9.4)
  - React (0.60.5):
    - React-Core (= 0.60.5)
    - React-DevSupport (= 0.60.5)
    - React-RCTActionSheet (= 0.60.5)
    - React-RCTAnimation (= 0.60.5)
    - React-RCTBlob (= 0.60.5)
    - React-RCTImage (= 0.60.5)
    - React-RCTLinking (= 0.60.5)
    - React-RCTNetwork (= 0.60.5)
    - React-RCTSettings (= 0.60.5)
    - React-RCTText (= 0.60.5)
    - React-RCTVibration (= 0.60.5)
    - React-RCTWebSocket (= 0.60.5)
  - React-Core (0.60.5):
    - Folly (= 2018.10.22.00)
    - React-cxxreact (= 0.60.5)
    - React-jsiexecutor (= 0.60.5)
    - yoga (= 0.60.5.React)
  - React-cxxreact (0.60.5):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-jsinspector (= 0.60.5)
  - React-DevSupport (0.60.5):
    - React-Core (= 0.60.5)
    - React-RCTWebSocket (= 0.60.5)
  - React-jsi (0.60.5):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-jsi/Default (= 0.60.5)
  - React-jsi/Default (0.60.5):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
  - React-jsiexecutor (0.60.5):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-cxxreact (= 0.60.5)
    - React-jsi (= 0.60.5)
  - React-jsinspector (0.60.5)
  - react-native-background-timer (2.1.1):
    - React
  - react-native-calendar-events (1.7.3):
    - React
  - react-native-keep-awake (4.0.0):
    - React
  - react-native-webrtc (1.69.2):
    - React
  - react-native-webview (5.8.1):
    - React
  - React-RCTActionSheet (0.60.5):
    - React-Core (= 0.60.5)
  - React-RCTAnimation (0.60.5):
    - React-Core (= 0.60.5)
  - React-RCTBlob (0.60.5):
    - React-Core (= 0.60.5)
    - React-RCTNetwork (= 0.60.5)
    - React-RCTWebSocket (= 0.60.5)
  - React-RCTImage (0.60.5):
    - React-Core (= 0.60.5)
    - React-RCTNetwork (= 0.60.5)
  - React-RCTLinking (0.60.5):
    - React-Core (= 0.60.5)
  - React-RCTNetwork (0.60.5):
    - React-Core (= 0.60.5)
  - React-RCTSettings (0.60.5):
    - React-Core (= 0.60.5)
  - React-RCTText (0.60.5):
    - React-Core (= 0.60.5)
  - React-RCTVibration (0.60.5):
    - React-Core (= 0.60.5)
  - React-RCTWebSocket (0.60.5):
    - React-Core (= 0.60.5)
  - RNCAsyncStorage (1.3.4):
    - React
  - RNGoogleSignin (2.0.0):
    - GoogleSignIn (~> 4.4.0)
    - React
  - RNSound (0.11.0):
    - React
    - RNSound/Core (= 0.11.0)
  - RNSound/Core (0.11.0):
    - React
  - RNVectorIcons (6.0.2):
    - React
  - RNWatch (0.2.0):
    - React
  - yoga (0.60.5.React)

DEPENDENCIES:
  - Amplitude-iOS (~> 4.0.4)
  - BVLinearGradient (from `../node_modules/react-native-linear-gradient`)
  - Crashlytics (~> 3.12.0)
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - Fabric (~> 1.9.0)
  - Firebase/Core (~> 5.18.0)
  - Firebase/DynamicLinks (~> 5.18.0)
  - Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - ObjectiveDropboxOfficial (~> 3.9.4)
  - React (from `../node_modules/react-native/`)
  - React-Core (from `../node_modules/react-native/React`)
  - React-cxxreact (from `../node_modules/react-native/ReactCommon/cxxreact`)
  - React-DevSupport (from `../node_modules/react-native/React`)
  - React-jsi (from `../node_modules/react-native/ReactCommon/jsi`)
  - React-jsiexecutor (from `../node_modules/react-native/ReactCommon/jsiexecutor`)
  - React-jsinspector (from `../node_modules/react-native/ReactCommon/jsinspector`)
  - react-native-background-timer (from `../node_modules/react-native-background-timer`)
  - react-native-calendar-events (from `../node_modules/react-native-calendar-events`)
  - react-native-keep-awake (from `../node_modules/react-native-keep-awake`)
  - react-native-webrtc (from `../node_modules/react-native-webrtc`)
  - react-native-webview (from `../node_modules/react-native-webview`)
  - React-RCTActionSheet (from `../node_modules/react-native/Libraries/ActionSheetIOS`)
  - React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)
  - React-RCTBlob (from `../node_modules/react-native/Libraries/Blob`)
  - React-RCTImage (from `../node_modules/react-native/Libraries/Image`)
  - React-RCTLinking (from `../node_modules/react-native/Libraries/LinkingIOS`)
  - React-RCTNetwork (from `../node_modules/react-native/Libraries/Network`)
  - React-RCTSettings (from `../node_modules/react-native/Libraries/Settings`)
  - React-RCTText (from `../node_modules/react-native/Libraries/Text`)
  - React-RCTVibration (from `../node_modules/react-native/Libraries/Vibration`)
  - React-RCTWebSocket (from `../node_modules/react-native/Libraries/WebSocket`)
  - "RNCAsyncStorage (from `../node_modules/@react-native-community/async-storage`)"
  - RNGoogleSignin (from `../node_modules/react-native-google-signin`)
  - RNSound (from `../node_modules/react-native-sound`)
  - RNVectorIcons (from `../node_modules/react-native-vector-icons`)
  - RNWatch (from `../node_modules/react-native-watch-connectivity`)
  - yoga (from `../node_modules/react-native/ReactCommon/yoga`)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Amplitude-iOS
    - boost-for-react-native
    - Crashlytics
    - Fabric
    - Firebase
    - FirebaseAnalytics
    - FirebaseAnalyticsInterop
    - FirebaseCore
    - FirebaseDynamicLinks
    - FirebaseInstanceID
    - GoogleAppMeasurement
    - GoogleSignIn
    - GoogleToolboxForMac
    - GoogleUtilities
    - GTMSessionFetcher
    - nanopb
    - ObjectiveDropboxOfficial

EXTERNAL SOURCES:
  BVLinearGradient:
    :path: "../node_modules/react-native-linear-gradient"
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  React:
    :path: "../node_modules/react-native/"
  React-Core:
    :path: "../node_modules/react-native/React"
  React-cxxreact:
    :path: "../node_modules/react-native/ReactCommon/cxxreact"
  React-DevSupport:
    :path: "../node_modules/react-native/React"
  React-jsi:
    :path: "../node_modules/react-native/ReactCommon/jsi"
  React-jsiexecutor:
    :path: "../node_modules/react-native/ReactCommon/jsiexecutor"
  React-jsinspector:
    :path: "../node_modules/react-native/ReactCommon/jsinspector"
  react-native-background-timer:
    :path: "../node_modules/react-native-background-timer"
  react-native-calendar-events:
    :path: "../node_modules/react-native-calendar-events"
  react-native-keep-awake:
    :path: "../node_modules/react-native-keep-awake"
  react-native-webrtc:
    :path: "../node_modules/react-native-webrtc"
  react-native-webview:
    :path: "../node_modules/react-native-webview"
  React-RCTActionSheet:
    :path: "../node_modules/react-native/Libraries/ActionSheetIOS"
  React-RCTAnimation:
    :path: "../node_modules/react-native/Libraries/NativeAnimation"
  React-RCTBlob:
    :path: "../node_modules/react-native/Libraries/Blob"
  React-RCTImage:
    :path: "../node_modules/react-native/Libraries/Image"
  React-RCTLinking:
    :path: "../node_modules/react-native/Libraries/LinkingIOS"
  React-RCTNetwork:
    :path: "../node_modules/react-native/Libraries/Network"
  React-RCTSettings:
    :path: "../node_modules/react-native/Libraries/Settings"
  React-RCTText:
    :path: "../node_modules/react-native/Libraries/Text"
  React-RCTVibration:
    :path: "../node_modules/react-native/Libraries/Vibration"
  React-RCTWebSocket:
    :path: "../node_modules/react-native/Libraries/WebSocket"
  RNCAsyncStorage:
    :path: "../node_modules/@react-native-community/async-storage"
  RNGoogleSignin:
    :path: "../node_modules/react-native-google-signin"
  RNSound:
    :path: "../node_modules/react-native-sound"
  RNVectorIcons:
    :path: "../node_modules/react-native-vector-icons"
  RNWatch:
    :path: "../node_modules/react-native-watch-connectivity"
  yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga"

SPEC CHECKSUMS:
  Amplitude-iOS: 2ad4d7270c99186236c1272a3a9425463b1ae1a7
  boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
  BVLinearGradient: e3aad03778a456d77928f594a649e96995f1c872
  Crashlytics: 07fb167b1694128c1c9a5a5cc319b0e9c3ca0933
  DoubleConversion: bb338842f62ab1d708ceb63ec3d999f0f3d98ecd
  Fabric: f988e33c97f08930a413e08123064d2e5f68d655
  Firebase: 02f3281965c075426141a0ce1277e9de6649cab9
  FirebaseAnalytics: 23851fe602c872130a2c5c55040b302120346cc2
  FirebaseAnalyticsInterop: efbe45c8385ec626e29f9525e5ebd38520dfb6c1
  FirebaseCore: 52f851b30e11360f1e67cf04b1edfebf0a47a2d3
  FirebaseDynamicLinks: f209c3caccd82102caa0e91d393e3ccc593501fd
  FirebaseInstanceID: bd6fc5a258884e206fd5c474ebe4f5b00e21770e
  Folly: de497beb10f102453a1afa9edbf8cf8a251890de
  glog: aefd1eb5dda2ab95ba0938556f34b98e2da3a60d
  GoogleAppMeasurement: 6cf307834da065863f9faf4c0de0a936d81dd832
  GoogleSignIn: 7ff245e1a7b26d379099d3243a562f5747e23d39
  GoogleToolboxForMac: ff31605b7d66400dcec09bed5861689aebadda4d
  GoogleUtilities: 1e25823cbf46540b4284f6ef8e17b3a68ee12bbc
  GTMSessionFetcher: 32aeca0aa144acea523e1c8e053089dec2cb98ca
  nanopb: 2901f78ea1b7b4015c860c2fdd1ea2fee1a18d48
  ObjectiveDropboxOfficial: a5afefc83f6467c42c45f2253f583f2ad1ffc701
  React: 53c53c4d99097af47cf60594b8706b4e3321e722
  React-Core: ba421f6b4f4cbe2fb17c0b6fc675f87622e78a64
  React-cxxreact: 8384287780c4999351ad9b6e7a149d9ed10a2395
  React-DevSupport: 197fb409737cff2c4f9986e77c220d7452cb9f9f
  React-jsi: 4d8c9efb6312a9725b18d6fc818ffc103f60fec2
  React-jsiexecutor: 90ad2f9db09513fc763bc757fdc3c4ff8bde2a30
  React-jsinspector: e08662d1bf5b129a3d556eb9ea343a3f40353ae4
  react-native-background-timer: 0d34748e53a972507c66963490c775321a88f6f2
  react-native-calendar-events: 2fe35a9294af05de0ed819d3a1b5dac048d2c010
  react-native-keep-awake: eba3137546b10003361b37c761f6c429b59814ae
  react-native-webrtc: 1415d2a54b2246dd85ba95eb3e4bf2b66533f951
  react-native-webview: a95842e3f351a6d2c8bc8bcc9eab689c7e7e5ad4
  React-RCTActionSheet: b0f1ea83f4bf75fb966eae9bfc47b78c8d3efd90
  React-RCTAnimation: 359ba1b5690b1e87cc173558a78e82d35919333e
  React-RCTBlob: 5e2b55f76e9a1c7ae52b826923502ddc3238df24
  React-RCTImage: f5f1c50922164e89bdda67bcd0153952a5cfe719
  React-RCTLinking: d0ecbd791e9ddddc41fa1f66b0255de90e8ee1e9
  React-RCTNetwork: e26946300b0ab7bb6c4a6348090e93fa21f33a9d
  React-RCTSettings: d0d37cb521b7470c998595a44f05847777cc3f42
  React-RCTText: b074d89033583d4f2eb5faf7ea2db3a13c7553a2
  React-RCTVibration: 2105b2e0e2b66a6408fc69a46c8a7fb5b2fdade0
  React-RCTWebSocket: cd932a16b7214898b6b7f788c8bddb3637246ac4
  RNCAsyncStorage: 8e31405a9f12fbf42c2bb330e4560bfd79c18323
  RNGoogleSignin: d030c6c6591db24c3cee649f64c7babf0a1699a0
  RNSound: c980916b596cc15c8dcd2f6ecd3b13c4881dbe20
  RNVectorIcons: d819334932bcda3332deb3d2c8ea4d069e0b98f9
  RNWatch: 09738b339eceb66e4d80a2371633ca5fb380fa42
  yoga: 312528f5bbbba37b4dcea5ef00e8b4033fdd9411

PODFILE CHECKSUM: 6b6e260b4be4e86f9d05c0d7dab40f60118bb355

COCOAPODS: 1.7.2
```

**Comment by paweldomas** [comment]
Do you have any ideas what might be wrong?

**Comment by saghul** [comment]
Clear the Xcode derived data, this happened to me once too.

**Comment by paweldomas** [comment]
> Clear the Xcode derived data, this happened to me once too.

Yup, that helped.

**Comment by paweldomas** [comment]
I think the test should be okay. This one passed including Travis iOS build minus some flakiness:
http://ci.jitsi.org/view/pr-testing/job/jitsi-meet-PR-test/6586/

**Comment by saghul** [comment]
Green builds: http://ci.jitsi.org/view/pr-testing/job/jitsi-meet-PR-test/6591/ https://travis-ci.org/jitsi/jitsi-meet/builds/574470146

**Comment by saghul** [comment]
@markmadlangbayan yes it is.

**Pull request merged**
