### PR TITLE
lang: update French translation

### PR DESCRIPTION
**Pull request by daimoc**
Lobby doesn't have the same meaning in french, it shoud be called "Salle d'attente" instead.

### CODE REVIEW

**Comment by daimoc** [comment]
CLA already signed.

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Jenkins test this please.

**Comment by damencho** [comment]
@daimoc Really sorry for not merging it earlier, can you resolve the conflict so I can merge it. Thanks.

**Comment by damencho** [comment]
Oh there is another one french translation, are you ok, to merge the other one and you will fix the conflicts? WDYT?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/pull/8114

**Comment by damencho** [comment]
@daimoc WDYT?

**Comment by damencho** [comment]
Asking cause yours is smaller and easier to redo on top of the other one?

**Comment by daimoc** [comment]
Hi @damencho , sorry i didn't your second comment before I resolve the conflict.
But It's ok, you can merge the other PR and I'll redo my change on top of it.

**Comment by damencho** [comment]
@daimoc I just merged the other one, can you fix it so I can merge it. Thanks and sorry.

**Review by roms2000 — APPROVED** [review]
Impeccable 👍

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
It was simple enough so I did it, thank you.

**Pull request merged**
