### PR TITLE
fix(dialog): fix on-screen keyboard overlapping dialog boxes

### LINKED ISSUE #6194: Mobile on-screen keyboard overlapping on dialogs
## Description

I built the current master branch and ran it on multiple devices. In several cases the onscreen keyboard overlapped dialog boxes. For example when the chat asks for my name or I want to set a password for a meeting.

## Current behavior
The on-screen keyboard overlaps the dialog. The "OK" button is only partially visible.

Artboard

## Expected Behavior
The dialog should be "pushed" upwards by the keyboard so it does not overlap.

## Possible Solution
Wrap the dialog in a KeyboardAvoidingView.

## Steps to reproduce
1. Run jitsi-meet in an iPhone 8 emulator `react-native run-ios --simulator "iPhone 8"`
2. In the Jitsi app join a room
3. Click on the chat
4. The dialog box asking for your name should open (if the dialog box does not open you may need to uninstall the app so your name is not set)

# Environment details
I was testing this on my iPhone 8 (iOS 13.4.1) and my LG V30 (Android 9) smartphone. I also confirmed that this bug occurred on other devices using simulators.

### PR DESCRIPTION
**Pull request by robojones**
fix #6194

### CODE REVIEW

**Comment by robojones** [comment]
I have tested this on my LG V30 and iPhone 8:

Artboard

**Comment by robojones** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

**Comment by robojones** [comment]
Oops.. accidentally clicked on close 😆

**Comment by robojones** [comment]
I signed the CLA

**Comment by zbettenbuk** [comment]
@robojones can you please explain the platform specific different behaviour?

**Comment by robojones** [comment]
The docs for the KeyboardAvoidingView used those settings in their example so I adopted it and it seems to work.
https://reactnative.dev/docs/keyboardavoidingview

**Comment by saghul** [comment]
Can you please test if it has a meaningful difference. We are using `height` everywhere at the moment with good results.

**Comment by robojones** [comment]
I am not able to find any difference between height and padding. The platform specific behavior is removed. I wonder why they are using the padding in the KeyboardAvoidingView example.

**Comment by saghul** [comment]
Thanks a lot for this!

**Pull request merged**
