### PR TITLE
fix(iframeAPI): startShareVideo command.

### PR DESCRIPTION
**Pull request by hristoterezov**

### CODE REVIEW

**Comment by yash10019coder** [comment]
Hi @hristoterezov I'm using Jitsi meet android SDK for making an Android video calling app, but I have to do some changes in the UI for the android app how can I modify and build my own version of Jitsi SDK 
please help

**Comment by saghul** [comment]
Please don’t hijack PRs to ask unrelated questions.

**Comment by yash10019coder** [comment]
> Please don’t hijack PRs to ask unrelated questions.

Can I ask some where else please tell me it's very important

**Comment by saghul** [comment]
Our community forum is the right place to ask.

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Unrelated test failure.

**Pull request merged**
