### PR TITLE
feat: add comment on async_handler_wrapper

### PR DESCRIPTION
**Pull request by ltorje-8x8**
It contains a comment on function used as to track who is calling async_handler_wrapper

### CODE REVIEW

**Comment by damencho** [comment]
@saghul Nope, we do not use it only there. But we talked offline with @ltorje-8x8 to mark all such places, so we do not break stuff by renaming and not fixing dependencies. 
But if this is the only dependency to jitsi-meet, yeah we maybe better copy it there so we are safe. WDYT @ltorje-8x8 ?

**Comment by damencho** [comment]
Thanks for the PR!

**Comment by saghul** [comment]
SGTM!

**Comment by damencho** [comment]
@ltorje-8x8 move it there, please and thank you!

**Comment by ltorje-8x8** [comment]
It is

**Comment by ltorje-8x8** [comment]
It is used in multiple places, not only for spot notifications --> see https://github.com/search?q=org%3Ajitsi%20async_handler_wrapper&type=code

**Comment by damencho** [comment]
That's what I said. But that is the same repo most of them, so everything is fine. If you are doing changes in same repo, you will take care for it to work.

As it is the only dependency to jitsi-meet in spot, let's copy the functionality there so we drop that dependency and do not worry about it.

**Pull request closed without merging**
