### PR TITLE
#8219 fixing the user placeholder translation issue 

### PR DESCRIPTION
**Pull request by BasmaAwatef**
+ Json files for translation updated to recognize and tnaslate the word "user".
+ input user tags property for transaltion (i18n) added.

### CODE REVIEW

**Comment by BasmaAwatef** [comment]
Already signed.

**Comment by damencho** [comment]
Why are these yml file changes, they are not relevant to this PR?
Please drop the modifications in all the languages, modifying just the English one is enough.
If a key is not found in a language it defaults to English.

**Comment by BasmaAwatef** [comment]
Hello, thank you for your feedback. 
For the YML files, I changed them to try and pass the workflow in my personal forked project but forgot to drop that modification. It's already fixed. 
I also changed all the translations in other languages for the word "user", except for the default one in "lang/main.json". 
I hope commits won't be confusing, I tried to squash them before making the PR, but I couldn't find a way to do it.

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
