### PR TITLE
fix(rn) adds debounce on onJoin function

### PR DESCRIPTION
**Pull request by tmoldovan8x8**

### CODE REVIEW

**Comment by saghul** [comment]
Not a fan of using time. Can't we use state instead? Next time it should be clean so we'd start over...

**Review by saghul — APPROVED** [review]
LGTM! All is well after hanging up and joining a new meeting later, right?

**Comment by tmoldovan8x8** [comment]
> 

yeah

**Comment by saghul** [comment]
> > 
> 
> yeah

Awesome, then wait for the CIs and land!

**Pull request merged**
