### PR TITLE
chore: remove unused images

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by virtuacoplenny** [comment]
What is the change with images/dropboxLogo_square.png?

**Comment by saghul** [comment]
> What is the change with images/dropboxLogo_square.png?

Removed the executable bit.

**Comment by virtuacoplenny** [comment]
Are you sure the flags images should be removed? They might be used by the css var $flagsImagePath and bc-css-flags.

**Comment by saghul** [comment]
> Are you sure the flags images should be removed? They might be used by the css var $flagsImagePath and bc-css-flags.

Aha! You're totally right! Restoring that one...

**Pull request merged**
