### PR TITLE
feat(external-api) Expose meeting session id

### PR DESCRIPTION
**Pull request by horymury**

### CODE REVIEW

**Comment by damencho** [comment]
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events#videoconferencejoined

**Comment by horymury** [comment]
> Seems fine, but people can be calling this before meeting has started and will be getting empty string ... Maybe we can add that as part of the event on conference joined? WDYT? Will that work for your usecase?

Sure, I can move it there

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Yeah, I'm not sure either as I think we have and other functions that will return garbage before the meeting is started/joined.

**Comment by damencho** [comment]
So maybe leave just the method, but in the doc we need to note that. In the beginning of the meeting that can be empty string. 
Actually on video conference joined we may still not have it, as to discover it we do a query to get the room form data. 
So to have it correct this should be an event not a getter, as we are not sure when this is available :)

**Pull request merged**
