### PR TITLE
feat (kick everyone)

### PR DESCRIPTION
**Pull request by HoppFoundation**
Hi,

we added a feature that would allow the moderator to kick everyone. This was a highly requested feature by schools. Used to close the rooms so that students wouldn't be left alone. -> related to #5653 
It can be disabled in interface_config.js.
It was created analogous to the mute everyone feature
The mobile code needs some changes to work on normal instances (We verify via the session ID to make sure students can't kick everyone)

https://github.com/hnzlmnn/jitsi-meet/blob/0ed273d6d5f99349f54cabe19a6abb8ae7bc0b3c/react/features/toolbox/components/native/KickEveryoneElseButton.js
https://github.com/hnzlmnn/jitsi-meet/blob/0ed273d6d5f99349f54cabe19a6abb8ae7bc0b3c/react/features/toolbox/components/native/KickEveryoneElsePrompt.js

those are the native files though (sadly I (@AliKarpuzoglu)  messed up the commit and merged at the same time so it is a bit harder to see :D )

### CODE REVIEW

**Comment by HoppFoundation** [comment]
It's signed

**Comment by saghul** [comment]
Can you please take care of the linting errors?

**Comment by AliKarpuzoglu** [comment]
I'll fix it, I forgot to re-run the linter

**Comment by HoppFoundation** [comment]
linting issues are fixed

**Pull request closed without merging**
