### PR TITLE
Accessibility: keyboard navigation on the toolbar (Context menu)

### PR DESCRIPTION
**Pull request by ahmadkadri**
**Description:** When user use the keyboard navigation and open video or audio settings under menu the focus should move and stay in the under menu till the under menu closed.

**Actual Behavior:** 
1- After opening the menu using keyboard navigation, user have navigate with tap on all toolbar buttons to reach it.
2- The keyboard focus with tap move to other elements (buttons) even if the menu is open.
3- If the menu is open and the focus on other element press ESC doesn't close it. 

**Expected Behavior:** 
1- After opening the menu using keyboard navigation, the focus should move directly to the menu.
2- The focus should stay in inside the menu.
3- By clicking ESC closed the menu and move the focus back to the button.

Before:

https://github.com/user-attachments/assets/f26bd5c8-47b9-44e3-a705-fb383c8f2c49

After:

https://github.com/user-attachments/assets/0ebe1e9e-39e6-423d-9112-2474e5078ce5

issue jitsi community: https://community.jitsi.org/t/accessibility-keyboard-navigation/133334

**NOTE:** This PR included the fix of "ResizeObserver loop completed with undelivered notifications". This error typically occurs when the ResizeObserver detects changes in element sizes and tries to update the layout, but the changes trigger more layout recalculations than the browser can handle in a single event loop cycle. Browsers like Chrome trigger this error as a warning and not necessarily because something is broken.

### CODE REVIEW

**Comment by ahmadkadri** [comment]
Jenkins please test this please!

**Comment by ahmadkadri** [comment]
@saghul  is there any update on this PR?

**Comment by Calinteodor** [comment]
Jenkins please test this please.

**Comment by Calinteodor** [comment]
Jenkins test this please.

**Review by Calinteodor — APPROVED** [review]

**Pull request merged**
