### PR TITLE
 Translation eng to vietnameses (only change main-vi.json)

### PR DESCRIPTION
**Pull request by hkien2310**
I added the missing parts in the main-vi.json file according to the instructions at https://github.com/jitsi/jitsi-meet/blob/33db2bed34ab0bad1dc811a99fbe6751ded3655c/lang/readme.md

### CODE REVIEW

**Review by saghul — DISMISSED** [review]

**Comment by saghul** [comment]
Almost there! The "errors" section is not alphabetically sorted.

**Review by saghul — APPROVED** [review]

**Comment by hkien2310** [comment]
@saghul  Please tell me when will my update be updated on react sdk. Thank you

**Comment by hkien2310** [comment]
> The native one of the pure web one?

@saghul  When will it be updated in both (react-sdk and react-native-sdk).

**Comment by saghul** [comment]
The React SDK doesn't need updating because it relies on the external API, so it will be fixed when the next stable release comes out. A couple of weeks.

The RN SDK follows a different release cycle, 4 to 6 weeks.

**Pull request merged**
