### PR TITLE
fix: Fixes LE script on existing cert.

### PR DESCRIPTION
**Pull request by damencho**
Updates jaas shown message.

### CODE REVIEW

**Review by oanaianc — DISMISSED** [review]

**Comment by saghul** [comment]
You can look at the return code instead: https://github.com/jitsi/docker-jitsi-meet/blob/a1e82ea582ef95eb1b9593154601f0a211ef30f3/web/rootfs/etc/cont-init.d/10-config#L32

**Review by oanaianc — APPROVED** [review]

**Comment by damencho** [comment]
> You can look at the return code instead: https://github.com/jitsi/docker-jitsi-meet/blob/a1e82ea582ef95eb1b9593154601f0a211ef30f3/web/rootfs/etc/cont-init.d/10-config#L32

You mean there is a special code when the cert already exists locally?

**Comment by saghul** [comment]
It doesn't seem to be well documented, but it exits with 2 if a renew is not necessary: https://github.com/jitsi/docker-jitsi-meet/commit/700c04a6291d9eb3e940b21b7cba219fc7bd596d

**Comment by saghul** [comment]
Found it upstrean: https://github.com/acmesh-official/acme.sh/blob/ef01de6149b315a64a9861e93c2e802bd9a1d53e/acme.sh#L93 -- So it's: 0 ok, 1 error 2 no need to renew.

**Review by oanaianc — APPROVED** [review]

**Pull request merged**
