### PR TITLE
Load 3rd party JavaScript if config.enableThirdPartyRequests true

### PR DESCRIPTION
**Pull request by bickelj**
A step toward making third party javascript able to be disabled with a config entry.
It does not address the gravatar requests which are still present. [EDIT: commit 895bb3f helps remove these requests]

The approach in this request seems to work for the callstats requests, I am unsure if it is working exactly correctly for GA.

### CODE REVIEW

**Comment by bgrozev** [comment]
LGTM!

**Comment by bickelj** [comment]
The second commit allows gravatar requests to occur when the config option "enableThirdPartyRequests" is set to true.

Maybe there is a drop-in replacement avatar solution available, but for those of us who are going to set the new config option to false, that is not the priority at the moment.

Why not have each be configurable? Since there are two or more of us interested in disabling all third-party requests, for now it should be sufficient to have one option instead of three. If someone would like to submit a local avatar solution maybe the options could be revisited.

**Comment by bgrozev** [comment]
I don't think this works, because the UI code expects an image with a certain fixed size (30x30 or 100x100 IIRC). 

I'll test and merge these when I have the time (might have to wait until next week). Have you signed our CLA?

**Comment by bickelj** [comment]
I don't see any nasty warnings or errors in the two major browsers.

It does look a little over-sized in the "Contact List", but seems to fit.

Will look for the css and specify max height and width, though.

**Comment by bickelj** [comment]
@bgrozev commit c2c3d0f seems to help in the contact list. I think the other places already have height and width specified.

**Comment by bgrozev** [comment]
Great! Thank you for the contributions! This (not depending on the image size) is also a step towards using other external services other than gravatar. :)

**Comment by bickelj** [comment]
You're welcome! I hope you meant it's a step toward using self-hosted avatars : ).

Do you prefer these squashed or is the branch ok as is?

**Comment by bgrozev** [comment]
Sure, a step towards self-hosted avatars as well ;)
The commits are fine.

**Comment by emcho** [comment]
Hey @bickelj , thanks for your PR! 

Could you please make sure you sign our contributor agreement so that we can merge? 
https://jitsi.org/icla
or, if you are doing this on behalf of an employer:
https://jitsi.org/ccla

**Comment by bickelj** [comment]
@emcho Yw. There should be a CLA signed a few weeks ago in your records. Let me know if it didn't come through.

**Comment by bgrozev** [comment]
Merged with a647400cb869ff02cfe2050307efa39f1cd897fc and ACKed. Thank you!
I changed the name of the config flag, so that the current behavior is preserved without updating config.js (which happens if you update via debian packages).

**Comment by bickelj** [comment]
Thank you for including it, and good call on the rename.

**Pull request merged**
