### PR TITLE
feat: (video-thumbnail) add permanent video participant name to thumbnail

### PR DESCRIPTION
**Pull request by andioltean**
fixed layout issues and removed participant bame on hove except for self

### CODE REVIEW

**Comment by psi-4ward** [comment]
Can anyone post a screenshow how it looks like now?

**Comment by psi-4ward** [comment]
found it on https://alpha.jitsi.net

tile-view looks not very good imho

**Comment by andioltean** [comment]
I will address the design in an upcoming pull request.

**Comment by psi-4ward** [comment]
Got some positive feedback from my users :-)

**Pull request merged**
