### PR TITLE
android: log an error if Activity doesn't implement the required interface

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
You might be able to work without it if you know what you are doing.

**Comment by zbettenbuk** [comment]
Then why the "must" word and the error? Better make it a warning then?

**Comment by saghul** [comment]
It's a strong encouragement. Honestly I'd rather throw an exception, but then we'd need to handle it in the place were we currently use it properly and things get messy...

**Comment by zbettenbuk** [comment]
Let's throw a RuntimeException (or any children of it, e.g. ClassCastException) and it doesn't have to be handled then. But I'm just afraid that this log message may get lost in the enormous log we have.

**Comment by saghul** [comment]
> Let's throw a RuntimeException (or any children of it, e.g. ClassCastException) and it doesn't have to be handled then.

Excellent idea, thanks! Will fix.

**Comment by saghul** [comment]
Updated, PTAL.

**Comment by saghul** [comment]
MErging because the failing test is unrelated.

**Pull request merged**
