### PR TITLE
fix(settings) remove legacy compatibility code

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
Not 100% sure this won't break anything, so let's discuss.

**Comment by saghul** [comment]
@damencho Do you know if any of the removed stuff is used by Jibri for example?

**Comment by damencho** [comment]
Nope, jibri only uses xmpp_username and password from the localstorage. I think those were just local settings of web/mobile from two or more years ago ...

**Comment by saghul** [comment]
> Nope, jibri only uses xmpp_username and password from the localstorage. I think those were just local settings of web/mobile from two or more years ago ...

Cool, mind giving it your seal of approval then?

**Review by damencho — APPROVED** [review]

**Pull request merged**
