### PR TITLE
Include slovenian translations

### PR DESCRIPTION
**Pull request by nordlolek**
main-sl.json and languages-sl.json were not jet included.

### CODE REVIEW

**Comment by nordlolek** [comment]
CLA signed

**Comment by saghul** [comment]
AFAIS that language is mostly empty, lots of translated strings are missing. Is there another PR adding those?

**Comment by nordlolek** [comment]
There will bi additional PR with string translations. For now this PR would solve our need to recompile js files to include slovenian translations.

**Comment by saghul** [comment]
Sorry, but if we merge this anyone with a mobile set to Slovenian will see the mostly untranslated UI. I'd rather have a mostly complete translation before merging this.

**Comment by nordlolek** [comment]
OK. I will add translations, just give me a day or two :)

**Comment by luixxiul** [comment]
This needs rebase.

**Comment by nordlolek** [comment]
Please let me know, if there is anything I can do, to make this merge happening.
Thank you all!

**Comment by luixxiul** [comment]
He'll soon take care of the localization PRs including this 😄

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by nordlolek** [comment]
Hi! Can please anybody answer me, why these changes are not jet visible in latest jitsi deployments using this procedure:  https://jitsi.org/downloads/ubuntu-debian-installations-instructions/ ?
When can I expect next stable release?

**Pull request merged**
