### PR TITLE
Added all missing languages from languages.json

### PR DESCRIPTION
**Pull request by gonsalet**
Added to languages-ca.json all missing languages from languages.json, with names in Catalan.

### CODE REVIEW

**Comment by gonsalet** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

I have signed the CLA.

**Comment by damencho** [comment]
We are adding languages to the list of available when it is 30-40 percent ready. At the moment I cannot tell what is the percentage :)

**Comment by gonsalet** [comment]
Hi @damencho,

What do you mean? I updated the translated language list at languages-ca.json so that it includes all the languages currently included in languages.json.

When I set up Jitsi Meet in Catalan and I drop down the language list, the most recently added languages are shown in English (not translated into Catalan). I thought maybe languages-ca.json was the file to update to bring the Catalan translation of language names up to date.

Is this right? Can this pull request be approved, or is something else missing? Thanks!

**Comment by damencho** [comment]
I mean that again I'm not reading carefully, sorry. Everything is fine.

**Comment by gonsalet** [comment]
Great, thanks! :)

**Pull request merged**
