### PR TITLE
feat(recording): add sounds for when recording starts and stops

### PR DESCRIPTION
**Pull request by virtuacoplenny**

### CODE REVIEW

**Comment by virtuacoplenny** [comment]
Note: the same sound is being used for recording and live streaming. I'm still waiting on confirmation if that should be the case.

**Comment by lyubomir** [comment]
@paweldomas,  you figured out most of the sound architecture and subsequent fixes, so could you please review this?

@zbettenbuk, because you're working on recording, you may want to take a look at this to make sure it works for you.

**Comment by virtuacoplenny** [comment]
Rebased and force pushed per request.

**Comment by virtuacoplenny** [comment]
@paweldomas, would you feel any differently if I told you "recordingOn" has the speech "recording is on" and "recordingStopped" has the speech "recording has stopped"? I agree the lack of balance between on and stopped isn't ideal but I was on the fence whether to name it based on what's said or based on the intent of the files...I went with what is said.

**Pull request merged**
