### PR TITLE
add upper sorbian translation

### PR DESCRIPTION
**Pull request by zobadaniel**
This is a translation of Jitsi Meet to Upper Sorbian, a minority language spoken in Germany. We'd love to have it included in Jitsi Meet.

### CODE REVIEW

**Comment by zobadaniel** [comment]
CLA is signed. Please let me know what else is missing to include this language into jitsi meet.

**Comment by damencho** [comment]
You need to sort the file, check the failed tests.

**Comment by zobadaniel** [comment]
I think I found what was missing. Check runs fine locally now.

**Comment by damencho** [comment]
jenkins test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
