### PR TITLE
Rn jitsi sdk user info meeting options

### PR DESCRIPTION
**Pull request by Larens94**
Hi, I don't know if it can help you.

I added userInfo to set the avatar, name and email.

Sincerely

### CODE REVIEW

**Comment by danilvalov** [comment]
`flags` is an object, not an array. Don't change this type please

**Comment by Larens94** [comment]
I'm sorry but I didn't realize it was changed to array honestly...

**Comment by saghul** [comment]
Ping @Calinteodor

**Comment by Calinteodor** [comment]
@Larens94 can you please fix the lint errors? Thank you!

**Comment by Larens94** [comment]
> @Larens94 can you please fix the lint errors? Thank you!

it should be ok now.

**Comment by Larens94** [comment]
> @Larens94 can you please fix the lint errors? Thank you!

Hi, before adding the space between one line and another it gave an error.
Now with space it gives another.

Surely I'm doing something wrong, can you tell me where is the problem?

Thank you

Cordially.

**Comment by Calinteodor** [comment]
> > @Larens94 can you please fix the lint errors? Thank you!
> 
> Hi, before adding the space between one line and another it gave an error. Now with space it gives another.
> 
> Surely I'm doing something wrong, can you tell me where is the problem?
> 
> Thank you
> 
> Cordially.

If you go to Files changed section, you can see where the error is. 
There is some unneeded extra space that must be removed.
Plus, add an extra space before interface IUserInfo and one more between interface IUserInfo and interface IAppProps. Thank you!

**Comment by Larens94** [comment]
> > > @Larens94 can you please fix the lint errors? Thank you!
> > 
> > 
> > Hi, before adding the space between one line and another it gave an error. Now with space it gives another.
> > Surely I'm doing something wrong, can you tell me where is the problem?
> > Thank you
> > Cordially.
> 
> If you go to Files changed section, you can see where the error is. There is some unneeded extra space that must be removed. Plus, add an extra space before interface IUserInfo and one more between interface IUserInfo and interface IAppProps. Thank you!

I think I did it right.

**Review by Calinteodor — APPROVED** [review]

**Comment by Larens94** [comment]
> > > > @Larens94 can you please fix the lint errors? Thank you!
> > > 
> > > 
> > > Hi, before adding the space between one line and another it gave an error. Now with space it gives another.
> > > Surely I'm doing something wrong, can you tell me where is the problem?
> > > Thank you
> > > Cordially.
> > 
> > 
> > If you go to Files changed section, you can see where the error is. There is some unneeded extra space that must be removed. Plus, add an extra space before interface IUserInfo and one more between interface IUserInfo and interface IAppProps. Thank you!
> 
> I think I did it right.

Next I would like to add this:
file: \jitsi-meet\react-native-sdk\index.tsx
```
    /**
     * When you close the component you need to reset it.
     * In some cases it needs to be added as the parent component may have been destroyed.
     * Without this change the call remains active without having the jitsi screen.
     */
    useLayoutEffect(() => {
        return () => {
            const dispatch = app.current?.state?.store?.dispatch;
            dispatch && dispatch(appNavigate(undefined));
        };
    }, []);
```


I'm still testing it but it seems to work fine.

the problem is that the call remains active if the parent component is destroyed... in my case I need jitsi to manage autonomously the resources no longer needed when the component is closed and then close everything.


Sincerely

**Pull request merged**
