### PR TITLE
add option to show or hide the browser suboptiomal warning in the interface_config

### PR DESCRIPTION
**Pull request by husseinraoouf**
add option to show or hide the browser suboptiomal warning in the interface_config

why this is useful ?

i am trying to embed jitsi in a small place and it almost working fine but the warning banner is too big so i just wanted to hide it and maybe make a custom warning my self

### CODE REVIEW

**Comment by husseinraoouf** [comment]
i have added firefox and the warning still appear

**Comment by husseinraoouf** [comment]
also i think the possible answers (`chrome, chromium, edge, electron, firefox, nwjs, opera, safari`) may not cover all the browsers
and i want to hide the warning in all cases

**Comment by husseinraoouf** [comment]
just to let you know i have signed your CLA :)

**Comment by saghul** [comment]
LGTM, but this needs a rebase, can you please do that?

**Comment by husseinraoouf** [comment]
@saghul 
done :)

**Pull request closed without merging**
