### PR TITLE
i18n: Update Occitan locale

### PR DESCRIPTION
**Pull request by Mejans**
100% translated now

### CODE REVIEW

**Comment by damencho** [comment]
There are lint errors that you need to fix.

**Comment by Mejans** [comment]
Hello,
what has to be changed?

**Comment by damencho** [comment]
Looking at the [error](https://github.com/jitsi/jitsi-meet/actions/runs/12303590129/job/34339040934?pr=15389) they are not sorted. 

You can use this to help you: https://github.com/jitsi/jitsi-meet/blob/master/resources/lang-sort.sh

**Comment by Mejans** [comment]
@damencho done! Thanks for the script, I will keep it locally!

**Pull request merged**
