### PR TITLE
feat(conference): dismiss calendar notification

### PR DESCRIPTION
**Pull request by Calinteodor**
1.  Added meeting title to the notification.
2. Created action that dismisses calendar notification.

https://user-images.githubusercontent.com/26413496/225306944-87901384-67ec-444f-b34b-84b4b3e79e7f.MOV

### CODE REVIEW

**Comment by saghul** [comment]
Won't this mean that if there is no ongoing meeting in the first 10 seconds, the notification will never be displayed? Or am I reading this wrong?

**Comment by Calinteodor** [comment]
> Won't this mean that if there is no ongoing meeting in the first 10 seconds, the notification will never be displayed? Or am I reading this wrong?

If my understanding is correct, setTimeout delays showing the notification with 10 seconds. 
When we used setInterval, we shown the notification every 10 seconds.

**Comment by saghul** [comment]
> If my understanding is correct, setTimeout delays showing the notification with 10 seconds and no longer shows it if we close it.
> When we used setInterval, we show the notification every 10 seconds, even if we close it.

I don't think so.

If you use setTimeout you'll only evaluate if you need to display a notification once.

Imagine you join a meeting at 12:00 and have another one at 12:30. The first meeting goes long, then at 12:30 you should see the notification. Unless you use an interval, you won't show it.

I think we need to handle the notification dismissal (or maybe show a custom "don't remind me" action) to skip it for good.

**Comment by Calinteodor** [comment]
> > If my understanding is correct, setTimeout delays showing the notification with 10 seconds and no longer shows it if we close it.
> > When we used setInterval, we show the notification every 10 seconds, even if we close it.
> 
> I don't think so.
> 
> If you use setTimeout you'll only evaluate if you need to display a notification once.
> 
> Imagine you join a meeting at 12:00 and have another one at 12:30. The first meeting goes long, then at 12:30 you should see the notification. Unless you use an interval, you won't show it.
> 
> I think we need to handle the notification dismissal (or maybe show a custom "don't remind me" action) to skip it for good.

We could add a destructive button next to Join, that reads "Don't remind me" and dispatches an action that skips the notification for good.

**Comment by saghul** [comment]
> We could add a destructive button, next to Join, that reads "Don't remind me" and dispatches an action that skips the notification for good.

Me likey!

**Review by saghul — APPROVED** [review]

**Pull request merged**
