### PR TITLE
Add Dockerfile

### LINKED ISSUE #1388: Consider having an official docker image
It would be nice to have one (or different) official Docker image.

I will work on it for me, if you are intersted, I can help you making it official.
In the mean time, i could also PR it here?

Let me know what you think!

### PR DESCRIPTION
**Pull request by pierreozoux**
Closes #1388

### CODE REVIEW

**Comment by saghul** [comment]
@jitsi/jitsi-meet do we want to have this? If so I'm happy to review it.

**Comment by 466** [comment]
> @jitsi/jitsi-meet do we want to have this? If so I'm happy to review it.

Just to let you know, this is something at least someone (me! :) ) is waiting for!

**Comment by pierreozoux** [comment]
closing in favor of: https://github.com/jitsi/jitsi-meet/issues/1388

**Comment by frankgu** [comment]
I am also wait for the `official` version of docker support. 👍

**Pull request closed without merging**
