### PR TITLE
fix: display dial-in code on a new line

### PR DESCRIPTION
**Pull request by TBG-FR**
## Issue
In the "invite people" modal, the phone number and the PIN code are displayed on the same line. It causes the PIN code to break in the middle, misleading people when they try to join a conference by phone.

## Changes
A very small change, to add a line break between phone number and PIN code

### Before
image

### After
image

### CODE REVIEW

**Comment by TBG-FR** [comment]
Hey @damencho or @bgrozev or @saghul , could you review and accept that small modification ? It's a little thing, but a lot of users are misled and do not type all numbers of the PIN code...

Thanks in advance 🙏 have a nice day 😄

**Comment by damencho** [comment]
This file no longer exists.

**Comment by horymury** [comment]
> This file no longer exists.

Yep it was renamed to DialInNumber.tsx. But the same fix can be applied on the new file.

**Comment by saghul** [comment]
Can you apply the fix pl? We let this one slide for months...

**Comment by horymury** [comment]
> Can you apply the fix pl? We let this one slide for months...

Created new PR . Closing this one

**Comment by horymury** [comment]
Addressed in a new PR

**Comment by TBG-FR** [comment]
Thanks a lot guys 🙏 
(for reference : #13309 )

**Pull request closed without merging**
