### PR TITLE
feat: whitelist domains for jwt enabled rooms, closes: #11999

### PR DESCRIPTION
**Pull request by debendraoli**
This mr provides ability to configure domains to allow whitelisted domains to enter jwt auth enabled rooms.

### CODE REVIEW

**Review by saghul — APPROVED** [review]
LGTM. @damencho ?

**Comment by damencho** [comment]
I guess this PR is because of https://github.com/jitsi/jitsi-meet/issues/11999#issuecomment-1213144347
I want first to check the issue to see what's going on as it used to work before flipping enable domain verification, so if that issue is fixed this may turn out is not needed ... Wdyt?

**Comment by damencho** [comment]
And the change in the PR searches a full jid in a list of domains ...

**Comment by damencho** [comment]
We have taken it offline with @saghul and after discussing it, we decided that the way to go is just add the jid of jigasi or jibri to the admins of the main much and that will skip the token verification for those users. 
https://github.com/jitsi/jitsi-meet/blob/f07bd4a0d6e0765162c8ac4b2290c09438b01a0b/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L83

**Pull request closed without merging**
