### PR TITLE
Add fullscreen.enabled flag for mobile platforms

### PR DESCRIPTION
**Pull request by alariej**
Add a new mobile _Feature Flag_ called "fullscreen.enabled" (default value = true) which allows to disable the immersive mode, where the device's status bar and navigation bar (Android) are hidden.

Tested on LG G6 (Android 9.0) and iPhone 7 (iOS 14.4)

In reference to https://github.com/jitsi/jitsi-meet/issues/2771#issuecomment-788714328

### CODE REVIEW

**Comment by saghul** [comment]
Code LGTM, , can you appease the linter please?

**Comment by alariej** [comment]
@saghul Linter and CLA done.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Cheers!

**Comment by alariej** [comment]
@saghul Hi, I have submitted a new pull request (https://github.com/jitsi/jitsi-meet/pull/8976) with this commit: https://github.com/alariej/jitsi-meet/commit/501ef1275693791ed2e91cebea3a8883da856868. It adds the `fullscreen.enabled` condition to the `_onImmersiveChange` function, which triggers on Android when a permission dialog pops up. Without this change, the conference returns to fullscreen even when the flag is set to false. I should have caught that in the original PR :-(

**Pull request merged**
