### PR TITLE
fix(dial-in-info): Qiuck fix of JitsiMeetJS undefined error.

### PR DESCRIPTION
**Pull request by hristoterezov**

### CODE REVIEW

**Comment by paweldomas** [comment]
@virtuacoplenny is it one of the cases with the circular references you were writing to me about ?

**Comment by paweldomas** [comment]
🚓this is one of the cases were work on a real fix needs to be scheduled as soon as the quick fix goes in

**Comment by hristoterezov** [comment]
@paweldomas Agree! I'm looking into it right now!

**Comment by paweldomas** [comment]
ok, I see so the point here is to not import lib-jitsi-meet. So it's not about circular references

**Pull request merged**
