### PR TITLE
fix(redux) fix not working with Redux Devtools

### PR DESCRIPTION
**Pull request by saghul**
Screenshot 2022-03-28 at 10 15 03

NOTE: It can get slow due to how large our state is.

### CODE REVIEW

**Comment by JohannesPertl** [comment]
It also still doesn't work for me

**Comment by saghul** [comment]
Have you tried it locally while doing `make dev` ? We have not deployed this to meet.jit.si yet.

**Comment by damencho** [comment]
I'm always testing with deploying it to my dev instance.

**Comment by JohannesPertl** [comment]
Can you take a look at that fix again? It's not working in the newest release too, and using the redux devtools also freezes the browser. I tested it on meet.jit.si, with `make dev` and instance with docker, both locally and on a remote server

**Comment by saghul** [comment]
I don't have the time right now, but if it freezes the browser it might be "working" since last I tried it was very slow due to the sheer size of our state.

**Comment by JohannesPertl** [comment]
@saghul Thx, I kept it running for a longer time and it actually works :+1:

**Pull request merged**
