### PR TITLE
[RN] Implement full screen mode while in a conference

### PR DESCRIPTION
**Pull request by saghul**
Use immersive mode on Android and hide the status bar on iOS.

### CODE REVIEW

**Comment by saghul** [comment]
@lyubomir This PR will have a slight conflict after you land #1254 due to the import statement.  After that one lands I'll rebase this one and switch to using the `CONFERENCE_WILL_JOIN` action instead of `CONFERENCE_JOINED`. You should be able to test it as-is on top of master though.

**Comment by saghul** [comment]
Added a new commit which hides the statusbar on iOS.  This gives us a consistent experience across platforms.

**Comment by saghul** [comment]
Refactored this a bit and squashed both commits into one, which does the job for both Android and iOS.

**Comment by saghul** [comment]
Rebased and force-pushed now that we have WILL_JOIN. This is now ready for review.

**Comment by saghul** [comment]
Rebased again since there were some conflicts after recent PRs.

**Comment by mduisenov** [comment]
i've removed immersive library, but still immersive mode enabling on joining in a conference. 
How can i remove immersive mode?

**Pull request merged**
