### PR TITLE
Enable polls moderation

### PR DESCRIPTION
**Pull request by dimitardelchev93**
Example implementation of https://github.com/jitsi/jitsi-meet/issues/10225 web (no native changes)

### CODE REVIEW

**Comment by gpatel-fr** [comment]
@dimitardelchev93

How did this community call turn out (I'm not keen to listen to it just to find out - or that you did not bother).
If it did not go well, it seems a shame to let all this work rot while the feature to limit to moderator seems to have a general usefulness,  IIRC it was already asked for on the forum. Restricting polls use in prosody seems trivial enough.

```
--- mod_polls.lua.old	2021-09-27 21:50:38.000000000 +0200
+++ mod_polls.lua	2021-11-04 11:02:17.428416562 +0100
@@ -10,6 +10,8 @@
 
 local is_healthcheck_room = util.is_healthcheck_room;
 
+restrict_polls_to_moderators = module:get_option_boolean("restrict_polls_to_moderators", false);
+
 -- Checks if the given stanza contains a JSON message,
 -- and that the message type pertains to the polls feature.
 -- If yes, returns the parsed message. Otherwise, returns nil.
@@ -61,6 +63,14 @@
 
 	if data.type == "new-poll" then
 		if check_polls(room) then return end
+	              
+		if restrict_polls_to_moderators then
+                    local role = room.get_affiliation(room, event.stanza.attr.from);
+                    if role ~= "owner" then
+	               module:log("warn", "not creating poll for non moderator %s", data.senderName);
+		       return true;
+		    end
+	        end
 
 		local answers = {}
 		for _, name in ipairs(data.answers) do

```

come to think of it, maybe it would be worth it to add a new data.type 'restricted-polls' and to handle it in JS code.

**Comment by damencho** [comment]
Closing for now. This PR needs rebase and backend handling, in order to move it forward.

**Comment by dimitardelchev93** [comment]
Hi @damencho, sorry for the delay, I will rebase master for this PR and add the backend too eventually if there is a chance you will need it in the future, we do have a use cases for it and it would be great for us not to have to apply our changes on top of the LTS each time :), we have other ideas like adding anonymous polls too, but maybe it is better not to make this PR more complicated for now

**Comment by saghul** [comment]
> Hi @damencho, sorry for the delay, I will rebase master for this PR and add the backend too eventually if there is a chance you will need it in the future, we do have a use cases for it and it would be great for us not to have to apply our changes on top of the LTS each time :), we have other ideas like adding anonymous polls too, but maybe it is better not to make this PR more complicated for now

Sounds about right.

**Comment by pstackoverflow** [comment]
> Hi @damencho, sorry for the delay, I will rebase master for this PR and add the backend too eventually if there is a chance you will need it in the future, we do have a use cases for it and it would be great for us not to have to apply our changes on top of the LTS each time :), we have other ideas like adding anonymous polls too, but maybe it is better not to make this PR more complicated for now

@dimitardelchev93  . Thank you for the above contribution. It will be good to see the backend side of code with anonymous pool functionality even if they do not end up getting merged to Jitsi code. If you think that will make it complex, just put in a different tag (e.g. anonymouspolls) .

**Comment by dimitardelchev93** [comment]
@pstackoverflow here is my anonymous polls implementation https://github.com/jitsi/jitsi-meet/pull/11814

**Pull request closed without merging**
