### PR TITLE
enforce logo by default

### PR DESCRIPTION
**Pull request by emcho**

### CODE REVIEW

**Comment by coccochanel** [comment]
where i can find interfaceConfigWhitelist in my server?


thanks

**Comment by saghul** [comment]
> where i can find interfaceConfigWhitelist.js in my server?
> 
> thanks

It's part of the app bundle, you can't edit it without rebuilding the app.

**Comment by coccochanel** [comment]
thanks for the answer!
how can i rebuild the app?

**Comment by damencho** [comment]
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web

**Comment by damencho** [comment]
Please use the community forum and avoid comments on random issues and PRs, thank you.

**Pull request merged**
