### PR TITLE
Update main-pt.json

### PR DESCRIPTION
**Pull request by jluisfa**
Update of the translation to portuguese language of Portugal

### CODE REVIEW

**Comment by jluisfa** [comment]
I send the signed CLA in this email.

Com os meus melhores cumprimentos,

José Luís Andrade
Consultor, Formador Certificado, Auditor Qualificado

+351 914011290
Espinho, Porto
www.joseluisandrade.com


jitsi-jenkins ***@***.***> escreveu no dia segunda,
14/06/2021 à(s) 18:40:

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by damencho** [comment]
The check failed. There is a missing comma 
```
Unexpected string
   420|     "me": "eu",
```

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
