### PR TITLE
Feature To Get List Of Participants 

### PR DESCRIPTION
**Pull request by mr-shitij**
Because of covid-19 pandemic all educational systems are conducting their classes online and so it is required by teachers to be able to get list of students for presenty and that's why added a feature so that teacher can able to get list of present student in meeting

We use jitsi meet in our collage and i found this a crucial feature in jitsi that's why i added this I hope you also found this help full...!

### CODE REVIEW

**Comment by mr-shitij** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Yes, I did that

**Comment by mr-shitij** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Yes, I did that

**Comment by Nokia808** [comment]
It seem that this is 2nd time to submit this PR ?? - see:
https://github.com/jitsi/jitsi-meet/pull/7880

**Comment by mr-shitij** [comment]
> It seem that this is 2nd time to submit this PR ?? - see:
> #7880

Yes.. !!. Actually last time I wait for a month for review but nothing happed actually so I think is there is any fault from my side so I submitted for preview again. It is my first contribution to open source community.

**Comment by saghul** [comment]
Hey there. I'm really sorry this fell through the cracks. We get more PRs than we can handle at times.

We have been working on such a feature ourselves for a while, it's very close to being in PR. More features in the new panel will follow. Here is a mockup:

Screenshot 2021-03-22 at 10 44 52

So unfortunately I have to close this. I'm really sorry I missed your PR and couldn't let you know earlier.

**Pull request closed without merging**
