### PR TITLE
feat: new security icon

### PR DESCRIPTION
**Pull request by zbettenbuk**
The new icons for the security menu:

image

### CODE REVIEW

**Comment by saghul** [comment]
Did you discuss with Tibi the E2EE label merger with this?

**Comment by zbettenbuk** [comment]
> Did you discuss with Tibi the E2EE label merger with this?

wha do you mean? That the e2ee field was moved to the new sec. menu? That was a direct request from Emil. Or did you mean something else?

**Comment by saghul** [comment]
@zbettenbuk I mean the E2EELabel component that is displayed when every participant enables E2EE. I talked with Tibi about "merging" it with the security shields.

**Comment by zbettenbuk** [comment]
@saghul let's do that as a separate task, it's not closely related to this change

**Comment by saghul** [comment]
It's extremely related since the merger has design implication for the current proposed shields. Please check with Tibi.

**Pull request merged**
