### PR TITLE
commented down stuff

### PR DESCRIPTION
**Pull request by hxrshxz**
It was supposed to be a part of the documentation it seems but wasn't commented so I solved that issue

### CODE REVIEW

**Comment by hxrshxz** [comment]
done

**Comment by damencho** [comment]
We do not accept this change.

**Comment by damencho** [comment]
Can you explain more, what is not in the documentation and why are you commenting this?

**Comment by damencho** [comment]
image

**Comment by damencho** [comment]
Everything looks as expected. So this change will remove the last entry which we do not want to do.

**Comment by hxrshxz** [comment]
ok my apologies

**Comment by hxrshxz** [comment]
i am new here so can u suggest me some good first issues

**Pull request closed without merging**
