### PR TITLE
Update main-uk.json

### PR DESCRIPTION
**Pull request by ostasevych**
Updated Ukrainian localisation, added e2ee strings.

### CODE REVIEW

**Comment by damencho** [comment]
Can you please Close previous PRs if they are not relevant. And keep just one open, please.

**Comment by damencho** [comment]
Also make sure tests are passing, seems you broke the file while editing.

**Comment by ostasevych** [comment]
> Also make sure tests are passing, seems you broke the file while editing.

I made several changes. The last one passed successfully... I may send the file to you, if necessary.

**Comment by luixxiul** [comment]
@ostasevych Which one of the PRs should be left open? would you please close ones except the valid one? thanks!

**Comment by ostasevych** [comment]
> @ostasevych Which one of the PRs should be left open? would you please close ones except the valid one? thanks!
Thanks, please, review #6840, the last one.

**Comment by ostasevych** [comment]
> @ostasevych Which one of the PRs should be left open? would you please close ones except the valid one? thanks!
Thanks, please, review #6840, the last one. The others are no more relevant.

**Comment by luixxiul** [comment]
Closing as duplicate of https://github.com/jitsi/jitsi-meet/pull/6840

**Pull request closed without merging**
