### PR TITLE
Fixed firefox scrollbar issue (#8586)

### PR DESCRIPTION
**Pull request by andrewckor**
This PR fixes the issue (#8586)

### CODE REVIEW

**Comment by saghul** [comment]
@muscat1 I choose you Mihai!

**Comment by muscat1** [comment]
Thanks for looking into the issue!
Took a brief look, but could only get my hands on a Windows machine to test it, and the scrollbar doesn't display on my Mac.
This fix does make the scrollbar prettier when present, and hides it when not needed however I've found a couple of issues.

This is what the scrollbar looks like with the added fix:

148427313_2650839665207097_1316063015281070657_n

However, from what I've noticed, adding `flex-direction: column` ends up pinning the participants to the top of the filmstrip, rather than the bottom, when scrolling isn't a thing, as such:

148588108_777208566256476_799114684521613254_n

The interesting bit that I discovered is the fact that, currently, **that filmstrip is not scrollable whatsoever on Firefox!** (Even if the ugly scrollbar is present)

I've dug around a bit and I might've found a working solution, but I'm not sure if it's fully functional across browsers and operating systems. My proposal would be to add the following:

```
flex-direction: column;
justify-content: flex-end;
overflow-y: auto;
```
What this will do, from what I've tried, is keep the content at the bottom when there aren't enough participants while also hiding the scrollbar, but display the default scrollbar (without the transparent `scrollbar-color`) when applicable, also ensuring the content is actually scrollable, as such:

148020321_207567804401110_2085179361867621599_n

Now I'm not sure if this doesn't break some other things so if you agree with my proposal, please test it out and let me know of your findings. Also, if you are adamant about making it transparent, maybe @saghul can chime in with some of his styling-wisdom. Also pinging @vp8x8 for his CSS-wisdom.

**Comment by saghul** [comment]
I'd just make it invisible if possible...

**Comment by andrewckor** [comment]
This fix is coming from an existing project we are working on, and we tried all of your suggestions, before end up with this solutions. Two things to consider:

1) If you change the flexbox settings, the scroll issue is being fixed on Firefox bit breaks on Chrome.

2) If you select `overflow: auto;` you get another ugly bug that is really really annoying. There is a specific height with a specific amount of user that can make the sidebar appear and disappear many times, ended up having a flickering. That's why overflow: scroll; is better because it displays no scrollbar track on many browsers except Firefox.

And here comes the fix I submitted that makes the scrollbar track transparent ONLY on Firefox, unless you have the many participants where you get a scrollbar handle.

**Comment by muscat1** [comment]
That's fair, what I intended with my proposal is to only apply it to Firefox as well, inside the `@-moz-document url-prefix()` selector. And regardless of that, the fact the initial fix pins participants to the top still remains... I wasn't aware of the `overflow-y: auto` issue, to be honest, so I'm not sure how to proceed with it.

**Review by smatt989 — APPROVED** [review]

**Pull request closed without merging**
