### PR TITLE
feat(avatar) Update design

### PR DESCRIPTION
**Pull request by robertpin**

### CODE REVIEW

**Comment by saghul** [comment]
```
Logger.js:154 2023-03-09T15:31:11.602Z [JitsiMeetJS.ts] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught TypeError: Cannot read properties of undefined (reading 'text01') Script: webpack-internal:///./node_modules/@mui/styles/getStylesCreator/getStylesCreator.js Line: 36 Column: 9 StackTrace:  TypeError: Cannot read properties of undefined (reading 'text01')
    at styles (webpack-internal:///./react/features/base/avatar/components/web/StatelessAvatar.tsx:33:34)
```

**Comment by robertpin** [comment]
> ```
> Logger.js:154 2023-03-09T15:31:11.602Z [JitsiMeetJS.ts] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught TypeError: Cannot read properties of undefined (reading 'text01') Script: webpack-internal:///./node_modules/@mui/styles/getStylesCreator/getStylesCreator.js Line: 36 Column: 9 StackTrace:  TypeError: Cannot read properties of undefined (reading 'text01')
>     at styles (webpack-internal:///./react/features/base/avatar/components/web/StatelessAvatar.tsx:33:34)
> ```

Where is this happening? Shouldn't `make` fail?

**Comment by robertpin** [comment]
Jenkins test this please

**Comment by saghul** [comment]
It was happening at runtime, the large view would not get rendered. Let me test again.

**Comment by saghul** [comment]
I still get this error:

```
 2023-03-10T11:23:03.285Z [JitsiMeetJS.ts] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught TypeError: Cannot read properties of undefined (reading 'text01') Script: webpack-internal:///./node_modules/@mui/styles/getStylesCreator/getStylesCreator.js Line: 36 Column: 9 StackTrace:  TypeError: Cannot read properties of undefined (reading 'text01')
    at styles (webpack-internal:///./react/features/base/avatar/components/web/StatelessAvatar.tsx:33:34)
    at Object.create (webpack-internal:///./node_modules/@mui/styles/getStylesCreator/getStylesCreator.js:27:35)
    at attach (webpack-internal:///./node_modules/@mui/styles/makeStyles/makeStyles.js:114:34)
    at eval (webpack-internal:///./node_modules/@mui/styles/makeStyles/makeStyles.js:259:7)
    at useSynchronousEffect (webpack-internal:///./node_modules/@mui/styles/makeStyles/makeStyles.js:210:14)
    at useStyles (webpack-internal:///./node_modules/@mui/styles/makeStyles/makeStyles.js:251:5)
    at WithStyles (webpack-internal:///./node_modules/@mui/styles/withStyles/withStyles.js:74:23)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:2522:157)
    at updateForwardRef (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:2720:145)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3105:1579)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:657:119)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:677:45)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:696:126)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4036:1)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3825:270)
    at workLoopSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3818:30)
    at renderRootSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3815:195)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3745:121)
    at scheduleUpdateOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3626:1)
    at updateContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4225:313)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4268:29)
    at unbatchedUpdates (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3770:209)
    at legacyRenderSubtreeIntoContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4268:1)
    at Object.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4270:519)
    at LargeVideoManager.updateAvatar (webpack-internal:///./modules/UI/videolayout/LargeVideoManager.js:489:44)
    at eval (webpack-internal:///./modules/UI/videolayout/LargeVideoManager.js:262:12)
```

The LargeView seems to be broken somehow.

Also, the new font looks a bit small, specially when the avatars are large:

Screen Shot 2023-03-10 at 12 26 20

vs:

Screen Shot 2023-03-10 at 12 26 55

**Comment by robertpin** [comment]
> The LargeView seems to be broken somehow.

I'll look into it.

 
> Also, the new font looks a bit small, specially when the avatars are large:

Hmm. It looked okay on prejoin. I'll have another look

**Comment by robertpin** [comment]
Jenkins test this please

**Comment by robertpin** [comment]
Jenkins test this please

**Review by dudumanbogdan — APPROVED** [review]
👍

**Pull request merged**
