### PR TITLE
Feat/lobby challenge response

### PR DESCRIPTION
**Pull request by doganbros**
Better moderation capabilities in locked down rooms: challenge/response in lobby [#9714](https://github.com/jitsi/jitsi-meet/issues/9714)
challenge-response support in chat
knocking participants list updates
knocking participants conditonal checks to show message button
handle challenge-response message events
allow messages in mod_muc_lobby_rooms.lua

Co-authored-by: Fecri Kaan Ulubey f.kaan93@gmail.com

### CODE REVIEW

**Comment by gpatel-fr** [comment]
Hello

I wanted to give a try to this feature however I don't know if I'm doing it wrong but it crashes immediately:

react-dom.production.min.js:196 TypeError: i.getLobbyLocalId is not a function

What's troubling is searching the jitsi-meet source directory I find only this:
```
grep -ir getLobbyLocalId *
react/features/chat/actions.any.js:        const lobbyLocalId = conference.getLobbyLocalId();
react/features/chat/actions.any.js:        const lobbyLocalId = conference.getLobbyLocalId();
react/features/lobby/components/AbstractKnockingParticipantList.js:        _lobbyLocalId: conference && conference.getLobbyLocalId(),
react/features/lobby/actions.any.js:        const id = conference.getLobbyLocalId();
```
I don't find any definition for this function - is your PR depending on another that I failed to find ?

**Comment by umitdogan1** [comment]
> Hello
> 
> I wanted to give a try to this feature however I don't know if I'm doing it wrong but it crashes immediately:
> 
> react-dom.production.min.js:196 TypeError: i.getLobbyLocalId is not a function
> 
> What's troubling is searching the jitsi-meet source directory I find only this:
> 
> ```
> grep -ir getLobbyLocalId *
> react/features/chat/actions.any.js:        const lobbyLocalId = conference.getLobbyLocalId();
> react/features/chat/actions.any.js:        const lobbyLocalId = conference.getLobbyLocalId();
> react/features/lobby/components/AbstractKnockingParticipantList.js:        _lobbyLocalId: conference && conference.getLobbyLocalId(),
> react/features/lobby/actions.any.js:        const id = conference.getLobbyLocalId();
> ```
> 
> I don't find any definition for this function - is your PR depending on another that I failed to find ?
You also need to pull lib-jitsi-meet PR here:
https://github.com/jitsi/lib-jitsi-meet/pull/1811

**Comment by gpatel-fr** [comment]
Thanks I should have thought of that. In fact I thought of it for about 2 secondes before dismissing it because I was thinking that lib-jitsi-meet being low level library would have nothing to do with lobby, a UI feature. Guess I was wrong about that.

Anyway, after giving it a quick whirl, it's pretty well thought out and implemented. 
One could have dreamt of a more complete separation between normal chat and lobby chat, but money don't grow on trees (especially foundation's money) and reusing the existing dialog saved certainly developer's time. 
One could have also dreamt of more tools tips (on the black arrow on each message in the lobby chat,; I wondered for about one minute before understanding what it was about) but it's a really minor minor nit.
I tried to turn a bit adversarial (it's about lobby after all) and sent a pretty loooong message (as in about 250 characters) from the lobby to the moderator, was displayed withtout problem, but the reply was displayed on the lobby screen in a pretty crazy way, all around the place (but one could say: serves the guy right, was trying to disturb the moderator's screen and it's *his* screen that is completely messed up).
Yet another minor nit: some people could object to the moderator's nick being sent to anyone trying to enter. Could say that it's the conference's moderator that is sending the message (more anonymous == more private)

I have tried to send everything and now I have only ONE thing that sticks in my mind: the wording.

Challenge/message.

It's pretty jargony. I know that at your sponsor they are thinking about computers all the time, but it's pretty in-the-face for people for whom challenge/response authentication is an alien concept.

How about this:
```
--- a/lang/main.json
+++ b/lang/main.json
@@ -80,8 +80,8 @@
         "today": "Today"
     },
     "chat": {
-        "challengeResponseNotice": "Challenge-response message to {{recipient}}",
-        "challengeResponseMessageTo": "Challenge-response message to {{recipient}}",
+        "challengeResponseNotice": "Lobby: message sent to {{recipient}}",
+        "challengeResponseMessageTo": "Lobby: message to {{recipient}}",
         "enter": "Enter room",
         "error": "Error: your message was not sent. Reason: {{error}}",
         "fieldPlaceHolder": "Type your message here",
@@ -1201,8 +1201,8 @@
         "knockingParticipantList": "Knocking participant list",
         "allow": "Allow",
         "backToKnockModeButton": "Ask to join",
-        "challengeResponseStartedNotification": "{{moderator}} started a challenge-response chat with {{attendee}}",
-        "challengeResponseStartedTitle": "{{moderator}} has started a challenge-response chat with you.",
+        "challengeResponseStartedNotification": "{{moderator}} sent a lobby message to {{attendee}}",
+        "challengeResponseStartedTitle": "To grant you access, {{moderator}} expects an answer from you.",
         "dialogTitle": "Lobby mode",
         "disableDialogContent": "Lobby mode is currently enabled. This feature ensures that unwanted participants can't join your meeting. Do you want to disable it?",
         "disableDialogSubmit": "Disable",


Finally I should stress that I am just an observer and have nothing to do with the Jitsi project, so feel free to drop my thoughts to the bitbucket.


```

**Comment by gpatel-fr** [comment]
Hello

Did you not sign the CLA ? I'm not sure your PR will be looked at if you don't say you did.
And it would be a shame, because it's quite interesting and well done.

**Comment by umitdogan1** [comment]
> Hello
> 
> Did you not sign the CLA ? I'm not sure your PR will be looked at if you don't say you did. And it would be a shame, because it's quite interesting and well done.

Sure we do sign CLA. I don't think we had an issue related to CLA. It seems Jitsi team is busy with other tasks. You may follow up the merge process from here: https://github.com/jitsi/jitsi-meet/issues/9714

**Comment by gpatel-fr** [comment]
Hello again

I have seen that your PR don't apply cleanly anymore, this weekend I have rebased it on my test server without problem and tested it again, there is still no functional breakage. I have also tested it with the Jitsi-meet test suite (only the lobby) and it passes. That's good.

However I have also taken a second look at it and have seen some things that trouble me.

1) I stand by my first objection about the language: 'challenge-response' is computer specific language and should not be displayed to users. However, there is another issue I did not address in my proposition. The whole context of this change is the adversarial relationship between would-be participants and meeting managers. From this point of view, it's not sufficient to simply change the text; it's also necessary to replace {moderator} by 'a moderator' (anonymous). Knocking persons are asking to enter and the onus of providing information is on them, they do not need to know who is replying to them.

2) speaking of need to know, the 'groupchat' use in Prosody is problematic. If you look at the presence handling in the lobby Lua module (just before your change) you'll notice that there was no small pain suffered to massage the presence message to avoid that knocking users can see the presence of others users. As you use groupchat, other lobby knocking users can see each other. The attack vector is to connect to a meeting EU (Evil user) know are taking place but don't know who is participating, assuming it's restricted information, EU ask for enter but do not reply to the challenge. While the moderator (and possibly other moderators) reply to other users, EU can gather the nicks used. If they are real names, EU win, having learned what they want to know. Possibly EU can try to get access another time by using the nick gathered.
How to fix ? you could possibly filter the groupchat messages like it's done for the presence. Or consider dropping the groupchat altogether and use only private message for everything. I guess it would be necessary then to explicitly send the initiate dialog to the other moderators.  But it would simplify the code.

3) Speaking of simplifying the code, what's the use of MODERATOR_CHATTING_WITH_LEFT ? why send a message in this case since the lobby knocking users already get a presence unavailable stanza ? I have tried to delete the sending code:
```
--- a/react/features/lobby/actions.any.js
+++ b/react/features/lobby/actions.any.js
@@ -350,21 +350,6 @@ export function updateLobbyParticipantOnModeratorLeave(participantId: string) {
             return dispatch(removeChallengeResponseParticipant(true));
         }
 
-        if (!knocking) {
-            // inform knocking participant when their moderator leaves
-            const participantToNotify = knockingParticipants.find(p => p.chattingWithModerator === participantId);
-
-            if (participantToNotify) {
-                conference.sendPrivateLobbyMessage(participantToNotify.id, {
-                    type: MODERATOR_CHATTING_WITH_LEFT,
-                    moderatorId: participantToNotify.chattingWithModerator
-                });
-            }
-            dispatch({
-                type: REMOVE_CHALLENGE_RESPONSETING_WITH_MODERATOR,
-                moderatorId: participantId
-            });
-        }
     };
 }

```
and everything seems to work just as well. So unless I'm missing something, it could go. Less code is alway better IMO.

4) on code readability, the 'REMOVE_CHALLENGE_RESPONSETING_WITH_MODERATOR' name is not good at all. I have not investigated what it's doing (time flies), but it's much worse than MODERATOR_CHATTING_WITH_LEFT (a bit clumsy but I think it should be totaled anyway see point 3) because it does not make sense at all, it's not bad English, it's not *even* English.

5) on the Prosody module, a small detail: you deleted part of this line:
      elseif stanza.name == 'iq' and stanza:get_child('query', DISCO_INFO_NS) then
            -- allow disco info from the lobby component
to remove the test on the query child, but left the following comment. This is not coherent, and removing apparently unrelated code should be explained in the commit message. I have also tried to leave the code exactly as it was before (just leaving the added line to allow messages), and the functionality is not impacted at all. So why remove this 'and stanza:get_child('query', DISCO_INFO_NS)' ??? I don't know why it's here but we can assume it was put there for a reason.

6) missing in action: lobby knocks handling is duplicated in the Participants pane. Your changes are not replicated there. I guess it's not a mortal sin (personal opinion of course) because I think that it's mostly used for mobile use, and your change don't address mobile for now. Also, I think that moderating a complex meeting on a mobile is a slightly absurd requirement. Using the functionality on a mobile to enter meetings is a solid use case, moderating them, less so (I think). But you should justify this one.

7) I said that the Jitsi-meet lobby test was still working, but do you intend to produce a test for the feature ? It's a complex one, I don't think that Jitsi devs will accept your PR without some automatic regression test. 

I don't know if you are still waiting for a review or if you have off-channel exchanges with Jitsi team, but if it's the former, you may consider addressing some of the ideas I outlined before resubmitting an updated PR.

**Comment by damencho** [comment]
Hey @doganbros Can you fix the conflicts, I want to move this forward and probably will create a separate deployment for it so Product team can take a look.
There is one thing that we are moving the lobby notifications https://github.com/jitsi/jitsi-meet/pull/10766 and if we merge that PR there will be again conflicts which will need more refactoring. 
Not sure how to proceed with both ...

**Comment by umitdogan1** [comment]
@damencho thanks. Ok will fix the conflicts and let you know.

**Comment by damencho** [comment]
Thanks. Also, check the comments from @gpatel-fr, I think they are valid.

**Comment by umitdogan1** [comment]
@damencho sure we are already on it. @gpatel-fr thank you.

**Comment by doganbros** [comment]
This pull request has been moved to #10847.

**Pull request closed without merging**
