### PR TITLE
Update main-ar.json

### PR DESCRIPTION
**Pull request by ali-alhaidary**

### CODE REVIEW

**Comment by ali-alhaidary** [comment]
@saghul

**Comment by ali-alhaidary** [comment]
> Hi, thanks for your contribution! If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Already signed.

**Comment by ali-alhaidary** [comment]
@saghul kindly review and merge...

**Comment by damencho** [comment]
Jenkins test this please

**Comment by ali-alhaidary** [comment]
Jenkins test this please

**Review by saghul — APPROVED** [review]

**Pull request merged**
