### PR TITLE
doc(quick-install): Update recommend browser list

### PR DESCRIPTION
**Pull request by jayaddison**
Update the list of example browsers during quick-install.  Follows on from [prior discussion](https://github.com/jitsi/jitsi-meet/pull/5227/commits/dadc83900f70c11b100b92aae2acce25480ab460#r394485413) and is based on [browser market share](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#Summary_tables) (Wikimedia, Nov 2019) and Jitsi's [optimal browser list](https://github.com/jitsi/jitsi-meet/blob/4824c8714aeb35bfa4bd373dbbada018e49dc0e2/interface_config.js#L178) at the time of writing.

### CODE REVIEW

**Comment by jayaddison** [comment]
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

(I've signed the CLA)

**Comment by luixxiul** [comment]
Hello, I would like to let you know that since the documentation was moved to https://github.com/jitsi/handbook/, I cherry-picked this comment and opened a PR here https://github.com/jitsi/handbook/pull/1 with other commits on documentation. I hope you don't mind. 

This PR should be closed after the PR on the new repository is merged.

Thank you for your commit!

**Comment by jayaddison** [comment]
Thanks for doing that and retaining the author commits @luixxiul.  I'll take a look at the developer handbook soon and provide any future documentation feedback/improvements there.

**Comment by luixxiul** [comment]
> retaining the author commits

I believe that is the best way of avoiding plagiarism and recognizing the author 😄

**Pull request closed without merging**
