### PR TITLE
fix: don't let robots index jitsi installations

### PR DESCRIPTION
**Pull request by janwillemvd**
Currently, [Google](https://www.google.com/webhp?q=site:meet.jit.si) (and other engines) will index everything.

This PR avoids that.

### CODE REVIEW

**Comment by janwillemvd** [comment]
@jitsi-jenkins signed

**Comment by saghul** [comment]
Thanks for this! Is this required now that we have this? https://github.com/jitsi/jitsi-meet/commit/6596e27f696c8fb7bf7e7bd0574ae2640f865e6f

**Comment by janwillemvd** [comment]
@saghul I hadn't see 6596e27

6596e27 should be sufficient indeed, however you might consider adding the html noindex meta tag to the jitsi room URLs as well (and not on the home page). Better safe than sorry ;)

**Comment by saghul** [comment]
Thanks for confirming! I think we currently don't have a very good way to put it just for the in-conference page, since they both load head.html. Let's keep this open nevertheless, and see how it could be applied.

**Comment by Echolon** [comment]
Are is there a direct suggestion how to proceed on this topic?

**Pull request closed without merging**
