### PR TITLE
feat: Moves luajwtjitsi in jitsi-meet.

### PR DESCRIPTION
**Pull request by damencho**

### CODE REVIEW

**Comment by damencho** [comment]
Hey @saghul @aaronkvanmeerten wdyt?

**Review by aaronkvanmeerten — APPROVED** [review]

**Review by saghul — APPROVED** [review]
I like it. Should we deprecate the other repo?

**Comment by saghul** [comment]
> There are some tests in luajwtjitsi that we lose with this ...

We could keep the other repo as the canonical source and just copy snapshots here? That way we preserve the tests?

**Comment by damencho** [comment]
yep, sounds good. I need to figure out now the tests failing :) aaa because of missing those debian dependencies on pr-testing machine. Will fix it and re-run tests

**Comment by damencho** [comment]
will study it further and test again.

**Review by aaronkvanmeerten — APPROVED** [review]

**Pull request merged**
