### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by paweldomas** [comment]
Also are you sure there's no way around `__filename`?

**Comment by saghul** [comment]
> Also are you sure there's no way around lack of `__filename` for RN?

I tried but either couldn't find a way of ran out of talent. My understanding is that it's not possible to provide it since Metro would have to do it as part of the bundling process.

**Comment by paweldomas** [comment]
> I tried but either couldn't find a way of ran out of talent. My understanding is that it's not possible to provide it since Metro would have to do it as part of the bundling process.

I see. I guess that filename would not be so useful given how we use `middleware.js`, `actions.js`, `reducer.js` etc. names anyway.

**Comment by saghul** [comment]
> I see. I guess that filename would not be so useful given how we use `middleware.js`, `actions.js`, `reducer.js` etc. names anyway.

Indeed. They also just make the logline longer.

**Comment by saghul** [comment]
Jenkins please test this please.

**Pull request merged**
