### PR TITLE
add mention of UDP ports to open on the proxy.

### PR DESCRIPTION
**Pull request by danielleberre**
Dear jitsi team,

Thanks for your great tool! I have been using it for a week to teach. It worked pretty well.

Just one small note regarding the installation process, that I followed to install my own instance.

I am behind a NAT. I had to open the range of UDP ports 16384 to 32768 to have jitsi fully working.

This PR updates the quick-install documentation with that information.

Keep up the good work!

### CODE REVIEW

**Comment by damencho** [comment]
Why do you need that? For which component? No component is using those ports.

**Comment by danielleberre** [comment]
Until I opened those ports, jitsi runs out of sockets after 1 hour of use (20 users).
I had those messages:

```
org.ice4j.socket.MergingDatagramSocket.log() Cannot find socket to remove.
org.jitsi.impl.neomedia.rtp.TransportCCEngine.log() No source SSRC, can't send RTCP.
```

googling gave me the suggestion to open those ports. Since then, jitsi works just fine.

**Comment by damencho** [comment]
Running out of sockets is another problem and will not be fixed by forwarding ...

**Comment by damencho** [comment]
jvb just uses port 10000 udp, all traffic comes on that port,

**Comment by danielleberre** [comment]
ok, closing the PR then. Sorry for the inconvenience.

**Pull request closed without merging**
