### PR TITLE
FEAT: Automatically copy invite URL after creating a room

### LINKED ISSUE #7501: Automatically copy invite URL after creating a room?
**Is your feature request related to a problem you are facing?**

Zoom has the feature where creating a new room will automatically copy the URL (and just the URL) into your system's copy buffer for immediate pasting into chat, mail, etc. I notice that even after having switched to Jitsi a number of months ago I keep pasting (accidentally) whatever is in my buffer because my brain keeps thinking the URL will already be copied ... 

**Describe the solution you'd like**

I'd love if we could add this (optionally, and maybe even just in the Electron app, depending on whether browsers would support this without user interaction).

### PR DESCRIPTION
**Pull request by RabeeAbuBaker**
Resolves #7501
- Automatically copy invite URL after creating a room

### CODE REVIEW

**Comment by damencho** [comment]
Have you tested this? I suspect browsers will not let you access clipboard in nonuser interaction event ... 
Also to be able to merge it, you should add that behind a flag and disable it by default.

**Comment by RabeeAbuBaker** [comment]
> Have you tested this? I suspect browsers will not let you access clipboard in nonuser interaction event ...
> Also to be able to merge it, you should add that behind a flag and disable it by default.

I did test it, it worked perfectly. At least on Chrome. Should I do further testing on other browsers to make sure?
If it's disabled by default, how should it be enabled?

**Comment by RabeeAbuBaker** [comment]
Closing the PR for an issue with github username (committed code with wrong account)

**Comment by damencho** [comment]
> Should I do further testing on other browsers to make sure?

Yep. At least Firefox and Safari.


> If it's disabled by default, how should it be enabled?

Whoever wants can enable it on their deployments by default or through an URL. We need to discuss it internally whether we want to enable it on deployments we control. Anyway, that is a big change in behavior, and that should be disabled by default and people should be able to control it.

Personally I don't like this behavior, I would be very annoyed if an app is deleting my clipboard automatically.

**Pull request closed without merging**
