### PR TITLE
feat(prejoin) show error when trying to join and name is required

### PR DESCRIPTION
**Pull request by quitrk**

### CODE REVIEW

**Comment by damencho** [comment]
Why is this change? If button is not being disabled anymore you will need to update and tests. And add tests for the new cases https://github.com/jitsi/jitsi-meet-torture/blob/master/src/test/java/org/jitsi/meet/test/PreJoinTest.java

**Comment by damencho** [comment]
@quitrk ^ ?

**Comment by quitrk** [comment]
Requested by UX team, will update tests

**Comment by damencho** [comment]
Jenkins test this please.

**Pull request merged**
