### PR TITLE
Added Portuguese European (Portugal) pt language

### PR DESCRIPTION
**Pull request by Ricardo-Simoes**
Took ptBR (Brazilian) as base, and added pt Portuguese European (Portugal). I need this to work fast since in my country schools and companies are closed and/or quarantine and people, students, and professors need an open-source solution for video conferencing, and advising the Portuguese goverment to adopt open source solutions

### CODE REVIEW

**Comment by jluisfa** [comment]
In meet.jit.si only the "Portuguese (Brazil)" option is there.
The Portuguese European (Portugal) option is not available 

imagem2

**Comment by damencho** [comment]
Yep, it wasn't added to https://github.com/jitsi/jitsi-meet/blob/master/lang/languages.json, I'll add it.

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/pull/8930

**Comment by jluisfa** [comment]
Now, in alpha.jitsi.net and beta.meet.jit.si, already appears "Language: Portuguese".
Thanks!
imagem2

However, the text on the screen is not translated into Portuguese from Portugal.

imagem3

I suggest a quick UI translation of the file jitsi-meet/lang/main-pt.json by adding:

```
+ "joinMeeting": "Participar da reunião"
+ "joinTooltip": "Participar da reunião"
+ "joinWithoutAudio": "Participar sem áudio"
+ "doNotShow": "Não mostre este ecrã novamente"
+ "lookGood": "O seu microfone está a funcionar corretamente"

+ "lonelyMeetingExperience": {
+        "youAreAlone": "Está sozinho na reunião",
+        "button": "Convidar outros"
+    }

+ "inviteMorePrompt": "Convide mais pessoas"
```

**Pull request merged**
