### PR TITLE
ref(conference) retrieve local tracks from store instead of keeping l…

### PR DESCRIPTION
**Pull request by quitrk**
…ocal references

### CODE REVIEW

**Comment by damencho** [comment]
What is the problem you were seeing which you are trying to fix?

**Comment by quitrk** [comment]
this is part of a larger refactoring plan to move logic away from conference.js (e.g. in this case this will be required for moving the logic for initializing the devices list)

**Comment by paweldomas** [comment]
Make sure that this works with iframe API which allows to do track operations, before the store is ready. I think that was the biggest obstacle in moving the tacks from conference.js to the store.

**Comment by paweldomas** [comment]
Hm but looking at the code it already relies on the store being ready, so maybe not important or this is broken already.

**Pull request closed without merging**
