### PR TITLE
Update Virtual Background Model

### PR DESCRIPTION
**Pull request by rpulapura**
* Correcting lint errors from https://github.com/jitsi/jitsi-meet/pull/9867

### CODE REVIEW

**Review by quitrk — DISMISSED** [review]

**Comment by saghul** [comment]
Thanks for the update! What's the difference between the landscape and non-landscape model?

**Comment by rpulapura** [comment]
> Thanks for the update! What's the difference between the landscape and non-landscape model?

The landscape model has the same dimensions of the larger of the two previous models. We decided to go with that rather than introducing lag with the bigger model.

**Comment by saghul** [comment]
Sounds good. Let's remove the unused model from this PR then please.

**Comment by rpulapura** [comment]
> Sounds good. Let's remove the unused model from this PR then please.

Hi! Just wanted to follow up on this, are any further changes needed?

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
So sorry for the delay on this one. Merged!

**Pull request merged**
