### PR TITLE
Croatian translation of main-hr.json

### PR DESCRIPTION
**Pull request by milotype**
Complete translation with current "main.json" file

### CODE REVIEW

**Comment by saghul** [comment]
The `kontakti` key,, which I'm not even use it's valid, since we use our key names in English, is not alphabetically sorted in the `addPeople` dialog. I suspect you translateed both ends by mistake. The left side should read "contacts" and then it will be sorted correctly.

**Comment by milotype** [comment]
@jitsi-jenkins OK, just signed your CLA.

**Comment by milotype** [comment]
@saghul Thank you for catching it. Sorry for the mistake. I've updated the file in my branch.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Thank you!

**Pull request merged**
