### PR TITLE
Optimize PNG images

### PR DESCRIPTION
**Pull request by maximal**
I optimized all PNG files in this repo with `optipng` utility on maximum compression settings. The result is incredibly good.

Total PNG images’ size decreased by 22 MiB out of 98.57 MiB. Which is 22.4 % size saving.

If this diff is too big for the repo I can make a pull request for web accessible icons only (`images` directory). It will be 47 of 431 KiB saving (−11 %).

Some statistics:
* Total PNG files: 116
* Total size: 98.57 MiB (103’358’172 Bytes)
* Optimized files: 81 of 116
* Total size after optimization: 76.49 MiB (80’202’177 Bytes)
* Saved: 22.08 MiB (23’155’995 Bytes) which is 22.4 %

### CODE REVIEW

**Comment by maximal** [comment]
> If you haven't already done so

:heavy_check_mark: Done.

**Comment by luixxiul** [comment]
Despite being amazed, I wonder if compressing the original files would be a proper solution 🤔 Compressing during building would be better I assume. Just my 2 cents.

**Comment by maximal** [comment]
> Despite being amazed, I wonder if compressing the original files would be a proper solution  Compressing during building would be better I assume. Just my 2 cents.

Maybe you’re right. Just keep in mind that this process is quite long (10 minutes on Core i5 or so).

**Comment by luixxiul** [comment]
For ~80 files, yeah it would take around that 😓 

Though PNG is lossless compression, I'm no expert here, so please disregard my comments.

**Comment by paulmenzel** [comment]
Looks good, and is sensible to do. Maybe to one commit per directory/component (Android, iOS, badges, …), so in case regressions are noticed, they can be easily reverted?

**Comment by maximal** [comment]
> Looks good, and is sensible to do. Maybe to one commit per directory/component (Android, iOS, badges, …), so in case regressions are noticed, they can be easily reverted?

Could you pleas provide here needed directories then? Unfortunately I’m not familiar with this project’s structure and architecture.

@paulmenzel

**Comment by luixxiul** [comment]
@saghul / @damencho: Would you please let us know what you would think on this PR? Thanks!

**Pull request closed without merging**
