### PR TITLE
feat(rn) switch to XCFramework and WebRTC M87

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Review by gpolitis — APPROVED** [review]

**Comment by maxired** [comment]
Hey @saghul would to be able to explain the reason of that change ?
I am trying to build a version without that commit, and this is currently failing. SO would like to know if this is related.

**Comment by saghul** [comment]
Sure thing. XCFramework are easier to manage since there is no need for manual architecture slicing both when building the framework and when submitting to the store.

What problem are you running into? Are you using CocoaPods 1.10 ?

**Comment by maxired** [comment]
Capture d’écran 2020-12-02 à 20 42 20

currently using cocoapod 1.9 and xcode 11.4.1 , but same issue was reproduced with codoapod 1.10 and code 12.

I thought the release 1.84.1 from this lib would fix the issue, but does not seems like it does.

**Comment by saghul** [comment]
If you are using master then you need 1.87. Xcode 12 and CocoaPods 1.10 are required.

**Pull request merged**
