### PR TITLE
fix(whiteboard) compute serverUrl once to limit rerenders

### PR DESCRIPTION
**Pull request by mihhu**

### CODE REVIEW

**Comment by damencho** [comment]
LGTM, one quick question. We do not print anything if whiteboard is disabled and not used on the deployment, right?

**Comment by mihhu** [comment]
> LGTM, one quick question. We do not print anything if whiteboard is disabled and not used on the deployment, right?

You mean [this error](https://github.com/jitsi/jitsi-meet/pull/14600/files#diff-3af1cc873af7d049e6a20be8e2444c35d53111ad532381bf58dd42113435ad9dR190)? It won't show up unless a postMessage is called from the WhiteboardApp entry point that's passed to the Whiteboard WebView (and the collab data is missing).

**Review by damencho — APPROVED** [review]

**Comment by saghul** [comment]
How are re-renders  happening, given the URL is in config thus loaded once?

**Comment by mihhu** [comment]
> How are re-renders happening, given the URL is in config thus loaded once?

[This selector](https://github.com/jitsi/jitsi-meet/blob/master/react/features/whiteboard/functions.ts#L91) is called directly in the views and @damencho pointed out it can be improved.

**Comment by saghul** [comment]
I had misread, it's the full url, so it makes sense!

**Comment by damencho** [comment]
I was seeing the construction of the URL even when the whiteboard was not shown as the component is there. But even when whiteboard is on, we should do that once and not on every possible action.

**Pull request merged**
