### PR TITLE
feat: introduce green screen effect

### PR DESCRIPTION
**Pull request by tflanagan**
First off, Jitsi is a wonderful tool, thank you for all of your hard work.

In looking for alternative conference tools, Jitsi is at the top of the list, but one of the key features that prevents it from becoming the chosen solution is the lack of a "green screen" effect.

In an effort to fast track this much needed feature, I went ahead and made a rough introduction.

React and your environment in general are pretty foreign to me, so I'm sure there are some things you would've done differently. Please don't hesitate to point them out.

That said, I used the blur effect as a starting point, including the beta tag, and went from there. Overall, it works pretty well.

One of the key differences is that I noticed the blur effect introduces a potential leak in regards to the web worker. When you disable the effect, the worker persists. Granted, if you re-enable it, the same worker is consumed, but when it is disabled and never reactivated, the worker persists. Looking into the functionality of the worker, it seemed pretty strange. It looks like a manual FPS-esque/animation timer, so I removed that concept and switched to using `requestAnimationFrame`. I'm unsure of the original development conversation and the reasons these decisions were made, but I believe the blur effect should switch to this method as well and will open a separate PR if desired.

This PR introduces the "green screen" effect in a few different ways. There is the typical chroma key effect, then two implementations of the `bodyPix` library, MobileNet and ResNet.

Most parameters are configurable in a new "Green Screen" settings tab, including the color via a color picker widget for the chroma key effect, the chroma key threshold, all the various `bodyPix` parameters via dropdowns and range sliders, and the ultimate rendering FPS. Making these configuration options available was an effort to give users with lower tiered computers the ability to use the functionality.

Testing has been pretty minimal. I've used my 5 year old desktop, 10 year old laptop, 3 year old android and ios phones. Without too much resource usage, all were able to use at least the Chroma Key and MobileNet settings, with only the desktop being able to use the ResNet setting.

Possible additions/changes:
- Support (short?) video clips as a green screen
- More configuration (segmentationThreshold, maxDetections)
- Automatically restart the effect when enabled and settings have changed
- Preview of rendered green screen effect instead of just the selected image in the settings tab
- Different euclidean distance equation for the chroma key effect

References: #5860

### CODE REVIEW

**Comment by jallamsetty1** [comment]
Hi @tflanagan, this is very impressive! Thank you for your efforts, it is a big feature and I am sure Jitsi community would be very excited about a Green screen feature. Sorry it took us a while to take a peek at this PR.

The reason we have blur still in beta is the cpu load it generates on the client machines and even on the latest macbooks we get a very low fps since the mask computations take long. Enabling it on some of the slower laptops totally overwhelm the browser making it totally unresponsive.

We had planned some optimizations around the blur feature but Covid-19 made us push it to the bottom of the list as we had to address the more pressing issues around scalability. One idea we had was to move the mask computation to a worker so that the UI/main thread is not blocked while the mask is being computed. Looks like it is a common practice - https://erdem.pl/2020/02/making-tensorflow-js-work-faster-with-web-workers

I was very intrigued and built your branch but I ran into an error, I fixed it but I still couldn't get it to work. The effect didn't load and there was an error with starting the camera. Maybe you forgot to push some of your changes ?

Regarding your comment about using `requestAnimationFrame`, the callback passed to it will only be invoked before the next repaint. So I would assume that the mask will not be rendered if you have another window covering your browser so that the rendering pauses. Don't you see that happening ? The other participants in the call should clearly see that the effect will be paused when that happens.

**Comment by tflanagan** [comment]
Thanks for your comments. I apologize for the errors, could you elaborate?

I'll do more testing with the WW approach and try to find the missing commit from my side to resolve your errors.

**Comment by jallamsetty1** [comment]
> Thanks for your comments. I apologize for the errors, could you elaborate?
> 
> I'll do more testing with the WW approach and try to find the missing commit from my side to resolve your errors.

Sorry for the delay.
Looks like createVideoGreenScreenEvent method definition is missing from Analytics. After I commented out the send event, I wasn't able to see the green screen effect. The screen went gray and there was a camera error but I didn't see any errors in the console logs.
Screen Shot 2020-08-13 at 8 25 14 PM
Screen Shot 2020-08-13 at 8 33 03 PM

**Comment by heikar** [comment]
@tflanagan have you any news about it?

**Comment by tflanagan** [comment]
I'm not able to reproduce the issue in my test environment. My test environment also was missing the analytic function, however, that was not preventing the feature from working.

Screenshot_11

As I do not think the webworker vs requestAnimationFrame concept is what's at fault, I'm curious about your environment and what's going on.

**Comment by tflanagan** [comment]
@jallamsetty1, if you could try going to https://meet.quickbase.dev/ and testing it there. I'm curious what would happen. (This is my personal testing environment)

**Comment by hmharshit** [comment]
> > @jallamsetty1, if you could try going to https://meet.quickbase.dev/ and testing it there. I'm curious what would happen. (This is my personal testing environment)
> 
> I didn't get a chance to debug why the effect wasn't getting enabled on my instance but I tried to join a call on your test environment. It is asking me to enter a userid/password to join the call.

@jallamsetty1 I had a also used this code to enable this feature in my instance. I was also facing the same issue. I modified the webpack.config.js which fixed this issue for me & I'm able to use this feature. May be it helps.

**Comment by tflanagan** [comment]
@hmharshit 

What was the fix to `webpack.config.js`?

**Pull request closed without merging**
