### PR TITLE
Feat/emit raise hand event

### PR DESCRIPTION
**Pull request by m0hdasif**
This will expose the raise hand event to the external API.

### CODE REVIEW

**Comment by m0hdasif** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

We have signed the CLA for corporations as "VideoFacilitator Pty Ltd"

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by damencho** [comment]
What is the purpose of these changes? We realized that it doesn't change the participant properties, so it will not notify the remote participants that the participant had raise hand.

**Comment by m0hdasif** [comment]
> What is the purpose of these changes? We realized that it doesn't change the participant properties, so it will not notify the remote participants that the participant had raise hand.

The purpose of this change is to expose the raise hand event to the external API. 
Yes, it does not change the participant properties, but we have added a new event(raise-hand-updated). The event will notify the remote participants whenever user raise/lower the hand with handRaisedStatus and participant ID. This change can be used to get the event in external(iframe) API and can be used to show the list of participants with raised hand.

**Review by damencho — CHANGES_REQUESTED** [review]
These changes will break mobile.

**Comment by m0hdasif** [comment]
> These changes will break mobile.

@damencho, 
Since the changes are not modifying/ removing the existing feature, may I know how it can break the existing app in mobile? 

What changes should I make to get the raise hand event  notification in external API without breaking changes?

And, I could find any event with name **participantUpdated** in the [External API](https://github.com/jitsi/jitsi-meet/blob/master/modules/API/external/external_api.js) if we need to add the data in the participant properties.

**Comment by damencho** [comment]
You cannot use APP.API. in code used on mobile.

**Comment by damencho** [comment]
You need at least: 
```
if (typeof APP !== 'undefined') {

```
You can see in other places how is that protected.

**Review by damencho — APPROVED** [review]

**Comment by m0hdasif** [comment]
the requested changes

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by damencho** [comment]
@m0hdasif Can you also update the docs for available events once we merge it: https://github.com/jitsi/handbook/blob/master/docs/dev-guide/iframe.md? Thanks.

**Comment by m0hdasif** [comment]
Sure @damencho , I will do it.

**Comment by m0hdasif** [comment]
@damencho, the said changes are done in the [Handbook PR #130](https://github.com/jitsi/handbook/pull/130).

**Pull request merged**
