### PR TITLE
Allow user to select camera or microphone

### PR DESCRIPTION
**Pull request by isymchych**
This allows user to select other camera or microphone.

**Still WIP!**

### CODE REVIEW

**Comment by Starl3n** [comment]
A good device to test this with is the Surface Pro 3 or 4. The default camera is on the back of the tablet so changing to the front camera presents as an issue for end users.

**Comment by akuckartz** [comment]
I can test on an Android phone with two cameras.

**Comment by isymchych** [comment]
Hi
You can already try to test it if you want - there should be 2 dropdowns with your devices in the Settings sidebar

It's stil WIP just because UI should probably be improved :)

**Comment by akuckartz** [comment]
@isymchych :smile:

**Comment by isymchych** [comment]
updated version of PR is here https://github.com/jitsi/jitsi-meet/pull/492

**Pull request closed without merging**
