### PR TITLE
Optimised Images

### PR DESCRIPTION
**Pull request by agarwalutkarsh554**

### CODE REVIEW

**Comment by agarwalutkarsh554** [comment]
I have signed the CLA please check

**Comment by saghul** [comment]
Optimized how?

**Comment by agarwalutkarsh554** [comment]
The size of every image is reduced by at least 60%

**Comment by saghul** [comment]
Thanks for the effort here. We are not keen on doing these optimizations at this point though. A number of those images are obsolete, and generally, their size if not an issue in practical terms.

**Pull request closed without merging**
