### PR TITLE
fix(libre-build) skip spurious Firebase and GCM dependencies

### PR DESCRIPTION
**Pull request by saghul**
Fixes: https://github.com/jitsi/jitsi-meet/issues/8353

### CODE REVIEW

**Comment by saghul** [comment]
Marking as draft since react-native-device-info needs updating to avoid hardly depending on com.android.installreferrer

**Comment by saghul** [comment]
Tested the fix, works now, with the updated react-native-device-info.

**Comment by saghul** [comment]
https://github.com/react-native-device-info/react-native-device-info/pull/1156 should fix it, I'll pull the new release once it's merged upstream.

**Comment by saghul** [comment]
Made another PR to device-info and 8.0.0 is now out.

**Review by tmoldovan8x8 — APPROVED** [review]

**Comment by licaon-kter** [comment]
I'm pushed the recipe with -fdroid2 tag, is that ok or I should update it?

**Comment by saghul** [comment]
That's ok, this PR went to master, but that tag has it included already since it was on a release branch. Thanks for your help with the F-Droid build!

**Pull request merged**
