### PR TITLE
fix(copyText): in iframe for chrome<85

### PR DESCRIPTION
**Pull request by hristoterezov**

### CODE REVIEW

**Review by damencho — APPROVED** [review]

**Comment by saghul** [comment]
So what happens in Chrome 85. We checked caniuse for the clipboard API and didn't see anything: https://caniuse.com/mdn-api_clipboard_writetext

Please add these kinds of info to the commit message so the knowledge is not lost.

**Comment by damencho** [comment]
It is broken for using it cross domain ... I should have pasted the bugreport

**Comment by damencho** [comment]
It is very complicated story anyway when you include different domains and different electron and different implementations in electron usage ...

**Comment by damencho** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1074489

**Comment by saghul** [comment]
Thanks for pasting that here!

**Pull request merged**
