### PR TITLE
Adds setting subject and adding event on receiving such change.

### PR DESCRIPTION
**Pull request by damencho**

### CODE REVIEW

**Comment by damencho** [comment]
Yep, we need it to be set from the iframe api, which this pr addresses. The lib-jitsi-meet already fires events when this is changed on the server, so next step is to hook it in the UI, redux or whatever is needed.

**Comment by damencho** [comment]
If this available on the mobile, I suppose it is already using the lib events and stores it and what is missing is just the web UI?

**Comment by saghul** [comment]
> If this available on the mobile, I suppose it is already using the lib events and stores it and what is missing is just the web UI?

No, we currently show the room name nicely formatted or the JWT caller name.

**Comment by saghul** [comment]
>  The lib-jitsi-meet already fires events when this is changed on the server, so next step is to hook it in the UI, redux or whatever is needed.

Is that going to be part of this PR or upcoming ones?

**Comment by damencho** [comment]
> Is that going to be part of this PR or upcoming ones?

Upcoming I guess. We need to schedule the work. This one was, I think, in Hristo's to-do list, but I was bored on Sunday and took it as I was discussing the backend with some oder folks few days ago ...

**Pull request merged**
