### PR TITLE
Add the ability to configure a 'minimal' display mode

### PR DESCRIPTION
**Pull request by gerges**
I've added a minimal display option that hides all non-call features, let me know what you think

### CODE REVIEW

**Comment by hristoterezov** [comment]
@gerges Thank you for the PR! Sounds like an useful feature.

Don't you think it would be better if we have an enumerated set of enabled buttons in the interface_config instead of 2 different modes? That way users will be able to define their own sets of buttons.

**Comment by paweldomas** [comment]
@hristoterezov for me 'minimal' is ok as it's simplier for the start. Making it possible to define own set of buttons could be another step. But it's just my personal opinion not sure what the others think.

**Comment by emcho** [comment]
I agree that different people will have a different view of what minimal is. Just passing a set of buttons doesn't sound significantly more complicated anyway.

**Comment by gerges** [comment]
I've opened pull request #338 to refactor the toolbar to better support the suggestions above, once that's merged i'll address these comments

**Comment by gerges** [comment]
I'm going to close this PR and create another for a configurable toolbar

**Pull request closed without merging**
