### PR TITLE
Fixed insecure-room-name-warning color to dark red.

### PR DESCRIPTION
**Pull request by P-FardeenMalik**
Close https://github.com/jitsi/jitsi-meet/issues/14224

The color message changed to dark red, now the message can be easily read.

### CODE REVIEW

**Comment by P-FardeenMalik** [comment]
Done @jitsi-jenkins I have signed for individual

**Comment by P-FardeenMalik** [comment]
after

This is the screenshot after changing the color to dark

**Comment by P-FardeenMalik** [comment]
Hello @saghul is there any issue in merging this pull request? If yes feel free to tell

**Comment by saghul** [comment]
The text it's still very hard to read. It needs a background or something. We'll ask design.

**Pull request closed without merging**
