### PR TITLE
Tileview status api

### PR DESCRIPTION
**Pull request by sretika**
Adding isTileViewEnabled() to external API that returns the current Tileview status.

### CODE REVIEW

**Comment by sretika** [comment]
CLA signed.

**Comment by guillaumepotier** [comment]
Hi there,

Thanks for this PR. I think this is a great and needed improvement, in order to know better when to toggle Tileview or not.

It would be great if a project admin could review and validate this one.

Best

**Comment by luixxiul** [comment]
@guillaumepotier did you test the PR to approve that (per https://github.com/jitsi/jitsi-meet/pull/6764#pullrequestreview-424152740)?

**Comment by faahren** [comment]
Hello !
Any idea why this has never been merged ?
Thanks

**Comment by ptandler** [comment]
Hi, this would be so helpful, please consider merging!

**Comment by ptandler** [comment]
looking at the changes, this doesn't look very complicated to review, I think ...

**Comment by pandel** [comment]
+1 still searching for solution to enable tile view permamently! Please add this feature :-)

**Comment by ptandler** [comment]
@pandel This https://github.com/jitsi/jitsi-meet/issues/5764#issuecomment-647041932 from @NodeGuy worked perfectly for me.

If you in addition remove the tile button, then it should be enabled permanently I guess

**Comment by vrde** [comment]
Looking forward to see this merged :)

**Comment by pratik9722** [comment]
@ptandler thanks for that but is it possible that we can also define pin participants by display name.
That way I can show which participan's video should are shown when title view is not enabled ( & also follow me options is not enabled by moderator )

**Pull request closed without merging**
