### PR TITLE
fix(i18n) Accessiblity labels translations

### PR DESCRIPTION
**Pull request by guusdk**
As accessibility labels are likely to be used by assistive technologies (screen readers, text-to-speech software, speech recognition software, etc), it is desirable to have accessibility labels available in the native language of the end user. As such, their values should be translatable.

This PR replaces most* hard-coded English values for accessibility labels with a lookup through the translation mechanism.

I've rebuild the SDK using this fix, and tested a simple Android app on a device that depends on speech recognition, with very nice results.

\* The always-on-top components are excluded

### CODE REVIEW

**Comment by damencho** [comment]
Hum, I wonder how this will work with tests. We use those labels for mobile testing.

**Comment by damencho** [comment]
Seems both mobile test failed :(

**Comment by damencho** [comment]
You need to create a PR and in torture with the changed strings.

**Comment by saghul** [comment]
@guusdk Thanks for doing this! Changes look good at a first glance, but as @damencho said our PR tests use those labels to locate views in the hierarchy, so you'll need to update the tests too. Sorry I forgot about this.

**Comment by guusdk** [comment]
I've now restored the exact value of the accessibility labels on the welcome page. That's what the tests appear to be looking for. Let's see how this turns out.

**Comment by guusdk** [comment]
That resulted in more of the same issues. I'll revert that last change, and modify torture instead.

**Comment by guusdk** [comment]
I've now created a PR for torture, here: https://github.com/jitsi/jitsi-meet-torture/pull/186

Can one of you test both changes, without merging any of the PRs? If not... pick one? :D

**Comment by guusdk** [comment]
To provide some context as to why I'd prefer to change the value of those labels: the pre-existing labels were mostly one word. When using speech recognition software, there is a good chance that with simply talking, you unintentionally trigger an action by saying that word out of context. Using more than one word dramatically reduces the chance of that happening.

**Comment by damencho** [comment]
@guusdk Are both PRs to be tested together? To do so, you need to have the same branch name in both PRs.

**Comment by guusdk** [comment]
I have now created https://github.com/jitsi/jitsi-meet-torture/pull/187 which uses the same branch name.

**Comment by damencho** [comment]
The tests are failing with a lot of errors like:
No element found for:[aria-label="Profile"] which seems releated to this PR.

**Comment by guusdk** [comment]
Where do you observe those failures? I have seen another (that I now fixed), but that was unrelated to "Profile".

"Profile" is the one constant value that I did not modify in torture, as I didn't rename something that had 'Profile' as its value. Could this be a failure that was introduced before? I'd be happy to have a look if you can point me at the failing test.

**Comment by damencho** [comment]
It is not only profile, there are a bunch of those. I'm just checking here the test results from the link "Details". For example: 
http://pr-reports.jitsi.org/jitsi-meet-PR-test/4296/chrome-chrome-reports/html/

**Comment by guusdk** [comment]
Ah, thanks - I was looking at the mobile tests only. I'll look into them. In the mean time, if you have any idea what could have caused them... as I wrote: I did not remove/rename the value that is now reported missing. :-/

**Comment by damencho** [comment]
There is a hidden trick with the test results ;) You can download an archive(http://pr-reports.jitsi.org/jitsi-meet-PR-test/4296/test-reports.zip) and take a look at that. There should be some screenshots and also the html page in the moment of the failure, so you can check on beta how does that html looks like and how did those labels changed it to guess why that arial-label did change.

**Comment by guusdk** [comment]
I found an earlier commit IADMITNOTHING! that changed the label for call quality. That's likely the culprit. I'll poke around with these for a bit...

**Comment by guusdk** [comment]
I've initially replaces all values of the (react native) accessibilityLabel properties. What I neglected to do was to do something similar with the aria-label properties. I've now done that. Some translation values are used for both type of properties, which can get confusing. Let's see how the tests perform now.

**Comment by guusdk** [comment]
Empty files are now dropped.

**Comment by guusdk** [comment]
Anything stopping us from merging this?

**Comment by guillaumeagis31** [comment]
Possible to get it merge?  Really need it too ! Thanks

**Comment by damencho** [comment]
jenkins test this please

**Comment by damencho** [comment]
@guusdk I think this PR broke the iOS test

org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map: 
- native content: "By.chained({By.AccessibilityId: Enter room name})" 
- html content: "by id or name "roomNameInput""
io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:102)
io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:61)
io.appium.java_client.ios.IOSElement$$EnhancerByCGLIB$$d311658.sendKeys(<generated>)
org.jitsi.meet.test.mobile.MobileParticipant.doJoinConference(MobileParticipant.java:256)

Do you have an idea?

**Comment by damencho** [comment]
Hum, but I also saw it green ... strange

**Comment by guusdk** [comment]
@damencho I cannot explain this. The locator string ("Enter room name") seems to be correct: it is both what the test is told to look for (in the `iOSFindBy` annotation on `org.jitsi.meet.test.pageobjects.mobile.WelcomePageView#roomNameInput`) as well as the accessibility label translation as provided in property `welcomepage.accessibilityLabel.roomname` of `lang/main.json` That property is used in `react/features/welcome/components/WelcomePage.native.js` (line 88) to set the accessibility label.

I can't find the error that you quoted, by the way. In the [last test run that I can see](http://pr-reports.jitsi.org/jitsi-meet-PR-test/4391/ios-chrome-reports/html/), I get this error quoted below for the IOS tests. If I read this correct, the tests are unable to find the test device? That, coupled with your remark that sometimes the test is passing, but sometimes not, could indicate a timing issue. Perhaps the device and/or application has not finished booting/loading yet, before the test is executed?

```
setupClassPrivate	783s	Method arguments: org.testng.TestRunner@78ac1102
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: '13802dace3e26f1562668ee4aeab1d47eea047d2' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.27 seconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'ip-10-0-0-20', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-86-generic', java.version: '1.8.0_141'
Driver info: driver.version: IOSDriver
	sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
	org.jitsi.meet.test.mobile.base.MobileParticipantFactory.doCreateParticipant(MobileParticipantFactory.java:80)
	org.jitsi.meet.test.mobile.base.MobileParticipantFactory.doCreateParticipant(MobileParticipantFactory.java:31)
	org.jitsi.meet.test.base.ParticipantFactory.createParticipant(ParticipantFactory.java:35)
	org.jitsi.meet.test.hybrid.HybridParticipantFactory.doCreateParticipant(HybridParticipantFactory.java:83)
	org.jitsi.meet.test.base.ParticipantFactory.createParticipant(ParticipantFactory.java:35)
	org.jitsi.meet.test.base.ParticipantHelper.createParticipant(ParticipantHelper.java:147)
	org.jitsi.meet.test.base.ParticipantHelper.createParticipant(ParticipantHelper.java:99)
	org.jitsi.meet.test.SetupConferenceTest.setupClass(SetupConferenceTest.java:40)
	org.jitsi.meet.test.base.AbstractBaseTest.setupClassPrivate(AbstractBaseTest.java:187)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)
	org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)
	org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	org.testng.TestRunner.privateRun(TestRunner.java:648)
	org.testng.TestRunner.run(TestRunner.java:505)
	org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)

```

**Pull request merged**
