### PR TITLE
Update for Occitan

### PR DESCRIPTION
**Pull request by Mejans**
Update and rearranging some strings.

### CODE REVIEW

**Comment by Mejans** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.
Cant you just remember who signed and who didn't? I did!

**Comment by damencho** [comment]
Nope this is a bot.

**Comment by damencho** [comment]
Jenkins test this please.

**Comment by Mejans** [comment]
> Jenkins test this please.

Who? Me? I don't what/who Jenkins is, sound like an old singer to me.

**Review by saghul — APPROVED** [review]

**Pull request merged**
