### PR TITLE
workflow: add luacheck as a GitHub action

### PR DESCRIPTION
**Pull request by emrahcom**
This commit adds a GitHub action which checks Lua codes via `luacheck`.

We (me and @shawnchin) tested this workflow action in [prosody-plugins](https://github.com/jitsi-contrib/prosody-plugins). It seems OK.

### CODE REVIEW

**Comment by saghul** [comment]
Looks like the linter uncovered some stuff! Do you mind taking a look?

**Comment by emrahcom** [comment]
Hi @saghul,

Do you mean failed codes of Lua files? If so, I'm thinking to send seperate pull requests for them.

**Comment by saghul** [comment]
yeah I mean the failed lua files. You can push multiple commits to this one PR, that would also be fine!

**Comment by emrahcom** [comment]
Yes but there are 134 warnings and it seems like it will take time to fix and test all of them. Therefore I think to work on them one by one in my spare time.

**Comment by saghul** [comment]
Can we make the linter pass with warnings instead of erroring out?

**Comment by emrahcom** [comment]
Sure, I will update it today

**Review by saghul — APPROVED** [review]
LGTM! @damencho can you PTAL?

**Pull request merged**
