### PR TITLE
Make Chinese(Simplified) selectable in settings

### PR DESCRIPTION
**Pull request by JoshuaTang**
Hi,

I noticed that even though translation of Chinese(Simplified) has been almost complete at http://translate.jitsi.org/, the language is not selectable in the settings side panel. Could you add the language there?

Thank you.

### CODE REVIEW

**Comment by JoshuaTang** [comment]
@jitsi-jenkins 
Thanks for your remind! I have already signed the CLA in the June. :)

**Comment by JoshuaTang** [comment]
@jitsi-jenkins 
Thanks for your remind! I have resigned the CLA with my GitHub name. :)

**Comment by damencho** [comment]
This is an automated message and checking the CLA is done by hand, so disregard it.

**Comment by damencho** [comment]
Hey @JoshuaTang I've made another PR https://github.com/jitsi/jitsi-meet/pull/1830 which removes this hard coded values from the code, for languages that are shown in the UI. 
I'm waiting currently for an opinion on this from the other developers. 
If that got merged this we can close this PR.

**Pull request closed without merging**
