### PR TITLE
feat(config) allow overriding desktop deeplinking toggle

### PR DESCRIPTION
**Pull request by csett86**
Signed-off-by: Christoph Settgast <csett86_git@quicksands.de>

### CODE REVIEW

**Comment by saghul** [comment]
This is intentional. Specially crafted URLs could conceal the fact that a user is directed to download a different app than the server admin intended, for example.

**Comment by csett86** [comment]
Oh I see, I was not aware of that. Background is: With some changes in the recent months, deeplinking and Chromium no longer work well together, the GUM is not triggered and failing if deeplinking is enabled and the "Launch in Web" is chosen. Works fine in Firefox (to then trigger the permission prompt, but Chromium fails.

I wanted to enable config override to reproduce it on alpha.jitsi.net. But in that case: I will just allow overriding "deeplinking.desktop.enabled", that should do no harm. What do you think, @saghul?

**Comment by saghul** [comment]
That should be fine indeed!

Aside, do you have JS console logs when things fail?

**Comment by csett86** [comment]
I have updated this PR accordingly, please approve @saghul 

I did not get meaningful logs on the GUM issue yet, will try to reproduce and collect logs and then create a proper issue for it

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
> I have updated this PR accordingly, please approve @saghul
> 
> I did not get meaningful logs on the GUM issue yet, will try to reproduce and collect logs and then create a proper issue for it

Sounds good!

**Comment by csett86** [comment]
@saghul Now I got the proper logs, see #14737 for it

**Comment by saghul** [comment]
Thanks! We'll check it out!

**Pull request merged**
