### PR TITLE
feat(p2p): refactor configuration options

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
@gpolitis @paweldomas can you PTAL? Also https://github.com/jitsi/lib-jitsi-meet/pull/526

**Comment by saghul** [comment]
Can you PTAL again? I added a new commit which processed nested options. Also /cc @damencho.

**Comment by paweldomas** [comment]
Looks good as far as I can tell, we still need to adjust the torture tests

**Comment by saghul** [comment]
Jenkins, test this please.

**Pull request merged**
