### PR TITLE
Add Russian to the supported languages list

### LINKED ISSUE #793: Add a Russian translation at Pootle
My comrades are eager to translate jitsi-meet to Russian. Please add Russian language support to your Pootle deploy!

### PR DESCRIPTION
**Pull request by cmrd-senya**
fix #793

### CODE REVIEW

**Comment by cmrd-senya** [comment]
Hey! We have a working deploy of jitsi meet with Russian-speaking users and we receive requests to have a translation. Please, help us, I bet this is an easy undemanding issue. Otherwise we'll have to do the manual local translation of the json files, which is a waste of resources in terms of the jitsi project.

**Comment by cmrd-senya** [comment]
Yes, I have signed it earlier, see #663.

**Comment by bgrozev** [comment]
Thanks for your interest in the project, and good luck with the translation! Closing this since the files you changed is managed by pootle.

Please ignore Jenkins' requests for a CLA -- it doesn't check the current list. I confirm we have the CLA.

**Comment by cmrd-senya** [comment]
Thanks!

**Pull request closed without merging**
