### PR TITLE
audio-only: move audio-only handling to standalone feature

### PR DESCRIPTION
**Pull request by saghul**
This refactors all handling of audio-only to a single feature in preparation for
for a larger refactor.

The main motivation to do this is that lastN is a "global" setting so it helps
to have all processing for it in a single place.

### CODE REVIEW

**Comment by saghul** [comment]
jenkins please test this please

**Comment by saghul** [comment]
Jenkins please test this please

**Comment by paweldomas** [comment]
Im wondering why last-n and audio only are in the same feature. Are you planning on putting more stuff there ? When we talked my understanding was that last-N would track other variables and adjust the last-N value accordingly as an output of all inputs.

**Comment by paweldomas** [comment]
Maybe even rework it as a state change listener rather than a middleware listening to actions

**Comment by saghul** [comment]
> Im wondering why last-n and audio only are in the same feature. Are you planning on putting more stuff there ? When we talked my understanding was that last-N would track other variables (probably in other features) and adjust the last-N value accordingly as an output of all inputs.

You mean splitting out the last N handling to some features/base/lastn feature? Sounds good, I'll give that a shot!

> Maybe even rework it as a state change listener rather than a middleware listening to actions

I only use state listeners where is makes things better. Do you have specific sugestions on what things could improve by chaging them from a middleware to a state listener?

Thanks for taking a look!

**Comment by paweldomas** [comment]
> I only use state listeners where is makes things better. Do you have specific sugestions on what things could improve by changing them from a middleware to a state listener?

Yes, I specifically mean the last-N feature where it seems to depend on the state of all the other modes being turned on or off:

Here checks for audio only state:
https://github.com/jitsi/jitsi-meet/pull/4502/files#diff-19a195cded315d450198b4ce6c473ad0R64

Here checks if conference wants to override the last N:
https://github.com/jitsi/jitsi-meet/pull/4502/files#diff-19a195cded315d450198b4ce6c473ad0R86

Here audio only again, but when it's set ? Btw this doesn't take conference into account.
https://github.com/jitsi/jitsi-meet/pull/4502/files#diff-19a195cded315d450198b4ce6c473ad0R120

Here filmstrip enabled:
https://github.com/jitsi/jitsi-meet/pull/4502/files#diff-19a195cded315d450198b4ce6c473ad0R157

I suppose that a state listener might be able to fetch all states in one go and produce one output.

**Comment by paweldomas** [comment]
Im also thinking that maybe the audio only could stay as well in the base/conference as a reducers flag. This new feature fells to me more like a last N and not audio only feature.

**Comment by saghul** [comment]
> Yes, I specifically mean the last-N feature where it seems to depend on the state of all the other modes being turned on or off:

I see what you mean.



> Here audio only again, but when it's set ? Btw this doesn't take conference into account.

The setLastN handling check  for the conference.

> Im also thinking that maybe the audio only could stay as well in the base/conference as a reducers flag. This new feature fells to me more like a last N and not audio only feature.

I think I'd rather have it as a standalone too, since it does a bit more than that, it also mutes the local video, which is arguably not related with the conference.

Thanks for the review, I'll move towards having base/lastn and trying to simplify things with a state listener.

**Pull request merged**
