### PR TITLE
feat(config): Add config option for making display name read only

### PR DESCRIPTION
**Pull request by vp8x8**

### CODE REVIEW

**Comment by damencho** [comment]
This is just a UI addition, right? We do not need to disable it from changes through the iframe API?

**Comment by vp8x8** [comment]
This was done so clients who embed the iframe can add configOverwrite with this option. Once set it should not be reverted and the default is off (i.e. the name is editable).

As I mentioned in the comment in `config.js` this should mainly come in hand for the case when JWT is used so the user will not be able to edit his name. Right now although we use the name from the JWT a user can at any time change the display name.

**Comment by vp8x8** [comment]
Jenkins please test this please.

**Comment by shawnchin** [comment]
Many thanks. I had this exact requirement too and currently using an ugly workaround -- https://community.jitsi.org/t/only-use-display-name-from-jwt/101016/7?u=shawn

Does this influence just the various display name input fields, or would it also stop someone from calling `APP.conference.changeLocalDisplayName(...)` from console to change name? In other words, this is exactly what I need on the UI side, but will I still need extra logic on prosody to ensure users always have display name from JWT token?

**Review by saghul — APPROVED** [review]
LGTM. One question tough: shouldn't this be automatic when there is a JWT? As in, if there is a JWT with a name in it we should use that and not allow a change. Unless the JWT doesn't set one, then it's free game. Does that make sense @damencho ?

**Comment by damencho** [comment]
Yep make sense.

**Comment by saghul** [comment]
@vp8x8 Will you be making this automagic as per the discussion above?

**Comment by vp8x8** [comment]
@saghul Yes. Added to my list

**Pull request merged**
