### PR TITLE
update the Farsi language translation

### PR DESCRIPTION
**Pull request by amirho3inhashemi**
hi
i updated farsi language stuffs.
please merge.

### CODE REVIEW

**Comment by amirho3inhashemi** [comment]
i have signed cla
it's done

**Comment by M2Vpersian** [comment]
amirho3inhashemi i need your help
please call me or send for me your number
-0935-658-5862-

**Comment by damencho** [comment]
If you want to merge the translation update, drop the unrelated changes.

**Comment by saghul** [comment]
No follow-up, closing.

**Pull request closed without merging**
