### PR TITLE
Update language list

### PR DESCRIPTION
**Pull request by nkcth**

### CODE REVIEW

**Comment by damencho** [comment]
What us the reason behind this change? 
With so many additions the list will become overcrowded and hard to read, but maybe that is just me.
@saghul WDYT?

**Comment by nkcth** [comment]
The change is about some languages are missing from the list.

Reference
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows

**Comment by nkcth** [comment]
BTW, the Chinese language is not only used in China and Taiwan.
If it's hard to read, maybe use the terms Chinese (Simplified) and Chinese (Traditional) instead of Chinese (China) and Chinese (Taiwan)?

**Comment by damencho** [comment]
Some languages were intentionally removed as they had less than 25% translation.

**Comment by nkcth** [comment]
I translated the list of languages from lang/languages.json to the local language.
Should I remove these changes and keep only the minor changes in Chinese language?

**Comment by nkcth** [comment]
@damencho 
I will close this PR and open an issue to give a suggestion. #12047 
pls take a look, thx.

**Pull request closed without merging**
