### PR TITLE
fix(facial-recognition) avoid image data conversion

### PR DESCRIPTION
**Pull request by saghul**
TF 3.0 supports getting an ImageBitmap in fromPixels: https://js.tensorflow.org/api/3.0.0/#browser.fromPixels

### CODE REVIEW

**Comment by saghul** [comment]
Untested. @gabiborlea can you PTAL?

**Comment by gabiborlea** [comment]
> Untested. @gabiborlea can you PTAL?

I was actually preparing to open a PR myself with these changes. I have the same changes and it seems to work just fine.

**Comment by gabiborlea** [comment]
But I'll test again just to be sure

**Comment by saghul** [comment]
Awesome, thank you!

**Comment by gabiborlea** [comment]
Works fine!

**Review by gabiborlea — APPROVED** [review]

**Review by quitrk — APPROVED** [review]

**Pull request merged**
