### PR TITLE
feat(prejoin/native): clear notifications when joining

### PR DESCRIPTION
**Pull request by Calinteodor**

### CODE REVIEW

**Review by saghul — CHANGES_REQUESTED** [review]
What if the prejoin page is not used?

**Comment by Calinteodor** [comment]
> What if the prejoin page is not used?

Updated.

**Review by saghul — COMMENTED** [review]
Can't we maybe dispatch it right after creating the tracks in line 141?

**Comment by Calinteodor** [comment]
> Can't we maybe dispatch it right after creating the tracks in line 141?

I was thinking about that, but is it necessary to connect first and afterward clear them out?

**Comment by saghul** [comment]
> > Can't we maybe dispatch it right after creating the tracks in line 141?
> 
> @saghul I was thinking about that, but isn't it necessary to connect first and afterwards clear notifications out?

Nope, we can do it early.

**Review by saghul — APPROVED** [review]

**Pull request merged**
