### PR TITLE
Include support for translations at permissions alert

### PR DESCRIPTION
**Pull request by vicfran**
Include support for translated string resources at device permission dialog because it contains hardcoded english strings.

This PR includes new strings at _main.json_ and their belonging translations to Spanish.

Changes made uses `i18next.t()` function to gather translations.

Attached image of what this PR tries to handle.
Thank you

Screenshot_20210507-125939

### CODE REVIEW

**Comment by damencho** [comment]
Please fix the lint errors. You can test locally by running `npm run lint`

**Comment by vicfran** [comment]
@damencho thank you, I have fixed lint errors until I have no one on my local lint tests.

I have squashed lint issues fix commit into already existing commit in order to clean the history and made a rebase with new changes merged into master today, hope you find this right.

thank you!

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Comment by vicfran** [comment]
@damencho thank you

**Pull request merged**
