### PR TITLE
Update main-fr.json

### PR DESCRIPTION
**Pull request by roms2000**
Add missing translation.
Improve French language / French styling.
Fix typos.

### CODE REVIEW

**Comment by roms2000** [comment]
> 
> 
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

That's was done.

**Comment by damencho** [comment]
@daimoc Can you take a look please?

**Comment by daimoc** [comment]
Hi, that's a good Improvement in the French translation with a great work on label consistency.

**Comment by damencho** [comment]
@daimoc Thank you.

**Review by damencho — APPROVED** [review]

**Pull request merged**
