### PR TITLE
feat: add ipados to list of Platform.OS

### PR DESCRIPTION
**Pull request by mfts**
This helps show the mobile redirect page when using Safari on iPadOS 13+

### CODE REVIEW

**Comment by mfts** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Signed

**Comment by saghul** [comment]
Neat! I think we should add an extra property instead of replacing ios with ipados. That was done for symmetry with React Native and may introduce subtle bugs because everyone expects the platform on a iPad to be "ios".

**Comment by mfts** [comment]
I moved the check for `ipados` to the property conditional for `ios`

**Review by jallamsetty1 — APPROVED** [review]

**Comment by jallamsetty1** [comment]
Jenkins please test this please.

**Pull request merged**
