### PR TITLE
Improve keyboard shortcut handling

### PR DESCRIPTION
**Pull request by champtar**
KeyboardEvent is a mess.

KeyboardEvent.which gives you, in theory, a decimal representation of the key pressed.
"r" or "R" gives you 82, which is "R", you can look at KeyboardEvent.shiftKey,
but you don't have access to capslock...

Maybe you want to use numbers, but of course NumPad will not give you the same than
"normal" numbers ...

Now if you use something else than letter, for exemple "?",
on a QWERTY keyboard "/" and "?" gives you 191,
on a AZERTY keyboard "," and "?" gives you 188, so we have to stick to letters.

This was for keydown and keyup events, keypressed event return the real char
(lower "a", "/", "?", ...) but it fails in some cases

The only non broken property is KeyboardEvent.key,
but it's only supported since Chrome 51, Opera 38, and not supported by Safari
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

A good reference & test:
http://unixpapa.com/js/testkey.html
http://unixpapa.com/js/key.html

Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>

### CODE REVIEW

**Comment by bgrozev** [comment]
Ideally I would like to use "?", as it is somewhat standard. I recognize that the current implementation doesn't work everywhere. However, can we keep the current "?" binding which works at least sometimes and add "H" as a second option?

**Comment by champtar** [comment]
@bgrozev if you want to stick to "?" i prefer to use KeyboardEvent.key, so we can also use NumPad

**Comment by bgrozev** [comment]
> @bgrozev if you want to stick to "?" i prefer to use KeyboardEvent.key, so we can also use NumPad

I have no preference one way or the other. I don't really understand the difference, actually, I had to hack it up in very little time and just based it on the code that was already there and only tested on my computer :(

**Comment by champtar** [comment]
take a quick look (10s) at http://unixpapa.com/js/testkey.html, you will see the difference (tick DOM3)

**Comment by bgrozev** [comment]
So you propose to match on KeyboardEvent.key instead of KeyboardEvent.which? That'd be great, except for the lack of support in safari.

**Comment by champtar** [comment]
I can implement a fallback with the current code (buggy in some case)
What's the status of the temasys plugin?

**Comment by bgrozev** [comment]
Using KeyboardEvent.key with a fallback for Safari seems like a good solution to me. The temasys plugin is still in use, AFAIK.

Note that there is an ongoing effort to switch to a new react-based interface. It may be a waste of time to do the change here if porting will require a re-write, but I don't know much about this. @lyubomir any thoughts?

**Comment by champtar** [comment]
hi @bgrozev 
I've updated my patch
I know about the ongoing effort to use react, but the change isn't that complicated

**Comment by bgrozev** [comment]
Thanks, @champtar !
On my computer typing a "?" (shift + "/") results in two keyup events, with values of "which" respectively 191 and 16. However String.fromCodePoint(191) does not return "?" (it returns "¿"), so I don't think this will work on safari. So I think this wouldn't work on safari. Maybe 191 should be handled the same way as 27 in getKeyboardKey()?

**Comment by champtar** [comment]
good catch @bgrozev (i was still using H instead of ? when i did my tests)
I'll add it to the switch (i knew there will be more candidate :) ) so safari + qwerty is working
can you tests numbers with your qwerty keyboard please?

**Comment by bgrozev** [comment]
Do you happen to have this deployed somewhere where I can do the test?

It would be awesome if we could somehow make jenkins persist the testing environment for certain PRs, so we can do manual testing as well.

**Comment by champtar** [comment]
just go to http://unixpapa.com/js/testkey.html
for me (with normal keys not NumPad)
0 => 48
1 => 49
9 => 57

**Comment by bgrozev** [comment]
Yeah, same here on all browsers I tried

**Comment by champtar** [comment]
@bgrozev improved a bit more, i now handle keypress event before fallback

**Comment by bgrozev** [comment]
Thank you!

**Pull request merged**
