### PR TITLE
Add a network schemas

### PR DESCRIPTION
**Pull request by pierreozoux**
This is to help understanding how things are wired.

### CODE REVIEW

**Comment by damencho** [comment]
There is one more connection, where jicofo is connected to prosody using xmpp port 5222.

**Comment by pierreozoux** [comment]
Thanks for your quick feedback @damencho I fixed it.

**Comment by damencho** [comment]
Sorry I overlooked it at the first time, but the connection to nginx is not 80, it is 443. Webrtc is not working with http.

**Comment by pierreozoux** [comment]
Ok, I slightly updated the document then, I know it is incomplete as 443 will collide with videobridge, but well, in my case, I'll have a different ip for videobridge. If not, it needs a lot more changes.

What do you think?

**Comment by damencho** [comment]
Well, you are right. When using nginx or apache jvb binds by default to 4443. When using jetty, there is no web server other than the jetty inside jvb handles 443 for media and web.

**Comment by pierreozoux** [comment]
Ok, actually it is now updated.
(It is incomplete without the generation of TLS for nginx, but well, it is already a good overview)

**Pull request merged**
