### PR TITLE
tss-react doesn't need a type anotation for the Theme

### PR DESCRIPTION
**Pull request by garronej**
Hello,  

I am the author of [`tss-react`](https://tss-react.dev).  
I noticed that you used a type annotations for the `Theme` everywhere `makeStyles` is used, it's no longer required with TSS.  

Thank you for your great work on this great software!  

Best,  

PS: I also bumpted `tss-react` to the latest version.

### CODE REVIEW

**Comment by saghul** [comment]
Thank you!

**Comment by saghul** [comment]
Can you please check the CI failures? They seem directly related to this change.

**Comment by garronej** [comment]
Hi @saghul,  

Sorry about that. And sorry about re-implementing module augmentation, @robertpin [had already do so](https://github.com/jitsi/jitsi-meet/blob/282817db28cf175a3d7fc2b177752cc3df2d5b7f/react/features/base/ui/functions.web.ts#L8-L14).  

Anyway, I just rebased.

**Comment by saghul** [comment]
No worries, thanks a ton for helping out!

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by robertpin — APPROVED** [review]

**Comment by robertpin** [comment]
Thanks for the help @garronej 

While we're on the topic: should we be able to change `withStyles` from `mui` to `tss-react`? I tried it when we switched `makeStyles` to `tss-react` but it didn't work. The classes object is generated with class names, but the styles don't get injected in the DOM

**Comment by garronej** [comment]
Hey @robertpin,  
I will submit another PR to migrate to TSS's `withStyles`!

**Comment by garronej** [comment]
Sorry I didn't do it yet but I didn't forgot.  
I did some extra work on `withStlyes` https://docs.tss-react.dev/api/withstyles  
I should be able to do the migration quickly. I'll try to find the time soon.

**Pull request merged**
