### PR TITLE
enable react-native-gifted-chat in the mobile app

### PR DESCRIPTION
**Pull request by dgeorgiev06**
image
image

The code accomplishes the following:

1. Button at the bottom of the app for opening the chat and displaying unread message count when the chat is closed.  
2. Display the chat in a transparent modal component as a top layer.  To close the chat touch the screen to the side of the chat. 

I started getting this when a message sent from the web is received in the app after I upgraded my local file tree to the latest head version.  Not sure what has changed:

screen shot 2018-10-26 at 1 53 33 pm

### CODE REVIEW

**Comment by saghul** [comment]
Thanks for sending this! I’ll take a look as soon as I can!

**Comment by saghul** [comment]
Hey,

Just letting you know that we haven't forgotten, but we are a bit busy ATM. I'll get back to this ASAP.

**Comment by dgeorgiev06** [comment]
No worries. Thanks

**Comment by zbettenbuk** [comment]
Hello @dgeorgiev06 ,

Finally we now had time to get back to this. We highly reworked the PR to fit our infra and coding style, please see the new PR here: https://github.com/jitsi/jitsi-meet/pull/3725

I've placed a co-authored notice in the PR mentioning you.

Can you please make sure you have the CLA readily signed? Otherwise we cannot merge your work. Please see link in an automated comment above.

**Comment by dgeorgiev06** [comment]
This is great. Thank you!!  

I signed the cla in late October. Do you need a link?

**Comment by zbettenbuk** [comment]
@dgeorgiev06 We're migrating our CLAs right now, so yes, it would be great if you could send it to me privately: zoli@sip-communicator.org

Thank you,
Zoli

**Comment by saghul** [comment]
Superseded by https://github.com/jitsi/jitsi-meet/pull/3725 Let's continue the discusion there if needed. Thanks a lot for your efforts!

**Comment by zbettenbuk** [comment]
@dgeorgiev06 I haven't received your CLA yet. Can you please make sure I get it soon? Thanks!

**Comment by dgeorgiev06** [comment]
I emailed it some time back. Forwarded it again just in case to your personal email.  Let me know if you don’t see it. Thanks

**Comment by zbettenbuk** [comment]
@dgeorgiev06 Thanks, I just found it in the spam folder... my bad, sorry!

**Comment by dgeorgiev06** [comment]
No worries. Thanks for looking into this feature!

**Comment by zbettenbuk** [comment]
@dgeorgiev06 The feature landed in master! Thanks for the contribution, great work!

**Comment by dgeorgiev06** [comment]
This is awesome. Thank you guys!!

**Pull request closed without merging**
