### PR TITLE
i18n: zh_TW: new translation

### PR DESCRIPTION
**Pull request by pan93412**
By the way, what happened with <translate.jitsi.org>?

### CODE REVIEW

**Comment by Mejans** [comment]
Hello,
you now have to use this weblate instance: https://hosted.weblate.org/projects/jitsi/main/

**Comment by pan93412** [comment]
@Mejans Oh. Let them merge this and Weblate will automatically handle this.

**Comment by damencho** [comment]
Please check my comment in https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by pan93412** [comment]
@damencho well, so what should I do currently? Wait for merging, or manually upload these translations after it becomes available?

**Comment by damencho** [comment]
Please drop the files from android folder and I will merge those.

**Comment by pan93412** [comment]
@daimoc Done. Thanks a lot!

**Comment by pan93412** [comment]
By the way, why shouldn't I translate those files in `android/`?

**Comment by damencho** [comment]
I asked the mobile team and I got an answer that we do not want to translate those.

**Pull request merged**
