### PR TITLE
fix: Disabled all UI for hiding self view and uses config.

### PR DESCRIPTION
**Pull request by damencho**
This allows the use of the feature through config overwrite only.

### CODE REVIEW

**Review by jallamsetty1 — APPROVED** [review]

**Review by yanas — APPROVED** [review]

**Review by hristoterezov — APPROVED** [review]

**Comment by saghul** [comment]
Why did we remove this? There no explanation here.

**Comment by damencho** [comment]
@saghul https://community.jitsi.org/t/couple-of-issues-with-hide-self-view/108960?u=damencho

**Comment by damencho** [comment]
This is temporary workaround till its fixed, which is done in https://github.com/jitsi/jitsi-meet/pull/10620

**Comment by saghul** [comment]
Thanks!

**Pull request merged**
