### PR TITLE
 lang:New translation Hindi(hi)

### PR DESCRIPTION
**Pull request by 4host**
Work in progress. I will update this on the way. I also want to quickly test this out. Thanks

### CODE REVIEW

**Comment by 4host** [comment]
CLA individual signed

**Comment by damencho** [comment]
You need to add languages-hi json file and add your new language to the main languages.json one.

**Review by damencho — CHANGES_REQUESTED** [review]
You need to add languages-hi json file and add your new language to the main languages.json one.

**Comment by damencho** [comment]
Are you expecting more changes? 

Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
