### PR TITLE
Remove callstats

### PR DESCRIPTION
**Pull request by bgrozev**
- ref: Remove precall test.
- ref: Remove callstats.

### CODE REVIEW

**Comment by saghul** [comment]
Can you please also remove the react-native-callstats dependency?

**Comment by bgrozev** [comment]
> Can you please also remove the react-native-callstats dependency?

I removed it from the root package.json, but I don't know what to do about react-native-sdk. When I run `npm i` inside its directory it automatically updates some of its dependencies to the parent's versions and that's probably not what we want.

**Comment by saghul** [comment]
You can just drop it from package.json there. Sepa are synced on release. Come to think of it we should drop the lock file... I'll take care of that.

**Comment by saghul** [comment]
I think the package is imported, we need its use gone too.

**Review by saghul — DISMISSED** [review]

**Review by saghul — APPROVED** [review]

**Pull request merged**
