### PR TITLE
feat(prejoin) default to enabled

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Review by damencho — DISMISSED** [review]

**Comment by damencho** [comment]
Hah this broke the teats for some reason

**Comment by saghul** [comment]
I thought we set it to disabled with URL parameters?!

**Comment by damencho** [comment]
Nothing in the logs, many screenshots show prejoin so there must be a case where the URL setting is not working ...

**Comment by saghul** [comment]
> Nothing in the logs, many screenshots show prejoin so there must be a case where the URL setting is not working ...

I'll look into it.

**Review by damencho — APPROVED** [review]

**Pull request merged**
