### PR TITLE
Fix speaker stats search dependency and remove duplicate logic #9751

### PR DESCRIPTION
**Pull request by dimitardelchev93**
Fix speaker stats search dependency and remove duplicate logic.

### CODE REVIEW

**Comment by gabiborlea** [comment]
Hi! I noticed an issue, that the dialog is not rendered every second as it used to be, and because of this, you cannot see live updates of the speaker stats when having the dialog opened, to see updates you have to close the dialog and open it again. I saw that you got rid of the state from the SpeakerStats component, so there is no setState to be called in order to render the component.

**Comment by dimitardelchev93** [comment]
> Hi! I noticed an issue, that the dialog is not rendered every second as it used to be, and because of this, you cannot see live updates of the speaker stats when having the dialog opened, to see updates you have to close the dialog and open it again. I saw that you got rid of the state from the SpeakerStats component, so there is no setState to be called in order to render the component.

Did you find that issue before my changes in this PR, because it is fixed with those changes, I test again and everything seems to work fine? But yes the problem was that the dialog was not rerendering on search criteria update, it should be fixed now.

speaker-stats-reloading-each-second

**Comment by damencho** [comment]
Bothe me and @gabiborlea tested it and we were not seeing the updates.

**Comment by damencho** [comment]
@gabiborlea found the issue before this PR, but we tested with it and we still see it.

**Comment by dimitardelchev93** [comment]
> @gabiborlea found the issue before this PR, but we tested with it and we still see it.

Apologies to both, I eventually saw what you mean, a fix was added.

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
