### PR TITLE
[feat] Add support for jiconop

### PR DESCRIPTION
**Pull request by Khalidmamdou7**
> This PR is not intended for merge
> While working on GSoC Project to implement [jiconop for websockets](https://github.com/jitsi/gsoc-ideas/blob/master/2024/jiconop-ws.md), I needed to enable [jiconop for BOSH](https://github.com/jitsi/jiconop) to understand the concepts behind it and experiment it. So, This PR is part of this [guide](https://community.jitsi.org/t/how-to-how-to-enable-jiconop-for-bosh/131097), in case anyone needed to do the same.

A previously dropped service [jiconop](https://github.com/jitsi/jiconop) which optimizes the initial connection of BOSH by adding a proxy between clients and the server.

This draft pull request shows the needed changes in jitsi-meet files in order to re-add the support for this abandoned service, in case someone wanted to experiment with it.

### CODE REVIEW

**Comment by saghul** [comment]
I'm confused. If this PR is not intended for merging, what is it intended for?

**Comment by Khalidmamdou7** [comment]
> I'm confused. If this PR is not intended for merging, what is it intended for?

I thought it would be appropriate to use it in this [guide](https://community.jitsi.org/t/how-to-how-to-enable-jiconop-for-bosh/131097?u=khaled_mamdouh). If I should close it, please let me know. Sorry for the confusion

**Comment by saghul** [comment]
What is the context here? Why would you like to bring it back? Have you tested using WebSockets?

**Comment by Khalidmamdou7** [comment]
> What is the context here? Why would you like to bring it back? Have you tested using WebSockets?

For a Gsoc project, I amy work on building a similar oroject for websockets. So, in order to understand the concept I brought it back. And thought that in case someone tried to do the same, this guide may be needed.

**Comment by saghul** [comment]
I am one of the GSoC admins, so I suspected that was the case.

Please do mention that in the PR description so people passing by can know the context.

**Comment by Khalidmamdou7** [comment]
Done and sorry for the confusion

**Pull request closed without merging**
