### PR TITLE
Update to React Native 0.67

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
For reference, this is where I started: https://react-native-community.github.io/upgrade-helper/?from=0.66.4&to=0.67.4

**Comment by Calinteodor** [comment]
Except the fact that there are tests that fail on Firefox, everything looks good.

**Review by Calinteodor — APPROVED** [review]

**Review by Calinteodor — CHANGES_REQUESTED** [review]
Tests failing on Firefox, except that, everything looks good.

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
> Tests failing on Firefox, except that, everything looks good.

Thanks for testing! If you check, the Jenkins failures are due to an unavailable API. I'm running them again just in case though.

**Review by Calinteodor — APPROVED** [review]

**Pull request merged**
