### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by SilentKernel**
Added missing french translation

### CODE REVIEW

**Comment by saghul** [comment]
Thanks for woking on this! Alas I have to ask you to use our Pootle interface: https://github.com/jitsi/jitsi-meet/tree/master/lang#translating-jitsi-meet

**Comment by SilentKernel** [comment]
Oh sorry, did not see that :s

**Comment by saghul** [comment]
No worries, it's not very visible :-S Thanks for understanding.

**Comment by LAfricain** [comment]
Hello, is the Android client already internationalized? BEcause currently i have juste thé english.

**Pull request closed without merging**
