### PR TITLE
in config, mention useRoomAsSharedDocumentName

### PR DESCRIPTION
**Pull request by fwolfst**
Found via https://github.com/jitsi/jitsi-meet/issues/1016 .

I can also craft a PR that includes the commented out setting directly after etherpad_base with a comment about its usage. Just ping me and I'll adjust.

Signed the CLA already.

### CODE REVIEW

**Comment by saghul** [comment]
> I can also craft a PR that includes the commented out setting directly after etherpad_base with a comment about its usage. Just ping me and I'll adjust.

This would be nice, thank you for volunteering to do that!

**Comment by fwolfst** [comment]
Done.

> This would be nice, thank you for volunteering to do that!

Happy to do that. CLA was already signed.

**Comment by fwolfst** [comment]
Mmh, missed that this one staled out. What happened?

**Comment by saghul** [comment]
Oops

**Comment by saghul** [comment]
Looks like it fell through the cracks, so sorry about that. Can you please fix the conflicts?

**Comment by fwolfst** [comment]
> Looks like it fell through the cracks, so sorry about that. Can you please fix the conflicts?

no problem, happens everyday. I'll try to look into it later.

**Comment by fwolfst** [comment]
> Looks like it fell through the cracks, so sorry about that. Can you please fix the conflicts?

Done.

**Comment by fwolfst** [comment]
> > Looks like it fell through the cracks, so sorry about that. Can you please fix the conflicts?
> 
> Done.

Some cracks building? ;)

**Review by saghul — APPROVED** [review]

**Pull request merged**
