### PR TITLE
Add starting asterisk to JSDocs

### PR DESCRIPTION
**Pull request by federico-ntr**
Some of the JSDocs inside the file had an asterisk at the start of each line, some didn't. For consistency, I simply added the asterisks using the ones who already had them as a format guide.

### CODE REVIEW

**Comment by damencho** [comment]
@saghul wdyt? 
In my opinion, I'm not seeing a problem with the current version of the file in the repo, but it maybe just me.

**Comment by saghul** [comment]
> @saghul wdyt? 
> 
> In my opinion, I'm not seeing a problem with the current version of the file in the repo, but it maybe just me.
> 
> 

I agree with you. This is not something we've heard frequently enough yet IMHO.

**Comment by federico-ntr** [comment]
I made that change because I got confused while reading the config file in a hurry. I may be the only one, but I still think it's better to apply to the standards, even when they are de facto and not de iure.

**Comment by saghul** [comment]
That file contains block comments, not JSDocs. Our block comment syntax is correct, so I don't agree with the "standards" argument here.

I don't have a strong opinion, but following the rest of the file we should probably just do line comments for everything, since it makes uncommenting chunks easier.

**Comment by federico-ntr** [comment]
I don't think the lines in those blocks are meant to be uncommented since they are explanations of the property below them. I don't think they MUST be JSDocs, though, since they don't use any of its features. Still the double asterisk at the start of a block comment is usually interpreted as the start of docs. This is what VSCode does, for example, but almost every IDE does the same:
js docs as tooltip on visual studio code

I know I'm being fussy, sorry for that, I really appreciate your work here 😅

**Pull request closed without merging**
