### PR TITLE
interface_config: bring back config trailer

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by damencho** [comment]
This is not for developers, this is for the users who regularly break their deployment forgetting to remove the coma at the last element. They do not run eslint after apt install jitsi-meet :P

**Comment by saghul** [comment]
Exactly what @damencho said :-)

**Comment by hristoterezov** [comment]
> This is not for developers, this is for the users who regularly break their deployment forgetting to remove the coma at the last element. They do not run eslint after apt install jitsi-meet :P

@damencho @saghul Why it will break? Objects with trailing commas are handled gracefully, isn't it? I even tested adding one to interface_config.js and it is working as expected! What am I missing?

**Comment by damencho** [comment]
The last property with comma breaks UI

**Comment by damencho** [comment]
@saghul actually we were testing this and this really does not fix anything at the moment. The only error is if you miss a comma on a previous property, but having that at the end does not help in that case.

**Comment by hristoterezov** [comment]
@saghul Just FYI: just tested with  @damencho and trailing commas won't break anything! What potentially can break in this  situation is if you don't have comma in one of the commented options and you uncomment it.

No change needed if this thing help you with something.

**Comment by dandv** [comment]
If the last comma-guarding fake property is no longer needed by the current JSON parser, then I'm in favor of getting rid of it.

**Pull request merged**
