### PR TITLE
Added more delegate functionality in mobile SDK

### PR DESCRIPTION
**Pull request by imdatsolak**
Added:

- (on)participantJoined
- (on)participantLeft
- (on)participantKicked

delegate methods to iOS and listener methods to Android SDK.

### CODE REVIEW

**Comment by imdatsolak** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Hi, I already have signed the CLA - so, no worries there.

**Comment by imdatsolak** [comment]
> We should send some "Participant" object with the event, rather than just the id and the count. The application can keep the count by storing the participant objects.
> 
@saghul : I am more than happy to do that, but I don't know how. I would need some minor guidance on that.
My major goal was to detect if the the second-to-last user has left so that I, as the last user, can "hang up" the call by leaving the conference.

Alternatively, I would suggest to expose "getNumParticipants" as an additional call (like in the Web API so that the delegate can call-back and check for remaining number of participants.
What do you think?

**Comment by saghul** [comment]
> I am more than happy to do that, but I don't know how. I would need some minor guidance on that.

Sure thing. First we'd need to pass participant objects as NSData / Maps to native. Then build a little class there to represent them before calling the delegate method. Or maybe we can start just by passing the objects as they come, we can refine that later.



>  I would suggest to expose "getNumParticipants" as an additional call (like in the Web API so that the delegate can call-back and check for remaining number of participants.
> What do you think?

Sounds good. But I guess you'd do that by storing the participants as they come / go and return its count, right?

At any rate, make the changes and let's keep iterating on this PR 👍

**Comment by imdatsolak** [comment]
@saghul : I have changed the data passed to { participant: {...}, numParticipants: <int>} 
I think, leaving numParticipants make a lot of sense as that avoids another call-back and local handling. JitsiMeet is the only source-of-truth wrt number of participants and I think it should stay that way...

**Comment by imdatsolak** [comment]
Hi @saghul - any plans on when you think this could be merged? thx

**Comment by imdatsolak** [comment]
I have deleted the fork and created it anew because of some issues - will send a new PR from a new fork

**Comment by nathando** [comment]
hi, sorry for open a closed thread but has this PR been merged as on SDK version 2.10 ? We really need this functionality. Thank you for your effort and contributions!

**Comment by saghul** [comment]
Alas, nope.

**Pull request closed without merging**
