### PR TITLE
allow more characters in meeting name when reverse proxied

### PR DESCRIPTION
**Pull request by ctr49**
excluding special locations (bosh, xmpp, legacy lib).
addresses #3811

### CODE REVIEW

**Comment by damencho** [comment]
This file is not the one used for the deployments. This is already fixed there
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example#L62
These files are examples for the manual install which is there just to show how things are done, but it is no longer updated.

**Comment by saghul** [comment]
Can we remove that example-config folder maybe @damencho  ?

**Comment by damencho** [comment]
We can but we should remove and the manual config in the same commit.

**Comment by saghul** [comment]
Ah crap, forgot about that.

**Pull request closed without merging**
