### PR TITLE
feat(more-settings)

### PR DESCRIPTION
**Pull request by Mahdhir**
Added abilty to hide more tab under settings

For feature request https://github.com/jitsi/jitsi-meet/issues/11678

### CODE REVIEW

**Review by saghul — DISMISSED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by Mahdhir** [comment]
Fixed linting issues

**Comment by Mahdhir** [comment]
@saghul Can you review this during your free time ? :)

**Comment by Mahdhir** [comment]
Jenkins please test this please.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by Mahdhir** [comment]
@saghul Can we merge this when you are free? :)

**Comment by saghul** [comment]
Done, cheers!

**Pull request merged**
