### PR TITLE
chore(deps): bump rtcstats  9.0.1. to 9.2.0

### PR DESCRIPTION
**Pull request by andrei-gavrilescu**
Bump rtcstats to a newer version which includes some dependencies cleanup.

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by andrei-gavrilescu** [comment]
Jenkins test this please

**Comment by andrei-gavrilescu** [comment]
Jenkins test this please

**Comment by andrei-gavrilescu** [comment]
Jenkins please test this please.

**Comment by andrei-gavrilescu** [comment]
Jenkins please test this please.

**Review by saghul — APPROVED** [review]
All green captain!

**Pull request merged**
