### PR TITLE
Fix overflow on meet.jit.si home page

### PR DESCRIPTION
**Pull request by guilhermemarconi**
The home page now can scroll normally, and the scroll is blocked on the conference page.

### CODE REVIEW

**Comment by guilhermemarconi** [comment]
Done! 😄

**Comment by virtuacoplenny** [comment]
I'm currently waiting on verification that you have indeed signed the CLA--I trust but I must verify. You might want to add overflow hidden for other meeting screens too to prevent bounce scrolling, which is what I assume was one reason why overflow hidden was added to body in the first place. I still see the bounce scroll in horizontal filmstrip mode in both filmstrip only and non-filmstrip only.

**Comment by virtuacoplenny** [comment]
I just realized it might not be obvious how to test those UI modes without your own deployment... Properties on interfaceConfig and config, which are used to configure the meeting in various ways, can be overridden with the location's hash. For example, appending #interfaceConfig.VERTICAL_FILMSTRIP=false to the meeting url will give you horizontal filmstrip mode.

**Comment by virtuacoplenny** [comment]
I haven't heard back from you for a few weeks and I started wanting this fixed. We went with another approach in https://github.com/jitsi/jitsi-meet/pull/2181. Sorry for superseding your change. For what it's worth, your pull request along with another contributor's pull request that fixes the same issue have been in the back of my mind since they were opened.

**Pull request closed without merging**
