### PR TITLE
Implement Link preview

### PR DESCRIPTION
**Pull request by jadhavsaurabh**
Special thank to this package [https://www.npmjs.com/package/@dhaiwat10/react-link-preview](url)

I have implemented simple but very importartant feature for web based jitsi-meet, chat UI.

**Old Chat UI**
jitsiOldChatUI

**New Chat UI-A**
jitsiNewUI

**New chat UI-B**
preview

### CODE REVIEW

**Comment by jadhavsaurabh** [comment]
I am always open for any code suggestions.
If needed, I can make similar change for Native component as well.

**Comment by gigabyteservice** [comment]
Good job,  one more suggestion if you are interested. add the functionality of tagging someone (so tagged person will get notification ) & quote someone elses message, so if I will quote your message which was 5 messages above & after quoting if someone sees my message and click on that then the user will directly slide up to that particular message and see that I'm was talking about that message, this thing is available in all different messaging platform like WhatsApp, skype, etc. this is very useful when lot of people are talking in one chat.


1)  tagging
aid8803912-v4-1200px-Tag-Someone-on-WhatsApp-on-Android-Step-7

2) qoute message
whatsapp_for_android_message_quotes_replies_blurred

**Comment by jadhavsaurabh** [comment]
@gigabyteservice Sure friend, good to hear you liked my work.
I will try my best looking into tagging feature!
**Use cases will be:**
1) Once I start typing `@` I should be able to see list of users matching the typed string
2) tagged user will see his name highlighted
As simple as that, no more complex logic & usecases and easy to understand user experience.

I would like to raise separate PR for that so it's easy to roll out upcoming features for you guys.

**Comment by shawnchin** [comment]
If I understand correctly, by using `@dhaiwat10/react-link-preview`, every user that renders the preview will end up making a request to a [public proxy](https://github.com/dhaiwat10/rlp-proxy) which handles the metadata extraction from the URL.

Other than possible availability issues, being able to trigger a call to a 3rd party server for all clients by simply posting a link does raise some security and privacy questions.

I'm not doubting that this is a nice feature to have, but I personally would be cautious about using this on my deployments and would not want this enabled by default. If I do use it I would need to be able to configure it to use my own proxy (current module hardcodes to `https://rlp-proxy.herokuapp.com`) and cache mechanism (open source rlp-proxy server uses supabase).

**Comment by jadhavsaurabh** [comment]
@shawnchin That's a very good point, but the `@dhaiwat10/react-link-preview` is using the proxy to avoid the [cross-origin](https://web.dev/cross-origin-resource-sharing/) issue and the author has recommended not using the proxy for production as the server will face bottleneck issues.

And they provide an alternative option to pass `customFetcher` [reference](https://github.com/Dhaiwat10/react-link-preview#customfetcher-function)

**Comment by shawnchin** [comment]
To clarify, I am not knocking the implementation of `react-link-preview`; using an intermediate service as a proxy (or doing it on service backend) to handle things like cors and caching is expected for a link preview implementation.

My concern was purely on what else might be needed to integrate this into Jitsi. Specifically, we need to consider:
1. Making this an optional feature rather than enabled by default.
2. Be very clear about requiring the proxy if the feature is enabled. 
3. Respecting `disableThirdPartyRequests` config.
4. Have an easy way for deployments to point to own proxy without having to recompile Jitsi Meet. Ideally with documentation recommending and describing how to deploy ones own proxy.

What I'm trying to avoid is having someone upgrade Jitsi and unknowingly starts sending client chat links to a third party. There are many privacy sensitive Jitsi deployments out there; something like this will have unpleasant consequences.

That said, I do appreciate your contribution. It is indeed a nice feature.

_Disclaimer: I am just an interested party and not part of the Jitsi project. This is purely my personal opinion and doing the above does not guarantee that the feature will get merged._

**Comment by damencho** [comment]
I agree with all the opinions expressed by @shawnchin . Just the "Making this an optional feature rather than enabled by default.", we the Jitsi Team try not to accept features that will be disabled by default, those get easily broken over time and are hard for us to support and needs constant attention for security updates.

The only option for implementing this feature is to have an event from the app for new messages through the iframe api and add a new method there that a message with certain id can be edited, so the listener can push new content replacing the current message. That should be easy to add, I recently added an internal action where display name for messages can be edited, (a breakout rooms fix)
https://github.com/jitsi/jitsi-meet/commit/1c4283eecabd481cb2d2795840196fbfe36e7534

**Pull request closed without merging**
