### PR TITLE
Add several chat configuration items

### PR DESCRIPTION
**Pull request by vladertel**
Introducing CHAT_ON_THE_LEFT and CHAT_STARTS_OPEN boolean variables in interface_config.js

### CODE REVIEW

**Comment by vladertel** [comment]
Hi? I sent the agreement more than a week ago. Any news on this PR?

**Comment by saghul** [comment]
I'd suggest you split this into 2 PRs since they are unrelated. I can see CHAT_STARTS_OPEN being useful for some, but I'd oppose to the change in layout of the chat. I don't think we want to support it anywhere else except on the left.

**Comment by vladertel** [comment]
I understand your position but I believe new chat layout will fit really well in tall and narrow chat clients. Maybe it's worth to give it a try? P.S. I will split these commits in 2 PR's in an hour or two.

**Comment by saghul** [comment]
> I believe new chat layout will fit really well in tall and narrow chat clients.

True that. We should better adapt our UI to layout changes, but having an option to do that is not really a way forward IMHO.

**Pull request closed without merging**
