### PR TITLE
Expose GetP2PConnectionState

### PR DESCRIPTION
**Pull request by wuttke**
Allow to query for P2P connection state on the external API

### CODE REVIEW

**Comment by wuttke** [comment]
I've signed the CLA with my previous pull request. ;)

**Comment by saghul** [comment]
Why would this be useful?

**Comment by wuttke** [comment]
This method can be used to notify the end-user if there is no peer-to-peer connection. (Which is believed to be superior in terms of data protection.)

In our use case, we use embedded Jitsi to provide audio and video for physician-patient meetings. Patient's privacy is of highest importance.

(And the new API call doesn't hurt, right?)

**Comment by saghul** [comment]
Oh yeah a new API does hurt because it has to be maintained going forward.

More importantly this API requires that you actively check for the state, but the connection may flip-flop between P2P and JVB in case of flaky connections.

When a 3rd participant joins the connection switches to the JVB and you won’t know if you need to check for the P2P status or not.

I think relying on this for data protection reasons is not a good choice. We now support E2EE in beta which is: https://jitsi.org/blog/e2ee/

**Comment by wuttke** [comment]
I agree it would be better if there was an event that tells us if the p2p connection state changes.
Until then, polling (I do every 10s) is fine for us.
E2EE is very interesting and would be great but we don't have it right now. Furthermore, unfortunately (!!) we have regulations requiring p2p even if there was e2ee (silly).
Maintaining these few lines of codes seems doable. I agree one should be careful what external API to expose. This one only allows to peek for some internal state. I'd be fine to generalize this: Maybe ask for state given an opaque key?

**Comment by wuttke** [comment]
BTW, I also listen to the participantLeft and participantJoined events to trigger a new state check.

**Pull request closed without merging**
