### PR TITLE
Mobile UI tweaks

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by vp8x8** [comment]
I don't know if it's an emulator thing but on IOS the conference timer does not change.

**Comment by saghul** [comment]
It's now just rendering minutes, as per the new design, so you'll need to wait a full minute to see it change.

**Comment by vp8x8** [comment]
> It's now just rendering minutes, as per the new design, so you'll need to wait a full minute to see it change.

Oh I see `DURATION_FORMAT = 'hh:mm'`. Still pretty confusing. If I'm seeing 00:03 I'm automatically processing it as 3 seconds instead of minute 3.

Anyways, great stuff! Tested on various devices and scenarios and it looks nice.

**Comment by vp8x8** [comment]
Sorry accidentally closed it, lol.

**Comment by saghul** [comment]
Did you intent to close it? Also, if all is ok, care to stamp it? I'll double check with Tibi on the date format.

**Review by vp8x8 — DISMISSED** [review]

**Review by vp8x8 — APPROVED** [review]

**Pull request merged**
