### PR TITLE
Update Catalan (ca) translation

### PR DESCRIPTION
**Pull request by jmontane**

### CODE REVIEW

**Comment by jmontane** [comment]
Hi,
This PR updates and fixes Catalan translation.

I see a Linter check error, but I can't find the problem. Can you help me?

Thanks in advance.

**Comment by saghul** [comment]
We fixed the problem yesterdday, can you please rebase?

**Comment by jmontane** [comment]
I'm sorry, @saghul, but I'm not a programmer guy, I translate only. Can you help about "rebase" a forked repository?

Thanks

**Comment by jmontane** [comment]
Google is our friend. Rebase is done and all checks are pased now :)

**Comment by saghul** [comment]
Thank you!

**Pull request merged**
