### PR TITLE
[RN] Rework avatar caching

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by paweldomas** [comment]
There's a fade-in effect kicking in when the avatar is displayed for the first time. Can you try looking into that ?

Otherwise it removes the main JS thread blocking which is awesome ! Good job !

**Comment by saghul** [comment]
> There's a fade-in effect kicking in when the avatar is displayed for the first time. Can you try looking into that ?

The WIP commit hopefully fixes that.

**Comment by paweldomas** [comment]
the fade is still there

**Comment by paweldomas** [comment]
I wonder how it it fully fix it, given that it only changes when the FastImage is displayed, but it doesn't fix the FastImage

**Comment by saghul** [comment]
@paweldomas Looks like the animation comes from the native library(ies): https://github.com/DylanVann/react-native-fast-image/issues/100

I can try to fix it upstream. I'd still keep the WIP patch though.

**Pull request merged**
