### PR TITLE
ref(overflow-menu) Use ContextMenu component

### PR DESCRIPTION
**Pull request by robertpin**
refactor overflow menu to use ContextMenu component
refactor toolboxItem to use ContextMenuItem when needed

### CODE REVIEW

**Comment by robertpin** [comment]
Jenkins test this please

**Review by saghul — DISMISSED** [review]
LGTM but I'd like another pair of eyes on this one.

**Comment by robertpin** [comment]
Jenkins test this please

**Comment by robertpin** [comment]
Jenkins test this please

**Review by quitrk — APPROVED** [review]

**Pull request merged**
