### PR TITLE
Automatically assign feature-request tag to issues

### PR DESCRIPTION
**Pull request by rugk**
…if they are reported as a feature request, of course.

### CODE REVIEW

**Comment by rugk** [comment]
Note you could do the same with bug if you create a bug label.
As for CLA: Well, this patch very certainly does not meet the bar of the threshold of originality, but yeah… 

----

I also have a wish then:

[Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/) – a project promoting open source contributions – is running this month.

As [they have changed the rules recenty](https://dev.to/devteam/hacktoberfest-etiquette-for-contributors-ec6) you do now have to tag your repository/repositories (=set a GItHub topic) if you want to have participated in this with the tag `hacktoberfest`.
AFAIK you can alternatively also [tag single PRs with `hacktoberfest-accepted`](https://hacktoberfest.digitalocean.com/details#details) to mark them as a valid PR. (Otherwise all merged or positively reviewed PRs count.)

Could you do so, so one may send some PRs and participate there?

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
We can tag PRs if the contributor is interested in it sure!

**Comment by saghul** [comment]
Speaking of, would you like this PR to count towards your hacktoberfest score?

**Comment by rugk** [comment]
Yeah would be nice.

**Pull request merged**
