### PR TITLE
lang: fix(lang) update Occitan translation

### PR DESCRIPTION
**Pull request by Mejans**
New strings translated so as to be up to date :)

### CODE REVIEW

**Comment by Mejans** [comment]
Not so clear to me this error message is.

**Comment by saghul** [comment]
The keys need to be alphabetically sorted, or the build will fail.

**Comment by Mejans** [comment]
I used https://codeshack.io/json-sorter/ then changed the tab by spaces...Still not okay?
Why has Json have to be so complicated for nothing?

**Comment by Mejans** [comment]
I give it, this tool it not helping at all, if it wants it sorted, let it sort it.

**Comment by saghul** [comment]
```
       "videoUnmuteBlockedTitle": "Restabliment de la camèra e del partiment de burèu blocat  !",
        "viewLobby": "Veire sala d’espèra",
        "participantWantsToJoin": "Vòl rejónher la reünion",
        "participantsWantToJoin": "Vòlon rejónher la reünion",
        "waitingParticipants": "{{waitingParticipants}} personas"
```

Those keys you added are not alphabetically sorted.

**Comment by Mejans** [comment]
It's the way Weblate gave it to me

**Comment by Mejans** [comment]
It's really not a pleasure to contribute...
No interface
Non sense notification for licence thing
Non human beings job to accomplish to finish the translation.

**Comment by saghul** [comment]
I agree. We are working to have an interface to do this better, but for now that's where we are, unfortunately.

**Comment by Mejans** [comment]
Well, I don't see what to change here...

**Comment by gpatel-fr** [comment]
@Mejans 

Hello, I feel for you. In fact on reading on the Jitsi forum some poor soul asking for the old automated translation tool that Jitsi-meet used to have to be advised to use the very user-friendly tool that is npm (!!) I decided to write my own tool to manage translations, so that I could do my own translations without touching npm, and more importantly that I could give other would be translators a less hostile reply. Adress is [here](https://notabug.org/gpatel-fr/jitsi-translate-tools)

Readme may be a bit intimidating but basic use is not too complicated, if you have a workstation with Python(3) in the path, it should work by downloading the 2 files, the main.json reference and your language file, then run chklang -a oc and it should generate a file with the new strings to translate at the proper place for the new Jitsi-meet thingy (I checked, I just generated a new translation for my language and it passed) and all you have to do is to edit the new file to search all strings prefixed by '!!' and change them (and remove the !! of course). 

Hope this helps and keep up the good work ! See my [post](https://community.jitsi.org/t/current-state-of-translations/107729/2?u=gpatel-fr) on the Jitsi forum, occitan is in the top 10 !

**Comment by saghul** [comment]
I force-pushed your branch. There were bogus whitespaces and one key was still out of order.

**Review by saghul — APPROVED** [review]

**Comment by Mejans** [comment]
@gpatel-fr merci ! Actually I set up a Weblate instance for projects missing an interface.
For some reason it does not sort strings in JSON, or maybe I didn't look deep enough in the configuration.
Your tool can be useful to many of us! Happy to be in the top 10 :)

**Pull request merged**
