### PR TITLE
One participant message

### PR DESCRIPTION
**Pull request by patidars**
Added a way to display message like “Please wait for others to join”. 
Exposed an optional props from mobile native platform called ‘onlyOneParticipantMessage’. If we pass this prop from native(android/iOS) and there is only one participant in conference then this message will get displayed. If there are more than one participant in conference then  this message will not get display.
This could be a welcome message which can tell user to be on conference and wait until others join.

### CODE REVIEW

**Comment by patidars** [comment]
I have signed CLA.
Thanks

**Comment by patidars** [comment]
@damencho @saghul 
Can you please review this PR.

**Comment by saghul** [comment]
Hi there!

First, thanks for walking the extra mile here and making the PR work for both iOS and Android from the get go.

While I entertain the idea behind this patch, I'm not very fond of the implementation. We generally don't want to get text directly from props and render it, because it wouldn't be internationalized. So here is a proposal!

- add a new boolean config option: showSingleParticipantMessage (default to false)
- Put the text that should be displayed in main.json, with the other texts
- The APIs would only set it to true or false (this could even be done with a feature flag on mobile)

This way the text can be translated and every app doesn't need to do it on their own, should they want to use this feature.

**Comment by patidars** [comment]
@saghul 
Thanks for reviewing PR. 

- I have added flag to enable single participant message(default to false).
- Added default message in main.json which get display if condition meet.
- We are still able to pass customised display message , if we get message from native then it will get display otherwise default message will get displayed.

Let me know if anything else you want to modify/add.
Thanks

**Comment by saghul** [comment]
Sorry I drropped the ball on this one :-/ I took another look and AFAIS the native parts still take the string. Now that the flag is implemented you should be able to drop all that code.

**Comment by patidars** [comment]
@saghul 
Thanks,
This native part will be an additional feature, which will allow others to customize message. If we don't send customized message to SDK then default message will get display.

**Comment by saghul** [comment]
@patidars That is not something I'm keen on merging since it bypasses all forms of translation. If you want different messages you can alwaysmodify main.json and make a custom build.

**Pull request closed without merging**
