### PR TITLE
Updating and uniforming italian translation

### PR DESCRIPTION
**Pull request by eppesuig**
- translate uniformly «meeting» to «conferenza», «chat» to «conversazione», ellipsys to «...», verbs in -ing with «in corso»
- correct a few typos
- update a message with old and unused placeholder
- translate some English messages
- always translate email in e-mail instead of mixed translations of «Email» and «e-mail»

### CODE REVIEW

**Comment by damencho** [comment]
> * translate uniformly «meeting» to «conferenza»,

In the past, we had all English strings using conference, but then move everything to meeting and this sounds in the opposite direction, is this true?

**Comment by eppesuig** [comment]
I've found different translations scattered on the file: conferenza (conference), and riunione (meeting) were the most used. I think only one should be be used. I am not preferring one of them. If, in the past, there was some agreement on preferring meeting over conference, I would update the Italian translation accordingly.

**Comment by damencho** [comment]
Yep meeting, check English for referrence

**Comment by eppesuig** [comment]
I've just updated the translation using riunione (meeting) in place of conferenza (conference).

**Comment by damencho** [comment]
Jenkins test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
