### PR TITLE
feat(Lobby): Adding autoknock feature as a config 

### PR DESCRIPTION
**Pull request by Payetus**
This PR solves  #10307 .

The objective is to be able to skip the "Ask to Join" page when Lobby is enabled.

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
@damencho any objections to this?

**Comment by damencho** [comment]
Nope

**Comment by Payetus** [comment]
@saghul  There seems to be a problem with the Testing Enviroment

**Comment by saghul** [comment]
Yep, not your fault.

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by Payetus** [comment]
@saghul  Do you have a time estimation on when this might be released?

**Comment by damencho** [comment]
It will be in the unstable repo in 30 mins or so.

**Pull request merged**
