### PR TITLE
fix(prejoin) implement ux improvements for mobile

### PR DESCRIPTION
**Pull request by quitrk**
Screenshot 2021-09-14 at 13 24 54

### CODE REVIEW

**Comment by quitrk** [comment]
jenkins please test this please

**Comment by vp8x8** [comment]
I've seen an error that looks like this with no yellow background. Is this how it's supposed to look like?

Screenshot 2021-09-15 at 11 59 11

**Comment by quitrk** [comment]
@vp8x8 fixed

**Review by vp8x8 — DISMISSED** [review]

**Comment by vp8x8** [comment]
Jenkins test this please.

**Comment by quitrk** [comment]
Jenkins test this please.

**Review by vp8x8 — APPROVED** [review]

**Comment by quitrk** [comment]
Jenkins please test this please. Pleeeeeaaaase

**Pull request merged**
