### PR TITLE
ref(info): new component for showing meeting info

### PR DESCRIPTION
**Pull request by virtuacoplenny**

### CODE REVIEW

**Comment by virtuacoplenny** [comment]
I tried to make a generic component for showing an inline dialog from a toolbar button. I'm not confident about how I did it, and even changed it a couple of times which is why it ended up getting squashed into one commit, and I can't think of better ideas right now so I'm putting this PR up for feedback.

**Comment by virtuacoplenny** [comment]
Assigning @yanas because in another pull request she had mentioned a todo of making a generic button for showing an inline dialog. Maybe she has some thoughts on how that could be implemented.

**Comment by yanas** [comment]
I like your generic ToolbarButtonWithDialog implementation.

**Comment by virtuacoplenny** [comment]
Are you asking about where primary and secondary toolbar buttons get mapped into the toolbar components? https://github.com/jitsi/jitsi-meet/blob/28b4595561fe255bad93333ec72e039f3130850e/react/features/toolbox/functions.web.js#L28

**Pull request merged**
