### PR TITLE
feat(ci): using .luacheckrc

### PR DESCRIPTION
**Pull request by wfleischer**

### CODE REVIEW

**Comment by wfleischer** [comment]
@emrahcom : Would you mind taking a look?

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Looks good!

**Comment by emrahcom** [comment]
Thank you @wfleischer
This looks like a better way to set arguments.

@shawnchin, IIRC you mentioned using RC file before but at the end we set arguments on the commandline. Can you check this commit too please.

**Comment by emrahcom** [comment]
I applied the same changes to https://github.com/jitsi-contrib/prosody-plugins/commit/bcc59039e973aa214bee3c7e45d6342ab69cdfbc

**Comment by shawnchin** [comment]
lgtm :)

**Comment by saghul** [comment]
Thanks folks!

**Pull request merged**
