### PR TITLE
Update Toolbox.tsx

### PR DESCRIPTION
**Pull request by neshvig10**
I have added the scroll option to the menu and also limited the maximum height of the menu to 50% of the window size

### CODE REVIEW

**Comment by neshvig10** [comment]
> What does this accomplish? Can you show some screenshots?

This allows the popover to have a maximum height of 50% of the app window 
This also enables scrolling in the popover

**Comment by neshvig10** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Ok then , I'm creating a new branch and making the changes again

**Comment by damencho** [comment]
> Ok then , I'm creating a new branch and making the changes again

you don't need to. This is automated response. Just publish some screenshots of the result.

**Comment by neshvig10** [comment]
> > Ok then , I'm creating a new branch and making the changes again
> 
> you don't need to. This is automated response. Just publish some screenshots of the result.

image
Here we can see scroll functionalities and maximum height of the popover has been changed to a percentage of window height

**Comment by saghul** [comment]
Thanks for the screenshots! @robertpin can you PTAL?

**Comment by robertpin** [comment]
This is unnecessary. The Overflow menu already resizes correctly when you have a small window. With this change it would make it too small on large screens

**Comment by neshvig10** [comment]
sorry

**Pull request closed without merging**
