### PR TITLE
Use tabs ARIA design pattern when using tabbed UI

### PR DESCRIPTION
**Pull request by Leimi**
_Related to https://github.com/jitsi/jitsi-meet/issues/12379_

There are a few tabbed UIs in the app: meetings list in the welcome screen, settings dialog, chat panel, desktop sharing screen dialog (I think I didn't forget any).

Those tabbed UIs were either unusable with a keyboard, or a bit cumbersome/misleading to use with a screen reader.

This whas because sometimes, keyboard support wasn't there. For example, the meetings calendar in the welcome screen wasn't reachable without a mouse. Or sometimes, the [tabs ARIA design pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) was used, but wasn't fully implemented. DOM attributes were used but keyboard interactions weren't handled. Those have been added.

In addition to using the ARIA pattern, sometimes DOM order had to be changed so that tabulation and screen reader announcements become more logical.

Here are before/after videos of some of the changes to get the idea:

<details>
<summary>Welcome page meetings lists</summary>

https://user-images.githubusercontent.com/221253/222515725-b348fcbd-e9c8-4c07-8f9b-2883ada504ba.mp4

https://user-images.githubusercontent.com/221253/222516795-656377d3-8650-46a1-8d22-444dc0f38e5d.mp4

</details>

<details>
<summary>Settings dialog</summary>

https://user-images.githubusercontent.com/221253/222515821-1997a1e9-3948-4321-9629-7031c3bb2907.mp4

https://user-images.githubusercontent.com/221253/222515961-197bb432-255f-4e09-ace7-ff4f0b053cac.mp4

_Note: you can see the dialog close icon has no focus styles, a fix is suggested in [this PR](https://github.com/jitsi/jitsi-meet/pull/12968/commits)._
</details>

### CODE REVIEW

**Comment by Leimi** [comment]
One noticeable change is that when using the tabs aria pattern, we hide/show the tab panels instead of adding/removing them from the DOM. It's a common thing to do for this case, as screen readers sometimes have trouble understanding when DOM is replaced instead of having things being shown/hidden.

**Comment by Leimi** [comment]
Hey @Calinteodor, in case you wanna check. Tomorrow I'll try to see the testing repo for my other PR not passing.

Will continue on accessibility stuff for most of next week I think!

**Comment by Calinteodor** [comment]
> Hey @Calinteodor, in case you wanna check. Tomorrow I'll try to see the testing repo for my other PR not passing.
> 
> Will continue on accessibility stuff for most of next week I think!

Hey @Leimi! No worries, I am working right now on fixing the tests and I am almost done.

**Comment by Leimi** [comment]
Oh okay, thanks!

**Comment by Calinteodor** [comment]
jenkins test this please

**Comment by Calinteodor** [comment]
@Leimi please rebase and fix conflicts. Thanks!

**Comment by Leimi** [comment]
Done :)

**Comment by Leimi** [comment]
Yeah I spoke too fast and updated right after haha

**Comment by Calinteodor** [comment]
jenkins test this please

**Comment by Calinteodor** [comment]
> Done :)

Nice work, @Leimi! All checks pass! 
Let's merge this!

**Review by Calinteodor — APPROVED** [review]

**Comment by Leimi** [comment]
Thanks :+1:

**Pull request merged**
