### PR TITLE
fix: use email context from JWT for reservations if JWT is used

### LINKED ISSUE #10947: JWT auth and reservations api
### Description:

We are using lib-jitsi-meet in our own application, and our application uses authentication with JWT. When we recently tried to integrate the reservations api as described in https://jitsi.github.io/handbook/docs/devops-guide/reservation we came across this:

REST calls to reservation api would not use mail_owner from JWT data, but only use the actual anonymous jid assigned on connecting.

### Steps to reproduce:

1. set up reservation system and create a reservation for a call, setting a mail_owner 
2. at the scheduled time, try to start teh conference using JWT auth, with user.email in JWT set to the reserved mail_owner

### Expected behavior:

A user that has the correct user.email in his JWT is able to start the conference.

### Actual behavior:

A user that has the correct user.email in his JWT is not able to start the conference; instead he receives a reservation error.

### Server information:

- Jitsi Meet version: jitsi-meet 2.0.6865-2

### PR DESCRIPTION
**Pull request by stefansaenger**
use email context from JWT auth if available for reservations api

resolves #10947

### CODE REVIEW

**Comment by shawnchin** [comment]
The issue you raised is a valid one -- it is important to be able to identify the user when validating a room reservation and user JID is not ideal in the case of JWT auth.

However, I would argue that hardcoding to email from JWT may not be the right answer for everyone. On my deployments for examples, I have users with different ids and usernames that could have the same email address set up, and using `context.user.id` from JWT payload makes more sense for me.

So rather than a hardcoded transformation as you've done, perhaps add an extra option config that takes a lua function that maps from creator_jid to any value someone might want to use. And we default to creator_jid if that function is not provided. This now opens up the feature to many other use cases and does not change behaviour for existing deployment.

Thoughts?

**Comment by stefansaenger** [comment]
Hi @shawnchin 

thanks for your input. 

Well - my first thought was that my PR should not change too much for existing deployments - if they are not using JWT auth, then as far as I see jitsi_meet_context_user is never present; so it would still use creator_jid as before.

However - I can see that this opens up a few new possibilities. However - by default only `context.user.id` and `context.user.email` are somewhat predefined, So as a logical step I added a config option (that will fall back to current behaviour) and now it also supports `context.user.id`.

**Comment by shawnchin** [comment]
> However - by default only context.user.id and context.user.email are somewhat predefined

I may just be splitting hairs here, but while `user.id` and `user.email` are mentioned explicitly in the tokens docs, it also states that "None of the information in the context field is used for token validation" and pretty much anything one stores in `context.user` is accessible on [`session.jitsi_meet_context_user`](https://github.com/jitsi/jitsi-meet/blob/ba6247daafe90fa5e2eb78916402646646b90624/resources/prosody-plugins/token/util.lib.lua#L302). So deployments might (I do) inject additional attributes to JWT to identify a specific user session for various purposes.

**Comment by shawnchin** [comment]
It's not my call if this gets merged or not, so let's leave this at "we have differing views of how it should be implemented, but we agree it is a useful feature to include".

My main concerns were:
1. the default behaviour should not change (which you have addressed in the following commit. Thanks!)
2. it should not assume the every jwt deployment would want mail_owner replaced by email from context (which you have also addressed. Thanks.)

I'm not qualified to offer a code review, but if I may be so bold as to offer a suggestion, perhaps extract all the mapping logic out as a separate function and call that from `get_or_create_reservations`? So something like:
```lua
local function get_or_create_reservations(room_jid, creator_jid)
    if reservations[room_jid] == nil then
        local mail_owner = get_mail_owner_from_creator_jid(creator_jid);

        module:log("debug", "Creating new reservation data for %s (created by %s)", room_jid, mail_owner);
        reservations[room_jid] = newRoomReservation(room_jid, mail_owner);
    end

    return reservations[room_jid];
end
```

**Pull request closed without merging**
