### PR TITLE
update zhTW translation

### PR DESCRIPTION
**Pull request by 5idereal**
Revert @thttg's changes (#12104) to follow [Microsoft's Localization style guide](https://learn.microsoft.com/en-us/globalization/localization/ministyleguides/mini-style-guide-trad-chinese#6-spacing) and terminology, spacing specifically.

### CODE REVIEW

**Comment by damencho** [comment]
@thttg is this ok? 
@5idereal what is the reason for this?

**Comment by 5idereal** [comment]
#12104 removes all the spacing between Chinese and English characters, which [reduces readability](https://github.com/vinta/pangu.js).

> 6. Spacing
Spacing is an important consideration when localizing strings into Traditional Chinese.
> The following general rules are applied:
> Half-width space is needed between Chinese characters and English letters or numbers.
> Half-width space is needed between Chinese characters and half-width punctuation marks: ( ), [ ]. Exception: This rule does not apply to : ; ! ?
> No space is needed around Chinese full-width punctuation marks.

Copied from [Microsoft's Localization style guide](https://learn.microsoft.com/en-us/globalization/localization/ministyleguides/mini-style-guide-trad-chinese#6-spacing).

@thttg also reuses terms from zhCN, For example, in line 462, 令牌 should be 權杖, and in line 676, 本地 should be 本機.

**Comment by thttg** [comment]
> @thttg is this ok? @5idereal what is the reason for this?

It looks good to me.

**Comment by damencho** [comment]
@5idereal can you drop the change from lang/main.json

**Review by damencho — APPROVED** [review]

**Pull request merged**
