### PR TITLE
fix(large-video): do not show avatar if no url

### PR DESCRIPTION
**Pull request by virtuacoplenny**
By default the large video dominant speaker avatar
has an empty src, which will result in a broken
image displaying. There is also disconnect with
non-react code trying to set an undefined src.
To prevent such until local avatar generation
work is done in the future, just don't show the
avatar.

### CODE REVIEW

**Comment by virtuacoplenny** [comment]
Depends on https://github.com/jitsi/jitsi-meet-torture/pull/231 to make up for the changed DOM.

**Comment by virtuacoplenny** [comment]
So somehow moving when this._room gets set in conference prevents large video switching on initial load... I'll have to revert/fix that.

**Comment by paweldomas** [comment]
@virtuacoplenny is it better now ? I'm not testing this changes, I trust you

**Comment by virtuacoplenny** [comment]
Yeah, it's better. I'm gonna keep testing though. It scares me that a bug was manifesting only when my developer tools was closed.

**Pull request merged**
