### PR TITLE
Speaker stats search fix #9751

### PR DESCRIPTION
**Pull request by dimitardelchev93**
Fixes search bugs when removing characters.

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins. test this please.

**Comment by damencho** [comment]
Jenkins. test this please.

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
@dimitardelchev93 Oh I didn't test it and merged it and now when I tested it on alpha.jitsi.net after the build, now search is not working at all ... will you take a look

**Comment by dimitardelchev93** [comment]
> @dimitardelchev93 Oh I didn't test it and merged it and now when I tested it on alpha.jitsi.net after the build, now search is not working at all ... will you take a look

yes, sorry I just see that, will check asap

**Comment by dimitardelchev93** [comment]
@damencho here is the fix https://github.com/jitsi/jitsi-meet/pull/10045

**Pull request merged**
