### PR TITLE
First version of end-user guide (spanish version)

### PR DESCRIPTION
**Pull request by jperera**
Based on english version of Peter E. Humphries': https://community.jitsi.org/t/end-user-web-conference-guide-for-jitsi/28974

### CODE REVIEW

**Comment by jperera** [comment]
Yes, I have already signed the CLA 🙂

**Comment by luixxiul** [comment]
This needs rebase.

**Comment by luixxiul** [comment]
Since the documentation has moved to https://github.com/jitsi/handbook/ I assume these changes should also be merged there.

**Comment by luixxiul** [comment]
@jperera What do you think about the proposal of mine above? thanks!

**Comment by jperera** [comment]
@luixxiul Perfect!

**Comment by luixxiul** [comment]
If I were you I would:

- move the proposed document to that Handbook's repository (and drop the related commits of this PR)
- push a commit to this (/ a new) PR to edit README.md to link to the document from under `## Installation` section with a sub heading such as `### Instrucción en Español` (?)

This is just my two cents.

**Pull request closed without merging**
