### PR TITLE
[RN] Don't request camera permission on first launch

### PR DESCRIPTION
**Pull request by saghul**
It will only be requested if a user joins a meeting or flips the switch from
video to audio and back, but never as the first thing when the welcome page is
mounted.

### CODE REVIEW

**Comment by saghul** [comment]
Android tests pass, but iOS tests don't seem to run? (@paweldomas is this correct?)

**Comment by saghul** [comment]
Please merge this one too: https://github.com/jitsi/jitsi-meet-torture/pull/200

**Comment by saghul** [comment]
@paweldomas Can I get your help with this please? I can't, for the life of me, explain what's going on. It works locally and Android tests also pass, I can't explain the iOS failure 😢

**Comment by paweldomas** [comment]
@saghul I will take a look - moving the conversation to the torture PR

**Comment by paweldomas** [comment]
jenkins test this please

**Comment by paweldomas** [comment]
@lyubomir the torture changes were good. The problem was in the PR script with fetching the changes from jitsi-meet PR branch to run the test. Do you approve this PR knowing that the torture tests are good now ?

**Pull request merged**
