### PR TITLE
Add MOBILE_APP_PROMO to whitelist

### PR DESCRIPTION
**Pull request by jhiswin**
Add MOBILE_APP_PROMO to whitelist to allow hiding the mobile app banner.  https://github.com/jitsi/jitsi-meet/issues/7060

### CODE REVIEW

**Comment by jhiswin** [comment]
Hello, I see that a mailing address is required for signing the CLA.  Is that address going to be stored somewhere?

**Comment by damencho** [comment]
> Hello, I see that a mailing address is required for signing the CLA. Is that address going to be stored somewhere?

Nope, this is used to identify people, comparing the commit's email address and whether that matches a signed document with such an address.

**Comment by damencho** [comment]
I'm not sure we want to remove `MOBILE_APP_PROMO ` from the whitelist. This can be easily controlled through the server's interface config.

**Comment by saghul** [comment]
We don't want to make that overridable for meet.jit.si. You can of course override it on your own deployment. Note that there is now a new button to join the conference using the mobile browser right on the page that is rendered.

**Pull request closed without merging**
