### PR TITLE
Remove legacy attribute

### PR DESCRIPTION
**Pull request by Mandroide**
Remove [legacy attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Attributes)

### CODE REVIEW

**Comment by Mandroide** [comment]
@saghul

**Comment by Mandroide** [comment]
@damencho

**Comment by damencho** [comment]
From the link you provided I see this will not work for Firefox older than 74 .. I wonder is this ok ...

**Comment by Mandroide** [comment]
> From the link you provided I see this will not work for Firefox older than 74 .. I wonder is this ok ...

I missed that one. I guess that might not be a good idea to remove legacy.

**Comment by saghul** [comment]
The current Firefox ESR versions is 78, with the previous one being 68. We have an unwritten rule of trying to keep the "previous to current" ESR version running. Now, I think this is a new (and small) enough feature to warrant an exception. LGTM.

**Review by saghul — APPROVED** [review]

**Pull request merged**
