### PR TITLE
[i18n] Update for Occitan

### PR DESCRIPTION
**Pull request by Quenty-tolosan**

### CODE REVIEW

**Comment by Quenty-tolosan** [comment]
Yes already done and said

**Comment by Mejans** [comment]
Hello @saghul ! Could you have a look at it, it's been pending for 11 days or so. Thanks :D

**Comment by saghul** [comment]
Sorry for the delay folks. Looks like this one has a conflict now. Can you please take care of it?

**Comment by Quenty-tolosan** [comment]
Hello, I'm not goot at Github and stuff. I have just deleted a part of the file, I don't know if it's correct...

**Pull request merged**
