### PR TITLE
Added new mobile SDK delegate methods re onParticipantJoined, 

### PR DESCRIPTION
**Pull request by imdatsolak**
Added new mobile SDK delegate (Listener) methods for iOS and Android:
- onParticipantJoined
- onParticipantLeft
- onParticipantKicked

For documentation, see the source-code

### CODE REVIEW

**Comment by imdatsolak** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Has already been done long time ago...

**Comment by saghul** [comment]
Closing since we've implemented these as part of SDK v3 (on master, unreleased yet). Sorry we couldn't take your PR in time, we gave the SDK a new twist so it should be easier to extend henceforth.

**Comment by imdatsolak** [comment]
No worries, when can we expect SDK v3?

**Comment by saghul** [comment]
Soon! (about a week I think)

**Pull request closed without merging**
