### PR TITLE
Moves checkbox for hiding self view to video tab from the general tab

### LINKED ISSUE #14407: Move Hide Self View to the Video Tab
**Is your feature request related to a problem you are facing?**
Yes, finding the **Hide Self View** in the General tab is non-intuitive.

**Describe the solution you'd like**
Move **Hide Self View** to the video tab under **Mirror my video** .

**Describe alternatives you've considered**
Add a hotkey for toggling Hide Self View?

I noticed this PR.

https://github.com/jitsi/jitsi-meet/pull/13339

I'm happy to create a similar PR to move the checkbox if project leads consider this is a desirable change.

### PR DESCRIPTION
**Pull request by smarizvi110**
resolves #14407

Moves checkbox for hiding self view to video tab from the general tab, under mirror my video checkbox

### CODE REVIEW

**Comment by smarizvi110** [comment]
Ran into a few issues with linting and forgot to pass the `disableSelfView` bool to the video popup. Should be fine now.

**Comment by smarizvi110** [comment]
Missed one lint due to expecting the linter to ignore the line. Fixed.

**Comment by saghul** [comment]
IIRC it used to be there but we had to move it for some reason.

We need to check with design.

**Comment by smarizvi110** [comment]
Made the pull request branch up-to-date with the main branch.

**Pull request closed without merging**
