### PR TITLE
Update jitsi-meet.conf

### PR DESCRIPTION
**Pull request by NFH26**
I was having errors like nginx enable to load stream then I found this error and it is now fixed for me. 

Ref. 
https://serverfault.com/questions/858067/unknown-directive-stream-in-etc-nginx-nginx-conf86

### CODE REVIEW

**Comment by damencho** [comment]
What will happen if it is already loaded?

**Comment by liberodark** [comment]
When try to use it : 

nginx -t
nginx: [emerg] module "ngx_stream_module" is already loaded in /etc/nginx/modules-enabled/60-jitsi-meet.conf:6

Is already used

**Comment by damencho** [comment]
So it fails?

**Comment by NFH26** [comment]
> So it fails?

it fails for me, the error was unknown directive “stream”  and I followed the answer in the link: https://serverfault.com/questions/858067/unknown-directive-stream-in-etc-nginx-nginx-conf86 to fix it, and now it is working :)

**Pull request closed without merging**
