### PR TITLE
feat(force-mute): Implement force-mute functionality

### PR DESCRIPTION
**Pull request by gimre**
This PR is part of a series of PRs in multiple repositories to enable force-mute functionality in jitsi meetings:
- https://github.com/jitsi/jicofo/pull/604
- https://github.com/jitsi/jitsi-meet/pull/7779
- https://github.com/jitsi/lib-jitsi-meet/pull/1329

### CODE REVIEW

**Comment by shubham2110** [comment]
@gimre  Hey !! Thanks for implementing it. 
Does it allow admin to  force mute specific participants?
Does it allow user to mute themselves on their wish ?
Does it allows admin to force mute everyone except few ?

**Comment by gimre** [comment]
Hey @shubham2110!
This allows meeting moderators to force-mute specific participants, yes. Force-muted participants will need to request an unmute from the moderators and after that is approved, they can unmute themselves.

Right now this is implemented as a blacklist, so having a force mute all except some would be unsuited. This implementation might change, though to consider a blacklist and a whitelist. Most use cases would be covered then!

**Comment by shubham2110** [comment]
Hey @gimre 
Since you have already developed so much. I would request you to make changes as follows. 
Freeze Mute state (Those who are muted will remain muted and those who are not muted will remain unmuted)
   Whenever Administrator Freeze the Mute state, any participant who is muted should not be able to unmute himself. 
   But participants who are unmuted should have control to mute themselves (Due to Privacy). later on if a participant who has 
   muted himself, should ask permission to unmute (I guess this is already there in your code. )

**Comment by skolmer** [comment]
Hi @gimre can we support you somehow? We are currently evaluating to add force mute video to the video-bridge. This would be a nice extension to this moderation feature. Not sure about the current state of this feature though and if video was considered yet.

**Comment by skolmer** [comment]
The PR's to mute video can now be found here: https://github.com/jitsi/jitsi-meet/pull/8630 
Would be great if you could add the force feature for this too if it gets merged.

**Comment by pratik9722** [comment]
when the moderator has tried to mute someone then the moderator got kick out from that room

**Comment by gimre** [comment]
> Please don't force push, but add commits on top of it ... I'm working with the code and now I don't know what changed with the last push ... Thank you

Sure thing, I didn't realize you're also touching this.

**Comment by damencho** [comment]
Closing in favor of https://github.com/jitsi/jitsi-meet/pull/9195

**Comment by Abhishek-500apps** [comment]
I want jitsi breif info

**Pull request closed without merging**
