### PR TITLE
Add button and shortcut for toggling "follows me"

### LINKED ISSUE #5272: [feature request] Add keyboard shortcut and icon for "Everybody follows me"
**Is your feature request related to a problem you are facing?**

I'm holding workshops using jitsi-meet together with a second person. The usual setup is us on one side, and a group of people in a room on the other side.

For discussions, we enable the "Everybody follows me" (EFM) and switch to the tile view. After the discussion is over, we switch back to our video (for all), then disable EFM, and switch only our view this time to the video of the other participant (usually a group in a room).

This way, we can control their projector image without anybody on the remote side having to take care of it and see the group video in large on our screen.

The problem is that toggling EFM takes us five mouse clicks each time.

**Describe the solution you'd like**

I'd like to be able to toggle EFM with a keyboard shortcut (or a single mouse click), ideally including a highlighted button which shows the state. This could be similar to the tile view button.

**Describe alternatives you've considered**

I've tried adding the keyboard shortcut myself and [asked about it](https://community.jitsi.org/t/how-to-add-key-bindings/24023/2?u=fd0), there's no easy way to add keyboard shortcuts right now.

**Closing remarks**

I'm willing to work on a PR which adds this feature (given a bit of guidance). Please let me know if such a PR would be merged :)

Thank you very much for all the work! Jitsi is awesome!

### PR DESCRIPTION
**Pull request by rtpt-alex**
This commits adds a new button and a keyboard shortcut for toggling the "everybody follows me" feature. Toggling it via the settings required around five mouse clicks. The button visualizes the current state and is only shown for moderators.

The icon should stand for a "follow me" car used on the apron of airports.

It looks like this:
DeepinScreenshot_select-area_20200327134848

The icon svg file is taken from WikiMedia and licensed as CC0, the source is:

https://commons.wikimedia.org/wiki/File:Taxi_-_The_Noun_Project.svg

Closes #5272

### CODE REVIEW

**Comment by rtpt-alex** [comment]
Please let me know if there's anything else I need to do, thanks for all your work!

**Comment by rtpt-alex** [comment]
I'm not sure what the next step here is. Is there anything I can do to help? Rebase on master again?

**Comment by saghul** [comment]
Sorry, looks like this one fell through the cracks. Let me check if want to proceed with this.

**Comment by rtpt-alex** [comment]
Great, thanks! We've been used it in production (rebasing on master as necessary) for holding larger presentations. It worked really well (with a dedicated person switching the view for all attendants as necessary)!

I'd love to get a quick yes/no if you're willing to merge this feature in general. If the answer is 'yes', then I'm willing to implement any changes needed. :)

**Comment by saghul** [comment]
So I checked and we don't think this feature should be exposed like that. It's something used rarely and the UX is very weird when more than one person enables it at a time.

Sorry it took this long to reach a conclusion.

**Comment by rtpt-alex** [comment]
Thanks for the feedback :)

**Pull request closed without merging**
