### PR TITLE
muteEveryone external API command

### PR DESCRIPTION
**Pull request by blalop**
Implements a command in the external API to mute all the participants except the one that executes this command.

### CODE REVIEW

**Comment by blalop** [comment]
Issue: #6483

**Comment by blalop** [comment]
@jitsi-jenkins Yes, we've already signed as idealista SAU.

**Comment by dortegau** [comment]
@saghul @damencho Seems that CI has skipped this PR. Can we do something to force it?

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by dortegau** [comment]
Thanks @damencho :)

**Comment by dortegau** [comment]
@blalop there are conflicts :)

@damencho @saghul It would be nice to know if this PR would be considered/checked or not to consider to fix that conflicts

**Comment by saghul** [comment]
@dortegau Oops, sorry for the delay. We've moved the docs here: https://github.com/jitsi/handbook/blob/master/docs/dev-guide/iframe.md

Can you please send a PR there and fix the conflict here by removing the docs part? Code LGTM.

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by dortegau** [comment]
Thanks @saghul :)

**Pull request merged**
