### PR TITLE
[RN] Try to create local tracks when unmuting, if track is missing

### PR DESCRIPTION
**Pull request by saghul**
See individual commits for a some more details.

### CODE REVIEW

**Comment by paweldomas** [comment]
Would it make sense to "ensure track" automatically when the app is finally unmuted according to every video mutism authority instead of having it as an argument ?

**Comment by saghul** [comment]
> Would it make sense to "ensure track" automatically when the app is finally unmuted according to every video mutism authority instead of having it as an argument ?

Not really, because when you come back from the background, for example, you don't want to do that. I tried both approaches and went with this one because it gives control to the user at the exact point where the action is being triggered, so it looks to me like the right place to make the most appropriate choice.

**Comment by saghul** [comment]
Jenkins please test.

**Comment by paweldomas** [comment]
>Not really, because when you come back from the background, for example, you don't want to do that. I tried both approaches and went with this one because it gives control to the user at the exact point where the action is being triggered, so it looks to me like the right place to make the most appropriate choice.

Why you would not want to create track when coming back from the background ? I don't see problem with that - especially with video, but I must be missing something

**Comment by saghul** [comment]
> Why you would not want to create track when coming back from the background ? I don't see problem with that - especially with video, but I must be missing something

Imagine the following case: you start a conference but deny video permission. Then at some point you put the app in the background. In this case we mute and unmute video (as we always do) but we don't want to ask you for permission or create the video track when you come back from the background. You didn't have a track, and that's how you should remain.

**Comment by saghul** [comment]
Jenkins, test this please.

**Comment by saghul** [comment]
Jenkins, test this please.

**Comment by saghul** [comment]
Jenkins, test this please.

**Comment by saghul** [comment]
Jenkins, test this please.

**Comment by paweldomas** [comment]
For the permission denied case maybe it should be marked explicitly or the muted by user flag flipped to true. I'm not a big fan of the ensure tracks flag, but I remember you said it's easy to change later, so I don't mind

**Comment by saghul** [comment]
> For the permission denied case maybe it should be marked explicitly or the muted by user flag flipped to true.

I disagree. The user never expressed their desire to mute, they expressed their desire not to use video. It *looks* similar, but IMHO it's not.

> I'm not a big fan of the ensure tracks flag, but I remember you said it's easy to change later, so I don't mind

You mean the name, or the fact that it exists at all?

**Comment by paweldomas** [comment]
>I disagree. The user never expressed their desire to mute, they expressed their desire not to use video. It looks similar, but IMHO it's not.

Well, but it works well for the UI. If user decides later to add video can click on "muted" video button to try adding it later on.

> You mean the name, or the fact that it exists at all?

The fact that it exists

**Comment by saghul** [comment]
Looks like our viewpoints are irreconcilable here. At any rate, tests pass now.

**Comment by lyubomir** [comment]
Obsoleted by/contained in https://github.com/jitsi/jitsi-meet/pull/1906.

**Pull request closed without merging**
