### PR TITLE
fix(config.js) Added missing participant left notification key.

### PR DESCRIPTION
**Pull request by ashiqhassan95**

### CODE REVIEW

**Comment by ali-alhaidary** [comment]
Do we need to add these keys to lang/main.js ?

**Comment by ashiqhassan95** [comment]
> Do we need to add these keys to lang/main.js ?

No.

**Review by saghul — APPROVED** [review]

**Comment by ali-alhaidary** [comment]
where would I find config.js on ubuntu installation please?

**Comment by saghul** [comment]
/etc/jitsi/meet/

**Pull request merged**
