### PR TITLE
Farsi (Persian) translation

### PR DESCRIPTION
**Pull request by mokazemi**
Full reviewing and proofreading Farsi translations.
Also fixed inconsistencies in used words with other platforms (e.g. BBB)

### CODE REVIEW

**Comment by damencho** [comment]
Seems your translation is not passing lint checks, you need to fox that. Seems like sorting is off.

**Comment by mokazemi** [comment]
> Seems your translation is not passing lint checks, you need to fox that. Seems like sorting is off.

Could you confirm that it's fixed now? I think it's now sorted.

**Comment by mokazemi** [comment]
> Seems your translation is not passing lint checks, you need to fox that. Seems like sorting is off.

Could you confirm that it's fixed now? I think It's now sorted. @damencho 



> Hi, thanks for your contribution! If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

I've already done this.

**Comment by damencho** [comment]
Jenkins teat this please.

**Comment by damencho** [comment]
Jenkins teat this please.

**Comment by damencho** [comment]
Let's spell it correctly 🤦 
Jenkins test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
