### PR TITLE
add option for external links

### PR DESCRIPTION
**Pull request by sualko**
This is specially useful in europe where you have to provide a link to legal information
and your privacy policy. There are still a couple of things to discuss:

- [ ] Rename option?
- [ ] SCSS vars for margin and color?
- [ ] Maybe add option to add to conference screen?
- [ ] Translation?

Screenshot:
2020-03-19 11 31 42 localhost a9f4fe4d87d0

### CODE REVIEW

**Comment by damencho** [comment]
There is already a hook to do those. Check meet.jit.si welcome page where the code is the same as jitsi-meet with few additional filled in hooks. Like in static welcomePageAdditionalContent.html ...

**Comment by sualko** [comment]
Those "hooks" seam to be pretty neat, but how do they behave if I do an update? Is this somewhere documented?

The beauty of my solution is that it's configurable in the config, which is the idea of a config I think. Especially in a setup with docker (which I use btw).

**Comment by luixxiul** [comment]
How about the status of this PR?

**Comment by Echolon** [comment]
@sualko Have you have sometime for working on this again?

**Comment by sualko** [comment]
> Have you have sometime for working on this again?

I can resolve the conflict, but I'm using jitsi meet anymore. So I don't have any intent to work on this more than that.

**Comment by Echolon** [comment]
Okay, I understand. If you could at least resolve it would be great!

**Pull request closed without merging**
