### PR TITLE
supports a '*' in the sub claim to allow access to any room

### PR DESCRIPTION
**Pull request by aaronkvanmeerten**
Opened to fix prosody modules to accept wildcards in 'sub' claims of the incoming token, not just wildcards in the 'room' claim of the token

### CODE REVIEW

**Comment by webintoit** [comment]
`sub` claim is used to identify the user, please, crate something custom for something very custom

**Comment by aaronkvanmeerten** [comment]
> `sub` claim is used to identify the user, please, crate something custom for something very custom

We use 'sub' to identify the tenant or domain used for the token.  This behavior is consistent with the documentation found here:

https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

**Comment by aaronkvanmeerten** [comment]
Jenkins test this please

**Comment by aaronkvanmeerten** [comment]
Jenkins test this please

**Pull request merged**
