### PR TITLE
minimized size without quality loss via optipng

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by PanderMusubi** [comment]
No problem. Will this form not be shared with others publically? As I will combine my name and my nickname email address.

**Comment by PanderMusubi** [comment]
@saghul

**Comment by saghul** [comment]
> No problem. Will this form not be shared with others publically? As I will combine my name and my nickname email address.

No, only 8x8 has access to it.

**Comment by saghul** [comment]
I don't think you need to sign it for this though. And thank you!

**Comment by PanderMusubi** [comment]
Thanks, can you unblock this PR?

**Pull request merged**
