### PR TITLE
prosody: fix JWT auth module for new Prosody versions

### PR DESCRIPTION
**Pull request by saghul**
See: https://github.com/jitsi/lib-jitsi-meet/issues/837

### CODE REVIEW

**Comment by saghul** [comment]
@damencho Let's start thinking what to do here. What's the oldest Ubuntu version we support?

**Comment by damencho** [comment]
So we are applying patch to trunk about that. I think the patch is not working on prosody 0.10 and the change is not there. At some point, our current patch was applied in prosody-trunk and at some point they changed it to the version that is currently in 0.11. I will check prosody 0.10 to be sure.
Anyway, this doesn't work with 0.9...

**Comment by saghul** [comment]
Sure, but do we need it to work there or can we use the officia repos to update beyond 0.9?

**Comment by damencho** [comment]
I don't think we even support that, for tokens, we only had the dependency of trunk: https://github.com/jitsi/jitsi-meet/blob/master/debian/control#L53
> prosody-trunk (>= 1nightly607)
So we are safe there, but what I wonder is that we install it as a virtual host module, can we have a lot of listeners for the same thing ... but we actually install this only for one host so it should be fine.
So if you think it works with 0.11 we can edit the [patch](https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_bosh.lua.patch) and add | dependency to support trunk and 0.11 or everything > 0.11.

**Comment by markmadlangbayan** [comment]
@saghul / @damencho , if this PR gets approved, does this mean there's no need to install prosody from trunk?  We can just install prosody from apt?

**Comment by damencho** [comment]
Not really, there are many other places where we fail with current modules. And this is not completely tested. I will be spending some time on the subject the following days or weeks.

**Comment by damencho** [comment]
Handled in https://github.com/jitsi/jitsi-meet/pull/4071

**Pull request closed without merging**
