### PR TITLE
Updating languages.json with manual variable value sorting

### PR DESCRIPTION
**Pull request by chipechop**
ISSUE: language names are not sorted alphabetically in the drop down language selection menu, in the preferences of the WEB version of jitsi
POSSIBLE SOLUTION: languages.json file could be sorted by variable value (like I did in my pull request), instead of by variable name (like it is now). I know the convention of json files require that the variables are listed alphabetically, but it seems easier to manually sort languages here in github, rather than doing it with code, during execution.

I don't know if this will originate any kind of debate, but I'd choose the "quick and dirty" solution of manual file sorting, like I did.

Cheers

image

### CODE REVIEW

**Comment by saghul** [comment]
Any manual operation is prone to bugs and inconsistencies.

We shall keep the alphabetical sorting based on ISO language name.

**Comment by chipechop** [comment]
> We shall keep the alphabetical sorting based on ISO language name.

I understand, but the language order in the APP should then be sorted programmatically... the sorting now, is pretty messy...

**Comment by saghul** [comment]
A patch for that would be most welcome!

**Comment by chipechop** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I can't code :'(                                                                                                                                                                                                                                                                                                                        Da: ***@***.***: 16 Aprile 2022 08:00A: ***@***.*** a: ***@***.***: ***@***.***; ***@***.***: Re: [jitsi/jitsi-meet] Updating languages.json with manual variable value sorting (PR #11389)  
A patch for that would be most welcome!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Pull request closed without merging**
