### PR TITLE
WIP fix(sounds): sound files not being loaded in release build

### PR DESCRIPTION
**Pull request by paweldomas**
This is work in progress. What sucks about this fix is that we have to copy and duplicate sound files. In addition to that the iOS fix is probably not acceptable, because the sounds are in the app project and not in the sdk. I haven't figured out how to solve this problem yet. There must be a flag or something, but I don't know those build system good enough.

### CODE REVIEW

**Comment by saghul** [comment]
> In addition to that the iOS fix is probably not acceptable, because the sounds are in the app project and not in the sdk.

Yeah, I think this is a no-no.

> haven't figured out how to solve this problem yet. There must be a flag or something, but I don't know those build system good enough.

In iOS, you'd need to get the SDK bundle. Here is how we do it for other files: https://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/RCTBridgeWrapper.m#L65 There is no JS method to get it, so maybe it needs exporting.

As for the file location, I think the files could be copied at build time, instead of duplicating them in the source tree. I think think we already have similar cases, with the ip.txt file for example. Ping me if you need help!

**Comment by paweldomas** [comment]
Here's some progress for the iOS. I've added a native method to get the SDP bundle's path. Currently it's in AppInfo module, but could be somewhere else - I'm open for suggestions if we decide to go this way.

On iOS there's no need to copy the files - it's enough to add them to the SDK project file and they will be bundled.

So currently the only problem seems to be that sound files are duplicated in res/raw folder of Android SDK. I've tried to copy them on build time to different places, but they are not included in the merge if there's no reference in the R class. And for that to appear it must be in the resources folder, before the sources are compiled. It's possible to add another directory for resources, but then it's structure needs to follow Android's resource scheme and currently the sounds folder does not.

Another solution would be to copy those files to the sdk resources dir just, before the build starts and delete afterwards, but it's kind of hacky.

Yet another way would be to copy files to assets dir like the fonts, but then we'd have to modify 'react-native-sounds' lib, as it currently does not support playing from assets.

https://github.com/zmxv/react-native-sound/blob/master/android/src/main/java/com/zmxv/RNSound/RNSoundModule.java#L149

https://stackoverflow.com/questions/16795600/can-you-play-a-mp3-file-from-the-assets-folder

**Comment by paweldomas** [comment]
> Actually it does support playing from the assets (stupid me):

So it is not supported by the version we use. I'll try to update.

**Comment by paweldomas** [comment]
new version https://github.com/jitsi/jitsi-meet/pull/2736

**Pull request closed without merging**
