### PR TITLE
Fixing some of security issues of js libraries

### PR DESCRIPTION
**Pull request by N-M**
Security issues fixed with `npm audit fix` command

### CODE REVIEW

**Comment by saghul** [comment]
can you please pin webpack to a specific version? we don't use `^`

**Comment by N-M** [comment]
> can you please pin webpack to a specific version? we don't use `^`

fixed

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by N-M** [comment]
Closing this since I am not sure why Jenkins test are failing.I will open a new PR after an investigation.

**Pull request closed without merging**
