### PR TITLE
fix(debian) skip all configuration with non interactive Debian frontend

### PR DESCRIPTION
**Pull request by saghul**
This is the case of Docker, for example, so this would allow us to
remove some hacks.

### CODE REVIEW

**Comment by damencho** [comment]
Why only in this postinist is the problem?

**Comment by saghul** [comment]
Because it's the place where we ask interactive questions to the user. If we have more places like this, applying the same logic would be desirable too!

**Comment by damencho** [comment]
Almost most of the post inst scripts have it, across all projects with debian package. 
Strange it fails with docker, I've been using this noninteractively in many occasions without a problem.

**Comment by damencho** [comment]
Wait, but this logic will break all installations that depend on noninteractive use of the scripts.

**Comment by saghul** [comment]
Good point. I'll try again, maybe I don't need this after alll...

**Comment by damencho** [comment]
This recipe is working fine for me

```
DEBIAN_FRONTEND=noninteractive apt-get install -q -y -o Acquire::ForceIPv4=true -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" jitsi-meet
```

**Comment by saghul** [comment]
Good stuff! I'll give that a try!

**Comment by saghul** [comment]
Confirmed we don't need this!

**Pull request closed without merging**
