### PR TITLE
These optimizations help improve the code's readability, reduce unnecessary lines

### PR DESCRIPTION
**Pull request by vempatisaivishal**
…essary lines, and ensure consistent style and structure. They also provide a more concise implementation without changing the functionality or behavior of the original code

### CODE REVIEW

**Comment by vempatisaivishal** [comment]
These optimizations help improve the code's readability, reduce unnecessary lines, and ensure consistent style and structure. They also provide a more concise implementation without changing the functionality or behavior of the original code

**Comment by vempatisaivishal** [comment]
can any one review the code so that I can merge the code

**Comment by saghul** [comment]
You removed all the comments, that's not ok.

**Comment by vempatisaivishal** [comment]
> You removed all the comments, that's not ok.

thanks a lot for your reply I will change the code

**Comment by vempatisaivishal** [comment]
added comments

**Comment by vempatisaivishal** [comment]
now add necessary interFaceConfig variable and reduced the length to 120 which was exceeded in previous code

**Comment by saghul** [comment]
Sorry but at this point your changes just add churn without added value.

interfaceConfig is a global we inject, for example.

**Pull request closed without merging**
