### PR TITLE
update uuid package to 8.3.2

### PR DESCRIPTION
**Pull request by pcvengros**
Currently used uuid@3.1.0 is outdated. As stated from author: Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.

### CODE REVIEW

**Comment by damencho** [comment]
And it failed to build...

**Comment by pcvengros** [comment]
yes, I did, double checked it. I am getting and error while running app on emulator:
[in strophe.js] TypeError: undefined is not an object (evaluating '_uuid.default.v4')
So far no luck on fixing.

**Comment by saghul** [comment]
Looks like an import error. The package structure has changed since v3, you need to adjust to the new one.

**Comment by saghul** [comment]
I don't think webpack is doing any vodoo :-) Use 2) and let's see what the linter has to say.

**Pull request closed without merging**
