### PR TITLE
chore(deps): update package-lock and package.json

### PR DESCRIPTION
**Pull request by virtuacoplenny**

### CODE REVIEW

**Comment by bbaldino** [comment]
this diff shouldn't include the removal of the button group from package lock, right? that's another pr?

**Comment by virtuacoplenny** [comment]
I combined them into one PR but left them as two commits. I didn't feel like making another PR for a separate package-lock updates.

**Comment by bbaldino** [comment]
ok, ready to merge then?

**Comment by virtuacoplenny** [comment]
Yeah, should be okay to go. The button-group removal from package-lock.json was missed from a previous package.json update that...well, removed button group. The lib-jitsi-meet update, with package-lock.json update, should resolve some audio output selection issues (or so I pray).

**Pull request merged**
