### PR TITLE
fix (external-api): fix notify video mute changed when presenting

### PR DESCRIPTION
**Pull request by horymury**
- small refactor to trigger `notifyVideoMutedStatusChanged` correctly when participant is presenting

@hristoterezov

### CODE REVIEW

**Review by saghul — APPROVED** [review]
LGTM

**Comment by izakgl** [comment]
Does this fix issue #7971? @horymury

**Comment by horymury** [comment]
@izakgl  yep it should fix it, though the behavior I noticed was a bit different: `notifyVideoMutedStatusChanged` was not triggered at all when participant was screen sharing. After my change it triggers and with correct `muted`  value.

**Comment by izakgl** [comment]
@horymury I checked and I confirm it works as intended now. Thank you!

**Comment by horymury** [comment]
> @horymury I checked and I confirm it works as intended now. Thank you!

glad to hear, thanks for confirming!

**Pull request merged**
