### PR TITLE
fixed issue #6393

### PR DESCRIPTION
**Pull request by DipanshiB**
Added in prompt on homepage regarding how to start a meeting. 
However the prompt has only been added to main.json and main-enGB.json files. Please add in the translations for other languages. 
Screenshot from 2020-06-02 15-36-59

### CODE REVIEW

**Comment by luixxiul** [comment]
@DipanshiB did you close this PR intentionally? thanks!

**Comment by DipanshiB** [comment]
> @DipanshiB did you close this PR intentionally? thanks!

Yes actually, I forgot to add in the name of my co-author. So I would need to re-commit the changes.

**Comment by luixxiul** [comment]
Actually you did not have to close the PR since you could simply run `git commit --amend && git push -f`to force push the amended commit ;-)

**Comment by DipanshiB** [comment]
Amended the commit, thank you :)

**Comment by DipanshiB** [comment]
@luixxiul Thank you, I've amended the commit :)

**Comment by DipanshiB** [comment]
@jitsi-jenkins I have signed the CLA. Please check and let me know.

**Comment by luixxiul** [comment]
I think it is appreciated to sort strings alphbetically on the JSON files.

**Comment by DipanshiB** [comment]
@luixxiul I've sorted them into alphabetical order

**Pull request closed without merging**
