### PR TITLE
Update Voice - Video toggle design, closes [#7087]

### PR DESCRIPTION
**Pull request by 532910**

### CODE REVIEW

**Comment by 532910** [comment]
Signed!

**Comment by saghul** [comment]
Sorry I missed this one. We made it that way so you can also tap "next" to it.

**Comment by 532910** [comment]
But the issue isn't fixed.

**Comment by saghul** [comment]
Changing the order after having it that way for literally years would confuse everyone. It may not be perfect but it is what it is.

With the introduction of navigation we are closer than ever from implementing the prejoin page and then it will disappear for good.

**Comment by 532910** [comment]
> With the introduction of navigation we are closer than ever from implementing the prejoin page and then it will disappear for good.

Nice!

BTW, the current Video/Voice switch is pretty weird: it is actually "low bandwidth mode" toggle not "video mute" as you would expect. If I join in `Voice` mode and disable "low bandwidth mode" lately camera will be turned on, which is very unexpected!

**Comment by saghul** [comment]
That's an unfortunate side effect of the audio-only mode becoming really a low-bandwidth mode.

We also need to modify that control to be a slider like on the web...

**Pull request closed without merging**
