### PR TITLE
Ignore ios/Pods

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by lyubomir** [comment]
I'll sit on this one more day because I'm thinking: `pod install` introduces 2 modifications visible through `git status` and the ignoring of `ios/Pods` hides merely 1 of the 2 but still leaves the modifications to `ios/jitsi-meet-react.xcodeproj/project.pbxproj` to attract the developers attention. After ignoring `ios/Pods` I'm more inclined to see modifications to `ios/jitsi-meet-react.xcodeproj/project.pbxproj` and assume that they were not introduced by `pod install`.

**Comment by saghul** [comment]
Hum, I thought those changes were introduced by me opening the wrong file with Xcode.  I'll have another look tomorrow.

**Comment by saghul** [comment]
@lyubomir I updated this PR by adding a commit with the changes to the project file.  IMHO it's a good idea to have them because this way we'll have a clean tree after `pod install`.  I know it's a bit of churn, but I see no way to avoid it... at least it's contained in a file we don't regularly modify and it shouldn't create conflicts.

**Comment by saghul** [comment]
Rebased.

**Comment by saghul** [comment]
Jenkins is happy now.

**Comment by saghul** [comment]
Since we no longer use any CocoaPods I'm closing this for now.  We'll revisit when / if we use CocoaPods again.

**Pull request closed without merging**
