### PR TITLE
Request feedback on hangup from the AOT window

### PR DESCRIPTION
**Pull request by hristoterezov**

### CODE REVIEW

**Comment by virtuacoplenny** [comment]
I don't know much about the flows of api.js... Is it not possible to allow the user of the api to specify what gets passed into the call to APP.conference.hangup?

**Comment by hristoterezov** [comment]
Yes! It is possible but isn't that too specific? And also maybe we want the feedback always?

**Comment by virtuacoplenny** [comment]
Could you confirm then that the UX is to always show the feedback for filmstrip only after hangup?

**Comment by hristoterezov** [comment]
For filmstrip only we never show this dialog no matter of the passed arguments to APP.conference.hangup or other settings. But I don't think this is related to our public interface or the argument. As far as I know we don't have design for this dialog for filmstrip only but maybe in future we'll implement it and start showing it even for filmstrip only.

If you prefer I can add a parameter to the API command. Although I think there was a way to stop the feedback from showing with config options (but I'm not totally sure).

On the other hand I was just trying to mimic the hangup button behavior here.

So do you want me to do any changes?

**Pull request merged**
