### PR TITLE
Adding sq translation

### PR DESCRIPTION
**Pull request by ujdhesa**
Here you are the files to add Albanian translation to the project.

TIA

### CODE REVIEW

**Comment by ujdhesa** [comment]
Hello!
I don’t plan to sign any CLA.
I’d appreciate if someone able to do it (who has signed CLA) make a fork of my translation and add sq to the project.
TIA

**Comment by damencho** [comment]
> Hello!
> I don’t plan to sign any CLA.
> I’d appreciate if someone able to do it (who has signed CLA) make a fork of my translation and add sq to the project.
> TIA

No worries. 

You need to add your language to languages.json wit the English name in order to activate it

**Comment by ujdhesa** [comment]
@damencho  Many thanks!

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by damencho** [comment]
Jenkins, test this please

**Review by damencho — APPROVED** [review]

**Pull request merged**
