### PR TITLE
Added Turkish language on BuiltinLanguages.native.js

### PR DESCRIPTION
**Pull request by ferdibayrak**
Added Turkish lang

### CODE REVIEW

**Comment by ferdibayrak** [comment]
We have signed the CLA. Please check: #5876

**Comment by ferdibayrak** [comment]
Waiting for your response." @jitsi-jenkins @damencho

**Comment by damencho** [comment]
Could you please fix the conflicts, thanks.

**Comment by ferdibayrak** [comment]
What should we do my friend?

**Comment by damencho** [comment]
Fix this conflict:
image
There is a Resolve button to help you fix it.

**Comment by ferdibayrak** [comment]
Resolved. Please check. @damencho

**Comment by ferdibayrak** [comment]
The Jitsi Meet iOS app still doesn't show Turkish strings. What am i missing? @damencho @saghul @jcfischer

**Comment by damencho** [comment]
It needs to be updated... We need to push new version and wait for apple to approve it ... You will get it in few weeks.

**Comment by ferdibayrak** [comment]
Actually we mean an app with Jitsi iOS SDK. @damencho

**Pull request merged**
