### PR TITLE
[RN] Update React Native to version 0.51.0

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
Jenkins, please test.

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by saghul** [comment]
Hum, I cannot repro the problem locally... any idea @damencho ?

**Comment by damencho** [comment]
Maybe we need to clean node_modules on the PR machine? I've been seeing this at some point using an older version of lib-jitsi-meet with newer jitsi-meet (or the other way around, do not remember).

**Comment by saghul** [comment]
@damencho Sound about right.  We now need a new flow version, which this PR updates as a dependency.

**Comment by damencho** [comment]
Yep, it failed again:
17:17:24 Launching Flow server for /home/jenkins/jitsi-meet/node_modules/lib-jitsi-meet
17:17:24 Wrong version of Flow. The config specifies version ^0.56.0 but this is version 0.57.3

Is the flow updated in lib-jitsi-meet? Apparently the update should happen in both places.

**Comment by saghul** [comment]
Ah, FML, let me fix that.

**Comment by saghul** [comment]
https://github.com/jitsi/lib-jitsi-meet/pull/683

**Comment by saghul** [comment]
@damencho Thanks for the pointer, I made the corresponding PR, hopefully it works now!

**Comment by saghul** [comment]
Please hold this, looks like 52 is out and it should have Fragment support so we can also delete some code. I missed the fact that 52 was out, somehow :-(

**Comment by saghul** [comment]
So, looks like 0.52.0 *no es bueno*, there are 2 showstoppers: https://github.com/facebook/react-native/issues/17274 and https://github.com/facebook/react-native/issues/17027

I suggest we land this and wait for 0.52 to be ready, because there is an issue we are already running into, which 0.51 fixes: https://github.com/facebook/react-native/commit/f2c6877b91963878f36ec42f5f865427bc69488c#diff-e40bcf61507821200dcf1f573eb717e3

**Comment by saghul** [comment]
@lyubomir @paweldomas PTAL.

**Pull request merged**
