### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by sliard**
Hi,

I have spent a lot of time to make jitsi-meet work and I noticed some update to do on documentation.
I hope it helps :)

Samuel

### CODE REVIEW

**Comment by cmrd-senya** [comment]
I performed installation myself and may confirm the changes here are required for a proper installation

**Comment by bgrozev** [comment]
@sliard I'd like to merge the documentation update. Could you please split it from the jquery modification? Also, if you haven't already done so, please sign our CLA ([individual](https://jitsi.org/icla) or [corporate](https://jitsi.org/ccla))

**Comment by sliard** [comment]
@bgrozev done (for split and sign your CLA)

**Comment by cmrd-senya** [comment]
@bgrozev, could this one be merged please?

**Comment by bgrozev** [comment]
Yes, thanks for the reminder. I pushed a rebased version.

**Pull request closed without merging**
