### PR TITLE
Add Lithuanian (lt) translation

### PR DESCRIPTION
**Pull request by Baltix**
Please add Lithuanian translation. Translated by me - Mantas Kriaučiūnas (Baltix) and friend Raminta Stasaitytė :)

### CODE REVIEW

**Comment by damencho** [comment]
Please drop countries-lt.json from your PR.

**Comment by damencho** [comment]
Thanks. Those files are already available in one of the dependencies we use and are extracted from there and put in the binary installation package automatically.

**Comment by Baltix** [comment]
@jitsi-jenkins @damencho I've signed https://jitsi.org/icla for individuals but get strange response after signing - I was redirected to https://www.8x8.com/products/docusign-thank-you?env=e82053f3-6671-4331-a540-2841e829ae68&pf=2fbd46b1-ed23-46a3-a57e-c7c0005544ca&r=72f36e8e-0da3-49aa-99a0-dc6c9f4ecc93 
:-/
Btw, I don't understand why I should sign https://jitsi.org/ccla for corporations ?

**Comment by damencho** [comment]
I see your CLA, don't worry and jitsi-jenkins does not check it and may ask you again if you create a PR.

**Pull request merged**
