### PR TITLE
Implement the setVirtualBackground on External API

### PR DESCRIPTION
**Pull request by wguimaraes**
This commit implements access to set the virtual background via the external API command, as shown in the example below. It would be a great help to have this feature implemented in future versions, allowing a meeting to start with a default external or internal virtual background. If there is a better way to achieve this, please let me know:

```
api.executeCommand('setVirtualBackground', {
    backgroundEffectEnabled: true,
    backgroundType: 'image',
    virtualSource: 'https://external.url.image',
    selectedThumbnail: 'https://external.url.image',
    blurValue: 0
});
```

### CODE REVIEW

**Comment by saghul** [comment]
How is this not a duplicate of https://github.com/jitsi/jitsi-meet/pull/15324 ?

**Comment by wguimaraes** [comment]
> How is this not a duplicate of #15324 ?

Hi, today I noticed that an implementation was published three days ago. However, I am still submitting my implementation because I believe it complements the previous one by adding the ability to not only enable/disable background images but also to enable the blur feature independently or apply a blur level to the background image in a single command. If this is redundant, please disregard this pull request. The example is provided below:

```
api.executeCommand('setVirtualBackground', {
    backgroundEffectEnabled: true,
    backgroundType: 'image',
    virtualSource: 'https://external.url.image',
    selectedThumbnail: 'https://external.url.image',
    blurValue: 0
});
```
OR
```
api.executeCommand('setVirtualBackground', {
                    backgroundEffectEnabled: true,
                    backgroundType: 'blur',
                    blurValue: 50
                });  
```

**Comment by wguimaraes** [comment]
> blurValue

Hi again, after reviewing the options, it seems that although the **blurValue** option is present in the **react/features/virtual-background/reducer.ts** interface, it is not being applied to the image. I will investigate this further when I have more time. Once again, if this pull request is too redundant, please feel free to disregard it. Thank you!

**Comment by saghul** [comment]
WQe already have the `'set-blurred-background'` API command. While not ideal, we have people using it, so we cannot remove it now.

The current background API complements that well, so I see no reason to change that.

Thanks a lot for taking the time to send a PR though!

**Pull request closed without merging**
