### PR TITLE
Fix CallStats require and initialize API commands and keyboard shortc…

### PR DESCRIPTION
**Pull request by dwilson6**
…uts in init methods.

### CODE REVIEW

**Comment by hristoterezov** [comment]
Hello @dwilson6 ,

Thank you for the PR. 

Why do we need to initialize API commands and keyboard shortcuts with function call? Have you noticed some issues with the old code? I think the old code is working.

**Comment by dwilson6** [comment]
Sorry, I should have explained that.  I am using parts of jitsi-meet as a library and was running into a case where an error was being thrown when I was requiring those two modules because APP.UI wasn't defined yet (since they cache some UI functions). Moving the code into initialization makes it so the modules can be required in any order and APP.UI just needs to be defined before the module's init method is called.

Also, I just updated my email on the commit to the one on my contributor agreement.

**Comment by hristoterezov** [comment]
I think if you define APP.UI just before require call of the API module it should work for you without the init method. Do you think that will solve the issue for you without the changes? Or you need to use the API module before the initialization of APP.UI?

**Comment by dwilson6** [comment]
Yeah, I could do it that way.  Initially API was being required before APP.UI is defined but I could move around the way things are instantiated (API is required as part of a library which is required in my client) I was just wanting to make API and KeyboardShortcuts more resilient.

**Comment by hristoterezov** [comment]
@dwilson6 That make sense to me. Could you please declare "shortcuts" variable outside of the initShortcutHandlers function (like the declaration of "commands" variable from API.js) because currently it will be visible only in the function body?

**Comment by dwilson6** [comment]
That is done now. It should be good to go.

**Comment by hristoterezov** [comment]
@dwilson6 I have some question about the contributor agreement. Can you contact me private on hristo@jitsi.org?

**Pull request merged**
