### PR TITLE
update main-de.json

### PR DESCRIPTION
**Pull request by qwertiko**

### CODE REVIEW

**Comment by damencho** [comment]
Hwy Are you making changes to main.json?

**Comment by damencho** [comment]
The strings added were dropped from the code.

**Comment by qwertiko** [comment]
Thanks for checking. My mistake, I deleted the redundant entries in main.json and main-de.json.

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
