### PR TITLE
Add a new setting to remove individual sharing features from UI

### PR DESCRIPTION
**Pull request by skolmer**
This adds a new config value to set which sharing features should be displayed in the sharing dialog and on the pre-meeting screen. If this setting is missing completely it will show all the options so it will be a non-breaking change.
```
    /**
     * Specify which sharing features should be displayed. If the value is not set
     * all sharing features will be shown. You can set [] to disable all.
     */
    // SHARING_FEATURES: ['email', 'url', 'dial-in', 'embed'],
```

You can of course still remove `'invite'` from `TOOLSBAR_BUTTONS` to hide sharing features completely.

This PR will fix https://github.com/jitsi/jitsi-meet/issues/8498

### CODE REVIEW

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by damencho** [comment]
Hey, @skolmer have you run that on mobile ... there are few interfaceConfig usages, which I'm not sure are mobile safe?

**Comment by damencho** [comment]
As normally those are guarded like this: https://github.com/jitsi/jitsi-meet/blob/bd5901d59cba368f8453f709f148933dbaeb635b/react/features/notifications/functions.js#L27

**Comment by skolmer** [comment]
> 
> 
> As normally those are guarded like this:
> 
> https://github.com/jitsi/jitsi-meet/blob/bd5901d59cba368f8453f709f148933dbaeb635b/react/features/notifications/functions.js#L27

Just to clarify and because I'm not very experienced with react-native. Is it about the check if `interfaceConfig` is `undefined` - is that even possible? Or is it about ensuring that it returns a boolean in any case?
I only implemented this one for web so I haven't checked it on mobile.

**Comment by damencho** [comment]
interfaceConfig is not defined on mobile. So these settings and logic will be only for web.

**Comment by skolmer** [comment]
> interfaceConfig

**Comment by skolmer** [comment]
> 
> 
> interfaceConfig is not defined on mobile. So these settings and logic will be only for web.

Thanks for clarifying. 👍  I just added a check if `interfaceConfig` is defined so it will not break on mobile.

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by skolmer** [comment]
We just noticed a minor issue in the `DisalInSection` component today. The "more numbers" link is also shown if only one number is present in `_dialIn.numbers`.
If it's ok to you I will add the fix to this PR too but I can of course create a separate PR if you like.

**Comment by damencho** [comment]
Update this one.

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
@skolmer 
Hum seems there is some problem with this PR. One of the test is not enabled for PR testing but just for the test executed on building the packages and it is failing:
```
[11] TestFailure:
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".more\-numbers"}
  (Session info: chrome=88.0.4324.182)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-10-100-4-19', ip: '10.100.4.19', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-74-generic', java.version: '1.8.0_282'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: /tmp/.com.google.Chrome.zyaj30}, goog:chromeOptions: {debuggerAddress: localhost:36281}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 76f04f7c372904bcf8ecb5bcd00...}
Session ID: 76f04f7c372904bcf8ecb5bcd002322b
*** Element info: {Using=class name, value=more-numbers}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByClassName(RemoteWebDriver.java:412)
	at org.openqa.selenium.By$ByClassName.findElement(By.java:389)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at org.jitsi.meet.test.pageobjects.web.InviteDialog.openDialInNumbersPage(InviteDialog.java:65)
	at org.jitsi.meet.test.InviteTest.testViewMoreNumbers(InviteTest.java:99)
```
org jitsi meet test InviteTest-web participant1

The tests are ran against alpha.jitsi.net

**Comment by damencho** [comment]
I think it is maybe due to the last commit.

**Comment by damencho** [comment]
Nope. Its because it is hidden ... not sure what changed in the structure that made it start failing ...

**Comment by skolmer** [comment]
Can you send me the link to the failing test? maybe the test is set up to always check for the "more numbers" link even if there is only one number. I will try to look into it tomorrow.

**Comment by damencho** [comment]
Nope, you can test it yourself. alpha.jitsi.net has multiple numbers configured and the more numbers link is not shown ...

**Comment by damencho** [comment]
I think we don't have those test result publicly available, there are just accessible for the jitsi developers ...

**Comment by skolmer** [comment]
@damencho  I have checked the url and it is definitely showing more than one number, so in your screenshot the "more numbers" link should be definitively visible! https://alpha.jitsi.net/static/dialInInfo.html?room=TenderMaysSmellNear
Can we just role back the last commit of the PR to give me some time to check what went wrong here? I will provide a PR now that reverts those changes. Sorry for the trouble!

**Comment by damencho** [comment]
No worries, don't hurry for reverting, let's see it on Monday.

**Comment by skolmer** [comment]
Wasn't much work. Better to get the test running again until I find the time to get a real look into the cause of the issue. https://github.com/jitsi/jitsi-meet/pull/8697

**Pull request merged**
