### PR TITLE
Close overflow menu drawer when selecting participants option

### PR DESCRIPTION
**Pull request by dnna**
When using the responsive version of jitsi on a small screen, clicking the "Participants" button does not close the overflow menu drawer automatically. This causes the pane to appear behind the menu and causes a very awkward experience where the user has to manually close the menu by clicking outside of it while avoiding accidentally pressing buttons in the participants pane (see screenshot).

This PR fixes this similarly to how other buttons in that overflow menu work (see ChatButton), where it explicitly closes the overflow menu drawer when clicked.

image

### CODE REVIEW

**Comment by saghul** [comment]
Did you sign the CLA?

**Comment by dnna** [comment]
@saghul yeap, I signed it back when I made this PR https://github.com/jitsi/jitsi-meet/pull/13939

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
So sorry this took so long :-/

**Pull request merged**
