### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by neilzone**
Update FAQs to cover common questions from community.jitsi.org

### CODE REVIEW

**Comment by luixxiul** [comment]
I like these changes!

**Comment by luixxiul** [comment]
Hello, I would like to let you know that since the documentation was moved to https://github.com/jitsi/handbook/, I cherry-picked this comment and opened a PR here https://github.com/jitsi/handbook/pull/1 with other commits on documentation. I hope you don't mind. 

This PR should be closed after the PR on the new repository is merged.

Thank you for your commit!

**Comment by luixxiul** [comment]
@neilzone your work was successfully merged and available on live here: https://jitsi.github.io/handbook/docs/faq. Thanks again.

I found an issue on the page (`"secure domain" configuration` is not treated as a link due to a whitespace). Later I would create a follow-up PR over there.

**Comment by neilzone** [comment]
Thanks @luixxiul — the new documentation system looks great.

**Comment by luixxiul** [comment]
The link error has been taken care of.

**Pull request closed without merging**
