### PR TITLE
Update the Czech translation

### PR DESCRIPTION
**Pull request by mrksu**
I'm working on updating the Czech translation, which is missing many strings. I'm opening this PR in advance as a work in progress so that you're aware.

I've already signed the contributor license agreement.

For now, I'm creating many small commits but I can squash them later if you prefer.

### CODE REVIEW

**Comment by mrksu** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Signed.

**Comment by mrksu** [comment]
Hi @saghul or anybody else from the Jitsi team,

Could you please approve this update to the Czech translation that I've just finished? It adds many strings that were previously untranslated.

There are 22 commits on the branch now but if you'd like, I can squash them.

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by mrksu** [comment]
Hi @damencho, is there anything else I can do to finish this PR? Just checking if it's on the right track :-)

**Review by damencho — APPROVED** [review]

**Comment by mrksu** [comment]
Thanks!

**Pull request merged**
