### PR TITLE
feat(reservations): adds option to allow mail_owner aware reservation backends

### PR DESCRIPTION
**Pull request by stefanplk3**
adds reservations_mail_owner_aware option to reservations plugin to allow mail_owner aware reservations

By default the system assumes that the reservation backend returns the same HTTP response code regardless of the mail_owner for a given room name.

With this pull request the reservation system can handle user/room combinations. So "user1" get's access to room "room1" while "user2" gets access denied (if the reservation system says so). It preserves the current behavior as default (reservations_mail_owner_aware = false).

### CODE REVIEW

**Comment by shawnchin** [comment]
Haven't had a chance to look at the implications in details, but my concern is what might happen when multiple users attempt to join at about the same time. From a quick glance, my suspicion is that it is going to end up issuing multiple API calls; and since `reservations[room_jid]` is being replaced by latter calls, things could get messy as the different responses come back - context from previous calls are lost, and all handlers are operating on the same reservations object.

Have you had a chance to test that scenario? Perhaps by slowing down the API responses then attempting multiple simutaneous joins?

There's been some discussion about supporting mail_owner like how jicofo used to -- https://github.com/jitsi/jitsi-meet/issues/10947#issuecomment-1217153133 -- but alas I've never had the chance to revisit this.

**Comment by damencho** [comment]
Apparently we posted at the same time :) Thanks @shawnchin for looking into it.

**Comment by stefanplk3** [comment]
@shawnchin Good point, you could be right. I will check it. Perhaps we can prevent it with changing the keys of reservations to concat (room_jid .. creator_jid).

**Comment by shawnchin** [comment]
> changing the keys of reservations to concat (room_jid .. creator_jid).

Problem with that is you now lose the queue/cache mechanism since each join would  reference a different reservations object. This would also mess up with the room-destroyed handlers and duration timers that would also reference by room_jid.

---

There is certainly value in making this work. But I suspect it might need a much bigger refactor. As a rough sketch, we might still want to index reservation data by room_jid and queue requests as we do now, but we could do differently is:
* When API response comes back with rejection, rather than marking room as rejected for all, we first check the queue
    * if queue empty, continue with rejection
    * if queue has other users also attempting to create room, do not reject yet and instead reissue API call for next user in line
    * if any API call returns approval, allow everyone in. 
    * if requests for all users in the queue are rejected, then we reject all
* Once rejected, we should now delete reservations object rather than cache it so we behave consistently and reissue API calls even another user comes along and attempts to create room with their credentials.

The implications of this would be that, on a busy service, we are making a lot more API calls. A long queue for the same room would also mean the first joiner would have to wait a long time to see the rejection. There are some trade-offs and optimisations we can make to alleviate this, but perhaps too soon to go down this route :)

**Pull request closed without merging**
