### PR TITLE
fix(keyboardshortcut) spacebar release mutes participant

### PR DESCRIPTION
**Pull request by Calinteodor**

### CODE REVIEW

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Unrelated test failed, and we see that failure with FF from time to time, merging.

**Comment by skolmer** [comment]
@damencho What was the reasoning behind this change? Unfortunately it breaks the accessibility changes we did and now it is back to push-to-mute. So it mutes you when you trigger an element (button, dropdown, ..) with space.

**Comment by damencho** [comment]
Request by product that this should not be changed because of privacy concerns. People are used to just push space and without knowing whether they are muted or not they will be sure that they are muted and this was the use-case which is broken and could lead to huge implications for people.

**Comment by damencho** [comment]
> So it mutes you when you trigger an element (button, dropdown, ..) with space.

If there is no way of fixing that, we need to add a shortcut that will enable accessibility and toggle between both. When accessibility is turned on space will not function as push to talk and the other way around.

**Comment by skolmer** [comment]
So you mean people got used to the old behavior that a press on the space-bar will mute them? Hmm.. that's unfortunate. We also added a setting to disable all keyboard shortcuts though, so maybe we can communicate this option more prominent as accessibility solution?

**Comment by damencho** [comment]
Well

> We also added a setting to disable all keyboard shortcuts though, so maybe we can communicate this option more prominent as accessibility solution?

Well, isn't having the keyboard shortcuts making things more accessible? Clicking m to mute unmute is easier than going with the tab through all the buttons ... that's my point of view which can be wrong ... 

But the advice from product is to have a shortcut turning it(accessibility) on/off ... you can come to the community call in 3 hours if you want to bring it up so we can discuss it live.

**Comment by skolmer** [comment]
ok cool, I will join with a colleague. 10:30AM CST right?

**Comment by damencho** [comment]
Yes.

**Comment by skolmer** [comment]
> 
> 
> Yes.

Sorry, looks like I made the wrong time conversion and missed it by an hour. If you like we can schedule a meeting for this or move the conversation to the community forums. 

Basically you are right and shortcuts can make the application more accessible. The main issue here is that the global shortcuts of jitsi collide with default shortcuts of the browser elements and screen reader software so they will confuse screen-reader users. Here is a good overview of the keyboard shortcuts that are used by the most popular screen readers https://dequeuniversity.com/screenreaders/survival-guide#desktop-survival-guide-shortcut-keys If you compare it to the jitsi shortcuts you will see a lot of overlapping like F, T, SPACE, 1-6. SPACE is especially critical because it is used by a lot of input elements.

**Comment by damencho** [comment]
> Basically you are right and shortcuts can make the application more accessible. The main issue here is that the global shortcuts of jitsi collide with default shortcuts of the browser elements and screen reader software so they will confuse screen-reader users. Here is a good overview of the keyboard shortcuts that are used by the most popular screen readers https://dequeuniversity.com/screenreaders/survival-guide#desktop-survival-guide-shortcut-keys If you compare it to the jitsi shortcuts you will see a lot of overlapping like F, T, SPACE, 1-6. SPACE is especially critical because it is used by a lot of input elements.

So this is one more vote for a global shortcut for enable/disable accessibility which will disable some of the global shortcuts in order for the screenreader one to work ... If I'm not wrong same is in windows maybe and mac, there was a key that if you hold for few seconds and you turn on screenreader ...

**Comment by henningoschwald** [comment]
As a blind Jitsi user I rely on consistent and deterministic keyboard behavior. After the recent changes the space bar either works as push-to-talk or toggles a button, depending on whether a button is focussed or not, which is inconsistent.

I use push-to-talk a lot, but with the current behavior I can not be sure whether I am transmitting or not when pressing the space bar or if this triggered an unwanted action instead, which makes push-to-talk unusable for me. With pressing space I must be sure I am transmitting and when releasing space I must be sure to be muted again, especially because there is no immediate indication whether I am transmitting or not for screenreader users.

So please restore the previous behavior where the enter key interacts with the focussed control element and the space bar is used for push-to-talk. This worked perfectly reliable during the last months and I never had the issue of pressing space and wondering why the focussed control wasn't triggered.

**Comment by damencho** [comment]
@skolmer ^

**Comment by skolmer** [comment]
@henningoschwald Thanks for your valuable feedback. While understanding your arguments to have a consistent behavior throughout the application I have some mixed feelings regarding web standards. 
Jitsi uses some standard elements like buttons or radio lists which should have space-bar support. Removing space-bar support here would mean breaking web standards (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role). So it will then be consistent within Jitsi but not for web-applications in general.
Either way we need a some more consistent behavior. 
I was thinking about an accessibility mode that you can activate in the settings dialog which maps push to talk to another key so it doesn't interfere with the behavior of standard elements.

**Pull request merged**
