### PR TITLE
Add indicator for moderators to participants pane

### PR DESCRIPTION
**Pull request by nbeckindy**
Adds the star icon to indicate who are moderators in the participants pane. Placed to the left so that the video and audio states remain lined up.

### CODE REVIEW

**Comment by damencho** [comment]
Can you add a screenshot. 
Are the changes considering https://github.com/jitsi/jitsi-meet/blob/e2443f8d010dd5349b4dd07fd2d8c77ca94c5230/interface_config.js#L42 to hide it?

**Comment by damencho** [comment]
Hum, I don't think we show the stars on mobile, right? @saghul

**Comment by damencho** [comment]
Ahaa we do not show it if everyone is moderator ... so we must keep that behavior on mobile.

**Comment by saghul** [comment]
> Hum, I don't think we show the stars on mobile, right? @saghul

We do, if you long press on a participant and click on the "Connection Info" button.

**Comment by nbeckindy** [comment]
Thanks for the feedback! I added a commit which should respect DISABLE_FOCUS_INDICATOR and all users being moderators on native devices.

Here are a couple screenshots, one from the browser and one on native (iOS).

Screen Shot 2021-09-19 at 6 46 55 PM

Screen Shot 2021-09-19 at 6 47 08 PM

**Comment by saghul** [comment]
We already have a moderator indicator in master now, with a written "Moderator" subtext.

**Comment by saghul** [comment]
I asked design if we want to incorporate the icon, which I believe we don't. I has always been confusing...

**Pull request closed without merging**
