### PR TITLE
[Android] Fix crash if settings activity cannot be opened

### PR DESCRIPTION
**Pull request by saghul**
The documentation states this is possible, so make sure we handle such errors.

Ref:
https://developer.android.com/reference/android/provider/Settings.html#ACTION_APPLICATION_DETAILS_SETTINGS

### CODE REVIEW

**Comment by saghul** [comment]
@paweldomas I have no way to test it since it seems to be device specific, I made the patch based on a crash dump + reading the docs. It compiles though!

**Comment by paweldomas** [comment]
If the exception matches the one from the crash dump I guess it's fine

**Comment by paweldomas** [comment]
I'd say we return boolean from the "open" method and do something, show error message at least

**Comment by saghul** [comment]
@paweldomas Updated, PTAL.

**Pull request merged**
