### PR TITLE
fix(i18n) fix some country names

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by damencho** [comment]
Why?

**Comment by damencho** [comment]
I saw it.

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Can you also sent a PR to the library, the previous time we had such an issue, they fixed it and released a new version.

**Comment by saghul** [comment]
They explicitly rejected this change in the past because that's the actual ISO code for the country 🤷

**Pull request merged**
