### PR TITLE
feat(recording) - Show recording started notification to the initiator

### PR DESCRIPTION
**Pull request by saygun**
**Problem**
---
I have disabled recording notification sounds ("Recording is on / Recording is off") by using `disableRecordAudioNotification` in `config.js`. So whenever the user starts recording other participants in the meeting is seeing a notification on the left that says 
`{{participantName}} started the recording`. However, the initiator is not seeing any notification because `lib-jitsi-meet` is firing `RECORDER_STATE_CHANGED` event with `recorderSession` object and that object looks like this:
```
{
  ...,
  initiator: undefined,
  terminator: undefined,
  ...,
}
```

So as a result, when sounds are disabled, the initiator is not seeing any feedback rather than a red icon appears on the right.
The same thing doesn't happen when the initiator stops the recording, a "Recording stopped" notification is being rendered.

**Expected Behavior**
---
It would be good to show more visible feedback when the user starts the recording when `disableRecordAudioNotification` is being set to `true`. 

**Possible Solution**
---
As it is already featured for showing stopped recording notification, we could do the same thing.
```javascript
// react/features/recording/actions.any.js
export function showStoppedRecordingNotification(streamType: string, participantName?: string) {
    const isLiveStreaming
        = streamType === JitsiMeetJS.constants.recording.mode.STREAM;
    const descriptionArguments = { name: participantName };
    const dialogProps = isLiveStreaming ? {
        descriptionKey: participantName ? 'liveStreaming.offBy' : 'liveStreaming.off',
        descriptionArguments,
        titleKey: 'dialog.liveStreaming'
    } : {
        descriptionKey: participantName ? 'recording.offBy' : 'recording.off',
        descriptionArguments,
        titleKey: 'dialog.recording'
    };

    return showNotification(dialogProps, NOTIFICATION_TIMEOUT);
}
```
```javascript
// react/features/recording/middleware.js
...
if (initiator) {
  const initiatorName = initiator && getParticipantDisplayName(getState, initiator.getId());
                    
  initiatorName && dispatch(showStartedRecordingNotification(mode, initiatorName));
} else if (typeof recordingLimit === 'object') {
  // Show notification with additional information to the initiator.
  dispatch(showRecordingLimitNotification(mode));
}
...
```
The above check could be removed and it could be like this:

```javascript
if (typeof recordingLimit === 'object') {
  // Show notification with additional information to the initiator.
  dispatch(showRecordingLimitNotification(mode));
} else {
  dispatch(showStartedRecordingNotification(
      mode, initiator && getParticipantDisplayName(getState, initiator.getId())));
}
```

So in this way, other users will be seeing `{{participantName}} started the recording` and the initiator will be seeing `{{recording.on}}`. I did not modify language files. As far as I could see `recording.on` is defined but never used. If you guys confirm this feature, I think it would be better to change its value to `Recording started` same logic as `recording.off`

What do you guys think about it?

### CODE REVIEW

**Comment by saygun** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Okay, dear bot. I signed the CLA.

**Comment by damencho** [comment]
Looks good with one comment, the notification will look weird with the same Title and description. Have you tried not passing any description and just showing the title, does that work?

**Comment by saygun** [comment]
> Looks good with one comment, the notification will look weird with the same Title and description. Have you tried not passing any description and just showing the title, does that work?

Without `description` it looks like this:
Screen Shot 2021-01-07 at 6 55 33 PM

@damencho What do you think? Shall I update the localization files (`recording.on => "Recording started"`) or just pass an empty description?

**Comment by damencho** [comment]
Yep, change them. Can you check whether those are used somewhere else?

**Comment by saygun** [comment]
> Yep, change them. Can you check whether those are used somewhere else?

Sure. The last time I checked it, that key (`recording.on`) wasn't used anywhere but I am gonna double-check it.

**Comment by saygun** [comment]
I translated `recording.on` language key by using a script that sends a request to Google Translator API. Unfortunately, the below languages couldn't be found in Google Translate API, so I left those untouched.

`kab => Kabyle `
`sc => Sardinian`
`oc => Occitan`

I used `JSON.stringify(content, null, 4);` so that causes some indentation change in the files.
@damencho Please share your concerns. Thank you.

**Comment by damencho** [comment]
Please, change only the English one and the languages you speak, don't try to translate it everywhere and drop those changes, sorry for the trouble. Normally when we have the translation system in place, that update in the main language will show to all other translators that this needs to be changed.

**Comment by saygun** [comment]
No worries. I will revert it

**Comment by saygun** [comment]
@damencho Done it 👍

**Comment by damencho** [comment]
What about         "on": "Live Streaming", ?

**Comment by saygun** [comment]
@damencho You are totally right. I also added one more commit that updates the `liveStreaming.on` language key

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Pull request merged**
