### PR TITLE
fix: Fixes #10796 authentication in conference.

### LINKED ISSUE #10796: User authentication during a conference not working
### Description:

Guests cannot authenticate during a conference to get moderator rights.

### Steps to reproduce:

(I hope the labels for the buttons are correct - we are not using english for our installation.)
1. During a conference open the Settings dialog
2. In tab Profile and click the Login button
3. Enter your credentials
4. Sign in

### Expected behavior:

Sign in and get moderator rights.

### Actual behavior:

No sign in happens and no moderator rights are granted. You can retry it multiple times.

### Server information:

- Jitsi Meet version: docker-jitsi-meet stable-6726-1
- Operating System: Ubuntu 18.04 LTS

### Client information:

- Browser / app version: recent versions of Google Chrome and Firefox
- Operating System: Windows 10 / Fedora 35

### Additional information:

Log output in the developer-console:
2022-01-17T09:47:57.656Z [modules/xmpp/xmpp.js] <P.connectionHandler>:  My Jabber ID: _correct jabber id_/_some token_?

We use the internal authentication - not ldap.

### PR DESCRIPTION
**Pull request by damencho**

### CODE REVIEW

**Comment by gpatel-fr** [comment]
You are totalling secure domain functionality with this change. Login is stuck in a loop.
FYI the 'AuthRequired' weirdness is because when this routine is entered the first time after connecting to a secure domain, the state['features/base/conference'] don't hold a conference object, it is only holding a 'AuthRequired' object that is really the conference. So with your change the conference returned by MapStateToProps is undefined. It's strange and -of course- unexplained by any comment, but it is like that.

**Comment by saghul** [comment]
Thanks for testing this @gpatel-fr.

Indeed we represente the conference state by storing the conference object under different property names in Redux. For example, the property "joining" is the conference object, while joining.

So in this case authRequired is set when joining fails with an authentication required error.

**Comment by damencho** [comment]
Interestin, I was testing it yesterday and was able to join as moderator and as guest and this was fixing the issues for me. Maybe I'm missing some case.

**Comment by gpatel-fr** [comment]
I wiped everything, git cloned new jitsi-meet and lib-jitsi-meet, linked the two, make dev -> I can connect with my server all right.

After applying the patch, I get a loop on authentication (the auth window is displayed again and again).

Looking at the behaviour in the Chrome debugger:

- before the change: on initial login it was the authenticateAndUpgradeRole that was called and in the currently failing case of authentication of an unlogged in user, the second branch was taken, authentication was succeeding on connect and nothing more happened (onSuccess being undefined)

- with the change, at initial login it's the second branch that is taken (since conference is null now), and the same behaviour happens but on the initial login.

**Comment by damencho** [comment]
Yep, I have now the not working case.

**Comment by saghul** [comment]
@damencho I pushed a fixup commit, which fixes login on both cases for me. You can test against `meet.<my nickname>.net`.

The trick is to use either `authRequired` or `conference` as the reference to the conference object. The former will exist when you need to login before join, the latter after you join.

@gpatel-fr If you have some time to double-check that would be appreciated.

**Comment by gpatel-fr** [comment]
@saghul 
yes it works ! thanks :+1: 

There is just a remaining detail: what about the code in OnLogin ? it seems that now the branch
```
  } else {
            this.setState({
                loginStarted: true
            });

            connect(jid, password, roomName)
                .then(connection => {
                    onSuccess && onSuccess(connection);
                })
                .catch(() => {
                    this.setState({
                        loginStarted: false
                    });
                });
```
will never be taken, and (as well as the 'OnSuccess' const) could be removed.

Basically OnLogin is now just an unconditional call to authenticateAndUpgradeRole.

**Comment by saghul** [comment]
Thanks for testing!

We do have a case for the else branch IIRC. There is a slight difference between supporting guests and not supporting them. When no guests are supported the connection cannot be created so it's created from within that very dialog.

I'll look into the ending the conference part, that's not great.

**Comment by saghul** [comment]
Alright, pushed another fixup. Basically, we will no longer go back to the welcome page if we are already in the conference, which is the case if we are authenticating from within.

**Comment by damencho** [comment]
Tested works on my end. Thank you @saghul as I had created the PR can you approve your changes :)? So we can merge it

**Review by saghul — APPROVED** [review]

**Comment by gpatel-fr** [comment]
Thanks for the explanation ! May I add that it would make a great one line comment in the code ?

**Pull request merged**
