### PR TITLE
misc: set supported Node version to >= 6

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by hristoterezov** [comment]
@saghul It's not working for node <= 6? Really? Do you know what breaks it?

**Comment by saghul** [comment]
Some ES6 features which we use in webpack config. Since Node 4 is EOL, I guess it's time to move on.

**Comment by hristoterezov** [comment]
Oh! Sure! I'm not opposed the change, I was just curious!

Could you please post some examples of stuff that break node < 6?

**Comment by saghul** [comment]
See: https://github.com/jitsi/jitsi-meet/issues/1758

**Comment by hristoterezov** [comment]
jenkins test this please

**Pull request merged**
