### PR TITLE
feat(prejoin): Show avatar image on prejoin screen

### PR DESCRIPTION
**Pull request by vp8x8**

### CODE REVIEW

**Comment by vp8x8** [comment]
@jmacelroy We don't yet have tests because the feature still suffered a lot of changes (ui & functionality related). 

That's a very good point and I think we should invest in testing, but only after the feature is stable.

**Comment by saghul** [comment]
@vp8x8 You can greatly simplify all of this by passing the `participantId` prop instead of the raw URL: https://github.com/jitsi/jitsi-meet/blob/858a3d953c44bc4b03b84ca604fa6ca04a14a716/react/features/base/avatar/components/Avatar.js#L49

**Comment by vp8x8** [comment]
@saghul I have already tried to add the `participantId` as the `avatarID` from `settings` but it does not work.

I get the avatar, but only after joining the meeting. Am I missing something? 🤔

**Comment by saghul** [comment]
Have you tried getting the local participant and passing its ID?

**Comment by vp8x8** [comment]
There is an avatarID which is the same as the one from settings. But I've seen that the url is on the participant object. I'll try to use that.

**Pull request merged**
