### PR TITLE
Update main-nl.json

### PR DESCRIPTION
**Pull request by marctemp1**
Added missing Dutch translations

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
You need to alphabetically sort the keys, check the failed linter output.

**Comment by saghul** [comment]
@marctemp1 would you like to continue with this?

**Comment by saghul** [comment]
```
--- a/lang/main-nl.json
+++ b/lang/main-nl.json
@@ -1067,14 +1067,13 @@
         "pinToStage": "Vastzetten op podium",
         "remoteControl": "Extern beheer starten / stoppen",
         "screenSharing": "Deelnemer deelt zijn/haar scherm",
-        "showSelfView": "Eigen camera laten zien",
         "show": "Op podium weergeven",
+        "showSelfView": "Eigen camera laten zien",
         "unpinFromStage": "Losmaken van podium",
         "verify": "Verifiëer",
         "videoMuted": "Camera uitgeschakeld",
         "videomute": "Deelnemer heeft de camera gestopt"
     },
-    
     "virtualBackground": {
         "addBackground": "Achtergrond toevoegen",
         "apply": "Toepassen",
```

Almost there!

**Comment by marctemp1** [comment]
Thanks

**Comment by saghul** [comment]
Alas that didn't seem to do it. Can you please check the failed action output?

**Pull request closed without merging**
