### PR TITLE
feat: support rtl layout

### PR DESCRIPTION
**Pull request by c0m1t**
This pull requests allows the web app to change layout(direction) based on the language selected by the user. For languages like Persian or Arabic, it will be RTL.

Apparently it is not possible to support RTL using Sass. So I converted Sass styles to JSS, so with the help of `rtl` plugin from `jss-rtl` properties can be flipped. (for example `padding-left` would change to `padding-right`).

I kept the main layout the same, participants pane is still on the right, chat pane is still on the left, filmstrips are still on the right side, ... .

Prejoin:
Screen Shot 1400-12-15 at 22 02 25

Main layout:
Screen Shot 1400-12-15 at 22 03 09

Chat panel:
Screen Shot 1400-12-15 at 22 03 32

Overflow menu:
Screen Shot 1400-12-15 at 22 03 48

Dialogs:
Screen Shot 1400-12-15 at 22 03 59

Filmstrips:
Screen Shot 1400-12-15 at 22 04 41

### CODE REVIEW

**Comment by saghul** [comment]
Amazing work, thank you!

**Comment by c0m1t** [comment]
If you are willing to support RTL layout, I think it would be a good idea to encourage contributors to use JSS instead of Sass in their new pull requests.

**Comment by saghul** [comment]
Yep, JSS is where we are headed.

Now, this PR is huge, which means it will be hard to review and keep up to date with our own ongoing work.

Any chance you can break it down into smaller chunks, so we can start merging them one by one?

**Comment by c0m1t** [comment]
Sure.

Btw I already submitted these 2 pull requests 2 weeks ago #11038 and #11037.

**Comment by saghul** [comment]
Oh I must have missed those, thanks for the reminder!

**Comment by saghul** [comment]
Closing this since it has been broken down into smaller PRs. Amazing work @c0m1t !

**Pull request closed without merging**
