### PR TITLE
fix: leave the conference after it is destroyed

### PR DESCRIPTION
**Pull request by gabiborlea**

### CODE REVIEW

**Comment by damencho** [comment]
But usually there is a reason for destroying and we show that reason. We should at least give 10-15 seconds to the user to read that notification and then move on.
Also have you tested it with close page enabled and with close page disabled? What about when welcome page is disabled?

**Comment by gabiborlea** [comment]
Yes I have tested, it has the same behavior as a hang up for every case.

**Comment by gabiborlea** [comment]
you can test it here: https://gborlea.jitsi.net/

**Comment by damencho** [comment]
So this is limited to only those destroy reasons listed here: https://github.com/jitsi/jitsi-meet/blob/dc8237ec1cdbe71363e0f46adf7be67760bd5336/react/features/base/conference/constants.ts#L31
I wonder whether we want to do it for all ... but not part of this PR.

**Review by damencho — APPROVED** [review]

**Pull request merged**
