### PR TITLE
Update main-ru.json

### PR DESCRIPTION
**Pull request by Ch0bits**
I added some missing Russian translations and deleted obsolete ones.

### CODE REVIEW

**Comment by Ch0bits** [comment]
I signed.

**Comment by damencho** [comment]
Jenkins test this please.

**Review by saghul — APPROVED** [review]

**Comment by Ch0bits** [comment]
I have no idea why this test failed ( 
image

**Comment by saghul** [comment]
It's a flaky test, not related to your changes. Thank you!

**Pull request merged**
