### PR TITLE
Support any chars in roomname

### PR DESCRIPTION
**Pull request by champtar**
We need to review carefully if there is no security implication
or bugs depending on the client (jitsi-meet, ios, ...)

Signed-off-by: Etienne CHAMPETIER champetier.etienne@gmail.com

### CODE REVIEW

**Comment by champtar** [comment]
just tested and ```'``` in room name make jicofo throws execeptions

**Comment by marclaporte** [comment]
What is the use case?

This seems risky to me and I don't see the benefit. It's better to keep to a safe minimum whitelist and add to the list as needed.

Some user feedback (when invalid room name is attempted) is a good thing.

Best regards,

**Comment by champtar** [comment]
hi @marclaporte,
I agree it's risky but accepting only ascii char is totally latin centric
https://en.wikipedia.org/wiki/Alphabet#Types

My goal is to have #541 merged first,
but in the long run accepting utf8 if possible/safe is a good thing.

**Comment by marclaporte** [comment]
I see the need for letters in non-latin languages but this is not without risk:
http://unicode.org/reports/tr36/

My concern is mostly about special characters, for security but also code simplicity.
https://perishablepress.com/stop-using-unsafe-characters-in-urls/

And we want to keep the option for short / clean URLs.

What will you do with accents? Is déjà and deja the same room?

Keep in mind the URL could / should (in the future) serve to play back the recording after the meeting. And we'll want a way to have a URL for a specific set of parameters of the playback. Ex: to remove all webcams but the main one, or to skip to 30th minute, etc.

Best regards,

M :-)

**Comment by champtar** [comment]
I'm not working on jitsi-meet anymore

**Comment by marclaporte** [comment]
Right, but if issue is not resolved, it should stay open, no?

**Comment by champtar** [comment]
Well, the stale bot is going to close it, I'm just indicating that I will not do any changes, but you can take my contributions and resubmit them ;)

**Pull request closed without merging**
