### PR TITLE
lang: update OccitanTranslated new strings

### PR DESCRIPTION
**Pull request by Mejans**
Translation of new strings

### CODE REVIEW

**Comment by saghul** [comment]
Some of the translations are unordered:

diff --git a/lang/main-oc.json b/lang/main-oc.json
5
index 7e648d6..939bbda 100644
6
--- a/lang/main-oc.json
7
+++ b/lang/main-oc.json
8
@@ -365,6 +365,7 @@
9
         "shareVideoTitle": "Partejar una vidèo",
10
         "shareYourScreen": "Partejar vòstre ecran",
11
         "shareYourScreenDisabled": "Lo partiment d’ecran es desactivat.",
12
+        "sharedVideoDialogError": "Error : URL invalida",
13
         "sharedVideoLinkPlaceholder": "Ligam YouTube o ligam vidèo dirèct",
14
         "start": "Començar ",
15
         "startLiveStreaming": "Aviar una difusion en dirècte",
16
@@ -388,7 +389,6 @@
17
         "viewUpgradeOptions": "Veire las opcions de mesa a nivèl",
18
         "viewUpgradeOptionsContent": "Per obténer un accès sens limit a las foncionalitats premium coma l’enregistrament, la transcripcion, la difusion RTMP e encara mai, devètz passar al nivèl superior.",
19
         "viewUpgradeOptionsTitle": "Avètz descobèrt una foncionalitat premium !",
20
-        "sharedVideoDialogError": "Error : URL invalida",
21
         "yourEntireScreen": "Vòstre ecran complet"
22
     },
23
     "documentSharing": {
24
@@ -927,8 +927,8 @@
25
     "speaker": "Orator",
26
     "speakerStats": {
27
         "angry": "Encolerat",
28
-        "displayEmotions": "Afichar las emocions",
29
         "disgusted": "Desgostat",
30
+        "displayEmotions": "Afichar las emocions",
31
         "fearful": "Pauruc",
32
         "happy": "Content",
33
         "hours": "{{count}} oras",

**Comment by Mejans** [comment]
@saghul Ahora no sé ^^

**Comment by saghul** [comment]
```

7s
0s
Run git diff
diff --git a/lang/main-oc.json b/lang/main-oc.json
index 08f7bc6..939bbda 100644
--- a/lang/main-oc.json
+++ b/lang/main-oc.json
@@ -356,8 +356,6 @@
         "shareAudioWarningD2": "devètz reaviar lo partiment d’ecran e clicar l’opcion « partejar l’àudio ».",
         "shareAudioWarningH1": "Se volètz partejar pas que l’àudio :",
         "shareAudioWarningTitle": "Devètz arrestar lo partiment d’ecran abans lo partiment d’àudio",
-        "sharedVideoDialogError": "Error : URL invalida",        
-        "sharedVideoLinkPlaceholder": "Ligam YouTube o ligam vidèo dirèct",        
         "shareMediaWarningGenericH2": "Se volètz partejar vòstre ecran e l’àudio",
         "shareScreenWarningD1": "devètz arrestar lo partiment àudio abans lo partiment de l’ecran.",
         "shareScreenWarningD2": "devètz arrestar lo partiment àudio, aviar lo partiment d’ecran e clicar l’opcion « partejar l’àudio ».",
@@ -367,10 +365,12 @@
         "shareVideoTitle": "Partejar una vidèo",
         "shareYourScreen": "Partejar vòstre ecran",
         "shareYourScreenDisabled": "Lo partiment d’ecran es desactivat.",
+        "sharedVideoDialogError": "Error : URL invalida",
+        "sharedVideoLinkPlaceholder": "Ligam YouTube o ligam vidèo dirèct",
         "start": "Començar ",
         "startLiveStreaming": "Aviar una difusion en dirècte",
         "startRecording": "Arrestar l'enregistrament",
-        "startRemoteControlErrorMessage": "Una error s'es produsida en ensajar de començar la session de contraròtle a distància !",        
+        "startRemoteControlErrorMessage": "Una error s'es produsida en ensajar de començar la session de contraròtle a distància !",
         "stopLiveStreaming": "Arrestar lo dirècte",
         "stopRecording": "Arrestar l'enregistrament",
         "stopRecordingWarning": "Sètz segur que volètz arrestar l'enregistrament?",
@@ -928,7 +928,7 @@
     "speakerStats": {
         "angry": "Encolerat",
         "disgusted": "Desgostat",
-        "displayEmotions": "Afichar las emocions",        
+        "displayEmotions": "Afichar las emocions",
         "fearful": "Pauruc",
         "happy": "Content",
         "hours": "{{count}} oras",
```

There are still unsorted options, and also some bogus trailing whitespaces.

**Comment by gpatel-fr** [comment]
Hello @Mejans 

The Jitsi devs have made the translation work yet more difficult... but don't worry in the long term it will be much easier ! they should be at the presidential election in my country, they would fit perfeclty :-) Demain on rase gratis !

From what I understand, the test process seems to sort automatically the keys only to test that you did not sort them yourself before sending your patch. Oh well. I downloaded your repo, extracted the main-oc.json, used my little tool on a fresh downloaded jitsi-meet directory:

~/dev/jitsi-meet$ chklang oc  -r ~/main-oc2.json  -a -f
new version created as /home/gp/main-oc.json, 5 new key(s) from which 5 were added from a previous version
~/dev/jitsi-meet$ diff -ru ~/main-oc2.json ~/main-oc.json
--- /home/gp/main-oc2.json	2022-02-21 10:27:36.937763890 +0100
+++ /home/gp/main-oc.json	2022-02-21 10:50:28.697164700 +0100
@@ -356,8 +356,6 @@
         "shareAudioWarningD2": "devètz reaviar lo partiment d’ecran e clicar l’opcion « partejar l’àudio ».",
         "shareAudioWarningH1": "Se volètz partejar pas que l’àudio :",
         "shareAudioWarningTitle": "Devètz arrestar lo partiment d’ecran abans lo partiment d’àudio",
-        "sharedVideoDialogError": "Error : URL invalida",        
-        "sharedVideoLinkPlaceholder": "Ligam YouTube o ligam vidèo dirèct",        
         "shareMediaWarningGenericH2": "Se volètz partejar vòstre ecran e l’àudio",
         "shareScreenWarningD1": "devètz arrestar lo partiment àudio abans lo partiment de l’ecran.",
         "shareScreenWarningD2": "devètz arrestar lo partiment àudio, aviar lo partiment d’ecran e clicar l’opcion « partejar l’àudio ».",
@@ -367,10 +365,12 @@
         "shareVideoTitle": "Partejar una vidèo",
         "shareYourScreen": "Partejar vòstre ecran",
         "shareYourScreenDisabled": "Lo partiment d’ecran es desactivat.",
+        "sharedVideoDialogError": "Error : URL invalida",
+        "sharedVideoLinkPlaceholder": "Ligam YouTube o ligam vidèo dirèct",
         "start": "Començar ",
         "startLiveStreaming": "Aviar una difusion en dirècte",
         "startRecording": "Arrestar l'enregistrament",
-        "startRemoteControlErrorMessage": "Una error s'es produsida en ensajar de començar la session de contraròtle a distància !",        
+        "startRemoteControlErrorMessage": "Una error s'es produsida en ensajar de començar la session de contraròtle a distància !",
         "stopLiveStreaming": "Arrestar lo dirècte",
         "stopRecording": "Arrestar l'enregistrament",
         "stopRecordingWarning": "Sètz segur que volètz arrestar l'enregistrament?",
@@ -889,7 +889,7 @@
         "selectAudioOutput": "Sortida àudio",
         "selectCamera": "Camèra",
         "selectMic": "Microfòn",
-        "selfView": "Pròpria vista",
+        "selfView": "Vista de se",
         "sounds": "Sons",
         "speakers": "Naut-parlairs",
         "startAudioMuted": "Començan totes sens son",
@@ -917,7 +917,7 @@
         "serverURL": "URL del servidor",
         "showAdvanced": "Mostrar los paramètres avançats",
         "startWithAudioMuted": "Començar sens son",
-        "startWithVideoMuted": "Començar sens vidèo",
+        "startWithVideoMuted": "Començar sens vièdo",
         "version": "Version"
     },
     "share": {
@@ -928,7 +928,7 @@
     "speakerStats": {
         "angry": "Encolerat",
         "disgusted": "Desgostat",
-        "displayEmotions": "Afichar las emocions",        
+        "displayEmotions": "Afichar las emocions",
         "fearful": "Pauruc",
         "happy": "Content",
         "hours": "{{count}} oras",

if you had used it, the keys would have been sorted because my little program copy the main.json order, and the white space would not have been present :-)

using diff -ruZ don't show the difference, so there is some white space here:

-        "startRemoteControlErrorMessage": "Una error s'es produsida en ensajar de començar la session de contraròtle a distància !",        
+        "startRemoteControlErrorMessage": "Una error s'es produsida en ensajar de començar la session de contraròtle a distància !",

Yes vi shows the white space quite clearly, it comes from manual line adding.

**Comment by Mejans** [comment]
Hello, I did use weblate for I like it then used your program actually, it said "nothing to generate". I wanted it to sort things, apparently I didn't understand how it works.
Je crois que les développeurs d'ici n'aiment pas les traducteurs en fait ah ah ah. Je pense + de temps à régler des soucis inutile qu'à traduire -_-"

I hope this time will pass!

**Comment by Mejans** [comment]
LoL

**Comment by gpatel-fr** [comment]
no, my program don't sort by itself, it only copies the structure from the original main.json file. If you have already translated all strings, you have to use the -f switch to force it to do its thing. My operating mode is:
cd <jitsi meet dir> (either on git cloned directory, or on /usr/share/jitsi-meet on a working server)
english language keys that can't be found in language 'fr' (to create)
number of keys to add 0

'fr' language keys that can't be found in english version (to be cleaned)
number of keys to purge 0
-> nothing to do for lang fr, go to sleep !
gp@testreunion:/usr/share/jitsi-meet$ chklang oc
english language keys that can't be found in language 'oc' (to create)
dialog / sharedVideoDialogError
dialog / start
speakerStats / displayEmotions
toolbar / accessibilityLabel / selfView
videothumbnail / showSelfView
number of keys to add 5

'oc' language keys that can't be found in english version (to be cleaned)
number of keys to purge 0
-> job to do ! 
gp@testreunion:/usr/share/jitsi-meet$ chklang oc -a
new version created as /home/gp/main-oc.json, 5 new key(s) from which 0 were added from a previous version
I edit then~/main-oc.json, and replace all strings prefixed by '!!' by the best strings I can come up with. - that's the actual job of a translator. After that I push it to github and so far the newfangled thing from Jitsi-meet don't complain.

**Comment by gpatel-fr** [comment]
Your last attempt is removing the white spaces but still has the unsorted
-        "sharedVideoDialogError": "Error : URL invalida",        
-        "sharedVideoLinkPlaceholder": "Ligam YouTube o ligam vidèo dirèct",

**Comment by Mejans** [comment]
D de shareD is not between A de Audio and M de media?

**Comment by saghul** [comment]
Capitalization matters.

**Comment by Mejans** [comment]
how? there are no spaces, it's not a different word then.
Why this obsession to disgust contributors?

**Comment by saghul** [comment]
Look, I agree the process is not ideal, but that's what we have today. All we are doing is sorting keys and making sure all files are consistent.

There is no obsession to disgust anyone here.

The CI tells you exactly what you need to do with that `git diff`. I suspect you are just not using the right tool for the job here, using the GitHub editor is not a good way to edit these files.

**Comment by gpatel-fr** [comment]
@Mejans 

If you want to, we can discuss this either on the forum or in private exchange (mail or Jitsi meet). It's not that difficult once one has understood it :-)

**Pull request closed without merging**
