### PR TITLE
feat(breakout-rooms): renaming

### PR DESCRIPTION
**Pull request by wfleischer**
Allowing moderators to rename breakout rooms. See the related PR https://github.com/jitsi/lib-jitsi-meet/pull/1872.

### CODE REVIEW

**Comment by pcvengros** [comment]
@saghul any chance to get this reviewed and merged (lib part too). Thanks :)

**Comment by saghul** [comment]
We had a meeting with @wfleischer and agreed to add this functionality after some UI changes since it would make some interactions complicated otherwise.

**Comment by wfleischer** [comment]
Marked this as WIP for now. This PR is pending on some UI redesign. No ETA. Sorry.

**Comment by Ayko1595** [comment]
Hello! Are there any plans to reopen this PR? It would be a really nice feature to have. It can become quite confusing to divide into groups when they lack names 😊

**Comment by wfleischer** [comment]
> Hello! Are there any plans to reopen this PR? It would be a really nice feature to have. It can become quite confusing to divide into groups when they lack names 😊

It was suggested to redesign the breakout rooms UI by moving the feature from the participants list into a separate dialog and adding this feature and #10696 into the new UI. Unfortunately, I did not have cycles to do the UI redesign. As the way it is implemented in this PR is working for us, it is a bit of low priority for me :shrug: Sorry, @Ayko1595.

**Comment by Ayko1595** [comment]
Hello again! Just to get some clarification: Does the "UI redesign" part mean that the frontend code needs to be changed or does this feature need new UI design altogether?

**Comment by hristoterezov** [comment]
@wfleischer Discussed internally with the jitsi team and the UI requirement for the UI changed a little bit. I plan to rebase the PR, fix conflicts, etc and merge it with the UI and everything as it is. Thank you very much for the contribution!

**Comment by wfleischer** [comment]
> @wfleischer Discussed internally with the jitsi team and the UI requirement for the UI changed a little bit. I plan to rebase the PR, fix conflicts, etc and merge it with the UI and everything as it is. Thank you very much for the contribution!

Thanks, @hristoterezov! Going ahead will of course not prevent an eventual redesign of the breakout rooms UI in the future. But as the proverb says: A bird in the hand is worth two in the bush 😃

We have the code already on release 2.0.8615. So, if you wish, it would be easy for me to rebase. But I leave that decision to you as you may want to make additional adjustments.

Please also consider the PR feat(breakout-rooms): moderation of visibility #10696, which is on hold for the same reason as this one.

Let me know if there is anything I can do.

**Comment by hristoterezov** [comment]
@wfleischer Thank you! But I've already rebased it and started changing some small things - covert JS files to TS, convert the class components to functional, etc.

**Comment by hristoterezov** [comment]
I'm close this PR in favor of https://github.com/jitsi/jitsi-meet/pull/13584

@wfleischer Your original commit is rebased there.

**Comment by wfleischer** [comment]
Looks very good! Thank you @hristoterezov.

**Pull request closed without merging**
