### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by gardner**

### CODE REVIEW

**Comment by gardner** [comment]
Hi,
  Are you a real person? I don’t sign things that robots ask me to sign.

Thanks,
  Gardner

**Comment by damencho** [comment]
This is a jenkins plugin and asks people to sign the CLA if the user is not in the list of developers or was not whitelisted as CLA signed. If this is not signed, I'm afraid we cannot merge anything. Thanks.
Signing the CLA is also stated in the FAQ on the website: https://jitsi.org/faq#patch

**Comment by gardner** [comment]
Sorry, I didn't realize that Jitsi had been been acquired by Atlassian. I feel kind of tricked by having to provide my email address to find out that the document that I am asked to sign was with Atlassian. As developers I would encourage you to increase transparency around that and maybe list it on your FAQ.

I refuse to enter a legal agreement with Atlassian Pty Ltd. I do not grant Atlassian Pty Ltd the right to sublicense my work. I reject the agreement.

I have a bad taste in my mouth. I am going to go uninstall some software.

**Comment by damencho** [comment]
This was the case and before Atlassian, we had similar document but it was for Bluejimp, this is a common practice nowadays I would say. 
Sorry, to hear that, but everybody has a choice.

**Pull request closed without merging**
