### PR TITLE
Remove some cycles

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by hristoterezov** [comment]
@saghul Why do you need to remove cycles?

**Comment by saghul** [comment]
We need to remove them because they break things. Since we cannot fix them all at once I just go and fix them little by little as time allows. Look at the console when doing `make dev`, it prints all cycles.

This is just a follow-up of https://github.com/jitsi/jitsi-meet/commit/6e679f952f934264ec2b528a3646dc79c3159483 which just continues that effort with the guidelines originally stated.

This has been discussed already, I don't understand why we'd need to discuss it again... am I missing something?

**Comment by hristoterezov** [comment]
I think I'm missing this discussion. Anyway will return back to the commit and read the guidance...

Just FYI I don't think we generally have an issue with circular dependencies. Webpack is mostly taking care of those. The only problematic once IIRC were some global variables.

**Comment by hristoterezov** [comment]
I returned back to the commit message. Turns out I have missed the part with removing index.js from the features the previous time I read it. So my bad, sorry. Anyway those are my 2 cents on the direction you are trying to push:

I don't think we can ever be cycle free even with this approach. So I don't really understand why you are pushing in this direction. Also importing the files explicitly looks messier to me. If we have a problem with circular dependancy that would be indicator that something is wrong with the way we split a feature or the way a feature is implemented. I think the correct approach is to identify those features and fix them. I think your solution will mainly mask those underlying issues instead of fix them or improve the situation.

I actually have thought a bit about those issues that you are trying to solve and had some ideas.

Anyway no action needed!

**Pull request merged**
