### PR TITLE
Fix LoginDialog hidden by gUM-Overlay

### PR DESCRIPTION
**Pull request by michael-dev**
Running FF46 on Linux and Android. The gUM Dialog (zIndex 1013) hides the LoginDialog (zIndex 999 by default) , but the gUM Dialog will only be resolved when connection is completed (aka hideUserMediaPermissionsGuidanceOverlay is called once the Promise.all in createInitialLocalTracksAndConnect is resolved and that Promise includes "connect").

Fix this by increasing the connection dialog zIndex.

Alternatively this could by fixed by handling gUM and connection one after the other.

### CODE REVIEW

**Comment by michael-dev** [comment]
CLA has been signed.

**Comment by saghul** [comment]
Can you please rebase your patch? It no longer applies cleanly.

**Comment by saghul** [comment]
@virtuacoplenny cal you PTAL? I don't particularly like the solution, but it's a stopgap until that dialog is react-ified...

**Comment by virtuacoplenny** [comment]
Probably need to up the z-index now due to the gum overlay being zindex 1016 now. Manually triggering the login dialog on meeting (using the global APP.UI), it remains hidden behing the gum overlay when at 1014.

**Comment by virtuacoplenny** [comment]
Also, atlaskit's react dialog has a zindex of 510 versus the overlay's z-index of 1016. So reactification of the login dialog would cause this problem to pop up again. Which tells me this is probably an addressable problem right now, but I'm okay with the zindex change to fix it immediately (if you can consider two years after the PR open date to be immediate).

**Comment by saghul** [comment]
🤦‍♂️  I hadn't noticed the PR date. @michael-dev are you still keen on updating this PR?

**Comment by michael-dev** [comment]
I've resolved the conflict.

**Comment by virtuacoplenny** [comment]
Jenkins test this please.

**Pull request merged**
