### PR TITLE
Improve accessibility in breakout rooms list

### PR DESCRIPTION
**Pull request by ahmadkadri**
1. Improve the accessibility in breakout list for screen reader: the list of breakout has no role and no aria-label. by adding the right role and aria-label to the list and list items, we make it more readable and accessible for screen reader users. 

MicrosoftTeams-image

MicrosoftTeams-image (1)

2. Show participants list in breakout rooms: the show participants list button in the breakout room list item is now accessible for the keyboard users.

https://github.com/jitsi/jitsi-meet/assets/52747422/5e0bdb7e-5d7e-4e35-b42f-8ec2eb926a13

3. Context menu of a breakout room actions: 

- **focus trap:** if the context menu is open, the focus should always stay on the context menu and not lost by keyboard navigation to elements in the Background. (until it is closed)

- **keyboard navigation:** by navigating to the context menu, the first item/option will be auto focused. All item option will be navigable using arrow up and down keys and closed by Escape key.

https://github.com/jitsi/jitsi-meet/assets/52747422/c2457059-83c7-4f62-9f5f-2b44204e33cb

**Note:** these changes improve the accessibility of the context menu where ever it is used.

Note: @saghul this is an alternative pull request for https://github.com/jitsi/jitsi-meet/pull/13641 . 
for some reason the changes in the old pull request were overwritten

### CODE REVIEW

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by ahmadkadri** [comment]
> Jenkins please test this please.

@saghul i see that the tests are failing. how should we move forward with the PR?

**Comment by saghul** [comment]
It's possible the tests need an update, in case you changes some selectors for example.

https://github.com/jitsi/jitsi-meet-torture this is the repo with the tests.

If you make a PR there and use the same branch name your Jitsi Meet branch will be tested together with the tests branch in unison.

**Comment by Calinteodor** [comment]
@ahmadkadri There are still 3 tests failing and they seem to be related your changes. Try running them separately as it is easier to follow where the errors come from.

**Comment by emrahcom** [comment]
@saghul @Calinteodor,

I updated `jitsi-meet-tortune` for this PR.
https://github.com/jitsi/jitsi-meet-torture/pull/618

Could you please test this PR again against it.

**Comment by damencho** [comment]
> Could you please test this PR again against it.

Both PRs need to be with same branch name in order to be tested together. I can recreate both PRs with my account mathcing the branch name to be tested together.

**Comment by emrahcom** [comment]
I used the same branch name `nic/feat/accessibility/brekout`

**Comment by damencho** [comment]
> I used the same branch name `nic/feat/accessibility/brekout`

Yep, probably we need to update the scripts as it also take and the username into account, the way github shows it on top of this page.

**Comment by emrahcom** [comment]
> Yep, probably we need to update the scripts as it also take and the username into account

I can recreate the same PR by using the same username (`nordeck`) if it will help.

**Comment by damencho** [comment]
> > Yep, probably we need to update the scripts as it also take and the username into account
> 
> I can recreate the same PR by using the same username (`nordeck`) if it will help.

👍

**Comment by emrahcom** [comment]
@damencho I recreated the same PR in Nordeck's namespace.

https://github.com/jitsi/jitsi-meet-torture/pull/619

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by damencho** [comment]
@saghul @Calinteodor tests are passing now, can you take another look?

**Review by Calinteodor — APPROVED** [review]

**Comment by Calinteodor** [comment]
Good to go! Thank you @emrahcom @ahmadkadri for your help and contribution!

**Pull request merged**
