### PR TITLE
Convert tabs to spaces in mixed formatted prosody plugins

### PR DESCRIPTION
**Pull request by emrahcom**
- Convert tabs to spaces in mixed formatted prosody plugins to improve readability.
- Convert tabs to spaces in some plugins (_even they are not fixed formatted_) to match the common format

### CODE REVIEW

**Comment by saghul** [comment]
Can we use something to enforce this going forward? Some Lua linter?

**Comment by emrahcom** [comment]
Aftera quick search, [luacheck](https://github.com/mpeterv/luacheck) seems nice. It's available via `luarocks`

```bash
luarocks install luacheck
```

**Comment by saghul** [comment]
It would at least give us a bit more consistency after the first pass right?

Does Prettier work with Lua?

**Comment by emrahcom** [comment]
> It would at least give us a bit more consistency after the first pass right?

Yep.

> Does Prettier work with Lua?

According to [prettier doc](https://prettier.io/docs/en/plugins.html#official-plugins), no...
I found some third-party plugins in GitHub but they seems unstable. I never tried.

**Comment by saghul** [comment]
Oh.

Then would you mind adding a GH action which runs luacheck please?

**Comment by emrahcom** [comment]
I need to check how GH action works. I didn't use it before.

And `luacheck` creates a warning (not error) for `module:` usage. Such as `module:log` and `module:hook`...
I couldn't find yet what the correct way should be.

**Comment by emrahcom** [comment]
`luacheck -g` filters out warnings related with `module:XX` and I think it is good as a starting point.

**Comment by emrahcom** [comment]
Hi @saghul,

I created my first GH action on [jitsi-contrib/prosody-plugins -> luacheck.yml](https://github.com/jitsi-contrib/prosody-plugins/blob/main/.github/workflows/luacheck.yml)

If this is OK, we can apply it to this repo too. What do you think?

**Comment by saghul** [comment]
Sounds like a good starting point!

Should be easy to adapt to this repo with mi or changes, go for it!

**Comment by emrahcom** [comment]
I will recreate new pull-requests which are more meaningfull for the added `Luacheck` action.

**Pull request closed without merging**
