### PR TITLE
authdomain2

### PR DESCRIPTION
**Pull request by spellauge**
added authdomain

### CODE REVIEW

**Comment by spellauge** [comment]
added authdomain

**Comment by bgrozev** [comment]
LGTM

**Comment by gpolitis** [comment]
LGTM^2

**Comment by spellauge** [comment]
so i think, when doing the next jitsi-upgrade, i will not have to
redeploy my code.

thanks a lot

gustav, still struggeling

Am 14.10.2015 um 18:25 schrieb bgrozev:

**Pull request merged**
