### PR TITLE
feat(reactions) Open reactions menu on hover instead of click

### PR DESCRIPTION
**Pull request by robertpin**
Fixes issue on DialogPortal where the content would flash to the initial position then move to the correct position

### CODE REVIEW

**Comment by robertpin** [comment]
Jenkins test this please

**Comment by robertpin** [comment]
Jenkins test this please

**Comment by damencho** [comment]
Jenkins add to whitelist

**Comment by damencho** [comment]
Oh, not being tested is my fault, sorry.

**Comment by robertpin** [comment]
Jenkins test this please

**Review by quitrk — APPROVED** [review]

**Pull request merged**
