### PR TITLE
Move interface_config.js to etc, support local_watermark.png

### PR DESCRIPTION
**Pull request by Syonyk**
Per discussion in https://github.com/jitsi/jitsi-meet/issues/6279

This set of changes will, on new installs, copy interface_config.js to /etc/jitsi/meet, and create aliases for them in the web server configuration.

On upgrades, it copies the file into /etc/jitsi/meet, but does _not_ update the server configs.  Should it?  With how the config is created, it seems the only real option is to overwrite the old config.

This also adds, on nginx, support for a local_watermark.png file in /usr/share/jitsi/images that shouldn't be overwritten on package updates as watermark.png is.

I've not found any documentation referencing watermark.png to update, though I could add some if needed.

### CODE REVIEW

**Comment by Syonyk** [comment]
I've signed the CLA.

**Comment by Syonyk** [comment]
Ping about this, if anyone is looking at it.

Not overwriting the watermark and interface_config would be really nice with how fast the development and updates are happening lately!

**Comment by saghul** [comment]
Generally LGTM, thank you! I’ll take a closer look tomorrow.

**Comment by damencho** [comment]
I did a quick test: install the current stable and update the deb package generated from this PR and that brokes the deployment.
The problem is that this is missing in existing Nginx config:
```
        JITSI_MEET_INTERFACE_CONFIG="/etc/jitsi/meet/$JVB_HOSTNAME-interface_config.js"
        if [ ! -f $JITSI_MEET_INTERFACE_CONFIG ] ; then
            cp /usr/share/jitsi-meet-web-config/interface_config.js $JITSI_MEET_INTERFACE_CONFIG
        fi
```
On already installed deployments and interface_config is missing from /usr/share/jitsi-meet. Maybe a workaround, for the time being, is to have the file in both places.

**Comment by Syonyk** [comment]
I'm not sure if having the file in both places is the right option, but I agree that the config needs to change.

Would bumping the required versions together be a solution, or is the web config mostly static once deployed?

**Comment by damencho** [comment]
Web config is not something we change after deploying. 
There are cases we had to touch configs on update, but those are jicofo and bridge. 
Versions will not help, as we need people to be able to continue updating.

**Comment by Syonyk** [comment]
I've re-added the line that removed /usr/share/jitsi-meet/interface_config.js - so that should remain.

I'm not entirely sure how to document all this or where - thoughts?

**Comment by damencho** [comment]
I would say FAQ section customize my deployment or something like that ... Or maybe Saul can help with that when he wakes up.

**Comment by damencho** [comment]
Tested the latest changes everything seems fine. Old deployments after update continue using the interface config from usr/share ... and new deployments use it from /etc.
I agree it is confusing having the file in both places ... but let's hear @saghul's opinion.

**Comment by Syonyk** [comment]
Ok, I'll work on some documentation.  Tomorrow's supposed to be windy so I probably won't be doing as much outdoor work.  I think if we document it, and suggest one check/edit the server config, it'll be fine-ish for those who want to modify things.

**Comment by damencho** [comment]
Thank you.

**Comment by damencho** [comment]
By the way, I had a second thought. So let me share it. So we currently copy the file once ... and when there is update it is update in the template  and that's it ... nothing is updated.
If we mark the file as a config file, when there is an update and we try to replace the original one, if it was modified by the user it will offer to use local/remote version or to merge changes ...

**Comment by Syonyk** [comment]
The config files are not being handled as config files by the package, for sure.  I'm not sure how to transition that, and how to make it work with the domain-specific naming that Jitsi uses for the config files.

**Comment by damencho** [comment]
Nope, there is no reason, maybe for adding multiple sites ... but anyone doing such customization can do the rename ... for this one we can go with just interface_config.js if you are willing to do the changes ... I can test them. Maybe if you are doing that do it on top of current work so we can easily drop that commit and revert to the previous one ...

**Comment by Syonyk** [comment]
Oof.  That's a rough set of transitions to make.  Though I'l look into it.  If there are no objections to moving to just interface_config.js and config.js in /etc, that should make things far, far easier for people going forward.

My concern is not so much new installs, but having something that doesn't break existing installs completely on update. :)  I'll think about it.

**Comment by damencho** [comment]
O yeah, completely leave config js as it is, we are talking just for interface as we do not do any sed there or anything, we use the exact copy from source ...

**Comment by MagicFab** [comment]
Until there is a fix in the current packaging / implementation, someone had published a configuration backup / recovery script for this precise situation :

https://github.com/AndreStemmann/Jitsi-Meet-Scripts

**Pull request closed without merging**
