### PR TITLE
Introduce CHAT_STARTS_OPEN configuration variable

### PR DESCRIPTION
**Pull request by vladertel**
contributor agreement already signed

### CODE REVIEW

**Comment by vladertel** [comment]
Hello darkness, my old friend...

**Comment by vladertel** [comment]
I've come to talk with you again...

**Comment by vladertel** [comment]
Because a vision softly creeping...

**Review by damencho — CHANGES_REQUESTED** [review]
Sorry for the delay. The changes in middleware and reducer will break mobile.

**Pull request closed without merging**
