### PR TITLE
Added mute video moderation feature

### PR DESCRIPTION
**Pull request by skolmer**
This change adds the ability for a moderator to deactivate the camera of other participants. The implementation uses the same approach that was implemented to mute audio of other participants.

This feature consists of multiple PRs:
- https://github.com/jitsi/jitsi-media-transform/pull/329
- https://github.com/jitsi/jitsi-videobridge/pull/1570
- https://github.com/jitsi/jitsi-xmpp-extensions/pull/37
- https://github.com/jitsi/jicofo/pull/695
- https://github.com/jitsi/lib-jitsi-meet/pull/1496
- https://github.com/jitsi/jitsi-meet/pull/8630

### CODE REVIEW

**Comment by damencho** [comment]
Could you please correct the lint issues, thanks.

**Comment by skolmer** [comment]
> 
> 
> Could you please correct the lint issues, thanks.

sure, just one question. Is there a solution for this one or should I just type it as string?
image

**Comment by skolmer** [comment]
> 
> 
> > Could you please correct the lint issues, thanks.
> 
> sure, just one question. Is there a solution for this one or should I just type it as string?
> 

@damencho  I removed the import mentioned above. Not sure though how the docs now know which type is used here but at least the linter is now happy. Also fixed those other lint issues.

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — CHANGES_REQUESTED** [review]
LGTM, Thank you!

One small thing, you need to add the button to the default set of buttons in interface config: https://github.com/jitsi/jitsi-meet/blob/a7db7ecaffdef9386260d4e61c7eece72ee0ac37/interface_config.js#L209

**Comment by skolmer** [comment]
> 
> 
> LGTM, Thank you!
> 
> One small thing, you need to add the button to the default set of buttons in interface config:
> 
> https://github.com/jitsi/jitsi-meet/blob/a7db7ecaffdef9386260d4e61c7eece72ee0ac37/interface_config.js#L209

Ok, the new `mute-video-everyone` has been added to `TOOLBAR_BUTTONS`. We also added german translations for the new interface components.

**Comment by damencho** [comment]
Yep, we need to first merge the lib-jitsi-meet one (I left a small comment there) and then you can update it here (the lib-jitsi-meet hash) and we are good to go to test it on beta and alpha :)

**Comment by damencho** [comment]
It will be nice if we can add and tests in torture the same way we have and for mute ... but I don't want to block the PRs for the tests.

**Comment by skolmer** [comment]
> 
> 
> It will be nice if we can add and tests in torture the same way we have and for mute ... but I don't want to block the PRs for the tests.

I will put it on my list. I might be able to provide a PR to torture by beginning of next week.

**Comment by damencho** [comment]
> > It will be nice if we can add and tests in torture the same way we have and for mute ... but I don't want to block the PRs for the tests.
> 
> I will put it on my list. I might be able to provide a PR to torture by beginning of next week.

Nice, thank you!

**Comment by damencho** [comment]
You can update package.json with 9beb47fe5f5ae9caf0b206588e14fa676479ce31 for lib-jitsi-meet (and package-lock... ).

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by damencho — APPROVED** [review]

**Comment by skolmer** [comment]
> 
> 
> Jenkins, test this please.
Sorry, just realized I made a copy/paste error before, can you rerun?

**Comment by damencho** [comment]
Yep, no worries.

**Comment by damencho** [comment]
Actually, the tests check and start every 10 mins around the clock so I think you did it in time :) 
Will see :)

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
It is on alpha! :) Thank you!

**Comment by damencho** [comment]
Great work!

**Comment by skolmer** [comment]
> 
> 
> Great work!

Thanks! 👍 If you find some time, could you give me a short feedback if we are going in the right direction with this one: https://github.com/jitsi/jitsi-meet/pull/8660

We are currently doing a lot of optimizations for our customer and want to make it all available to the community too. The next one will be a larger PR where we make the UI finally WCAG 2.1 compliant. Still need to find the time for a final code review before I create the PR. It will be the follow up to https://github.com/jitsi/jitsi-meet/pull/8423

**Comment by skolmer** [comment]
> 
> 
> It will be nice if we can add and tests in torture the same way we have and for mute ... but I don't want to block the PRs for the tests.

I looked into the existing tests and noticed there are no tests for the remote audio mute feature yet that I could use as a base so I'm afraid I won't be a big help here. 😔 maybe anyone who already has experience writing those kind of tests can chime in? I can at least support with information about what needs to be tested.

**Comment by damencho** [comment]
Yep, no problem ... Yeah there are mute tests and kick is using the remote menu so I may try to add some in the following weeks, I have few tasks planned around tests

**Pull request merged**
