### PR TITLE
Added desktop sharing howto

### PR DESCRIPTION
**Pull request by neogeek83**
Adding howto for installing desktop sharing extensions

### CODE REVIEW

**Comment by neogeek83** [comment]
After entering my info in the https://jitsi.org/icla I'm unable to continue the signing process due to an issue with the document signing process:
   **"Unable to submit form data, Error: Error in the application."**

**Comment by neogeek83** [comment]
Tried again, issue with the icla seems to be resolved. So that's taken care of.

**Comment by bgrozev** [comment]
I'm going to close this PR and re-open it after a few minutes (as a workaround for a Jenkins-related issue we're running into).

**Comment by neogeek83** [comment]
So I'm not sure who the right reviewers would be for this documentation update, but just noticing it hasn't been merged yet. It's a super simple update.

**Pull request closed without merging**
