### PR TITLE
Add email

### PR DESCRIPTION
**Pull request by a7mdragab**
Add email to participants.

### CODE REVIEW

**Comment by a7mdragab** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

I want just to check if it is compatible first with the sdk

**Comment by saghul** [comment]
Unfortunately not. The JitsiParticipant object has no getEmail property.

**Comment by a7mdragab** [comment]
> Unfortunately not. The JitsiParticipant object has no getEmail property.

Can you tell me the path of this class

**Comment by a7mdragab** [comment]
> Unfortunately not. The JitsiParticipant object has no getEmail property.

In most implementation, it uses IJitsiParticipant interface. 
I already added getEmail() like getDisplayName() to it

**Comment by saghul** [comment]
Yes but that won't make it magically work. This object comes from lib-jitsi-meet.

**Pull request closed without merging**
