### PR TITLE
Supports prosody 0.11 when configuring.

### PR DESCRIPTION
**Pull request by damencho**
Doing few changes needed for general config and for tokens.

### CODE REVIEW

**Comment by saghul** [comment]
General comment: why don't we provide the "new" values and only change them for the old ones if the prosody version is too old instead of doing it the other way around?

Also, what Debian / Ubuntu versions can we support if we make 0.11 mandatory?

**Comment by damencho** [comment]
Well, I can change it to be the other way around, I started this way to bring as minimal changes as possible. But current config works with 0.9, 0.10 and prosody-trunk (at least the version we use) and the changes are only for 0.11.
Here are the debian ubuntus that have 0.11:
image

**Comment by saghul** [comment]
@damencho Understood, makes sense. Approved (I assume you tested it :-))

**Comment by damencho** [comment]
Yep, it is tested with installing prosody (0.11..) and with prosody-0.11 packages and after that jitsi-meet, both the prosody config change and the change when installing jitsi-meet-tokens.

**Comment by saghul** [comment]
🚀

**Pull request merged**
