### PR TITLE
ref(filmstrip): separate horizontal and vertical filmstrip styling

### PR DESCRIPTION
**Pull request by virtuacoplenny**
This will make it easier for tile layout filmstrip as there won't be as much overriding needed.

### CODE REVIEW

**Comment by virtuacoplenny** [comment]
Force pushed tor resolve conflicts in filmstrip.scss/horizontal_filmstrip.scss introduced from temasys styling removal. I've carried over the change in a new commit (the newest one).

**Comment by saghul** [comment]
@virtuacoplenny LGTM at a glance. You can squash the last commit into "ref(filmstrip): move some small video specific styling to own file" can't you?

**Comment by virtuacoplenny** [comment]
Force pushed to do a fixup to move the removal of the temasys style into " move some small video specific styling to own file."

**Comment by saghul** [comment]
@virtuacoplenny I see a conflict though, did you rebase?

**Comment by virtuacoplenny** [comment]
No I didn't rebase. I was going to take care of that later today.

**Comment by virtuacoplenny** [comment]
Force pushed to rebase onto latest master and resolve conflicts. Those were really nasty conflicts because they involved filmstrip css changes to account for removal of the use-new-toolbox class. A quick test on chrome and firefox checked out okay.

**Pull request merged**
