### PR TITLE
Improve Arabic translation

### PR DESCRIPTION
**Pull request by Flying-Light**
Modify some translations for their difficulty for the user.
Add some missing translations like "ask to unmute"

### CODE REVIEW

**Comment by saghul** [comment]
Ping @ali-alhaidary :-)

**Comment by Flying-Light** [comment]
> Hi, thanks for your contribution! If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Done!

**Comment by ali-alhaidary** [comment]
> Ping @ali-alhaidary :-)

LGTM :-)

**Review by ali-alhaidary — APPROVED** [review]

**Review by ali-alhaidary — APPROVED** [review]

**Review by ali-alhaidary — APPROVED** [review]
very good :+1:

**Review by saghul — APPROVED** [review]

**Pull request merged**
