### PR TITLE
Add remark about focus username

### PR DESCRIPTION
**Pull request by kevin-olbrich**
https://github.com/jitsi/jitsi-meet/issues/7376

### CODE REVIEW

**Comment by kevin-olbrich** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

/signed

**Comment by kevin-olbrich** [comment]
I've fixed indention but the check was already running during the force push and did not run again after that.

**Comment by paweldomas** [comment]
it's complaining about tabs instead of spaces used for indentation

**Comment by kevin-olbrich** [comment]
> it's complaining about tabs instead of spaces used for indentation

This has been fixed while a build was in progress. The current version should not have any issues. (CI built on old commit)

**Comment by paweldomas** [comment]
> This has been fixed while a build was in progress. The current version should not have any issues. (CI built on old commit)

No, I restarted it

**Comment by paweldomas** [comment]
So I've checked it locally by checking out the commit and there are spaces 🤷‍♂️

**Pull request merged**
