### PR TITLE
Andreabenini patch italianlanguage

### PR DESCRIPTION
**Pull request by andreabenini**
I have added the italian language to jitsi meet, feel free to comment or see that
Hope it helps

Ben

### CODE REVIEW

**Comment by bgrozev** [comment]
@andreabenini thanks for your efforts! We use pootle for the translation (http://translate.jitsi.org/projects/jitsi-meet/). I think we need to manually add your language there, and then you can translate via the web interface. @hristoterezov can you confirm please?

**Comment by andreabenini** [comment]
If confirmed I can manually do it for you if you need it, just drop me a note or let me know

**Comment by ibauersachs** [comment]
@andreabenini I've created Italian in Pootle. Unfortunately I cannot simply import your existing translation (i18next-conv doesn't create correct gettext files). You can either
- copy/paste all the translations into Pootle
- script a little and create a main-it.po from lang/main.json and lang/main-it.json so that it looks like the [German version](http://translate.jitsi.org/download/de/jitsi-meet/main-de.po)

If you do the latter, please send the result to dev@jitsi.org.

**Comment by hristoterezov** [comment]
> On Mar 24, 2015, at 2:10 PM, bgrozev <notifications@github.com> wrote:
> 
> @andreabenini <https://github.com/andreabenini> thanks for your efforts! We use pootle for the translation (http://translate.jitsi.org/projects/jitsi-meet/ <http://translate.jitsi.org/projects/jitsi-meet/>). I think we need to manually add your language there, and then you can translate via the web interface. @hristoterezov <https://github.com/hristoterezov> can you confirm please?
> 
> 

Yes.

**Comment by andreabenini** [comment]
Ok folks, I did it. 100% translated.
Hope it helps

Ben

**Comment by ibauersachs** [comment]
Committed from Pootle. Thank you!

**Pull request closed without merging**
