### PR TITLE
Move miscellaneous files to resources

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
Can you review this @aaronkvanmeerten ? Note that I also moved the nwjs stuff, I hope it has no side effects in projects using it.

**Comment by saghul** [comment]
@jitsi/developers anyone?

**Comment by saghul** [comment]
@jitsi/developers ohai?!

**Comment by damencho** [comment]
In debian/jitsi-meet-tokens.install we refer to prosody-plugins path, it needs an update there.

**Comment by saghul** [comment]
@damencho Ah, missed that, thanks! Updated, can you PTAL?

**Pull request merged**
